Text0ecf:
	hiragana "やあ ", "<RAMNAME>", "くんですか"
	line ""
	textfw4 "GR"
	textfw2 "団"
	textfw0 "との対戦 たのしんでますか?"
	line ""
	textfw0 "でんせつのとり"
	katakana "ポケモン"
	hiragana "の "
	katakana "カード"
	hiragana "も"
	line ""
	textfw0 "のこり 1枚 なんですよ"
	line ""
	textfw0 "いま ほしいのは"
	line ""
	textfw0 "「"
	katakana "サンダー", "<Lv>", "40」"
	hiragana "の "
	katakana "カード"
	hiragana "です"
	line ""
	textfw0 "「"
	katakana "サンダーストーム」"
	hiragana "の"
	line ""
	textfw0 "「"
	katakana "サンダー」"
	hiragana "の "
	katakana "カード"
	hiragana "なんですよ"
	line ""
	textfw0 "わたしの 「そらをとぶ"
	katakana "ピカチュウ」"
	hiragana "と"
	line ""
	textfw0 "こうかんしようと おもうのですが"
	line ""
	textfw0 "むこうのしまで "
	katakana "トレード"
	hiragana "したのとは"
	line ""
	textfw0 "えが ちがう "
	katakana "バージョン"
	hiragana "ですよ"
	line ""
	textfw0 "きみは 「"
	katakana "サンダー", "<Lv>", "40」"
	hiragana "の"
	line ""
	katakana "カード"
	hiragana "を もっていませんか?"
	done

Text0ed0:
	hiragana "やあ ", "<RAMNAME>", "くんですか"
	line ""
	katakana "ポケモンカード "
	hiragana "たのしんでますか?"
	line ""
	textfw0 "でんせつのとり"
	katakana "ポケモン"
	hiragana "の "
	katakana "カード"
	hiragana "も"
	line ""
	textfw0 "のこり 1枚 なんですよ"
	line ""
	textfw0 "いま ほしいのは"
	line ""
	textfw0 "「"
	katakana "サンダー", "<Lv>", "40」"
	hiragana "の "
	katakana "カード"
	hiragana "です"
	line ""
	textfw0 "わたしの 「そらをとぶ"
	katakana "ピカチュウ」"
	hiragana "と"
	line ""
	textfw0 "こうかんしようと おもうのですが"
	line ""
	textfw0 "むこうのしまで "
	katakana "トレード"
	hiragana "したのとは"
	line ""
	textfw0 "えが ちがう "
	katakana "バージョン"
	hiragana "ですよ"
	line ""
	textfw0 "きみは 「"
	katakana "サンダー", "<Lv>", "40」"
	hiragana "の"
	line ""
	katakana "カード"
	hiragana "を もっていませんか?"
	done

Text0ed1:
	hiragana "きみの きもちは"
	line ""
	textfw0 "とても ありがたいのですが"
	line ""
	textfw0 "きみは 「"
	katakana "サンダー", "<Lv>", "40」"
	hiragana "の"
	line ""
	katakana "カード"
	hiragana "を もっていませんね"
	line ""
	textfw0 "それでは "
	katakana "カード"
	hiragana "のこうかんは"
	line ""
	textfw0 "また こんどということで・・・"
	done

Text0ed2:
	hiragana "おやおや きみの「"
	katakana "サンダー", "<Lv>", "40」"
	hiragana "は"
	line ""
	textfw0 "ぜんぶ"
	katakana "デッキ"
	hiragana "に はいっているんですね"
	line ""
	katakana "ゲーム"
	hiragana "に つかっている"
	katakana "カード"
	hiragana "を"
	line ""
	textfw0 "もらうわけには いきませんよ"
	line ""
	textfw0 "それでは "
	katakana "カード"
	hiragana "のこうかんは"
	line ""
	textfw0 "また こんどということで・・・"
	done

Text0ed3:
	hiragana "おお それは ありがたい!"
	line ""
	textfw0 "それでは さっそく・・・"
	done

Text0ed4:
	textfw0 "<RAMNAME>"
	hiragana "は 「"
	katakana "サンダー」"
	hiragana "と"
	line ""
	textfw0 "「そらをとぶ"
	katakana "ピカチュウ」"
	hiragana "をこうかん!"
	done

Text0ed5:
	hiragana "この「"
	katakana "サンダー", "<Lv>", "40」"
	hiragana "は"
	line ""
	textfw0 "ありがたく いただきますよ"
	line ""
	textfw0 "これで でんせつのとり"
	katakana "ポケモン"
	hiragana "の"
	line ""
	katakana "カード"
	hiragana "が すべて そろいました"
	line ""
	textfw0 "たすかりましたよ"
	line ""
	textfw0 "ほんとうに ありがとう"
	done

Text0ed6:
	hiragana "やあ ", "<RAMNAME>", "くんですか"
	line ""
	textfw4 "GR"
	textfw2 "団"
	textfw0 "との対戦 たのしんでますか?"
	line ""
	textfw0 "ちょっと かわった"
	katakana "カード"
	hiragana "を"
	line ""
	textfw0 "てに いれたんですよ"
	line ""
	textfw0 "「"
	katakana "マサキ"
	hiragana "の"
	katakana "パソコン」"
	hiragana "という"
	line ""
	katakana "カード "
	hiragana "なんですよ"
	line ""
	textfw0 "どーも 対戦には つかえない"
	line ""
	katakana "カード"
	hiragana "のようですね・・・"
	line ""
	textfw0 "「わるい"
	katakana "カイリュー", "<Lv>", "33」"
	hiragana "となら"
	line ""
	textfw0 "こうかんしても いいんですが"
	line ""
	textfw0 "きみは どうです?"
	line ""
	textfw0 "こうかん しませんか?"
	done

Text0ed7:
	hiragana "やあ ", "<RAMNAME>", "くんですか"
	line ""
	katakana "ポケモンカード "
	hiragana "たのしんでますか?"
	line ""
	textfw0 "「"
	katakana "マサキ"
	hiragana "の"
	katakana "パソコン」"
	hiragana "の"
	katakana "カード"
	hiragana "を"
	line ""
	textfw0 "こうかんしませんか?"
	line ""
	textfw0 "いま ほしい"
	katakana "カード"
	hiragana "は"
	line ""
	textfw0 "「わるい"
	katakana "カイリュー", "<Lv>", "33」"
	hiragana "です"
	line ""
	textfw0 "きみは 「わるい"
	katakana "カイリュー", "<Lv>", "33」"
	hiragana "の"
	line ""
	katakana "カード"
	hiragana "を もっていませんか?"
	done

Text0ed8:
	hiragana "きみの きもちは"
	line ""
	textfw0 "とても ありがたいのですが"
	line ""
	textfw0 "きみは 「わるい"
	katakana "カイリュー", "<Lv>", "33」"
	hiragana "の"
	line ""
	katakana "カード"
	hiragana "を もっていませんね"
	line ""
	textfw0 "それでは "
	katakana "カード"
	hiragana "のこうかんは"
	line ""
	textfw0 "また こんどということで・・・"
	done

Text0ed9:
	hiragana "きみの「わるい"
	katakana "カイリュー", "<Lv>", "33」"
	hiragana "は"
	line ""
	textfw0 "ぜんぶ"
	katakana "デッキ"
	hiragana "に はいっているんですね"
	line ""
	katakana "ゲーム"
	hiragana "に つかっている"
	katakana "カード"
	hiragana "を"
	line ""
	textfw0 "もらうわけには いきませんよ"
	line ""
	textfw0 "それでは "
	katakana "カード"
	hiragana "のこうかんは"
	line ""
	textfw0 "また こんどということで・・・"
	done

Text0eda:
	hiragana "おお それは ありがたい!"
	line ""
	textfw0 "それでは さっそく・・・"
	done

Text0edb:
	textfw0 "<RAMNAME>"
	hiragana "は「わるい"
	katakana "カイリュー」"
	hiragana "と"
	line ""
	textfw0 "「"
	katakana "マサキ"
	hiragana "の"
	katakana "パソコン」"
	hiragana "をこうかん!"
	done

Text0edc:
	hiragana "この「わるい"
	katakana "カイリュー", "<Lv>", "33」"
	hiragana "は"
	line ""
	textfw0 "ありがたく いただきますよ"
	line ""
	textfw0 "これで わたしが ひつようとしている"
	line ""
	katakana "ポケモンカード"
	hiragana "は そろいましたよ"
	line ""
	textfw0 "ほんとうに たすかりました"
	line ""
	textfw0 "きみに かんしゃしていますよ"
	line ""
	textfw0 "これからも 対戦や "
	katakana "トレード"
	hiragana "で"
	line ""
	katakana "ポケモンカード"
	hiragana "を たのしんでください"
	done

Text0edd:
	hiragana "やあ ", "<RAMNAME>", "くんですか"
	line ""
	textfw0 "いらっしゃい"
	line ""
	textfw0 "いまは とくに ほしい"
	katakana "カード"
	hiragana "も"
	line ""
	textfw0 "こうかんする"
	katakana "カード"
	hiragana "も ないんです"
	line ""
	textfw0 "また こんど"
	line ""
	katakana "カード"
	hiragana "を こうかんしましょう"
	line ""
	textfw0 "よければ わたしのかいた本を"
	line ""
	textfw0 "みていってください"
	line ""
	textfw4 "GR"
	textfw2 "団"
	textfw0 "の ひとたちにも"
	line ""
	textfw0 "よんで もらっているんですよ"
	line ""
	textfw0 "きっと"
	line ""
	textfw0 "対戦で やくにたちますよ"
	done

Text0ede:
	hiragana "あら ", "<RAMNAME>", "くん?"
	line ""
	textfw0 "あなたも べんきょうにきたの?"
	line ""
	textfw4 "M"
	textfw0 "ṛ"
	katakana "イシハラ"
	hiragana "の本は 対戦のためになる"
	line ""
	textfw0 "すばらしい本ですわよ"
	line ""
	textfw0 "大かんぶの わたくし "
	katakana "ルイ"
	hiragana "も"
	line ""
	textfw0 "よく べんきょうに まいりますのよ"
	line ""
	textfw0 "まえにも ここで あったかしら?"
	line ""
	textfw0 "??・・・まあ いいわ"
	line ""
	textfw0 "みていらっしゃい こんどは"
	line ""
	textfw0 "あなたに まけませんからね"
	line ""
	textfw0 "でも 対戦は ここじゃなくて"
	line ""
	textfw4 "GR"
	textfw2 "団"
	textfw0 "の"
	katakana "キャッスル"
	hiragana "でね・・・"
	line ""
	textfw0 "それじゃあね ", "<RAMNAME>", "くん"
	done

Text0edf:
	hiragana "いつも ありがとうございます"
	line ""
	textfw4 "M"
	textfw0 "ṛ"
	katakana "イシハラ・・・"
	done

Text0ee0:
	hiragana "いえいえ わたしの本が"
	line ""
	textfw0 "おやくにたてば なによりです"
	done

Text0ee1:
	hiragana "では しつれいします"
	line ""
	textfw4 "M"
	textfw0 "ṛ"
	katakana "イシハラ・・・"
	done

Text0ee2:
	hiragana "やあ ", "<RAMNAME>", "くん"
	line ""
	katakana "ポケモンカード"
	hiragana "を たのしんでますか?"
	line ""
	textfw0 "きみのおかげで ひつような"
	katakana "カード"
	hiragana "は"
	line ""
	textfw0 "だいたい そろいました"
	line ""
	textfw0 "ですから "
	katakana "カード"
	hiragana "のこうかんは"
	line ""
	textfw0 "もう おしまいです!"
	line ""
	textfw0 "こんどは "
	katakana "ポケモンカード"
	hiragana "で"
	line ""
	textfw0 "対戦して たのしみましょう"
	line ""
	textfw0 "どうです? ", "<RAMNAME>", "くん"
	line ""
	textfw0 "わたしと 対戦してくれませんか?"
	done

Text0ee3:
	hiragana "やあ ", "<RAMNAME>", "くん"
	line ""
	katakana "ポケモンカード"
	hiragana "を たのしんでますか?"
	line ""
	textfw0 "いろんなひとと 対戦してみると"
	line ""
	textfw0 "たのしいでしょう ", "<RAMNAME>", "くん"
	line ""
	textfw0 "それに "
	katakana "カード"
	hiragana "のよさが"
	line ""
	textfw0 "よりよく りかいできるのですよ"
	line ""
	textfw0 "どうです? ", "<RAMNAME>", "くん"
	line ""
	textfw0 "わたしと 対戦してくれませんか?"
	done

Text0ee4:
	textfw4 "M"
	textfw0 "ṛイシハラ"
	hiragana "と 対戦しますか?"
	done

Text0ee5:
	hiragana "ありがとう ", "<RAMNAME>", "くん"
	line ""
	textfw0 "それでは 対戦をたのしみましょう"
	line ""
	katakana "サイドカード"
	hiragana "は"
	line ""
	textfw0 "6枚で おねがいいたします"
	done

Text0ee6:
	hiragana "そうですか?"
	line ""
	textfw0 "それは ざんねんですね"
	line ""
	textfw0 "それでは "
	katakana "カード対戦"
	hiragana "は"
	line ""
	textfw0 "また こんどということで・・・"
	done

Text0ee7:
	hiragana "さすがは ", "<RAMNAME>", "くん"
	line ""
	textfw0 "すっかり やられてしまいました"
	line ""
	textfw0 "でも たのしい対戦でしたよ"
	line ""
	textfw0 "これを あげましょう"
	done

Text0ee8:
	hiragana "いま さしあげた"
	katakana "カード"
	hiragana "で"
	line ""
	textfw0 "あたらしい"
	katakana "デッキ"
	hiragana "を つくってください"
	line ""
	textfw0 "そして もっと"
	line ""
	textfw0 "たのしい対戦を しましょう!"
	line ""
	textfw0 "それじゃあ ", "<RAMNAME>", "くん"
	line ""
	textfw0 "また ぜひ 対戦にきてくださいね"
	done

Text0ee9:
	hiragana "やあ・・・"
	line ""
	textfw0 "わたしが 勝ってしまいましたね"
	line ""
	textfw0 "なかなか たのしい対戦でしたね"
	line ""
	textfw0 "<RAMNAME>", "くん!"
	line ""
	textfw0 "それじゃあ ", "<RAMNAME>", "くん"
	line ""
	textfw0 "また 対戦にきてくださいね"
	done

Text0eea:
	textfw0 "フン フン "
	hiragana "なるほどね・・・"
	line ""
	textfw0 "さすがね・・・・"
	done

Text0eeb:
	hiragana "なに? いま "
	katakana "ポケモンカード"
	hiragana "の"
	line ""
	textfw0 "べんきょうしているのよ"
	line ""
	textfw4 "M"
	textfw0 "ṛ"
	katakana "イシハラ"
	hiragana "の本は 対戦のためになる"
	line ""
	textfw0 "すばらしい本ですわよ"
	line ""
	textfw0 "あなたも よんで"
	line ""
	textfw0 "べんきょうすると よろしいですわ"
	done

Text0eec:
	textfw0 "オートデッキマシン1"
	textfw3 "号"
	hiragana "が ある!"
	done

Text0eed:
	textfw0 "デッキ"
	hiragana "を つくりますか?"
	done

Text0eee:
	textfw0 "オートデッキマシン2"
	textfw3 "号"
	hiragana "が ある!"
	done

Text0eef:
	textfw0 "デッキ"
	hiragana "を つくりますか?"
	done

Text0ef0:
	textfw0 "デッキ"
	hiragana "きろく"
	katakana "マシン"
	hiragana "が ある!"
	done

Text0ef1:
	textfw0 "デッキ"
	hiragana "きろく"
	katakana "マシン"
	hiragana "を つかいますか?"
	done

Text0ef2:
	hiragana "この "
	katakana "オートデッキマシン"
	hiragana "は"
	line ""
	katakana "スゴイ"
	hiragana "んだぜ!"
	line ""
	katakana "デッキ"
	hiragana "を つくるのに"
	line ""
	textfw0 "ひつような"
	katakana "カード"
	hiragana "を もっていれば"
	line ""
	textfw0 "この"
	katakana "マシン"
	hiragana "が じどうてきに"
	line ""
	katakana "デッキ"
	hiragana "を つくってくれるんだ!"
	line ""
	textfw0 "この"
	katakana "マシン"
	hiragana "の"
	katakana "デッキ"
	hiragana "は"
	line ""
	katakana "キミ"
	hiragana "が たたかっていけば いくほど"
	line ""
	katakana "ドンドン "
	hiragana "ふえてゆくからね"
	line ""
	textfw0 "たまに みにきてくれよ"
	done

Text0ef3:
	hiragana "おめでとう ", "<RAMNAME>", "くん"
	line ""
	textfw0 "ついに "
	textfw4 "GR"
	textfw2 "団"
	textfw0 "を たおしたんだってね"
	line ""
	textfw0 "この"
	katakana "オートデッキマシン"
	hiragana "も"
	line ""
	textfw0 "やくに たったかい?"
	done

Text0ef4:
	hiragana "やあ ", "<RAMNAME>", "くん この"
	katakana "マシン"
	hiragana "は"
	line ""
	katakana "デッキ"
	hiragana "きろく"
	katakana "マシン"
	hiragana "って いうんだ"
	line ""
	textfw0 "じぶんでつくった "
	katakana "デッキ"
	hiragana "の"
	line ""
	textfw0 "つくりかたが きろくできる"
	katakana "マシン"
	hiragana "だ"
	line ""
	textfw0 "いちど きろくしておけば"
	line ""
	textfw0 "その"
	katakana "デッキ"
	hiragana "を いつでもつくれるんだ"
	line ""
	katakana "デッキ"
	hiragana "をつくるのに ひつような"
	line ""
	katakana "カード"
	hiragana "をもっていれば だけどね"
	line ""
	katakana "キミ"
	hiragana "の"
	katakana "ミニコン"
	hiragana "と つながってるから"
	line ""
	katakana "ドンドン"
	hiragana "きろくして おくといいぞ!"
	done

Text0ef5:
	textfw0 "グレートロケット("
	textfw4 "GR"
	textfw0 ")"
	textfw2 "団"
	hiragana "は"
	line ""
	textfw0 "とおくの"
	textfw3 "島"
	textfw0 "から きたってはなしだ"
	line ""
	textfw0 "なんでも "
	katakana "ボク"
	hiragana "らが みたこともない"
	line ""
	katakana "ポケモンカード"
	hiragana "を つかうらしいよ"
	line ""
	textfw0 "いったい どんな"
	katakana "カード"
	hiragana "を"
	line ""
	textfw0 "つかっているんだろ・・・"
	done

Text0ef6:
	hiragana "やあ ", "<RAMNAME>", "くん"
	line ""
	textfw0 "どうだい "
	textfw4 "GR"
	textfw2 "団"
	textfw0 "の"
	textfw3 "島"
	textfw0 "の対戦は"
	line ""
	textfw0 "あたらしい "
	katakana "ポケモンカード"
	hiragana "の対戦を"
	line ""
	textfw0 "くりひろげている そうじゃないか"
	line ""
	katakana "ボク"
	hiragana "も いつか "
	textfw4 "GR"
	textfw2 "団"
	textfw0 "の"
	textfw3 "島"
	textfw0 "へ"
	line ""
	textfw0 "いってみたいなぁ"
	done

Text0ef7:
	textfw0 "キミ"
	hiragana "のおかげで "
	textfw4 "GR"
	textfw2 "団"
	textfw0 "の"
	katakana "デッキ"
	hiragana "を"
	line ""
	textfw0 "ずいぶん 研究することが できたよ"
	line ""
	textfw4 "GR"
	textfw2 "団"
	textfw0 "とも なかよくなったことだし"
	line ""
	katakana "ボク"
	hiragana "も "
	textfw4 "GR"
	textfw2 "団"
	textfw0 "の"
	textfw3 "島"
	textfw0 "へ いこうかな"
	done

Text0ef8:
	hiragana "やあ ", "<RAMNAME>", "くん!"
	line ""
	textfw0 "しっているかな?"
	line ""
	textfw0 "こんど "
	textfw4 "D"
	textfw0 "ṛ"
	katakana "オーヤマ"
	hiragana "のつくった"
	line ""
	katakana "オート"
	hiragana "きろくの "
	katakana "デッキマシン"
	hiragana "は"
	line ""
	katakana "カード"
	hiragana "が ぜんぶ そろってなくても"
	line ""
	katakana "デッキ"
	hiragana "を つくってくれるんだ"
	line ""
	textfw0 "たりない"
	katakana "カード"
	hiragana "は ほかの"
	katakana "カード"
	hiragana "に"
	line ""
	textfw0 "おきかえて つくるんだ"
	line ""
	textfw0 "でも "
	katakana "カード"
	hiragana "が ぜんぜん"
	line ""
	textfw0 "たりないときには つくれないけどね"
	done

Text0ef9:
	hiragana "やあ よくきたね"
	line ""
	textfw0 "<RAMNAME>", "くん"
	line ""
	textfw0 "あたらしい "
	katakana "オートデッキマシン"
	hiragana "が"
	line ""
	textfw0 "かんせいしたんだ!"
	line ""
	textfw0 "この"
	katakana "オートデッキマシン2"
	textfw3 "号"
	hiragana "は"
	line ""
	textfw4 "GR"
	textfw2 "団"
	textfw0 "の"
	katakana "カード "
	hiragana "たいおうなんだ"
	line ""
	textfw0 "どんどん "
	katakana "デッキ"
	hiragana "のつくりかたを"
	line ""
	textfw0 "あつめておくから きてくれよ"
	done

Text0efa:
	hiragana "やったな ", "<RAMNAME>", "!"
	line ""
	textfw0 "ついに "
	textfw4 "GR"
	textfw2 "団"
	textfw0 "を たおしたんだって"
	line ""
	textfw0 "でも まだ おわりじゃないぜ"
	line ""
	katakana "デッキマシン"
	hiragana "も まだまだ はいるぜ"
	line ""
	textfw0 "それに ここに あつまった"
	katakana "デッキ"
	hiragana "も"
	line ""
	textfw0 "ぜんぶ ためしてみてくれよ"
	done

Text0efb:
	hiragana "おお!"
	line ""
	textfw0 "ぶじじゃったか ", "<RAMNAME>", "!"
	line ""
	textfw0 "たいへんじゃ! "
	katakana "グレートロケット"
	textfw2 "団"
	hiragana "が"
	line ""
	textfw4 "GR"
	textfw2 "団"
	textfw0 "が せめてきたんじゃ!"
	line ""
	textfw0 "このしまの "
	katakana "カードクラブ"
	hiragana "を"
	line ""
	textfw0 "つぎつぎと おそっているんじゃ"
	line ""
	textfw0 "みんなの"
	katakana "カード"
	hiragana "を うばったり"
	line ""
	katakana "クラブメンバー"
	hiragana "を ゆうかいしておる!"
	line ""
	textfw0 "このままでは このしまでは"
	line ""
	katakana "ポケモンカード"
	hiragana "が あそべなくなる"
	line ""
	katakana "グランドマスター"
	hiragana "を やぶった"
	line ""
	textfw0 "おまえのちからで "
	textfw4 "GR"
	textfw2 "団"
	textfw0 "をたおして"
	line ""
	katakana "ヤツ"
	hiragana "らから "
	katakana "ポケモンカード"
	hiragana "を"
	line ""
	textfw0 "とりもどしてくれ!"
	done

Text0efc:
	textfw4 "D"
	textfw0 "ṛオーヤマ"
	hiragana "のいらいを うけますか?"
	done

Text0efd:
	hiragana "たのむ! ", "<RAMNAME>"
	line ""
	textfw0 "おまえのちからが ひつようなのじゃ!"
	line ""
	katakana "ランド"
	hiragana "だけでは しんぱいなんじゃ"
	line ""
	textfw0 "たのむ ", "<RAMNAME>"
	done

Text0efe:
	hiragana "そうか やってくれるか!"
	line ""
	textfw0 "ありがとう ", "<RAMNAME>", "!"
	done

Text0eff:
	hiragana "それから"
	line ""
	textfw0 "この"
	katakana "ミニコン"
	hiragana "を やろう!"
	done

Text0f00:
	textfw0 "<RAMNAME>"
	hiragana "は"
	line ""
	textfw0 "「"
	katakana "ミニコン」"
	hiragana "を "
	katakana "ゲット!"
	done

Text0f01:
	hiragana "その"
	katakana "ミニコン"
	hiragana "は すぐれものじゃ"
	line ""
	katakana "メール"
	hiragana "をみたり"
	line ""
	textfw0 "つくった"
	katakana "デッキ"
	hiragana "を 研究"
	textfw1 "所"
	textfw0 "の"
	line ""
	katakana "デッキ"
	hiragana "きろく"
	katakana "マシン"
	hiragana "に おくれるんじゃ"
	line ""
	textfw0 "なにか じょうほうがはいったら"
	line ""
	katakana "ミニコン"
	hiragana "に "
	katakana "メール"
	hiragana "をおくるからな"
	line ""
	textfw4 "START"
	katakana "ボタン"
	hiragana "で "
	katakana "ミニコン"
	hiragana "を"
	line ""
	textfw0 "こまめに "
	katakana "チェック"
	hiragana "するんじゃぞ!"
	line ""
	textfw0 "たのんだぞ ", "<RAMNAME>", "!"
	line ""
	textfw4 "GR"
	textfw2 "団"
	textfw0 "から "
	katakana "カード"
	hiragana "をとりもどすんじゃ"
	done

Text0f02:
	hiragana "そういえば おまえも"
	line ""
	katakana "カード"
	hiragana "を うばわれたんじゃったのう!"
	line ""
	katakana "ヤツ"
	hiragana "らと対戦するには"
	line ""
	katakana "デッキ"
	hiragana "が ひつようじゃ!"
	line ""
	textfw0 "わしから"
	line ""
	textfw0 "この"
	katakana "デッキ"
	hiragana "を おまえにやろう!"
	done

Text0f03:
	textfw0 "<RAMNAME>"
	hiragana "は"
	line ""
	textfw0 "「さいしょの"
	katakana "デッキ」"
	hiragana "を "
	katakana "ゲット!"
	done

Text0f04:
	hiragana "まつんじゃ ", "<RAMNAME>", "!"
	done

Text0f05:
	textfw4 "GR"
	textfw2 "団"
	hiragana "は てごわいぞ"
	line ""
	textfw0 "<RAMNAME>", "!"
	line ""
	katakana "ポケモンカード"
	hiragana "の "
	katakana "ルール"
	hiragana "の"
	line ""
	textfw0 "かくにんは だいじょうぶか?"
	line ""
	textfw0 "もし しんぱいが あるようなら"
	line ""
	textfw0 "研究員の"
	katakana "ミカサ"
	hiragana "と れんしゅうしたり"
	line ""
	katakana "トレーニング"
	textfw1 "室"
	hiragana "で あらい"
	katakana "モン"
	hiragana "と"
	line ""
	textfw0 "対戦してみるんじゃよ"
	done

Text0f06:
	textfw0 "「"
	hiragana "れんしょう きろく」の"
	katakana "データ"
	hiragana "が"
	line ""
	textfw0 "なんらかのげんいんで こわれました"
	line ""
	textfw0 "「れんしょう きろく」の"
	katakana "データ"
	hiragana "を"
	line ""
	textfw0 "しょきか しました"
	done

Text0f07:
	textfw0 "50"
	hiragana "れんしょう たっせいじゃな"
	line ""
	textfw0 "きねんに "
	katakana "コイン"
	hiragana "を やろう"
	done

Text0f08:
	hiragana "どうじゃ? いいものじゃろう"
	line ""
	textfw0 "だいじに つかうんじゃぞ"
	done

Text0f09:
	textfw4 "GR"
	textfw2 "団"
	hiragana "の"
	katakana "ヤツ"
	hiragana "らは "
	katakana "クラブ"
	hiragana "を"
	line ""
	textfw0 "つぎつぎと おそっているようじゃ"
	line ""
	katakana "ランド"
	hiragana "が "
	katakana "ヤツ"
	hiragana "らのようすを"
	line ""
	textfw0 "さぐっている はずじゃ"
	line ""
	textfw0 "おまえも "
	katakana "クラブ"
	hiragana "のようすを"
	line ""
	textfw0 "しらべてくれ!"
	done

Text0f0a:
	hiragana "このしまに のこっている"
	textfw4 "GR"
	textfw2 "団"
	textfw0 "は"
	line ""
	textfw0 "5にんだけの ようじゃ"
	line ""
	textfw0 "ひとりは "
	katakana "ポケモンドーム"
	hiragana "で"
	line ""
	textfw0 "めいれいを だしているだけのようじゃ"
	line ""
	katakana "クラブ"
	hiragana "を おそっているのは"
	line ""
	textfw4 "GR"
	textfw0 "1"
	textfw3 "号"
	textfw0 "から"
	textfw4 "GR"
	textfw0 "4"
	textfw3 "号"
	textfw0 "の 4にん!"
	line ""
	katakana "ヤツ"
	hiragana "らを やっつければ"
	line ""
	textfw0 "こんらんも おちつくじゃろ"
	line ""
	textfw0 "たのむぞ ", "<RAMNAME>"
	done

Text0f0b:
	textfw0 "ランド"
	hiragana "のほうこくに よれば"
	line ""
	textfw4 "GR"
	textfw2 "団"
	textfw0 "は "
	katakana "クラブマスター"
	hiragana "や"
	line ""
	katakana "グランドマスター"
	hiragana "を じぶんたちの"
	line ""
	textfw0 "しまへ つれさったようじゃ"
	line ""
	textfw0 "なんとかして "
	katakana "ヤツ"
	hiragana "らのしまへ"
	line ""
	textfw0 "わたり かれらを たすけだすんじゃ"
	line ""
	textfw0 "たのんだぞ ", "<RAMNAME>"
	done

Text0f0c:
	hiragana "おう ", "<RAMNAME>", "か!"
	line ""
	textfw0 "ちょうしは どうじゃ!"
	line ""
	textfw4 "GR"
	textfw2 "団"
	textfw0 "は あたらしい"
	katakana "カード"
	hiragana "を"
	line ""
	textfw0 "つかって おるようじゃぞ"
	line ""
	textfw0 "「わるい"
	katakana "リザード」"
	hiragana "とか いった"
	line ""
	textfw0 "「わるい」進化"
	katakana "カード"
	hiragana "じゃ!"
	line ""
	textfw0 "たね"
	katakana "ポケモン"
	hiragana "は いっしょじゃが"
	line ""
	textfw0 "「"
	katakana "リザード」"
	hiragana "へ 進化させるのと"
	line ""
	textfw0 "「わるい"
	katakana "リザード」"
	hiragana "のわるい進化を"
	line ""
	textfw0 "させる 2つ進化が あるようじゃ"
	line ""
	textfw0 "いちど わるい進化をしてしまうと"
	line ""
	textfw0 "わるい進化しか できないようじゃ"
	line ""
	textfw0 "ちょっと むずかしいかも しれんが"
	line ""
	textfw0 "おまえなら うまく できるじゃろ!"
	done

Text0f0d:
	hiragana "どうじゃ ", "<RAMNAME>"
	line ""
	katakana "メール"
	hiragana "は よんでくれとるかの?"
	line ""
	textfw4 "GR"
	textfw2 "団"
	textfw0 "の"
	katakana "ヤツ"
	hiragana "ら 対戦に いろいろな"
	line ""
	textfw0 "じょうけんを つけてくるようじゃな"
	line ""
	textfw0 "じょうけんが あっても"
	line ""
	textfw0 "いつもと おなじじゃ"
	line ""
	textfw0 "なんども対戦して"
	line ""
	textfw0 "あいての"
	katakana "デッキ"
	hiragana "を 研究するのじゃ"
	line ""
	textfw0 "そうして あいての"
	katakana "デッキ"
	hiragana "の"
	line ""
	textfw0 "弱点をつく "
	katakana "デッキ"
	hiragana "をつくるのじゃ"
	line ""
	katakana "ガンバレ ", "<RAMNAME>"
	line ""
	hiragana "わしは おうえんしておるぞ!"
	done

Text0f0e:
	hiragana "おお ", "<RAMNAME>"
	line ""
	textfw0 "ちょうしは いいようじゃのう!"
	line ""
	textfw4 "GR"
	textfw2 "団"
	textfw0 "との対戦も いよいよ"
	line ""
	textfw0 "おおづめじゃのう!"
	line ""
	textfw0 "だが あわてるではないぞ"
	line ""
	textfw0 "いそがば まわれじゃ!"
	line ""
	katakana "クラブ"
	hiragana "のれんちゅうと 対戦して"
	line ""
	katakana "カード"
	hiragana "を あつめるんじゃ"
	line ""
	textfw0 "たくさんの"
	katakana "カード"
	hiragana "があれば"
	line ""
	textfw0 "さまざまな"
	katakana "デッキ"
	hiragana "が つくれるからのう"
	line ""
	textfw0 "がんばるのじゃ ", "<RAMNAME>"
	line ""
	katakana "ゴール"
	hiragana "は もうすぐじゃ!"
	done

Text0f0f:
	textfw0 "<RAMNAME>", "! "
	hiragana "おめでとう!!"
	line ""
	textfw0 "ついに "
	textfw4 "GR"
	textfw2 "団"
	textfw0 "を たおしたな"
	line ""
	textfw0 "だが"
	line ""
	textfw0 "かれらを うらむでないぞ!"
	line ""
	textfw0 "かれらとて "
	katakana "ポケモンカード"
	hiragana "を"
	line ""
	textfw0 "あいする こころに かわりはない"
	line ""
	textfw0 "これからは かれらも"
	line ""
	katakana "ポケモンカード"
	hiragana "の なかまじゃ"
	line ""
	textfw0 "みんなと 対戦して"
	line ""
	katakana "ポケモンカード"
	hiragana "を たのしむのじゃ"
	line ""
	textfw0 "そして りっぱな "
	katakana "カードマスター"
	hiragana "に"
	line ""
	textfw0 "なるんじゃぞ! ", "<RAMNAME>", "!"
	done

Text0f10:
	hiragana "もう!"
	line ""
	katakana "チャレンジマシン"
	hiragana "を ためしたかね?"
	line ""
	textfw0 "わしの 研究のせいかの"
	line ""
	textfw0 "どりょくの けっしょうじゃ!"
	line ""
	textfw0 "ぜひ"
	line ""
	textfw0 "ためしてみてくれ!"
	line ""
	textfw0 "かんたんな"
	katakana "ゲーム"
	hiragana "になっているから"
	line ""
	textfw0 "きがるに あそんでみるといいじゃろう"
	done

Text0f11:
	hiragana "なんだ ", "<RAMNAME>", "か!"
	line ""
	textfw4 "GR"
	textfw2 "団"
	textfw0 "の"
	katakana "キング"
	hiragana "を たおしたって?"
	line ""
	textfw4 "GR"
	textfw2 "団"
	textfw0 "の たたかいに 勝ったのは"
	line ""
	katakana "オレ"
	hiragana "の "
	katakana "サポート"
	hiragana "の おかげだからな!"
	line ""
	textfw0 "かんしゃ しろよ!"
	line ""
	textfw0 "<RAMNAME>"
	done

Text0f12:
	hiragana "いいか! ", "<RAMNAME>"
	line ""
	textfw0 "まってろ!"
	line ""
	textfw0 "いつか さいきょうの"
	katakana "デッキ"
	hiragana "をつくって"
	line ""
	textfw0 "おまえに ちょうせんしてやるからな!"
	line ""
	katakana "グランドマスター"
	hiragana "の"
	line ""
	katakana "グランドマスター"
	textfw2 "杯"
	hiragana "で あおうぜ!"
	done

Text0f13:
	hiragana "やあ ", "<RAMNAME>", "くんか"
	line ""
	textfw0 "なにか ようかい?"
	done

Text0f14:
	hiragana "それじゃあ"
	line ""
	textfw0 "れんしゅう対戦を はじめよう"
	line ""
	textfw4 "D"
	textfw0 "ṛ"
	katakana "オーヤマ"
	hiragana "の "
	katakana "アドバイス"
	hiragana "どおりに"
	line ""
	textfw0 "そうさするんだよ"
	done

Text0f15:
	textfw0 "ミカサ"
	hiragana "と 対戦しますか?"
	done

Text0f16:
	hiragana "また わからなくなったら"
	line ""
	textfw0 "れんしゅうに くるといいよ"
	done

Text0f17:
	hiragana "それじゃあ"
	line ""
	textfw0 "れんしゅう"
	textfw1 "用"
	textfw0 "の"
	katakana "デッキ"
	hiragana "で 対戦だ"
	done

Text0f18:
	textfw0 "サイドカード2枚"
	hiragana "で はじめよう"
	line ""
	textfw0 "こんどは "
	katakana "アドバイス"
	hiragana "が ないからね"
	done

Text0f19:
	hiragana "また いつでも おいで"
	line ""
	textfw0 "きほんは たいせつだからね"
	done

Text0f1a:
	hiragana "だいぶ"
	line ""
	textfw0 "おぼえてきたようですね"
	done

Text0f1b:
	hiragana "このちょうしで がんばって"
	line ""
	textfw0 "勝ち すすんでください"
	done

Text0f1c:
	hiragana "まだまだ ですね"
	line ""
	textfw0 "おちついて かんがえれば 勝てますよ"
	line ""
	textfw0 "れんしゅう対戦を もう いちど"
	line ""
	textfw0 "やってみては どうですか?"
	done

Text0f1d:
	hiragana "どうかな?"
	line ""
	textfw0 "あそびかたは わかったかい?"
	line ""
	textfw0 "これからも たのしく"
	line ""
	katakana "ポケモンカード"
	hiragana "を あそんでください"
	done

Text0f1e:
	hiragana "ひさしぶりだね ", "<RAMNAME>", "くん"
	line ""
	textfw0 "研究員の "
	katakana "ミカサ"
	hiragana "だよ"
	line ""
	katakana "ポケモンカード"
	hiragana "のあそびかたを"
	line ""
	katakana "キチン"
	hiragana "と かくにんして おこう!"
	line ""
	textfw0 "「れんしゅう対戦」で あそびかたを"
	line ""
	textfw0 "かくにんして おくかい?"
	done

Text0f1f:
	textfw0 "ミカサ"
	hiragana "と れんしゅう対戦しますか?"
	done

Text0f20:
	hiragana "わからなくなったら"
	line ""
	textfw0 "いつでも おいでよ・・・"
	line ""
	textfw0 "「れんしゅう対戦」を えらんで"
	line ""
	textfw0 "くれれば いつでも "
	textfw4 "OK"
	textfw0 "だからね"
	done

Text0f21:
	hiragana "それじゃあ"
	line ""
	textfw0 "「れんしゅう対戦」を はじめよう!"
	line ""
	textfw4 "D"
	textfw0 "ṛ"
	katakana "オーヤマ!"
	line ""
	hiragana "おねがいします!"
	done

Text0f22:
	hiragana "まずは きほんてきなことを"
	line ""
	katakana "ミカサ"
	hiragana "くんに きいてみるんじゃ"
	done

Text0f23:
	hiragana "それじゃ ", "<RAMNAME>", "くん"
	line ""
	textfw0 "なにを ききたいんだい?"
	done

Text0f24:
	hiragana "もう きくことは ないかな?"
	done

Text0f25:
	hiragana "では 「ならうより なれろ!」じゃ"
	line ""
	textfw0 "じっさいに やってみよう"
	line ""
	textfw0 "れんしゅう"
	textfw1 "用"
	textfw0 "の "
	katakana "デッキ"
	hiragana "じゃ"
	line ""
	textfw0 "これをつかって はじめよう!"
	line ""
	textfw0 "れんしゅうじゃから"
	line ""
	textfw0 "まずは てじゅんを おぼえるんじゃ"
	line ""
	textfw0 "わしが "
	katakana "アドバイス"
	hiragana "するから"
	line ""
	textfw0 "そのとおりに やってみるんじゃ"
	line ""
	textfw0 "わしの いうとおりに しなければ"
	line ""
	textfw0 "さきに すすまんからな"
	line ""
	textfw0 "「せつめいしょ」を みながら"
	line ""
	textfw0 "やってみると わかりやすいじゃろ"
	line ""
	textfw0 "それでは"
	line ""
	textfw0 "「れんしゅう対戦」の かいしじゃ!"
	done

Text0f26:
	hiragana "どうじゃ こんなかんじで"
	line ""
	textfw0 "対戦するのじゃ おもいだしたかな?"
	line ""
	textfw0 "いまは 「れんしゅう対戦」だから"
	line ""
	textfw0 "いうとおりに そうさしてもらったが"
	line ""
	textfw0 "ほかの たたかいかたも あるからな"
	line ""
	textfw0 "「ふつうに対戦」で ためすといい"
	line ""
	textfw0 "どうじゃ"
	line ""
	textfw0 "どんな"
	katakana "ゲーム"
	hiragana "か わかったかな?"
	line ""
	textfw0 "それとも"
	line ""
	textfw0 "もういちど やってみるかね?"
	done

Text0f27:
	textfw0 "「"
	hiragana "れんしゅう対戦」 しますか?"
	done

Text0f28:
	hiragana "では もういちど 対戦じゃ!"
	done

Text0f29:
	hiragana "そうか"
	line ""
	textfw0 "もし わからなくなったら"
	line ""
	katakana "ミカサ"
	hiragana "と もういちど"
	line ""
	textfw0 "対戦してみると いいじゃろう"
	done

Text0f2a:
	hiragana "わからなくなったら"
	line ""
	textfw0 "いつでも おいでよ・・・"
	line ""
	textfw0 "「れんしゅう対戦」を えらんで"
	line ""
	textfw0 "くれれば いつでも "
	textfw4 "OK"
	textfw0 "だからね"
	done

Text0f2b:
	textfw0 "ゲーム"
	hiragana "の"
	katakana "セーブ"
	hiragana "は"
	line ""
	textfw4 "START"
	katakana "ボタン"
	hiragana "を おして"
	line ""
	katakana "メニュー"
	hiragana "から 「にっき」を"
	line ""
	textfw0 "えらぶと できるからね"
	line ""
	textfw0 "そこの"
	katakana "パソコン"
	hiragana "を つかうことでも"
	line ""
	textfw0 "いろんなことが できるからね"
	line ""
	textfw0 "まあ いろいろ"
	line ""
	textfw0 "ためしてみると いいよ"
	done

Text0f2c:
	hiragana "これが "
	textfw4 "D"
	textfw0 "ṛ"
	katakana "オーヤマ"
	hiragana "のつくった"
	line ""
	katakana "チャレンジマシン"
	hiragana "だ!"
	line ""
	katakana "チャレンジマシン"
	hiragana "は"
	line ""
	katakana "ポケモンカード"
	hiragana "の 対戦"
	katakana "ゲームマシン"
	hiragana "だ"
	line ""
	katakana "ゲーム"
	hiragana "の"
	katakana "ルール"
	hiragana "は かんたんだ"
	line ""
	textfw0 " "
	line ""
	textfw0 "1つの"
	katakana "デッキ"
	hiragana "で "
	katakana "マシン"
	hiragana "がえらんだ"
	line ""
	textfw0 "5にんの"
	katakana "メンバー"
	hiragana "と 対戦するんだ!"
	line ""
	textfw0 "1つの"
	katakana "デッキ"
	hiragana "で 5にんの"
	katakana "メンバー"
	line ""
	hiragana "ぜんいんに 勝てば "
	katakana "クリア"
	hiragana "だ"
	line ""
	textfw0 "そのほかにも れんしょうきろくにも"
	line ""
	textfw0 "ちょうせんすることが できるぞ!"
	line ""
	textfw0 "さあ ", "<RAMNAME>", "くん"
	line ""
	katakana "デッキ"
	hiragana "をつくって ちょうせんしよう!"
	done

Text0f2d:
	hiragana "しっているとは おもうけれど"
	line ""
	katakana "カードクラブ"
	hiragana "は 8つあるんだ"
	line ""
	katakana "クラブ"
	hiragana "は "
	katakana "バトル アクア エレキ"
	line ""
	textfw0 "グリーン エスパー ファイア・・・"
	line ""
	hiragana "そして "
	katakana "ストーン サイエンス"
	hiragana "の"
	line ""
	textfw0 "8つの"
	katakana "クラブ"
	hiragana "だ"
	line ""
	textfw0 "でも "
	textfw4 "GR"
	textfw2 "団"
	textfw0 "が やってきて"
	line ""
	textfw0 "どうなってるかが しんぱいだよ"
	done

Text0f2e:
	hiragana "ついに"
	line ""
	textfw4 "GR"
	textfw2 "団"
	textfw0 "を たおしたんだね"
	line ""
	textfw0 "やっぱり"
	line ""
	textfw0 "<RAMNAME>", "は "
	katakana "スゴイ"
	hiragana "なぁ!"
	done

Text0f2f:
	textfw0 "カード対戦"
	hiragana "で 勝つと"
	line ""
	textfw0 "拡張"
	katakana "パック"
	hiragana "が もらえるんだ"
	line ""
	textfw0 "拡張"
	katakana "パック"
	hiragana "の なかには"
	line ""
	katakana "カード"
	hiragana "が 10枚はいってる"
	line ""
	textfw0 "拡張"
	katakana "パック"
	hiragana "の しゅるいによって"
	line ""
	textfw0 "はいっている"
	katakana "カード"
	hiragana "は ちがうんだ"
	line ""
	textfw0 "対戦あいてによって もらえる"
	line ""
	textfw0 "拡張"
	katakana "パック"
	hiragana "のしゅるいは ちがうけど"
	line ""
	textfw4 "GR"
	textfw2 "団"
	textfw0 "が"
	line ""
	katakana "カード"
	hiragana "を もっていったからな"
	line ""
	textfw4 "GR"
	textfw2 "団"
	textfw0 "のやつらを たおさないと"
	line ""
	textfw0 "拡張"
	katakana "パック"
	hiragana "は ふえないだろうな"
	done

Text0f30:
	hiragana "おめでとう ", "<RAMNAME>", "くん"
	line ""
	textfw4 "GR"
	textfw2 "団"
	textfw0 "を やっつけたんだって!"
	line ""
	textfw0 "拡張"
	katakana "パック"
	hiragana "も とりかえしたし!"
	line ""
	textfw4 "GR"
	textfw2 "団"
	textfw0 "の拡張"
	katakana "パック"
	hiragana "も ふえたんだろ!"
	line ""
	textfw0 "これで もっと たのしい"
	line ""
	katakana "ポケモンカード"
	hiragana "の対戦が できるよ"
	done

Text0f31:
	hiragana "このおくの"
	line ""
	textfw0 "電"
	textfw1 "算室"
	textfw0 "に いってごらん"
	line ""
	textfw0 "つくった"
	katakana "デッキ"
	hiragana "を きろくする"
	line ""
	katakana "デッキ"
	hiragana "きろく"
	katakana "マシン"
	hiragana "や"
	line ""
	katakana "ボク"
	hiragana "らの 研究のけっかを おさめる"
	line ""
	katakana "オートデッキマシン"
	hiragana "が あるんだよ"
	line ""
	textfw0 "あと むこうの"
	katakana "ヘヤ"
	hiragana "には"
	line ""
	katakana "トレーニングルーム"
	hiragana "が できたんだ"
	line ""
	textfw4 "D"
	textfw0 "ṛ"
	katakana "オーヤマ"
	hiragana "が "
	katakana "ポケモンカード"
	hiragana "を"
	line ""
	textfw0 "はじめる ひとのために つくったんだ"
	line ""
	textfw0 "いちど"
	line ""
	textfw0 "いってごらんよ"
	done

Text0f32:
	hiragana "ついに "
	textfw4 "GR"
	textfw2 "団"
	textfw0 "の"
	katakana "キング"
	hiragana "を"
	line ""
	textfw0 "たおしたんだってね"
	line ""
	textfw0 "きみが このたたかいで 対戦した"
	line ""
	katakana "デッキ"
	hiragana "のじょうほうは"
	line ""
	katakana "ボク"
	hiragana "らが ぶんせきして"
	line ""
	katakana "オートデッキマシン"
	hiragana "に いれておいたよ"
	line ""
	katakana "ポケモンカード"
	hiragana "は おくが ふかいから"
	line ""
	katakana "ボク"
	hiragana "らの研究に おわりはないんだ"
	done

Text0f33:
	textfw0 "ポケモン"
	hiragana "は なにを するにも"
	line ""
	katakana "エネルギー"
	hiragana "が ひつようなんだ"
	line ""
	katakana "エネルギー"
	hiragana "が ついていないと"
	line ""
	katakana "ワザ"
	hiragana "も つかえないし"
	line ""
	katakana "バトル場"
	hiragana "から"
	line ""
	textfw0 "「にげる」ことも できない"
	line ""
	katakana "エネルギー"
	hiragana "のしゅるいは 「草」「炎」"
	line ""
	textfw0 "「水」「雷」「超」「闘」の 6つある"
	line ""
	katakana "ポケモン"
	hiragana "によって ひつようとする"
	line ""
	katakana "エネルギー"
	hiragana "は ちがうんだ"
	line ""
	textfw0 "どの"
	katakana "ポケモン"
	hiragana "に どの"
	katakana "エネルギー"
	hiragana "が"
	line ""
	textfw0 "ひつようかは おぼえておこう"
	done

Text0f34:
	textfw0 "ポケモン"
	hiragana "は "
	katakana "ワザ"
	hiragana "をつかうことで"
	line ""
	textfw0 "あいての"
	katakana "ポケモン"
	hiragana "を こうげきできる"
	line ""
	katakana "ワザ"
	hiragana "を つかうには"
	line ""
	katakana "エネルギー"
	hiragana "が ひつようなんだ"
	line ""
	katakana "アズマオウ"
	hiragana "の 「たきのぼり」なら"
	line ""
	textfw0 "ひつような"
	katakana "エネルギー"
	hiragana "は 「", "<WATER>", "<COLORLESS>", "」"
	line ""
	textfw0 "「", "<WATER>", "<COLORLESS>", "」は 水"
	katakana "エネルギー1"
	hiragana "つと"
	line ""
	textfw0 "どの"
	katakana "エネルギー"
	hiragana "でもいいから もう1つ"
	line ""
	textfw0 "ひつような "
	katakana "エネルギー"
	hiragana "は"
	line ""
	katakana "ワザ"
	hiragana "によって ちがうからね"
	done

Text0f35:
	textfw0 "バトル場"
	hiragana "の"
	katakana "ポケモン"
	hiragana "と"
	line ""
	katakana "ベンチ"
	hiragana "の"
	katakana "ポケモン"
	hiragana "を いれかえるのは"
	line ""
	textfw0 "「にげる」"
	katakana "コマンド"
	hiragana "を"
	line ""
	textfw0 "つかうことで できるんだ"
	line ""
	katakana "バトル場"
	hiragana "の"
	katakana "ポケモン"
	hiragana "が "
	katakana "ピンチ"
	hiragana "なら"
	line ""
	katakana "ベンチ"
	hiragana "へ にがして あげよう"
	line ""
	textfw0 "「にげる」ときにも"
	line ""
	katakana "エネルギー"
	hiragana "は ひつようなんだ"
	line ""
	textfw0 "ひつような"
	katakana "エネルギー"
	hiragana "の数は"
	line ""
	katakana "ポケモン"
	hiragana "によって ちがうからね"
	done

Text0f36:
	textfw0 "ポケモンカード"
	hiragana "は たね"
	katakana "ポケモン"
	line ""
	textfw0 "1進化 2進化"
	hiragana "の 3つが ある"
	line ""
	katakana "ゼニガメ"
	hiragana "が たね "
	katakana "カメール"
	hiragana "が 1進化"
	line ""
	katakana "カメックス"
	hiragana "が 2進化 というかんじだ"
	line ""
	textfw0 "いつでも 場にだせるのは"
	line ""
	textfw0 "たね"
	katakana "ポケモン"
	hiragana "だけなんだ"
	line ""
	textfw0 "たね"
	katakana "ポケモン"
	hiragana "が 場にいれば"
	line ""
	textfw0 "1進化"
	katakana "カード"
	hiragana "をだすことで 進化できる"
	line ""
	textfw0 "2進化するには 1進化"
	katakana "カード"
	hiragana "が"
	line ""
	textfw0 "場に でているひつようが ある"
	line ""
	textfw0 "つまり "
	katakana "ゼニガメ"
	hiragana "が 場にいないと"
	line ""
	katakana "カメール"
	hiragana "には 進化できないし"
	line ""
	katakana "カメール"
	hiragana "が いなければ"
	line ""
	katakana "カメックス"
	hiragana "に 進化できないんだ"
	done

Text0f37:
	textfw0 "ポケモン"
	hiragana "の中には 特殊能力を"
	line ""
	textfw0 "もっているものが いる"
	line ""
	textfw0 "特殊能力には 場にでるだけで"
	line ""
	textfw0 "こうかが あるものや"
	line ""
	textfw0 "その特殊能力を つかわないと"
	line ""
	textfw0 "こうかが ないものが ある"
	line ""
	textfw0 "特殊能力を つかうには"
	line ""
	textfw0 "「とくしゅ」の"
	katakana "コマンド"
	hiragana "を つかうんだ"
	line ""
	textfw0 "特殊能力には いろいろあるから"
	line ""
	katakana "カード"
	hiragana "のせつめいを よく よむんだよ"
	done

Text0f38:
	textfw0 "「"
	hiragana "じぶんの番」は"
	line ""
	katakana "ワザ"
	hiragana "をつかうことで おわるんだ"
	line ""
	katakana "ワザ"
	hiragana "の"
	katakana "エネルギー"
	hiragana "が たりない"
	line ""
	textfw0 "「"
	katakana "マヒ "
	hiragana "ねむり」で うごけないときは"
	line ""
	textfw0 "「おわり」の"
	katakana "コマンド"
	hiragana "を えらんで"
	line ""
	textfw4 "A"
	katakana "ボタン"
	hiragana "を おすんだ"
	line ""
	textfw0 "これで 「じぶんの番」が おわり"
	line ""
	textfw0 "「あいての番」に なるんだ"
	line ""
	textfw0 "なにも できないときは"
	line ""
	textfw0 "「おわり」の"
	katakana "コマンド"
	hiragana "を えらぼう"
	done

Text0f39:
	textfw0 "対戦"
	hiragana "の勝ち まけは"
	line ""
	katakana "サイドカード"
	hiragana "で きまるんだ"
	line ""
	katakana "サイドカード"
	hiragana "は あいての"
	katakana "ポケモン"
	hiragana "を"
	line ""
	textfw0 "「きぜつ」させたときに ひける"
	katakana "カード"
	line ""
	textfw0 "サイドカード"
	hiragana "の枚数だけ あいての"
	line ""
	katakana "ポケモン"
	hiragana "を「きぜつ」させると 勝ちだ"
	line ""
	katakana "サイドカード4枚戦"
	hiragana "なら 4ひきの"
	line ""
	katakana "ポケモン"
	hiragana "を「きぜつ」させると 勝ちだ"
	line ""
	textfw0 "あとは じぶんの番に 山札から"
	line ""
	katakana "カード"
	hiragana "を ひけなかったら まけになる"
	line ""
	textfw0 "山札の のこりには"
	line ""
	textfw0 "きを つけるんだよ"
	done

Text0f3a:
	textfw0 "ホッホー! "
	hiragana "やあ!"
	line ""
	textfw0 "<RAMNAME>", "くん よくきたね!"
	line ""
	textfw0 "どうだい ", "<RAMNAME>", "くん"
	line ""
	textfw0 "すてきな "
	katakana "トレーニング"
	textfw1 "室"
	hiragana "だろう"
	line ""
	textfw0 "もっと "
	katakana "ポケモンカード"
	hiragana "を"
	line ""
	textfw0 "りかいしてもらうために つくったんだ"
	line ""
	katakana "ステップアップ"
	hiragana "ほうしきで"
	line ""
	katakana "トレーニング"
	hiragana "できるんだ"
	done

Text0f3b:
	textfw0 "ホッホー! ", "<RAMNAME>"
	hiragana "くん"
	line ""
	katakana "トレーニング"
	hiragana "して ゆくかい?"
	line ""
	katakana "ステップアップ"
	hiragana "ほうしきで"
	line ""
	katakana "トレーニング "
	hiragana "できるんだよ"
	done

Text0f3c:
	textfw0 "ホッホー! ", "<RAMNAME>"
	hiragana "くん"
	line ""
	textfw0 "また きてくれたのかい?"
	line ""
	katakana "ボク"
	hiragana "も "
	katakana "デッキ"
	hiragana "をつくったから"
	line ""
	textfw0 "こんどは ふつうに対戦も できるよ"
	line ""
	textfw0 "それとも "
	katakana "トレーニング"
	hiragana "の"
	line ""
	textfw0 "やりなおしかい?"
	done

Text0f3d:
	textfw0 "ホッホー! ", "<RAMNAME>"
	hiragana "くん"
	line ""
	textfw4 "GR"
	textfw2 "団"
	textfw0 "を たおしたんだって?"
	line ""
	textfw0 "ここでの "
	katakana "トレーニング"
	hiragana "は"
	line ""
	textfw0 "やくにたったかい?"
	line ""
	textfw0 "ところで どうだい"
	line ""
	katakana "トレーニング"
	hiragana "して ゆくかい?"
	done

Text0f3e:
	hiragana "まずは "
	katakana "ステップ1"
	hiragana "からだけど"
	line ""
	textfw0 "やって みるかい?"
	done

Text0f3f:
	hiragana "どの"
	katakana "ステップ"
	hiragana "で"
	line ""
	katakana "トレーニング"
	hiragana "するんだい?"
	done

Text0f40:
	textfw0 "対戦"
	hiragana "かい?"
	line ""
	textfw0 "それとも "
	katakana "トレーニング"
	hiragana "かい?"
	done

Text0f41:
	textfw0 "ホッホー!!"
	line ""
	hiragana "そうかい ざんねんだね"
	line ""
	katakana "トレーニング"
	hiragana "を やりたくなったら"
	line ""
	textfw0 "いつでも おいでよ"
	line ""
	katakana "ボク"
	hiragana "は ここにいるからさ"
	line ""
	textfw0 "じゃあね ", "<RAMNAME>", "くん"
	done

Text0f42:
	textfw0 "「ステップ1」"
	hiragana "だね・・・"
	line ""
	textfw0 "1ばんの"
	katakana "テーブル"
	hiragana "に ついてよ"
	done

Text0f43:
	hiragana "まずは"
	line ""
	katakana "ポケモンカード"
	hiragana "は 「進化」だよ"
	line ""
	textfw0 "「たね"
	katakana "ポケモン」"
	hiragana "を 「1進化"
	katakana "カード」"
	line ""
	textfw0 "「2進化カード」"
	hiragana "で 進化させよう"
	line ""
	katakana "トレーニング"
	hiragana "だから "
	katakana "キミ"
	hiragana "の"
	katakana "デッキ"
	hiragana "は"
	line ""
	textfw0 "つかうことが できないよ"
	line ""
	textfw0 "「"
	katakana "トレーニングデッキ」"
	hiragana "を つかって"
	line ""
	textfw0 "対戦して もらうからね"
	line ""
	katakana "サイドカード"
	hiragana "は 4枚だ"
	line ""
	katakana "トレーニング対戦"
	hiragana "を はじめよう!"
	done

Text0f44:
	hiragana "さすがだね ", "<RAMNAME>", "くん"
	line ""
	katakana "ステップ1 クリア"
	hiragana "だ!!"
	done

Text0f45:
	textfw0 "ホッホー! "
	hiragana "このちょうしで"
	line ""
	textfw0 "つぎの"
	katakana "ステップ"
	hiragana "にも "
	katakana "チャレンジ"
	hiragana "だよ"
	line ""
	textfw0 "また "
	katakana "トレーニング"
	hiragana "に おいでよ"
	line ""
	textfw0 "じゃあね! "
	katakana "ホッホー!!"
	done

Text0f46:
	textfw0 "ホッホー! "
	hiragana "きほんてきなところが"
	line ""
	textfw0 "わかって いないようだね"
	line ""
	katakana "ミカサ"
	hiragana "くんと 「れんしゅう対戦」を"
	line ""
	textfw0 "したほうが いいとおもうよ"
	line ""
	katakana "ホッホー!! "
	hiragana "じゃあね!"
	line ""
	textfw0 "また "
	katakana "トレーニング"
	hiragana "に おいでよ"
	done

Text0f47:
	textfw0 "「ステップ2」"
	hiragana "だね・・・"
	line ""
	textfw0 "2ばんの"
	katakana "テーブル"
	hiragana "に ついてよ"
	done

Text0f48:
	textfw0 "「ステップ2」"
	hiragana "は 「どく・"
	katakana "マヒ・"
	line ""
	textfw0 " "
	hiragana "こんらん・ねむり」の特殊状態だよ"
	line ""
	textfw0 "それぞれの こうかを"
	line ""
	textfw0 "かんがえて 対戦してみよう"
	line ""
	textfw0 "「どく・"
	katakana "マヒ・"
	hiragana "こんらん・ねむり」の"
	line ""
	textfw0 "じょうたいに なってしまったら"
	line ""
	katakana "ポケモン"
	hiragana "を"
	katakana "バトル場"
	hiragana "から にがしたり"
	line ""
	textfw0 "「なんでもなおし」で かいふくだ"
	line ""
	textfw0 "それと 「"
	katakana "トレーニング」"
	hiragana "だからね"
	line ""
	katakana "キミ"
	hiragana "の"
	katakana "デッキ"
	hiragana "は つかえないよ"
	line ""
	textfw0 "「"
	katakana "トレーニングデッキ」"
	hiragana "を"
	line ""
	textfw0 "つかって 対戦してもらうからね"
	line ""
	katakana "サイドカード"
	hiragana "は 4枚だ"
	line ""
	katakana "トレーニング対戦"
	hiragana "を はじめよう!"
	done

Text0f49:
	hiragana "さすがだね ", "<RAMNAME>", "くん"
	line ""
	katakana "ステップ2 クリア"
	hiragana "だ!!"
	done

Text0f4a:
	textfw0 "「"
	hiragana "どく・"
	katakana "マヒ・"
	hiragana "こんらん・ねむり」の"
	line ""
	textfw0 "こうかを りかいしよう"
	line ""
	katakana "パソコン"
	hiragana "の「ようごじてん」で"
	line ""
	textfw0 "かくにんすると いいぞ"
	line ""
	katakana "ホッホー!! "
	hiragana "じゃあね!"
	line ""
	textfw0 "また "
	katakana "トレーニング"
	hiragana "に おいでよ"
	done

Text0f4b:
	textfw0 "「ステップ3」"
	hiragana "だね・・・"
	line ""
	textfw0 "3ばんの"
	katakana "テーブル"
	hiragana "に ついてよ"
	done

Text0f4c:
	textfw0 "「ステップ3」"
	hiragana "は"
	line ""
	textfw0 "「特殊能力」を つかってみよう"
	line ""
	katakana "ポケモン"
	hiragana "の 「特殊能力」は"
	line ""
	textfw0 "「特殊能力」の こうかだけでなく"
	line ""
	katakana "トレーナーカード"
	hiragana "などと くみあわせて"
	line ""
	textfw0 "つかうと こうかは ぜつだいだ"
	line ""
	textfw0 "また 「"
	katakana "トレーニングデッキ」"
	hiragana "を"
	line ""
	textfw0 "つかっての 対戦だからね"
	line ""
	katakana "サイドカード"
	hiragana "は 4枚だ"
	line ""
	katakana "トレーニング対戦"
	hiragana "を はじめよう!"
	done

Text0f4d:
	hiragana "すごいや ", "<RAMNAME>", "くん"
	line ""
	katakana "ステップ3 クリア"
	hiragana "だ!!"
	done

Text0f4e:
	textfw0 "ホッホー! "
	hiragana "これで"
	line ""
	katakana "ステップ3"
	hiragana "を "
	katakana "クリア"
	hiragana "だ!"
	line ""
	textfw0 "さすがだね"
	line ""
	katakana "ステップ4"
	hiragana "は まだ じゅんび中だ"
	line ""
	textfw0 "そのうち はじめるから"
	line ""
	textfw0 "たまには ここに きておくれよ!"
	line ""
	katakana "ホッホー!!"
	line ""
	hiragana "じゃあね! まってるよ!"
	done

Text0f4f:
	textfw0 "ホッホー! "
	hiragana "これで"
	line ""
	katakana "ステップ3"
	hiragana "を "
	katakana "クリア"
	hiragana "だ!"
	line ""
	katakana "ステップ4"
	hiragana "は "
	katakana "ボク"
	hiragana "と対戦だ!"
	line ""
	textfw0 "いつでも 対戦に おいでよ!"
	line ""
	katakana "ホッホー!!"
	line ""
	hiragana "じゃあね! まってるよ!"
	done

Text0f50:
	hiragana "う"
	textfw4 "~"
	textfw0 "ん 「特殊能力」は"
	line ""
	textfw0 "つかいこなすのは むずかしいからね"
	line ""
	textfw0 "「特殊能力」の せつめいを"
	line ""
	textfw0 "じっくり よんで りかいするんだ"
	line ""
	textfw0 "そして ほかの"
	katakana "カード"
	hiragana "と"
	line ""
	textfw0 "くみあわせると なにかできるかもね"
	line ""
	katakana "ホッホー!! "
	hiragana "じゃあね!"
	line ""
	textfw0 "また "
	katakana "トレーニング"
	hiragana "に おいでよ"
	done

Text0f51:
	textfw0 "「"
	hiragana "ふつうに対戦」だね・・・"
	line ""
	textfw0 "4ばんの"
	katakana "テーブル"
	hiragana "に ついてよ"
	done

Text0f52:
	textfw0 "ホッホー! 「ステップ4」"
	hiragana "は"
	line ""
	katakana "ボク"
	hiragana "と しんけんしょうぶだ!!"
	line ""
	katakana "ボク"
	hiragana "の"
	katakana "デッキ"
	hiragana "と"
	line ""
	katakana "キミ"
	hiragana "の"
	katakana "デッキ"
	hiragana "で 対戦だよ"
	line ""
	katakana "ホッホー! ボク"
	hiragana "は"
	line ""
	textfw0 "2つ"
	katakana "デッキ"
	hiragana "を つくってあるんだ"
	line ""
	textfw0 "さあ"
	line ""
	textfw0 "どの"
	katakana "デッキ"
	hiragana "で 対戦しようかな?"
	line ""
	katakana "サイドカード"
	hiragana "は 4枚だ"
	line ""
	textfw0 "対戦を はじめよう!"
	done

Text0f53:
	textfw0 "ホッホー?"
	line ""
	hiragana "えっ まけちゃった"
	line ""
	textfw0 "やっぱり "
	katakana "キミ"
	hiragana "はつよいや!"
	line ""
	textfw0 "とっておきの これを あげよう"
	done

Text0f54:
	hiragana "もう ひとつの"
	katakana "デッキ"
	hiragana "のほうが"
	line ""
	textfw0 "よかったのかなぁ"
	textfw4 "~"
	line ""
	textfw0 "また 対戦にきてよ"
	line ""
	textfw0 "こんどは まけないからさ!!"
	line ""
	katakana "ホッホー!!"
	line ""
	hiragana "じゃあね! まってるよ!"
	done

Text0f55:
	textfw0 "ホッホー!!"
	line ""
	hiragana "どうだい まいったかい"
	line ""
	katakana "ボク"
	hiragana "だって"
	line ""
	textfw0 "この"
	katakana "ヘヤ"
	hiragana "を まかされているんだ"
	line ""
	katakana "ホッホー! "
	hiragana "そう"
	line ""
	textfw0 "かんたんには まけられないよ"
	line ""
	textfw0 "また 「"
	katakana "ステップ1」"
	hiragana "から"
	line ""
	textfw0 "やりなおしてみるかい?"
	done

Text0f56:
	textfw4 "D"
	textfw0 "ṛオーヤマ"
	hiragana "の めいれいで"
	line ""
	katakana "トレーニング"
	textfw1 "室"
	hiragana "を つくったんだけど"
	line ""
	textfw0 "あらい"
	katakana "モン"
	hiragana "のやつ"
	line ""
	textfw0 "こんなに ひろくしやがって!"
	line ""
	katakana "ステップ"
	hiragana "が かわるたびに"
	line ""
	textfw0 "だいいどう じゃないか!!"
	done

Text0f57:
	hiragana "よくきた ", "<RAMNAME>", "・・・"
	done

Text0f58:
	hiragana "われら 3にん・・・"
	done

Text0f59:
	textfw0 "イシイ! "
	hiragana "こっちを むけ!"
	done

Text0f5a:
	hiragana "あー・・・?"
	done

Text0f5b:
	hiragana "われら 3にん 無のさいだんを"
	line ""
	textfw0 "まもるもの なり!"
	line ""
	textfw4 "GR"
	textfw2 "団"
	textfw0 "の"
	katakana "キャッスル"
	hiragana "に いきたくば"
	line ""
	textfw0 "われら 3にんと たたかうのだ!"
	line ""
	textfw0 "ぜんいんに 勝てれば さいだんにある"
	line ""
	textfw0 "「無の"
	textfw4 "GR"
	textfw2 "団"
	katakana "コイン」"
	hiragana "を わたそう!"
	line ""
	textfw0 "われら 3にん とくていの"
	katakana "カード"
	hiragana "を"
	line ""
	textfw0 "いれなければ たたかわないぞ"
	line ""
	textfw0 "さあ だれからでも いいぞ"
	line ""
	textfw0 "われら 3にんと たたかうのだ!"
	done

Text0f5c:
	hiragana "おう おう おうー"
	line ""
	textfw0 "みんなに かったなぁー"
	line ""
	textfw0 "それじゃ 「無の"
	textfw4 "GR"
	textfw2 "団"
	katakana "コイン」"
	hiragana "を"
	line ""
	textfw0 "わたすぞー"
	done

Text0f5d:
	textfw4 "GR"
	textfw2 "団"
	hiragana "の"
	katakana "キャッスル"
	hiragana "に はいるにはー"
	line ""
	textfw0 "「超の"
	textfw4 "GR"
	textfw2 "団"
	katakana "コイン」"
	hiragana "が いるんだぞー"
	line ""
	textfw0 "超の"
	textfw4 "GR"
	textfw2 "団"
	textfw0 "の ようさいに いって"
	line ""
	katakana "リーダー"
	hiragana "の "
	katakana "マミ"
	hiragana "に あうんだー"
	line ""
	textfw0 "超の"
	textfw4 "GR"
	textfw2 "団"
	textfw0 "のようさいに"
	line ""
	textfw0 "いって こーーーーい!!"
	done

Text0f5e:
	hiragana "あー! ", "<RAMNAME>", "ー"
	line ""
	textfw0 "「超の"
	textfw4 "GR"
	textfw2 "団"
	katakana "コイン」"
	hiragana "もってんじゃん"
	line ""
	textfw0 "じゃあ もう "
	textfw4 "GR"
	textfw2 "団"
	textfw0 "の"
	katakana "キャッスル"
	hiragana "に"
	line ""
	textfw0 "はいれるんだなー"
	line ""
	textfw4 "GR"
	textfw2 "団"
	textfw0 "じゃない"
	katakana "ヤツ"
	hiragana "が "
	katakana "キャッスル"
	hiragana "に"
	line ""
	textfw0 "はいるのは はじめてだー!"
	line ""
	katakana "ビルリッチ"
	hiragana "さまに あったら"
	line ""
	textfw0 "よろしくなー"
	done

Text0f5f:
	hiragana "わしゃあ 無の"
	textfw4 "GR"
	textfw2 "団"
	textfw0 "の"
	katakana "ニシジマ"
	hiragana "じゃあ"
	line ""
	textfw0 "わしと 対戦するんじゃな?"
	line ""
	textfw0 "「", "<RAMTEXT>", "」ぜよ"
	line ""
	textfw0 "こいつを 4枚 "
	katakana "デッキ"
	hiragana "にいれろ!"
	line ""
	textfw0 "そうすれば 対戦してやるぜよ!"
	line ""
	textfw0 " "
	line ""
	textfw0 "じゃが わしゃあ きまぐれでの"
	line ""
	textfw0 "対戦したら いれる"
	katakana "カード"
	hiragana "をかえるぜよ"
	line ""
	textfw0 "じゃから かくごして"
	line ""
	textfw0 "対戦を いどむぜよ!"
	done

Text0f60:
	hiragana "こんどは"
	line ""
	textfw0 "「", "<RAMTEXT>", "」じゃ"
	line ""
	textfw0 "「", "<RAMTEXT>", "」を"
	line ""
	textfw0 "4枚そろえて きたろうな!"
	line ""
	textfw0 "そろってなけりゃ"
	line ""
	textfw0 "わしゃあ 対戦せんぜよ!"
	done

Text0f61:
	textfw0 "「", "<RAMTEXT>", "」"
	hiragana "じゃ!"
	line ""
	textfw0 "ちゃんと4枚 いれてきたじゃろうな?"
	line ""
	textfw0 "そうでなくては 対戦せんぜよ"
	line ""
	textfw0 "対戦をはじめて いいんじゃな?"
	done

Text0f62:
	textfw0 "ニシジマ"
	hiragana "と 対戦しますか?"
	done

Text0f63:
	hiragana "おいおい"
	line ""
	textfw0 "「", "<RAMTEXT>", "」"
	line ""
	textfw0 "こいつが 4枚 はいってなけりゃ"
	line ""
	textfw0 "わしゃあ 対戦せんぜよ"
	line ""
	katakana "カード"
	hiragana "のじゅんびを してから"
	line ""
	textfw0 "対戦に くるぜよ!"
	done

Text0f64:
	hiragana "もし "
	katakana "カード"
	hiragana "が ないなら"
	line ""
	katakana "ヒント"
	hiragana "を やるぜよ"
	line ""
	katakana "カード"
	hiragana "を さがすなら"
	line ""
	katakana "パソコン"
	hiragana "の"
	katakana "カードアルバム"
	hiragana "ぜよ"
	line ""
	katakana "アルバム"
	hiragana "で 拡張"
	katakana "パック"
	hiragana "のなかを みて"
	line ""
	textfw0 "ひつような"
	katakana "カード"
	hiragana "を さがすぜよ"
	line ""
	textfw0 "あとは その拡張"
	katakana "パック"
	hiragana "を"
	line ""
	textfw0 "くれる"
	katakana "ヤツ"
	hiragana "を さがすだけぜよ"
	line ""
	textfw0 "それでも"
	katakana "ダメ"
	hiragana "なら "
	katakana "ギフトセンター"
	hiragana "で"
	line ""
	textfw0 "ともだちから もらうぜよ"
	done

Text0f65:
	textfw0 "サイドカード"
	hiragana "は 6枚じゃあ!"
	line ""
	textfw0 "勝ったら 拡張"
	katakana "パック"
	hiragana "を やるぜよ!!"
	done

Text0f66:
	hiragana "わしを みて おそれを なしたか!"
	line ""
	textfw0 "それも しかたないぜよ!"
	line ""
	textfw0 "どきょうを つけてから"
	line ""
	textfw0 "わしに いどむぜよ!!"
	done

Text0f67:
	hiragana "また わしと 対戦するんじゃな?"
	line ""
	textfw0 "いいどきょうじゃ きにいったぜよ!"
	line ""
	textfw0 "こんかいは そうじゃのぉ"
	line ""
	textfw0 "「", "<RAMTEXT>", "」!"
	line ""
	textfw0 "「", "<RAMTEXT>", "」を"
	line ""
	textfw0 "4枚いれたら 対戦したるぜよ"
	line ""
	textfw0 "どうじゃ 対戦するんか?"
	done

Text0f68:
	textfw0 "「", "<RAMTEXT>", "」"
	line ""
	hiragana "うん これぜよ!"
	line ""
	textfw0 "「", "<RAMTEXT>", "」を"
	line ""
	katakana "デッキ"
	hiragana "に4枚 いれるぜよ"
	line ""
	textfw0 "そろってなけりゃ"
	line ""
	textfw0 "わしゃあ 対戦せんぜよ!"
	done

Text0f69:
	hiragana "だいじょうぶじゃろうな?"
	line ""
	textfw0 "「", "<RAMTEXT>", "」"
	line ""
	textfw0 "この"
	katakana "カード"
	hiragana "が 4枚 はいっとらんと"
	line ""
	textfw0 "対戦は やらんぜよ"
	line ""
	katakana "カード"
	hiragana "が はいっとれば"
	line ""
	textfw0 "対戦 かいしぜよ"
	done

Text0f6a:
	hiragana "おいおい いった"
	katakana "カード"
	hiragana "が"
	line ""
	katakana "デッキ"
	hiragana "に 4枚 はいっとらんぜよ"
	line ""
	textfw0 "「", "<RAMTEXT>", "」"
	line ""
	textfw0 "こいつが はいっとらんぜよ"
	line ""
	katakana "カード"
	hiragana "が 4枚 はいっとらんから"
	line ""
	textfw0 "わしゃあ 対戦せんぜよ"
	done

Text0f6b:
	textfw0 "カード"
	hiragana "は ちゃんと はいっとるから"
	line ""
	textfw0 "もんだい なしぜよ"
	line ""
	katakana "サイドカード"
	hiragana "は 6枚で"
	line ""
	textfw0 "対戦 かいしぜよ!"
	done

Text0f6c:
	hiragana "もし "
	katakana "カード"
	hiragana "が たりんのなら"
	line ""
	textfw0 "どーにかして てにいれるぜよ"
	line ""
	katakana "カード"
	hiragana "が はいってなけりゃ"
	line ""
	textfw0 "対戦に ならんぜよ!"
	done

Text0f6d:
	hiragana "ここまで くる"
	katakana "ヤツ"
	hiragana "は"
	line ""
	textfw0 "さすがに つよいぜよ はっははは!!"
	done

Text0f6e:
	hiragana "わしゃあ"
	line ""
	textfw0 "ひさびさに まけたぜよ"
	line ""
	textfw0 "こんつぎゃあ いれる"
	katakana "カード"
	hiragana "を"
	line ""
	textfw0 "かえな あかんぜよ"
	done

Text0f6f:
	hiragana "はっははは!"
	line ""
	textfw0 "わしゃあ かんたんには まけんぜよ!"
	line ""
	textfw0 "また くると いい!"
	line ""
	textfw0 "だが おぼえておくぜよ"
	line ""
	textfw0 "つぎの 対戦のときは"
	line ""
	textfw0 "入れる"
	katakana "カード"
	hiragana "を かえるつもりぜよ"
	done

Text0f70:
	hiragana "しょうこりもなく"
	line ""
	textfw0 "また まけてしもうたぜよ!"
	done

Text0f71:
	hiragana "この"
	katakana "デッキ"
	hiragana "で 勝てんのなら"
	line ""
	textfw0 "ほかの"
	katakana "ポケモン"
	hiragana "が はいったのにするか"
	line ""
	textfw0 "つぎの 対戦では いれる"
	katakana "カード"
	hiragana "を"
	line ""
	textfw0 "かえるかも しれんぜよ"
	done

Text0f72:
	textfw0 "対戦"
	hiragana "は 勝つことも まけることも"
	line ""
	textfw0 "どっちのばあいも あるぜよ"
	done

Text0f73:
	hiragana "あっれー? おれと しょうぶ?"
	line ""
	textfw0 "それじゃあ "
	textfw4 "GR"
	textfw0 "2"
	textfw3 "号"
	textfw0 "がー"
	done

Text0f74:
	hiragana "あっ そっかー"
	line ""
	textfw0 "もう いいんだっけかー"
	done

Text0f75:
	hiragana "もと"
	textfw4 "GR"
	textfw0 "2"
	textfw3 "号"
	textfw0 "だったー"
	line ""
	textfw0 "おれー "
	katakana "イシイ"
	hiragana "と 対戦するのかー?"
	line ""
	textfw0 "しても いーけどー まけたくないから"
	line ""
	textfw0 "じょうけんが あるぞー"
	line ""
	textfw0 "「", "<RAMTEXT>", "」を"
	line ""
	textfw0 "4枚 "
	katakana "デッキ"
	hiragana "に いれるんだー"
	line ""
	textfw0 "できるんなら 対戦してやっても"
	line ""
	textfw0 "いいよー"
	done

Text0f76:
	hiragana "おれと しょうぶしたいならー"
	line ""
	textfw0 "いまから いう"
	katakana "カード 4枚"
	hiragana "いれろー"
	line ""
	textfw0 "んーと こんどは"
	line ""
	textfw0 "「", "<RAMTEXT>", "」!"
	line ""
	textfw0 "これが 4枚 はいってたら"
	line ""
	textfw0 "しょうぶしてやるー"
	done

Text0f77:
	hiragana "えーとー "
	katakana "イシイ"
	hiragana "だー!"
	line ""
	textfw0 "4枚 いれてきたかー?"
	line ""
	textfw0 "「", "<RAMTEXT>", "」"
	line ""
	textfw0 "ちゃんと おぼえてるよなー?"
	done

Text0f78:
	textfw0 "イシイ"
	hiragana "と 対戦しますか?"
	done

Text0f79:
	textfw0 "ダメ"
	hiragana "だねー いった"
	katakana "カード"
	hiragana "が"
	line ""
	textfw0 "4枚 はいって ないもんねー"
	line ""
	textfw0 "「", "<RAMTEXT>", "」"
	line ""
	textfw0 "いれないと しょうぶしなーい"
	line ""
	textfw0 "わかったかー"
	line ""
	textfw0 "「", "<RAMTEXT>", "」だぞー"
	done

Text0f7a:
	textfw0 "オーケー オーケー!"
	line ""
	hiragana "ちゃんと "
	katakana "カード "
	hiragana "はいってるねー"
	line ""
	textfw0 "しょうぶは "
	katakana "サイドカード6"
	hiragana "まーい!"
	line ""
	textfw0 "んじゃ はじめよっかねー"
	done

Text0f7b:
	hiragana "なーんだー しょうぶしないのかー?"
	line ""
	textfw0 " "
	line ""
	textfw0 "ぜんいんと たたかって かたないと"
	line ""
	textfw0 "「無の"
	textfw4 "GR"
	textfw2 "団"
	katakana "コイン」 "
	hiragana "あげないぞー"
	done

Text0f7c:
	hiragana "おろろ・・・", "<RAMNAME>", "はー"
	line ""
	textfw0 "まだ おれと しょうぶしたいのかー?"
	line ""
	textfw0 "しょうぶしても いーけど"
	line ""
	katakana "カード "
	hiragana "していするぞー"
	line ""
	textfw0 "こんどは どーしよーかなー・・・"
	line ""
	textfw0 "「", "<RAMTEXT>", "」!"
	line ""
	textfw0 "「", "<RAMTEXT>", "」を"
	line ""
	textfw0 "4枚 いれたら しょうぶするぞー!"
	done

Text0f7d:
	hiragana "おう おう おうー!"
	line ""
	textfw0 "しょうぶだなー!"
	line ""
	textfw0 "こんどの していは・・・"
	line ""
	textfw0 "「", "<RAMTEXT>", "」ー!"
	line ""
	textfw0 "4枚 あるのかなー"
	line ""
	textfw0 "あれば すぐ しょうぶだー!"
	done

Text0f7e:
	textfw0 "「", "<RAMTEXT>", "」"
	line ""
	hiragana "ちゃんと いれてきたかー?"
	line ""
	textfw0 "ちゃんと"
	katakana "カード"
	hiragana "が 4枚 はいってたら"
	line ""
	textfw0 "しょうぶ しょうぶだー!"
	done

Text0f7f:
	textfw0 "「", "<RAMTEXT>", "」・・・"
	line ""
	hiragana "よーんまーい はいってなーい!"
	line ""
	textfw0 "それじゃ "
	katakana "ダメ ダメ"
	hiragana "だー"
	line ""
	textfw0 "いれる"
	katakana "カード"
	hiragana "を もっかい いうぞー"
	line ""
	textfw0 "「", "<RAMTEXT>", "」だー"
	line ""
	textfw0 "しょうぶしたきゃ 4枚 いれてこーい"
	done

Text0f80:
	hiragana "うぃーす! ちゃんと "
	katakana "カード"
	line ""
	hiragana "はいってるなー"
	line ""
	katakana "サイドカード"
	hiragana "は 6まーい!"
	line ""
	textfw0 "しょうぶ しょうぶ しょうぶだー!"
	done

Text0f81:
	hiragana "もしかしてー まだ "
	katakana "カード"
	hiragana "が"
	line ""
	textfw0 "たんないのかー?"
	line ""
	katakana "カード"
	hiragana "は あつめて つかって"
	line ""
	textfw0 "しょうぶしないとねー"
	done

Text0f82:
	hiragana "おろろ・・・まけちゃったよ"
	line ""
	textfw0 "なんでだろー・・・まっ いいか"
	done

Text0f83:
	hiragana "あっれー ぜんいんに 勝って"
	line ""
	textfw0 "ないじゃ あーりませんか"
	line ""
	textfw0 "ぜんいんに 勝たないと"
	line ""
	textfw0 "「無の"
	textfw4 "GR"
	textfw2 "団"
	katakana "コイン」"
	hiragana "は あげなーい"
	line ""
	textfw0 "ぜんいんに 勝ったら おれに"
	line ""
	textfw0 "はなしかけるんだなー"
	done

Text0f84:
	hiragana "なーんだ よわっちーなー"
	line ""
	textfw0 "そんなんじゃ "
	katakana "ダメ"
	hiragana "だぞー"
	line ""
	textfw0 "もっと つよくなってからー"
	line ""
	textfw0 "しょうぶに こーい"
	done

Text0f85:
	hiragana "おろろろろ・・・うーん 勝てない"
	line ""
	textfw0 "まっ いーや 拡張"
	katakana "パック "
	hiragana "わたすねー"
	done

Text0f86:
	hiragana "まけても どーでも いーやー"
	line ""
	textfw0 "そんじゃ またなー"
	done

Text0f87:
	textfw0 "勝"
	hiragana "ったぞー! でもなー 勝っても"
	line ""
	textfw0 "なにも もらえないから つまんないー"
	done

Text0f88:
	textfw0 "無"
	hiragana "の"
	textfw4 "GR"
	textfw2 "団"
	textfw0 "の この"
	katakana "サメジマ"
	hiragana "に"
	line ""
	textfw0 "たたかいを いどむのだな!"
	line ""
	textfw0 "「", "<RAMTEXT>", "」だ!"
	line ""
	textfw0 "4枚 いれてあれば たたかう!"
	line ""
	textfw0 "だが 4枚に たりなければ"
	line ""
	textfw0 "しょうぶは おあずけだ!!"
	line ""
	textfw0 "「", "<RAMTEXT>", "」は"
	line ""
	textfw0 "はいっているか?"
	line ""
	textfw0 "はいっていれば"
	line ""
	textfw0 "たたかいの はじまりだ!!"
	done

Text0f89:
	hiragana "おなじ"
	katakana "カード"
	hiragana "を していするのも"
	line ""
	textfw0 "つまらないかもしれん"
	line ""
	katakana "カード"
	hiragana "を よくきって"
	line ""
	textfw0 "えらぶことに する"
	line ""
	textfw0 "「", "<RAMTEXT>", "」だ!"
	line ""
	textfw0 "この"
	katakana "カード"
	hiragana "を4枚 いれてくれ"
	line ""
	textfw0 "もう 4枚 はいっているなら"
	line ""
	textfw0 "すぐに たたかいだ!"
	done

Text0f8a:
	hiragana "ちゃんと していした"
	katakana "カード"
	hiragana "を"
	line ""
	textfw0 "4枚 いれてきたか?"
	line ""
	textfw0 "「", "<RAMTEXT>", "」だぞ!"
	line ""
	textfw0 "わかっているな?"
	line ""
	textfw0 "「", "<RAMTEXT>", "」が"
	line ""
	textfw0 "4枚 はいっているなら たたかおう!"
	done

Text0f8b:
	textfw0 "サメジマ"
	hiragana "と 対戦しますか?"
	done

Text0f8c:
	hiragana "この "
	katakana "サメジマ"
	hiragana "の めは"
	line ""
	textfw0 "あざむくことは できない!"
	line ""
	textfw0 "「", "<RAMTEXT>", "」が"
	line ""
	textfw0 "4枚 はいっていないのは あきらか!"
	line ""
	textfw0 "じょうけんが そろうまで"
	line ""
	textfw0 "たたかいは おあずけだ!"
	done

Text0f8d:
	hiragana "うむ"
	line ""
	katakana "カード"
	hiragana "は そろっているな!"
	line ""
	textfw0 "それでは "
	katakana "サイドカード 6枚"
	hiragana "で"
	line ""
	textfw0 "たたかうぞ!!"
	done

Text0f8e:
	textfw0 "カード"
	hiragana "が たりなければ"
	line ""
	textfw0 "てにいれて こい!"
	line ""
	textfw0 "この"
	katakana "サメジマ"
	hiragana "さまは"
	line ""
	textfw0 "ここで まっていてやる!"
	line ""
	textfw0 "さあ"
	line ""
	katakana "カード"
	hiragana "を あつめてくるんだ!"
	done

Text0f8f:
	hiragana "この"
	katakana "サメジマ"
	hiragana "さまと"
	line ""
	textfw0 "また たたかう つもりなんだな?"
	line ""
	textfw0 "そうだな・・・・"
	line ""
	textfw0 "「", "<RAMTEXT>", "」だ!"
	line ""
	textfw0 "「", "<RAMTEXT>", "」を"
	line ""
	textfw0 "4枚 いれるんだ!"
	line ""
	textfw0 "すでに はいっているなら"
	line ""
	textfw0 "すぐに たたかいを はじめるぞ!"
	done

Text0f90:
	textfw0 "「", "<RAMTEXT>", "」"
	hiragana "だ"
	line ""
	textfw0 "ちゃんと 4枚 はいっているか?"
	line ""
	katakana "カード"
	hiragana "が はいっていれば"
	line ""
	textfw0 "たたかいを うけよう!"
	done

Text0f91:
	textfw0 "4枚 "
	hiragana "はいって いないな"
	line ""
	textfw0 "「", "<RAMTEXT>", "」が"
	line ""
	textfw0 "これでは たたかうわけには"
	line ""
	textfw0 "いかないな あきらめろ!"
	done

Text0f92:
	hiragana "よかろう! "
	katakana "カード"
	hiragana "は はいっている"
	line ""
	textfw0 "たたかいを はじめるぞ!"
	line ""
	katakana "サイドカード"
	hiragana "は 6枚"
	line ""
	textfw0 "いくぞ!"
	done

Text0f93:
	hiragana "むりに たたかう ひつようは ない"
	line ""
	textfw0 "いちど 勝ったのだからな"
	done

Text0f94:
	hiragana "ふっふふふふ・・・・はっははははは!"
	line ""
	textfw0 "この"
	katakana "サメジマ"
	hiragana "さまが まけたか!!"
	done

Text0f95:
	hiragana "とりあえず まけは まけだ"
	line ""
	textfw0 "みとめて おこう"
	done

Text0f96:
	hiragana "この"
	katakana "サメジマ"
	hiragana "さまに 勝とうなど"
	line ""
	textfw0 "10ねん はやいわ!"
	done

Text0f97:
	textfw0 "・・・拡張パック"
	hiragana "を わたそう"
	done

Text0f98:
	hiragana "この"
	katakana "サメジマ"
	hiragana "さまとて"
	line ""
	textfw0 "まけることも あるのだ"
	line ""
	textfw0 "つぎには べつな"
	katakana "ポケモン"
	hiragana "を"
	line ""
	textfw0 "していすることも かんがえるか"
	done

Text0f99:
	hiragana "まあ たまには 勝たせてもらわんと"
	line ""
	katakana "メンツ"
	hiragana "も たもてんからな"
	done

Text0f9a:
	hiragana "さあ ", "<RAMNAME>", "くん"
	line ""
	katakana "ファイナルカップ"
	hiragana "を はじめよう"
	line ""
	textfw0 "われらが 伝説の"
	katakana "ポケモンカード"
	hiragana "を"
	line ""
	textfw0 "あずかる "
	katakana "グランドマスター!"
	line ""
	hiragana "われら 4にんに 勝たなければ"
	line ""
	textfw0 "伝説の"
	katakana "ポケモンカード"
	hiragana "は "
	katakana "ゲット"
	hiragana "できん"
	line ""
	textfw0 "では まず"
	line ""
	katakana "ヒロコ"
	hiragana "と 対戦してもらおう!"
	done

Text0f9b:
	textfw0 "ウフフ・・・アタシ"
	hiragana "が 1人目よ"
	line ""
	textfw0 "炎の"
	katakana "クイーン・ヒ・ロ・コ!"
	line ""
	hiragana "いくわよ ", "<RAMNAME>", "くん"
	line ""
	katakana "ウフフ・・・"
	hiragana "てかげんは しないわ"
	line ""
	katakana "サイドカード"
	hiragana "は 6枚"
	line ""
	katakana "ウフフ・・・ "
	hiragana "さあ いくわよ!"
	done

Text0f9c:
	textfw0 "ウフフ・・・アタシ"
	hiragana "の まけよ"
	line ""
	textfw0 "さすがね ", "<RAMNAME>", "くん"
	done

Text0f9d:
	hiragana "つぎは "
	katakana "スティーブ"
	hiragana "と対戦だ!"
	line ""
	textfw0 "<RAMNAME>", "くん!"
	done

Text0f9e:
	textfw0 "ウフフ・・・"
	line ""
	textfw0 "アタシ"
	hiragana "の か・ち・よ"
	line ""
	textfw0 "そんなんじゃ"
	line ""
	textfw4 "GR"
	textfw2 "団"
	textfw0 "には 勝てないわよ"
	done

Text0f9f:
	textfw0 "ヘイ ", "<RAMNAME>", "!"
	line ""
	textfw0 "ミー"
	hiragana "と "
	katakana "ポケモンカードバトル"
	hiragana "ね"
	line ""
	katakana "サンダー・スティーブ"
	hiragana "との対戦は"
	line ""
	katakana "ビッグ グレート"
	hiragana "ね!"
	done

Text0fa0:
	textfw0 "<RAMNAME>"
	hiragana "くん"
	line ""
	katakana "デッキ"
	hiragana "のじゅんびは いいかね?"
	done

Text0fa1:
	hiragana "では"
	line ""
	textfw0 "<RAMTEXT>", "との対戦を はじめよう"
	done

Text0fa2:
	textfw0 "サイド"
	hiragana "は "
	katakana "シックスカード!"
	line ""
	textfw0 "レディ? ゴー"
	hiragana "ね!"
	done

Text0fa3:
	textfw0 "ユー アー ウィナー!"
	line ""
	textfw0 "オー グレート"
	hiragana "ね!"
	done
