Text11f3:
	hiragana "うふふ・・・うれしいなぁ"
	line ""
	textfw0 "こうかんしてくれて ありがとー"
	done

Text11f4:
	textfw0 "イマクニ?"
	hiragana "って ごぞんじ?"
	line ""
	textfw0 "まっかで "
	katakana "ブクブク "
	hiragana "してるのよ"
	line ""
	textfw0 "いままで いなかったのに"
	line ""
	textfw0 "きゅうに あらわれましたの"
	line ""
	textfw0 "ところで おききになりました?"
	line ""
	textfw0 "<RAMNAME>", "って"
	katakana "コ"
	hiragana "のこと"
	line ""
	textfw0 "<RAMNAME>", "とか いうのが"
	line ""
	textfw0 "このしまに きてるんですって"
	line ""
	textfw0 "なんでも"
	line ""
	katakana "カード"
	hiragana "を とりかえしに きたとか"
	line ""
	katakana "カード"
	hiragana "を あつめるしか できないのに"
	line ""
	textfw4 "GR"
	textfw2 "団"
	textfw0 "に さからうなんて"
	line ""
	textfw0 "ずいぶんと なまいきだと"
	line ""
	textfw0 "おおもいに なりませんこと"
	line ""
	textfw0 "あーら ごめんなさい"
	line ""
	textfw0 "おはなしが ながくなって"
	line ""
	textfw0 "わたくし おはなしするのが"
	line ""
	textfw0 "だいすきですの "
	katakana "オホホホホホ・・・"
	done

Text11f5:
	hiragana "あそこの 「ぱそこん」って"
	line ""
	textfw0 "つかったことあります?"
	line ""
	textfw0 "「ぱそこん」って べんりよねー"
	line ""
	textfw0 "ところで おききになりました?"
	line ""
	textfw0 "<RAMNAME>", "って"
	katakana "コ"
	hiragana "のことですわよ"
	line ""
	textfw0 "このしまに きてるじゃありませんこと"
	line ""
	textfw0 "なんでも しまのなかで"
	line ""
	textfw0 "勝ちまくってるそうですわ"
	line ""
	katakana "カード"
	hiragana "を あつめるしか できないのに"
	line ""
	textfw4 "GR"
	textfw2 "団"
	textfw0 "に 勝ちまくるなんて"
	line ""
	textfw0 "ずいぶんと なまいきだと"
	line ""
	textfw0 "おおもいに なりませんこと"
	line ""
	textfw0 "あーら ごめんなさい"
	line ""
	textfw0 "おはなしが ながくなって"
	line ""
	textfw0 "わたくし おはなしするのが"
	line ""
	textfw0 "だいすきですの "
	katakana "オホホホホホ・・・"
	done

Text11f6:
	textfw0 "カード"
	hiragana "は ぜんーぶ"
	line ""
	textfw0 "とりもどされてしまったそうよ"
	line ""
	katakana "グランドマスター"
	hiragana "とかいうのも"
	line ""
	textfw0 "ぜんいん かえったそうなの"
	line ""
	textfw0 "ところで おききになりました?"
	line ""
	textfw0 "<RAMNAME>", "って"
	katakana "コ"
	hiragana "のことですわよ"
	line ""
	textfw0 "なんでも こんどは "
	katakana "ビルリッチ"
	hiragana "さまの"
	line ""
	textfw0 "ところに いくつもりらしいですわ"
	line ""
	textfw4 "GR"
	textfw2 "団"
	textfw0 "を つくった"
	katakana "ビルリッチ"
	hiragana "さまに"
	line ""
	textfw0 "いどむなんて おろかですわ"
	line ""
	textfw0 "きっと まけてしまって なきながら"
	line ""
	textfw0 "かえることに なりますわ"
	line ""
	textfw0 "あーら ごめんなさい"
	line ""
	textfw0 "おはなしが ながくなって"
	line ""
	textfw0 "わたくし おはなしするのが"
	line ""
	textfw0 "だいすきですの "
	katakana "オホホホホホ・・・"
	done

Text11f7:
	textfw4 "GR"
	textfw2 "団"
	hiragana "は "
	katakana "カード"
	hiragana "を うばったことを"
	line ""
	textfw0 "はんせいしたそうですわ"
	line ""
	textfw0 "たしかに "
	katakana "カード"
	hiragana "を うばうのは"
	line ""
	textfw0 "やりすぎたかも しれませんわね"
	line ""
	textfw0 "ところで おききになりました?"
	line ""
	textfw0 "「ふういんの"
	katakana "トリデ」"
	hiragana "のこと"
	line ""
	textfw0 "むかし ひどい"
	katakana "デッキ"
	hiragana "が あって"
	line ""
	textfw0 "それを ふういんした そうですわ"
	line ""
	textfw0 "だいぶまえに なんにんか"
	line ""
	textfw0 "はいったひとが おりますの"
	line ""
	textfw0 "みなさん 「なく」か「わめく」か"
	line ""
	textfw0 "して でていらっしゃいましたわ"
	line ""
	textfw0 "あなたも いかれるのなら"
	line ""
	textfw0 "かくごなさることですわね"
	line ""
	textfw0 "あーら ごめんなさい"
	line ""
	textfw0 "おはなしが ながくなって"
	line ""
	textfw0 "わたくし おはなしするのが"
	line ""
	textfw0 "だいすきですの "
	katakana "オホホホホホ・・・"
	done

Text11f8:
	textfw0 "「"
	hiragana "わるい"
	katakana "ライチュウ", "<Lv>", "31」"
	hiragana "を"
	line ""
	textfw0 "くれって うるさいこが いるんだよね"
	line ""
	textfw4 "GR"
	textfw2 "団"
	textfw0 "に はいるのに "
	katakana "デッキ"
	hiragana "を"
	line ""
	textfw0 "つくってるんだから あげるもんか"
	done

Text11f9:
	hiragana "ちぇっ めずらしい"
	katakana "カード "
	hiragana "くれんなら"
	line ""
	textfw0 "あげれば よかったよ"
	line ""
	textfw0 "やっぱり しんせつな"
	katakana "ココロ"
	hiragana "が ないと"
	line ""
	katakana "ダメ"
	hiragana "なんだなー"
	line ""
	textfw0 "うん! きめた!"
	line ""
	textfw0 "これからは しんせつにしよう"
	done

Text11fa:
	hiragana "あれ? きみは "
	katakana "グランドマスター"
	hiragana "を"
	line ""
	textfw0 "たおした ", "<RAMNAME>", "くん!"
	line ""
	katakana "ウワサ"
	hiragana "には きいてましたが"
	line ""
	textfw0 "どうして ここにいるのです?"
	line ""
	textfw0 "・・・そうですか がんばってますね"
	line ""
	textfw0 "ぼくですか? ぼくは "
	katakana "タップ"
	line ""
	hiragana "おもしろそうなので "
	textfw4 "GR"
	textfw2 "団"
	textfw0 "に ばけて"
	line ""
	textfw0 "こっちのしまに きてみたんです"
	line ""
	textfw4 "GR"
	textfw2 "団"
	textfw0 "と 対戦したりして"
	line ""
	textfw0 "いろいろと ためしてみました"
	line ""
	textfw0 "ぼくの "
	katakana "デッキ"
	hiragana "を つくったのですが"
	line ""
	textfw0 "対戦を してみませんか?"
	line ""
	textfw0 "<RAMNAME>", "くんが 勝ったら"
	line ""
	textfw0 "拡", "FW0_be"
	katakana "パック"
	hiragana "を さしあげますよ"
	done

Text11fb:
	hiragana "やあ いらっしゃい ", "<RAMNAME>", "くん"
	line ""
	textfw0 "ぼくと 対戦に きてくれたのですか?"
	line ""
	textfw0 "ぼくは いつでも 対戦しますよ"
	line ""
	textfw0 "じゅんびは よろしいですか?"
	done

Text11fc:
	textfw0 "タップ"
	hiragana "と 対戦しますか?"
	done

Text11fd:
	hiragana "そうですね"
	line ""
	katakana "サイドカード"
	hiragana "は 4枚にしましょう"
	done

Text11fe:
	hiragana "それは ざんねんなことです"
	line ""
	textfw0 " "
	line ""
	textfw0 "ですが 対戦を ごきぼうされるなら"
	line ""
	textfw0 "いつでも こえを かけてください"
	line ""
	textfw0 "おまちしておりますよ"
	line ""
	textfw0 "<RAMNAME>", "くん"
	done

Text11ff:
	hiragana "うあー!!"
	line ""
	textfw0 "・・・いや しつれいしました"
	line ""
	textfw0 "おやくそくの 拡", "FW0_be"
	katakana "パック"
	hiragana "を"
	line ""
	textfw0 "おわたししましょう"
	done

Text1200:
	hiragana "よろしかったら"
	line ""
	textfw0 "また 対戦しましょう"
	done

Text1201:
	hiragana "もうしわけありませんが"
	line ""
	textfw0 "ぼくが 勝ってしまったようです"
	line ""
	textfw0 "こういうことも あるから"
	line ""
	textfw0 "対戦は おもしろいものです"
	done

Text1202:
	textfw0 "・・・・シュー・・ゴー・・・"
	line ""
	textfw0 "ウォーターーーーー!!"
	line ""
	textfw0 "ウォーター! "
	hiragana "わたし "
	katakana "アイラ!"
	line ""
	textfw0 "水"
	hiragana "の"
	textfw4 "GR"
	textfw2 "団"
	textfw0 "員 "
	katakana "シュー・・ゴー・・・"
	line ""
	textfw0 "シュー・・ゴー・・"
	hiragana "おくに いくなら"
	line ""
	textfw0 "たたかえ・・・"
	katakana "ウォーター!!"
	line ""
	textfw0 "シュー・・"
	hiragana "ここだけの・・・"
	katakana "ゴー"
	line ""
	hiragana "とくべつ"
	katakana "ルール・・シュー・・"
	line ""
	textfw0 "シュー・・"
	hiragana "ここせまい・・"
	line ""
	textfw0 "ひかえ"
	katakana "ポケモン 3"
	hiragana "びきしかだせない"
	done

Text1203:
	textfw0 "シュー・・・ゴー・・・"
	line ""
	textfw0 "ウォーターーーー!!"
	line ""
	hiragana "ひかえ"
	katakana "ポケモン 3"
	hiragana "びきだけ・・・"
	line ""
	textfw0 "それで対戦・・・"
	katakana "シュー・・ゴー・・"
	done

Text1204:
	textfw0 "アイラ"
	hiragana "と 対戦しますか?"
	done

Text1205:
	textfw0 "サイドカード 4枚"
	line ""
	textfw0 "対戦"
	hiragana "かいし "
	katakana "ウォーターーーーー!!"
	done

Text1206:
	textfw0 "シュー・・・ゴー・・・・"
	line ""
	textfw0 "ウォーターーーーーー!!!!"
	done

Text1207:
	textfw0 "シュー・・ゴー・・"
	line ""
	hiragana "こんどは まけない・・"
	katakana "ウォーター!!"
	done

Text1208:
	textfw0 "サイドカード 4枚"
	line ""
	textfw0 "シュー・・・ゴー・・・"
	done

Text1209:
	textfw0 "ウォーターーーーー!!!!"
	done

Text120a:
	hiragana "うぉー・・・たー・・・"
	done

Text120b:
	textfw0 "シュー・・・ゴー・・・"
	line ""
	hiragana "つぎ まけない・・"
	katakana "ウォーター!!"
	done

Text120c:
	textfw0 "ウォーターーーーー!!!!"
	done

Text120d:
	textfw0 "シュー・・・ゴー・・・・"
	line ""
	textfw0 "・・・シュー・・・ゴー・・・"
	done

Text120e:
	hiragana "うぉー・・・たー・・・"
	line ""
	textfw0 "・・しゅー・・・ごー・・・"
	done

Text120f:
	textfw0 "シュー・・トビラ "
	hiragana "あける・・・"
	line ""
	katakana "ゴー・・・"
	done

Text1210:
	textfw0 "ウォーターーーーー!!!"
	done

Text1211:
	textfw0 "シュー・・トビラ "
	hiragana "あいた・・"
	line ""
	katakana "シュー・・"
	hiragana "さき "
	katakana "ススメ・・・ゴー"
	done

Text1212:
	hiragana "ようこそ いらっしゃいました"
	line ""
	textfw0 "ここは 水の"
	textfw4 "GR"
	textfw2 "団"
	textfw0 "の"
	katakana "トリデ"
	hiragana "です"
	line ""
	textfw0 "いま あなたさまを "
	katakana "トリデ"
	hiragana "のなかへ"
	line ""
	textfw0 "おいれすることは できません"
	line ""
	textfw0 "「雷の"
	textfw4 "GR"
	textfw2 "団"
	katakana "コイン」"
	hiragana "が あれば"
	line ""
	textfw0 "なかへ おとおし いたしましょう"
	line ""
	textfw0 "雷の"
	textfw4 "GR"
	textfw2 "団"
	textfw0 "の"
	katakana "トリデ"
	hiragana "で"
	line ""
	katakana "コイン"
	hiragana "を てに おいれください"
	done

Text1213:
	hiragana "ようこそ いらっしゃいました"
	line ""
	textfw0 "ここは 水の"
	textfw4 "GR"
	textfw2 "団"
	textfw0 "の"
	katakana "トリデ"
	hiragana "です"
	done

Text1214:
	textfw0 "コイル"
	hiragana "の"
	katakana "マーク"
	hiragana "の"
	katakana "コイン"
	hiragana "を"
	line ""
	textfw0 "はめるような くぼみがある"
	done

Text1215:
	textfw0 "「雷"
	hiragana "の"
	textfw4 "GR"
	textfw2 "団"
	katakana "コイン」"
	hiragana "を はめますか?"
	done

Text1216:
	hiragana "ようこそ いらっしゃいました"
	line ""
	textfw0 "ここは 水の"
	textfw4 "GR"
	textfw2 "団"
	textfw0 "の"
	katakana "トリデ"
	hiragana "です"
	line ""
	textfw0 "水の"
	textfw4 "GR"
	textfw2 "団"
	textfw0 "の対戦について"
	line ""
	textfw0 "ごせつめいします"
	line ""
	textfw0 "水の"
	textfw4 "GR"
	textfw2 "団"
	textfw0 "の"
	katakana "リーダー"
	hiragana "は"
	line ""
	katakana "カノコ"
	hiragana "さまと もうします"
	line ""
	textfw0 "あうには 水の"
	textfw4 "GR"
	textfw2 "団"
	textfw0 "員3にんに"
	line ""
	textfw0 "勝たなければなりません"
	line ""
	textfw0 "なかには じょうけんつきで"
	line ""
	textfw0 "対戦をする"
	katakana "メンバー"
	hiragana "も おります"
	line ""
	textfw0 "では さきに おすすみになり"
	line ""
	textfw0 "対戦を おたのしみください"
	done

Text1217:
	hiragana "はぁーい あたし "
	katakana "カノコ!"
	line ""
	textfw0 "水"
	hiragana "の"
	textfw4 "GR"
	textfw2 "団"
	textfw0 "の"
	katakana "リーダー "
	hiragana "やってるの"
	line ""
	textfw0 "あなたは ", "<RAMNAME>", "さんよね"
	line ""
	textfw4 "GR"
	textfw2 "団"
	textfw0 "に さからっちゃってる"
	line ""
	textfw0 "あたしの 「水の"
	textfw4 "GR"
	textfw2 "団"
	katakana "コイン」"
	hiragana "が"
	line ""
	textfw0 "ほしいんだよね?"
	line ""
	textfw0 "あたしも ほかの"
	textfw4 "GR"
	textfw2 "団"
	textfw0 "の"
	katakana "リーダー"
	hiragana "と"
	line ""
	textfw0 "おんなじこと いうね"
	line ""
	textfw0 "あたしと 対戦して 勝ったら"
	line ""
	textfw0 "「水の"
	textfw4 "GR"
	textfw2 "団"
	katakana "コイン」"
	hiragana "を あ・げ・る"
	line ""
	textfw0 "あたしの かわいい水"
	katakana "ポケモン"
	hiragana "のために"
	line ""
	textfw0 "ここは 水が いっぱいなの"
	line ""
	textfw0 "だから 水"
	katakana "ポケモン"
	hiragana "は 「にげる」とき"
	line ""
	textfw0 "ひつような"
	katakana "エネルギー"
	hiragana "が 1つへるの"
	line ""
	textfw0 "3つ ひつようなら 2つ"
	line ""
	textfw0 "2つ ひつようなら 1つになる"
	line ""
	textfw0 "わかったかな?"
	line ""
	textfw0 "わかったら 対戦しーましょっ!"
	done

Text1218:
	hiragana "はぁーい ", "<RAMNAME>", "さん!"
	line ""
	textfw0 " "
	line ""
	textfw0 "「水の"
	textfw4 "GR"
	textfw2 "団"
	katakana "コイン」"
	hiragana "が ほしくて"
	line ""
	textfw0 "また きたのかな?"
	line ""
	textfw0 "それなら 対戦しーましょっ!"
	line ""
	textfw0 " "
	line ""
	textfw0 "あたしの かわいい水"
	katakana "ポケモン"
	hiragana "のために"
	line ""
	textfw0 "ここは 水が いっぱいなの"
	line ""
	textfw0 "だから 水"
	katakana "ポケモン"
	hiragana "は 「にげる」とき"
	line ""
	textfw0 "ひつような"
	katakana "エネルギー"
	hiragana "が 1つへるの"
	line ""
	textfw0 "おぼえてるわよねー"
	line ""
	textfw0 "じゃあ 対戦しーましょ?"
	done

Text1219:
	textfw0 "カノコ"
	hiragana "と 対戦しますか?"
	done

Text121a:
	textfw0 "サイドカード"
	hiragana "は ほかの"
	katakana "リーダー"
	hiragana "と"
	line ""
	textfw0 "おんなじの 6まーい"
	done

Text121b:
	hiragana "もしかしたら "
	katakana "デッキ"
	hiragana "のじゅんびが"
	line ""
	textfw0 "できてなかったのかな?"
	line ""
	textfw0 "まってるから じゅんびしておいでよ"
	done

Text121c:
	hiragana "はぁーい ", "<RAMNAME>", "さん!"
	line ""
	textfw0 "対戦しーましょっ!"
	line ""
	textfw0 "いろんな じょうけんで"
	line ""
	textfw0 "対戦するのも たのしくなったでしょ"
	line ""
	textfw0 "あたしの かわいい水"
	katakana "ポケモン"
	hiragana "のために"
	line ""
	textfw0 "ここは 水が いっぱいなの"
	line ""
	textfw0 "だから 水"
	katakana "ポケモン"
	hiragana "は 「にげる」とき"
	line ""
	textfw0 "ひつような"
	katakana "エネルギー"
	hiragana "が 1つへるの"
	line ""
	textfw0 "おぼえてるわよねー"
	line ""
	textfw0 "じゃあ 対戦しーましょ?"
	done

Text121d:
	textfw0 "サイドカード"
	hiragana "は 6まーい!"
	line ""
	textfw0 "それじゃ はじめよーね"
	done

Text121e:
	hiragana "あーん ざんねーん"
	line ""
	textfw0 "対戦したかったのにー"
	line ""
	textfw0 "まってるから また あそんでね"
	done

Text121f:
	hiragana "うっわー! "
	katakana "ウワサ"
	hiragana "どおりだねー"
	line ""
	textfw0 "すっごい つよいや"
	done

Text1220:
	hiragana "これなら よろこんで"
	line ""
	textfw0 "「水の"
	textfw4 "GR"
	textfw2 "団"
	katakana "コイン」"
	hiragana "を わたすね"
	done

Text1221:
	hiragana "うふふ 勝っちゃったぁー"
	line ""
	textfw0 "<RAMNAME>", "さんも つよかったよ"
	line ""
	textfw0 "つぎは 勝てないかも しれないね"
	line ""
	textfw0 "がんばってね"
	done

Text1222:
	textfw0 "アララ "
	hiragana "ざんねん"
	line ""
	textfw0 "にげきれなかった みたいね"
	line ""
	textfw0 "はぁーい 拡", "FW0_be"
	katakana "パック"
	hiragana "ね"
	done

Text1223:
	hiragana "あー たのしかった!"
	line ""
	textfw0 "また 対戦して あっそぼーね"
	done

Text1224:
	hiragana "うふふ 勝っちゃったー"
	line ""
	textfw0 "うれしーなぁ"
	line ""
	textfw0 "勝っても まけても"
	line ""
	textfw0 "たのしいけどねー"
	line ""
	textfw0 "また 対戦して あっそぼーね!"
	done

Text1225:
	hiragana "じゃじゃーん!"
	line ""
	textfw0 "これが そうでーす!"
	done

Text1226:
	textfw0 "「炎"
	hiragana "の"
	textfw4 "GR"
	textfw2 "団"
	katakana "コイン」"
	hiragana "は"
	line ""
	textfw0 "まーだ もってないみたいだね"
	line ""
	textfw0 "闘の"
	textfw4 "GR"
	textfw2 "団"
	textfw0 "の"
	katakana "トリデ"
	hiragana "に はいるなら"
	line ""
	textfw0 "「炎の"
	textfw4 "GR"
	textfw2 "団"
	katakana "コイン」"
	hiragana "が いるわよ"
	line ""
	textfw0 "だ・か・ら 炎の"
	textfw4 "GR"
	textfw2 "団"
	textfw0 "の"
	katakana "トリデ"
	hiragana "に"
	line ""
	textfw0 "いくと いいと おもうな"
	done

Text1227:
	hiragana "あっ もう 「炎の"
	textfw4 "GR"
	textfw2 "団"
	katakana "コイン」"
	hiragana "は"
	line ""
	textfw0 "もってるんだ すっごいね!"
	line ""
	textfw0 "もう 闘の"
	textfw4 "GR"
	textfw2 "団"
	textfw0 "の"
	katakana "トリデ"
	hiragana "に"
	line ""
	textfw0 "はいれちゃうんだー"
	line ""
	textfw0 "じゃあ もう いくんでしょ?"
	line ""
	textfw0 "がんばって いってらっしゃーい!"
	done

Text1228:
	hiragana "あらあら "
	textfw4 "GR"
	textfw2 "団"
	textfw0 "員じゃないのに"
	line ""
	textfw0 "なんのごようかしらぁ?"
	line ""
	katakana "アタシ? アタシ"
	hiragana "は "
	katakana "ミヤジマ"
	line ""
	textfw0 "水"
	hiragana "の"
	textfw4 "GR"
	textfw2 "団"
	textfw0 "員よぉ"
	line ""
	textfw0 "水のちからで おはだ "
	katakana "スベスベェ"
	line ""
	hiragana "なーんちゃってねぇん"
	line ""
	textfw0 "わかってるのよぉ"
	line ""
	katakana "アンタ ", "<RAMNAME>"
	hiragana "でしょ?"
	line ""
	textfw0 "水の"
	textfw4 "GR"
	textfw2 "団"
	katakana "リーダー カノコ"
	hiragana "ちゃんには"
	line ""
	katakana "カンタン"
	hiragana "に あわせられないわ!"
	line ""
	katakana "アタシ"
	hiragana "と 対戦なさい!"
	line ""
	textfw0 "勝ったら "
	katakana "トビラ"
	hiragana "を あけてあげるわ"
	line ""
	textfw0 "でも じょうけんつきよ!"
	line ""
	textfw0 "そうじゃなきゃ 対戦しないわ!"
	line ""
	katakana "デッキ"
	hiragana "に いれていい"
	katakana "エネルギー"
	hiragana "は"
	line ""
	textfw0 "水"
	katakana "エネルギー"
	hiragana "だけよ!"
	line ""
	textfw0 "わかったわね!"
	line ""
	textfw0 "わかったら 対戦よ!"
	done

Text1229:
	textfw0 "カノコ"
	hiragana "ちゃんに あいたければ"
	line ""
	katakana "アタシ"
	hiragana "と 対戦すんのよ!"
	line ""
	textfw0 "でも いれていい"
	katakana "エネルギー"
	hiragana "は"
	line ""
	textfw0 "水"
	katakana "エネルギー"
	hiragana "だけよ!"
	line ""
	textfw0 "おぼえているでしょうね!"
	line ""
	textfw0 "おぼえてなくても 対戦よぉ!"
	done

Text122a:
	textfw0 "ミヤジマ"
	hiragana "と 対戦しますか?"
	done

Text122b:
	hiragana "ちょっと! "
	katakana "デッキ"
	hiragana "の じゅんびが"
	line ""
	textfw0 "できていないんじゃないのぉ!"
	line ""
	textfw0 "水"
	katakana "エネルギー"
	hiragana "じゃない "
	katakana "エネルギー"
	hiragana "が"
	line ""
	katakana "デッキ"
	hiragana "のなかに はいってるわよぉ!"
	line ""
	textfw0 "わかったわね"
	line ""
	textfw0 "でなおして らっしゃい!"
	done

Text122c:
	textfw0 "アタシ"
	hiragana "は 4が "
	katakana "スキ"
	hiragana "なの"
	line ""
	textfw0 "だから "
	katakana "サイドカード"
	hiragana "は 4枚よ!"
	done

Text122d:
	hiragana "あーら そう!"
	line ""
	katakana "アタシ"
	hiragana "は いいのよ"
	line ""
	textfw0 "なーんにも こまらないから"
	done

Text122e:
	hiragana "しつこいわねー また きたの?"
	line ""
	textfw0 "わかってるわ 対戦してあげるわよぉ!"
	line ""
	katakana "デッキ"
	hiragana "に いれていい "
	katakana "エネルギー"
	hiragana "は"
	line ""
	textfw0 "水"
	katakana "エネルギー"
	hiragana "だけよ"
	line ""
	textfw0 "しかたないから 対戦してあげるわ"
	line ""
	textfw0 "じゅんびは いいわね!"
	done

Text122f:
	textfw0 "デッキ"
	hiragana "の じゅんびも しないで"
	line ""
	textfw0 "くるんじゃないわよぉ!"
	line ""
	textfw0 "水"
	katakana "エネルギー"
	hiragana "じゃない "
	katakana "エネルギー"
	hiragana "が"
	line ""
	katakana "デッキ"
	hiragana "のなかに はいってんじゃない!"
	done

Text1230:
	textfw0 "サイドカード"
	hiragana "は 4枚よ"
	line ""
	textfw0 "それでしか 対戦しないわ!"
	done

Text1231:
	textfw0 "対戦"
	hiragana "したくないなら きがるに"
	line ""
	katakana "アタシ"
	hiragana "に はなしかけないでよね!"
	line ""
	katakana "アタシ"
	hiragana "は "
	katakana "カノコ"
	hiragana "ちゃんの"
	line ""
	textfw0 "ものなんですからねーっだ!"
	done

Text1232:
	textfw0 "キーーー!! "
	hiragana "しんじられないわぁ!"
	line ""
	katakana "アタシ"
	hiragana "が まけるなんてっ!"
	line ""
	textfw0 "ふん!"
	line ""
	textfw0 "拡", "FW0_be"
	katakana "パック"
	hiragana "を あげるわよ!"
	line ""
	textfw0 "でも いいこと?"
	line ""
	textfw0 "すきで あげるんじゃないわ"
	line ""
	katakana "カノコ"
	hiragana "ちゃんの めいれいだから"
	line ""
	textfw0 "あげるんだからね!!"
	done

Text1233:
	hiragana "ううっ・・・"
	katakana "イヤ"
	hiragana "だけど"
	line ""
	textfw0 "しかたがないわ"
	line ""
	katakana "カノコ"
	hiragana "ちゃんの めいれいだもの"
	done

Text1234:
	hiragana "おぼっちゃん"
	done

Text1235:
	hiragana "おじょうちゃん"
	done

Text1236:
	hiragana "ふふん! あんたごときが"
	line ""
	katakana "アタシ"
	hiragana "に 勝てるはずがないのよ!!"
	line ""
	textfw0 "どう "
	katakana "アタシ"
	hiragana "の"
	katakana "ツメ"
	hiragana "の"
	katakana "アカ"
	hiragana "でも"
	line ""
	textfw0 "せんじて のんでみる?"
	line ""
	textfw0 "すこしは うまくなるかもねぇ"
	line ""
	textfw0 "<RAMTEXT>"
	done

Text1237:
	hiragana "なんで? どーして!"
	line ""
	katakana "アタシ"
	hiragana "が まけるの! のぉーー!!!"
	done

Text1238:
	textfw0 "アンタ"
	hiragana "が なにをしようと"
	line ""
	katakana "ゼッタイ"
	hiragana "に みとめないわ!!"
	done

Text1239:
	hiragana "ふふん! "
	katakana "アンタ"
	hiragana "ごときが"
	line ""
	katakana "アタシ"
	hiragana "に 勝てるはずが ないのよ!!"
	line ""
	katakana "アタシ"
	hiragana "は つよーいんだから!!"
	done

Text123a:
	textfw0 "センタ"
	hiragana "くんの "
	katakana "ヘヤ"
	hiragana "へ"
	line ""
	textfw0 "とおしてあげるわよ!!"
	done

Text123b:
	hiragana "ほら あけたわよ!"
	line ""
	textfw0 " "
	line ""
	katakana "カオ"
	hiragana "も みたくないんだから"
	line ""
	textfw0 "さっさと いきなさいよ!!"
	done

Text123c:
	hiragana "おいらは"
	katakana "センタ"
	hiragana "くんでーす!"
	line ""
	textfw0 "水の"
	textfw4 "GR"
	textfw2 "団"
	textfw0 "員だーい!"
	line ""
	katakana "グランドマスター"
	hiragana "の"
	katakana "カネコウジ"
	hiragana "さんを"
	line ""
	textfw0 "とっつかまえてまーす!"
	line ""
	textfw0 "おいらに勝ったら "
	katakana "カネコウジ"
	hiragana "さんを"
	line ""
	textfw0 "かえすし つぎの"
	katakana "ヘヤ"
	hiragana "にも いかせるよ"
	line ""
	textfw0 "あっ もちろん"
	line ""
	textfw0 "拡", "FW0_be"
	katakana "パック"
	hiragana "も あげるからね"
	line ""
	katakana "コイキング"
	hiragana "を 4枚いれた"
	katakana "デッキ"
	hiragana "を"
	line ""
	textfw0 "つくって くださいな"
	line ""
	textfw0 "そうしたら しょうぶしまーす"
	line ""
	textfw0 "いますぐ しょうぶする?"
	done

Text123d:
	textfw0 "デッキ"
	hiragana "に "
	katakana "コイキング4枚"
	line ""
	hiragana "いれてきたー?"
	line ""
	textfw0 "いれてきたんなら しょうぶしよー!"
	done

Text123e:
	textfw0 "センタ"
	hiragana "と 対戦しますか?"
	done

Text123f:
	textfw0 "ダメ"
	hiragana "じゃん! "
	katakana "ダメ"
	hiragana "じゃん!"
	line ""
	katakana "コイキング"
	hiragana "が 4枚 はいってないよ!"
	line ""
	katakana "コイキング"
	hiragana "を 4枚 いれないと"
	line ""
	textfw0 "おいらは しょうぶしないよ!"
	done

Text1240:
	textfw0 "コイキング"
	hiragana "は・・・そろってるね!"
	line ""
	katakana "サイドカード"
	hiragana "は 4枚ね"
	line ""
	textfw0 "よーし! しょうぶだよ!"
	done

Text1241:
	hiragana "あれ? しょうぶしないの?"
	line ""
	textfw0 "うん わかったよ"
	line ""
	textfw0 "おいらは まってるから"
	line ""
	textfw0 "また あそびに おいでよね"
	done

Text1242:
	hiragana "はーい! "
	katakana "センタ"
	hiragana "くんでーす!"
	line ""
	textfw0 "しょうぶ しょうぶー!!"
	line ""
	katakana "コイキング"
	hiragana "は いれてきたかい?"
	line ""
	textfw0 "4枚だよ 4枚!"
	line ""
	katakana "デッキ"
	hiragana "に はいってるなら"
	line ""
	textfw0 "しょうぶしよー"
	done

Text1243:
	hiragana "わすれちゃ "
	katakana "ダメ"
	hiragana "じゃん!"
	line ""
	katakana "コイキング 4枚"
	hiragana "だよ"
	line ""
	katakana "デッキ"
	hiragana "に いれてこないと"
	line ""
	textfw0 "しょうぶ できないんだー"
	line ""
	textfw0 "だから "
	katakana "コイキング"
	hiragana "を 4枚"
	line ""
	katakana "デッキ"
	hiragana "に いれたら はなしかけてよ"
	done

Text1244:
	textfw0 "サイドカード 4枚"
	hiragana "ね"
	line ""
	textfw0 "さあー いくぞー!"
	done

Text1245:
	hiragana "えー しょうぶ しないの?"
	line ""
	textfw0 "それでも いーけどさー"
	done

Text1246:
	hiragana "あっはははははは!"
	line ""
	textfw0 "まけちゃったよー"
	done

Text1247:
	textfw0 "ムリヤリ "
	hiragana "じょうけんを つけたのに"
	line ""
	textfw0 "つよかったねー"
	done

Text1248:
	textfw0 "センタ"
	hiragana "くん つよーい!!"
	line ""
	katakana "センタ"
	hiragana "くん "
	katakana "イカスー!!"
	line ""
	hiragana "えへへ ほめられたことないから"
	line ""
	textfw0 "じぶんで ほめてみました"
	done

Text1249:
	hiragana "つよくて おったまげー"
	done

Text124a:
	hiragana "きみは えらーい! つよーい!"
	line ""
	textfw0 "さいこー! しびれるー!"
	done

Text124b:
	textfw0 "センタ"
	hiragana "くんの 勝ちー!"
	line ""
	textfw0 "つよいですねー えらいですねー"
	line ""
	textfw0 "また じぶんで ほめてみました"
	line ""
	textfw0 "えへへへ・・・"
	done

Text124c:
	hiragana "えーと "
	katakana "カネコウジ"
	hiragana "さんを"
	line ""
	textfw0 "ださないとねー"
	done

Text124d:
	textfw0 "カネコウジ"
	hiragana "さーん!"
	line ""
	textfw0 "でてきて いいよー!"
	done

Text124e:
	hiragana "おひさしぶりですね"
	line ""
	textfw0 "<RAMNAME>", "くん"
	line ""
	textfw0 "わたしです"
	line ""
	katakana "グランドマスター"
	hiragana "の "
	katakana "カネコウジ"
	hiragana "です"
	line ""
	textfw0 "たすけて いただいて"
	line ""
	textfw0 "かんしゃいたします"
	line ""
	textfw0 "かんしゃの きもちに"
	line ""
	katakana "カード"
	hiragana "を さしあげましょう"
	line ""
	textfw0 "この"
	katakana "カード"
	hiragana "で "
	katakana "ゴージャス"
	hiragana "な"
	katakana "デッキ"
	hiragana "を"
	line ""
	textfw0 "つくってください"
	done

Text124f:
	hiragana "あとのこる "
	katakana "グランドマスター"
	hiragana "は"
	line ""
	katakana "ヒロコ"
	hiragana "と "
	katakana "リュウドー"
	hiragana "です"
	done

Text1250:
	hiragana "あとのこる "
	katakana "グランドマスター"
	hiragana "は"
	line ""
	katakana "リュウドー "
	hiragana "ひとりです"
	done

Text1251:
	hiragana "たのみますよ ", "<RAMNAME>", "くん"
	line ""
	textfw0 "かならず たすけだしてください"
	line ""
	textfw0 "わたしは "
	katakana "ポケモンドーム"
	hiragana "に"
	line ""
	textfw0 "かえるといたします"
	line ""
	textfw0 "たまには "
	katakana "ポケモンドーム"
	hiragana "へ"
	line ""
	textfw0 "わたしを たずねてきてください"
	line ""
	textfw0 "わたしの "
	katakana "ゴージャス"
	hiragana "な"
	katakana "デッキ"
	hiragana "と"
	line ""
	textfw0 "対戦いたしましょう"
	done

Text1252:
	hiragana "あと "
	katakana "アイラ"
	hiragana "さんの"
	katakana "ヘヤ"
	hiragana "への"
	line ""
	textfw0 "はしを かけるね"
	done

Text1253:
	hiragana "はしを かけて・・・"
	line ""
	textfw0 "よいしょ"
	done

Text1254:
	hiragana "さあ どうぞ"
	line ""
	katakana "アイラ"
	hiragana "さんの "
	katakana "ヘヤ"
	hiragana "に いっていいよ"
	line ""
	katakana "アイラ"
	hiragana "さんて おもしろいんだよ"
	line ""
	textfw0 "あうのを たのしみにしてね!"
	done

Text1255:
	hiragana "あれ? "
	katakana "デッキ"
	hiragana "もってるけど・・・"
	line ""
	textfw0 "きみも "
	textfw4 "GR"
	textfw2 "団"
	textfw0 "員じゃ ないんだね"
	line ""
	textfw0 "ぼくは "
	textfw4 "GR"
	textfw2 "団"
	textfw0 "に はいりたいんだけど"
	line ""
	textfw0 "どうしても "
	katakana "カード"
	hiragana "が たりなくて・・"
	line ""
	textfw0 "きみ 「わるい"
	katakana "カメックス", "<Lv>", "28」"
	line ""
	hiragana "もってないかなぁ?"
	line ""
	textfw0 "もってたら 「"
	katakana "カメックス", "<Lv>", "52」"
	hiragana "と"
	line ""
	textfw0 "こうかんして くれないかなぁ"
	done

Text1256:
	hiragana "たぶん この"
	katakana "デッキ"
	hiragana "が かんせいしたら"
	line ""
	textfw4 "GR"
	textfw2 "団"
	textfw0 "員になれると おもうんだ"
	line ""
	textfw0 "だから 「わるい"
	katakana "カメックス", "<Lv>", "28」"
	line ""
	hiragana "もってたら こうかんして くれない?"
	line ""
	textfw0 "おれいに 「"
	katakana "カメックス", "<Lv>", "52」"
	hiragana "を"
	line ""
	textfw0 "あげるからさっ!"
	done

Text1257:
	textfw4 "GR"
	textfw2 "団"
	textfw0 "員"
	hiragana "に なりたいのに"
	line ""
	textfw0 "「わるい"
	katakana "カメックス", "<Lv>", "28」 "
	hiragana "ないんだ"
	line ""
	textfw0 "だから いつでも いいから"
	line ""
	textfw0 "こうかんしてよ・・・"
	done

Text1258:
	hiragana "ぼくは "
	katakana "ホンキ"
	hiragana "で "
	textfw4 "GR"
	textfw2 "団"
	textfw0 "員に"
	line ""
	textfw0 "なりたいと おもってるんだ"
	line ""
	textfw0 "もってないなら"
	line ""
	textfw0 "「はい」なんて いうなよ!"
	line ""
	textfw0 "しんけんなんだから"
	line ""
	textfw0 "からかわないで くれよ!!"
	done

Text1259:
	hiragana "うーん いくら ぼくの"
	katakana "デッキ"
	hiragana "を"
	line ""
	textfw0 "つくるためでも "
	katakana "ダメ"
	hiragana "だよ"
	line ""
	textfw0 "そのために きみの"
	katakana "デッキ"
	hiragana "を"
	line ""
	textfw0 "こわすわけには いかないよ"
	line ""
	textfw0 "「わるい"
	katakana "カメックス", "<Lv>", "28」"
	hiragana "を"
	line ""
	textfw0 "つかわなくなったら こうかんしてよ!"
	done

Text125a:
	hiragana "ありがとう!"
	line ""
	textfw0 "こうかんしてくれるんだね!!"
	done

Text125b:
	hiragana "よーし! "
	textfw4 "GR"
	textfw2 "団"
	textfw0 "員に なるぞー!!"
	done

Text125c:
	hiragana "やあ きみか!"
	line ""
	textfw0 "なんとか "
	textfw4 "GR"
	textfw2 "団"
	textfw0 "員に なれそうだよ"
	line ""
	textfw0 "ありがとうね"
	line ""
	katakana "カード"
	hiragana "を こうかんしてくれて"
	done

Text125d:
	hiragana "やあ! きみか みてよ"
	line ""
	textfw0 "ぼく "
	textfw4 "GR"
	textfw2 "団"
	textfw0 "員に なれたんだ!"
	line ""
	textfw0 "これも 「わるい"
	katakana "カメックス", "<Lv>", "28」"
	hiragana "を"
	line ""
	textfw0 "くれたおかげだよ"
	line ""
	textfw0 "えっ? "
	katakana "メガネ?"
	line ""
	textfw0 "コンタクト"
	hiragana "にしたんだ"
	done

Text125e:
	hiragana "きみの おかげで ぼくは"
	line ""
	textfw4 "GR"
	textfw2 "団"
	textfw0 "員に なれたんだ!"
	line ""
	textfw0 "ほんとうに ありがとう!"
	done

Text125f:
	hiragana "ああ あんたが ", "<RAMNAME>", "さんかぇ"
	line ""
	textfw0 "がんばっとるようじゃな"
	line ""
	textfw0 "ええか 闘の"
	katakana "トリデ"
	hiragana "に はいるなら"
	line ""
	katakana "コイン"
	hiragana "が 2枚 ひつようじゃ"
	line ""
	textfw0 "水と炎の"
	textfw4 "GR"
	katakana "コイン"
	hiragana "を てにいれないと"
	line ""
	textfw0 "はいれんからな"
	line ""
	textfw0 "よーおぼえとくんじゃな"
	done

Text1260:
	hiragana "ああ ", "<RAMNAME>", "さんかえ"
	line ""
	textfw0 "がんばっとるようじゃな"
	line ""
	textfw0 "わしか? わしは どーでもよいんじゃ"
	line ""
	katakana "ポケモンカード"
	hiragana "が あそべればの"
	done

Text1261:
	hiragana "あたし "
	katakana "ユメ"
	hiragana "があるの!"
	line ""
	katakana "アクアクラブ"
	hiragana "の"
	katakana "ウッチー!"
	line ""
	hiragana "おなじ 水つかいとして"
	line ""
	textfw0 "かのじょと 対戦してみたいの!"
	line ""
	textfw0 "でも むこうのしまに いけるのは"
	line ""
	textfw4 "GR"
	textfw2 "団"
	textfw0 "でも えらばれたひとだけ・・・"
	line ""
	textfw0 "はぁ・・・せつないわ・・・"
	done

Text1262:
	textfw0 "<RAMNAME>"
	hiragana "ちゃんってこの おかげで"
	line ""
	textfw0 "むこうのしまに いけるわ"
	line ""
	textfw0 "ちかいうちに むこうに いって"
	line ""
	katakana "ウッチー"
	hiragana "と 対戦よ!"
	line ""
	textfw0 "これで "
	katakana "ユメ"
	hiragana "が かなうわ"
	done

Text1263:
	hiragana "おっと!"
	line ""
	textfw0 "<RAMNAME>", "じゃねぇか!"
	line ""
	katakana "オレ"
	hiragana "だ! おまえの"
	line ""
	textfw0 "しゅくめいの"
	katakana "ライバル ランド"
	hiragana "だ!"
	line ""
	textfw0 "<RAMNAME>", "も "
	katakana "ポケモンカード"
	hiragana "を"
	line ""
	textfw0 "とられちまったのか?"
	line ""
	katakana "グレートロケット("
	textfw4 "GR"
	textfw0 ")"
	textfw2 "団"
	hiragana "って"
	line ""
	katakana "ヤツ"
	hiragana "らの しわざらしいぜ!"
	line ""
	katakana "オレ"
	hiragana "は ひとあしさきに"
	line ""
	katakana "ヤツ"
	hiragana "らのうごきを しらべておくぜ!"
	line ""
	textfw0 "くわしい はなしは"
	line ""
	textfw4 "D"
	textfw0 "ṛ"
	katakana "オーヤマ"
	hiragana "に きいてくれ!"
	line ""
	textfw0 "じゃあな! ", "<RAMNAME>", "!"
	done

Text1264:
	hiragana "おっ!"
	line ""
	textfw0 "<RAMNAME>", "じゃねぇか!"
	done

Text1265:
	hiragana "たいへんだぜ ", "<RAMNAME>", "!"
	line ""
	textfw0 "どの"
	katakana "クラブ"
	hiragana "も やられちまってるぜ!"
	line ""
	textfw0 "いま この"
	katakana "クラブ"
	hiragana "に"
	line ""
	textfw4 "GR"
	textfw2 "団"
	textfw0 "の"
	katakana "ヤツ"
	hiragana "らは いないようだな"
	line ""
	textfw0 "どうやら "
	katakana "ストーンクラブ"
	hiragana "を"
	line ""
	textfw0 "おそっているらしいぜ!"
	line ""
	textfw0 "どーせ "
	katakana "オレ"
	hiragana "は"
	line ""
	katakana "カード"
	hiragana "がないから たたかえねぇしな!"
	line ""
	textfw0 "そうだ 「"
	katakana "カードポン!」"
	hiragana "で"
	line ""
	textfw0 "おたがいの"
	katakana "カード"
	hiragana "を ふやそうぜ!"
	line ""
	textfw0 "さあ 「"
	katakana "カードポン!」"
	hiragana "の"
	line ""
	textfw0 "じゅんびをしろよ!"
	done

Text1266:
	hiragana "よし いちおう"
	line ""
	katakana "データ"
	hiragana "を"
	katakana "セーブ"
	hiragana "しとくぜ!"
	done

Text1267:
	hiragana "いずれにしろ"
	line ""
	textfw0 "ここに"
	textfw4 "GR"
	textfw2 "団"
	textfw0 "は いない"
	line ""
	textfw0 "<RAMNAME>", "! おまえは"
	line ""
	katakana "ストーンクラブ"
	hiragana "に いってくれ!"
	line ""
	textfw0 "おれは ほかを もっと しらべて"
	line ""
	textfw4 "GR"
	textfw2 "団"
	textfw0 "の じょうほうを あつめるぜ!"
	line ""
	textfw0 "じゃあな"
	line ""
	textfw0 "<RAMNAME>", "!"
	done

Text1268:
	hiragana "たいへんだぜ ", "<RAMNAME>", "!"
	line ""
	textfw0 "この"
	katakana "クラブ"
	hiragana "も やられちまってるぜ!"
	line ""
	textfw0 "もう "
	katakana "プレイホール"
	hiragana "には"
	line ""
	textfw0 "<RAMTEXT>", "ってやつが いすわってやがる"
	line ""
	textfw0 "それに いま "
	textfw4 "GR"
	textfw0 "1"
	textfw3 "FW3_9d"
	textfw0 "ってやつが"
	line ""
	katakana "ストーンクラブ"
	hiragana "に むかったらしいぜ!"
	line ""
	textfw0 "もっとも "
	katakana "オレ"
	hiragana "は"
	line ""
	katakana "カード"
	hiragana "がないから たたかえねぇしな!"
	line ""
	textfw0 "そうだ 「"
	katakana "カードポン!」"
	hiragana "で"
	line ""
	textfw0 "おたがいの"
	katakana "カード"
	hiragana "を ふやそうぜ!"
	line ""
	textfw0 "さあ 「"
	katakana "カードポン!」"
	hiragana "の"
	line ""
	textfw0 "じゅんびをしろよ!"
	done

Text1269:
	hiragana "いずれにしろ ここは かんたんには"
	line ""
	textfw0 "やっつけられそうに ないぜ!"
	line ""
	textfw0 "<RAMNAME>", "! おまえは"
	line ""
	katakana "ストーンクラブ"
	hiragana "に いってくれ!"
	line ""
	textfw0 "おれは ほかを もっと しらべて"
	line ""
	textfw4 "GR"
	textfw2 "団"
	textfw0 "の じょうほうを あつめるぜ!"
	line ""
	textfw0 "じゃあな"
	line ""
	textfw0 "<RAMNAME>", "!"
	done

Text126a:
	hiragana "たいへんだぜ ", "<RAMNAME>", "!"
	line ""
	textfw0 "いま ここに "
	textfw4 "GR"
	textfw2 "団"
	textfw0 "がきてるぜ!"
	line ""
	textfw4 "GR"
	textfw0 "1"
	textfw3 "FW3_9d"
	textfw0 "ってやつが きて"
	line ""
	katakana "ストーンクラブ"
	hiragana "で 対戦してる!"
	line ""
	katakana "クラブメンバー"
	hiragana "は みんな まけた"
	line ""
	textfw0 "あとは "
	katakana "マスター"
	hiragana "の"
	katakana "ゲンゾウ"
	hiragana "だけだ!"
	line ""
	katakana "オレ"
	hiragana "も たたかいたいが"
	line ""
	katakana "カード"
	hiragana "がないから たたかえねぇしな!"
	line ""
	textfw0 "そうだ 「"
	katakana "カードポン!」"
	hiragana "で"
	line ""
	textfw0 "おたがいの"
	katakana "カード"
	hiragana "を ふやそうぜ!"
	line ""
	textfw0 "さあ 「"
	katakana "カードポン!」"
	hiragana "の"
	line ""
	textfw0 "じゅんびをしろよ!"
	done

Text126b:
	hiragana "でも 1枚ぐらい ふえたって"
	line ""
	textfw0 "どうにもなんねぇしなぁ"
	line ""
	textfw0 "ここは ", "<RAMNAME>", "!"
	line ""
	textfw0 "おまえに まかせたぜ!!"
	line ""
	textfw0 "おれは ほかを もっと しらべて"
	line ""
	textfw4 "GR"
	textfw2 "団"
	textfw0 "の じょうほうを あつめるぜ!"
	line ""
	textfw0 "じゃあな"
	line ""
	textfw0 "<RAMNAME>", "!"
	done

Text126c:
	hiragana "おっ!"
	line ""
	textfw0 "<RAMNAME>", "じゃねぇか!"
	done

Text126d:
	textfw4 "GR"
	textfw2 "団"
	hiragana "の"
	katakana "ヤツ"
	hiragana "らを"
	line ""
	textfw0 "ふたり やっつけたようだな"
	line ""
	textfw0 "さすが "
	katakana "オレ"
	hiragana "の"
	line ""
	textfw0 "しゅくめいの"
	katakana "ライバル ", "<RAMNAME>"
	hiragana "だ"
	line ""
	textfw0 "おかげで "
	katakana "オレ"
	hiragana "も"
	line ""
	textfw0 "だいぶ "
	katakana "カード"
	hiragana "が あつまったぜ"
	line ""
	textfw0 "とりあえず "
	katakana "デッキ"
	hiragana "をつくったぜ!"
	line ""
	textfw0 "<RAMNAME>", " 対戦だ!"
	line ""
	katakana "サイドカード"
	hiragana "は 6枚!"
	line ""
	textfw0 "勝ったら めずらしい"
	katakana "カード"
	hiragana "をやるぜ!"
	done

Text126e:
	hiragana "けっ やっぱ かきあつめた"
	katakana "カード"
	hiragana "じゃ"
	line ""
	textfw0 "こんなもんか・・・"
	line ""
	textfw0 "しかたねぇや まけたからな!"
	line ""
	textfw0 "この"
	katakana "カード"
	hiragana "を やるぜ!"
	done

Text126f:
	hiragana "もっと "
	katakana "カード"
	hiragana "あつめなきゃ"
	line ""
	katakana "ダメ"
	hiragana "だな・・・"
	line ""
	textfw0 "また "
	textfw4 "GR"
	textfw2 "団"
	textfw0 "のじょうほうを"
	line ""
	textfw0 "つかんだら おしえてやるぜ!"
	done

Text1270:
	hiragana "けっ この"
	katakana "オレ"
	hiragana "に まけてるようじゃ"
	line ""
	textfw4 "GR"
	textfw2 "団"
	textfw0 "には たちむかえないぜ"
	line ""
	textfw4 "GR"
	textfw2 "団"
	textfw0 "を ふたりやっつけたのは"
	line ""
	katakana "マグレ"
	hiragana "じゃないのか?"
	line ""
	textfw0 "じゃあな ", "<RAMNAME>"
	line ""
	katakana "オレ"
	hiragana "は いくぜ!"
	done

Text1271:
	hiragana "よぉ ", "<RAMNAME>", "!"
	line ""
	katakana "オレ"
	hiragana "は やったぜ!!"
	done

Text1272:
	hiragana "おまえが "
	textfw4 "GR"
	textfw2 "団"
	textfw0 "の"
	katakana "ヤツ"
	hiragana "らと"
	line ""
	textfw0 "たたかっているあいだに "
	katakana "オレ"
	hiragana "が"
	line ""
	katakana "ヤツ"
	hiragana "らの ひこう"
	textfw2 "FW2_8b"
	textfw0 "に しのびこんで"
	line ""
	katakana "カード"
	hiragana "を とりもどしたぜ!"
	line ""
	textfw0 "とりもどした "
	katakana "カード"
	hiragana "は"
	line ""
	katakana "クラブ"
	hiragana "のやつらに くばってきたぜ!"
	line ""
	textfw0 "これで このしまに"
	line ""
	textfw0 "拡", "FW0_be"
	katakana "パック"
	hiragana "が また1つ ふえるぜ!"
	line ""
	textfw0 "これが あたらしい拡", "FW0_be"
	katakana "パック"
	line ""
	textfw1 "FW1_f2"
	textfw0 "3"
	textfw2 "FW2_5a"
	textfw0 "「化"
	textfw1 "石"
	hiragana "のしま」だぜ!!"
	done

Text1273:
	hiragana "いよいよ"
	line ""
	textfw4 "GR"
	textfw2 "団"
	textfw0 "のしまへ のりこむぜ!"
	line ""
	textfw0 "きをつけろよ! "
	katakana "ヤツ"
	hiragana "らのしまだ!"
	line ""
	textfw0 "かんたんには いかないぜ!"
	line ""
	textfw0 "こっちのしまで たくさん対戦して"
	line ""
	katakana "カード"
	hiragana "をあつめるんだ!"
	line ""
	textfw0 "そうすりゃ いろんな"
	katakana "デッキ"
	hiragana "を"
	line ""
	textfw0 "つくれるように なるからな!"
	line ""
	textfw0 "じゃあ またな"
	line ""
	textfw0 "<RAMNAME>"
	done

Text1274:
	textfw0 "<RAMNAME>", " "
	hiragana "じゃねぇか!"
	line ""
	textfw0 "どうした こんなところで"
	done

Text1275:
	hiragana "どうやら ここは"
	line ""
	textfw4 "GR"
	textfw2 "団"
	textfw0 "の "
	katakana "ゲームセンター"
	hiragana "らしい!"
	line ""
	textfw0 "おくには "
	katakana "スロットマシーン"
	hiragana "やら"
	line ""
	katakana "ゲームマシン"
	hiragana "が いっぱい あるぜ"
	line ""
	katakana "ゲーム"
	hiragana "で "
	katakana "チップ"
	hiragana "をあつめると"
	line ""
	katakana "カード"
	hiragana "や"
	katakana "コイン"
	hiragana "を "
	katakana "ゲット"
	hiragana "できるってよ"
	line ""
	katakana "オレ"
	hiragana "も こんな"
	katakana "カード"
	hiragana "を もらったぜ"
	line ""
	textfw0 "ほら ", "<RAMNAME>", "に やるぜ!"
	done

Text1276:
	hiragana "でも その"
	katakana "カード"
	hiragana "は"
	line ""
	katakana "デッキ"
	hiragana "には いれられないからな!"
	line ""
	textfw0 "まっ ほかにも いろんなものが"
	line ""
	textfw0 "もらえるらしいぜ!"
	line ""
	textfw0 "でも "
	katakana "オレ"
	hiragana "たちの もくてきは"
	line ""
	textfw0 "うばわれた"
	katakana "カード"
	hiragana "を とりもどすのと"
	line ""
	textfw4 "GR"
	textfw2 "団"
	textfw0 "に つかまっている"
	line ""
	textfw0 "なかまを たすけだすこと だからな"
	line ""
	textfw0 "あんまり"
	katakana "ゲーム"
	hiragana "に むちゅうになって"
	line ""
	textfw0 "わすれるんじゃ"
	textfw4 "~"
	textfw0 "ねぇぜ!"
	line ""
	textfw0 "じゃあな ", "<RAMNAME>", "!"
	done

Text1277:
	hiragana "んっ なんだ! おまえ!"
	line ""
	textfw0 "ちょっと こっちへこい!"
	done

Text1278:
	hiragana "おまえ"
	line ""
	textfw4 "GR"
	textfw2 "団"
	textfw0 "員では ないな!"
	line ""
	textfw0 "きさまも "
	katakana "ポケモンカード"
	hiragana "を"
	line ""
	textfw0 "もっているようだな・・・"
	line ""
	textfw0 "まあ いい"
	line ""
	textfw0 "おまえのちからを みてやろう!"
	line ""
	katakana "オレ"
	hiragana "たちの 「わるい"
	katakana "ポケモン」"
	hiragana "に"
	line ""
	textfw0 "勝つことが できるかな?"
	line ""
	textfw0 "いくぞ ", "<RAMNAME>", "!"
	line ""
	katakana "サイドカード6枚"
	hiragana "で 対戦だ!"
	done

Text1279:
	hiragana "けっ なかなかやるじゃないか"
	line ""
	textfw0 "<RAMNAME>", "!!"
	done

Text127a:
	textfw0 "オレ"
	hiragana "だよ "
	katakana "ランド"
	hiragana "だ!"
	line ""
	textfw0 "おどろいたか? ", "<RAMNAME>", "!"
	line ""
	textfw0 "このかっこうじゃ "
	katakana "スパイ"
	hiragana "かつどうが"
	line ""
	textfw0 "できないから へんそうしてるんだ"
	line ""
	textfw0 "とりあえず まけたからな!"
	line ""
	textfw4 "GR"
	textfw2 "団"
	textfw0 "の拡", "FW0_be"
	katakana "パック"
	hiragana "を やるぜ!"
	done

Text127b:
	hiragana "いいか よくきけよ"
	line ""
	textfw4 "GR"
	textfw2 "団"
	textfw0 "の対戦の じょうほうだ!"
	line ""
	textfw4 "GR"
	textfw2 "団"
	textfw0 "の"
	katakana "ヤツ"
	hiragana "らは わるい"
	katakana "ポケモン"
	hiragana "の"
	line ""
	katakana "カード"
	hiragana "で "
	katakana "デッキ"
	hiragana "をつくっているんだ"
	line ""
	textfw0 "それに "
	katakana "デッキ"
	hiragana "に とくていの"
	katakana "カード"
	hiragana "を"
	line ""
	textfw0 "いれるように じょうけんを だしたり"
	line ""
	textfw0 "その対戦だけの とくべつ"
	katakana "ルール"
	hiragana "で"
	line ""
	textfw0 "たたかいを いどんでくる!"
	line ""
	textfw0 "対戦あいての はなしを よくきいて"
	line ""
	textfw0 "どういう 対戦か かくにんするんだぜ"
	line ""
	textfw0 "そうしないと"
	line ""
	textfw0 "たいへんなめに あうからな"
	line ""
	textfw0 "じゃ"
	line ""
	katakana "オレ"
	hiragana "は いくぜ!"
	done

Text127c:
	hiragana "また このかっこうで "
	katakana "スパイ"
	hiragana "してるぜ"
	line ""
	textfw0 "がんばれよ ", "<RAMNAME>"
	done

Text127d:
	hiragana "へっ たいしたことねぇな!"
	line ""
	textfw0 "<RAMNAME>", "!!"
	done

Text127e:
	textfw0 "オレ"
	hiragana "だよ "
	katakana "ランド"
	hiragana "だ!"
	line ""
	textfw0 "おどろいたか? ", "<RAMNAME>", "!"
	line ""
	textfw0 "このかっこうじゃ "
	katakana "スパイ"
	hiragana "かつどうが"
	line ""
	textfw0 "できないから へんそうしてるんだ"
	line ""
	katakana "オレ"
	hiragana "に まけるようじゃ"
	line ""
	textfw4 "GR"
	textfw2 "団"
	textfw0 "には 勝てないぜ!!"
	done

Text127f:
	hiragana "おい ", "<RAMNAME>", "!!"
	line ""
	textfw0 "こっちへ こいよ!!"
	done

Text1280:
	hiragana "あんしんしろ "
	textfw4 "GR"
	textfw2 "団"
	textfw0 "じゃない"
	line ""
	katakana "オレ"
	hiragana "だ! "
	katakana "ランド"
	hiragana "だ!!"
	done

Text1281:
	hiragana "どうやら 「", "<RAMTEXT>", "の"
	textfw4 "GR"
	textfw2 "団"
	katakana "コイン」"
	hiragana "を"
	line ""
	textfw0 "てに いれたらしいな?"
	line ""
	textfw0 "けど 闘の"
	textfw4 "GR"
	textfw2 "団"
	textfw0 "の"
	katakana "トリデ"
	hiragana "に"
	line ""
	textfw0 "はいるには もう1こ "
	katakana "コイン"
	hiragana "がいるぜ"
	line ""
	textfw0 "わかってるかもしれないが"
	line ""
	textfw0 "「", "<RAMTEXT>", "の"
	textfw4 "GR"
	textfw2 "団"
	katakana "コイン」"
	hiragana "だぜ!!"
	line ""
	textfw0 "闘の"
	textfw4 "GR"
	textfw2 "団"
	textfw0 "の"
	katakana "トリデ"
	hiragana "は "
	katakana "デッカイ"
	line ""
	textfw0 "ダンジョン"
	hiragana "に なっているらしいぜ"
	line ""
	textfw0 "まだまだ さきは ながいぜ"
	line ""
	textfw0 "<RAMNAME>", "!"
	line ""
	textfw0 "ここまで どれだけ つよくなったか"
	line ""
	katakana "オレ"
	hiragana "が おまえの"
	katakana "チカラ"
	hiragana "を みてやる!"
	line ""
	katakana "サイドカード6枚"
	hiragana "で 対戦だ!"
	line ""
	textfw0 "勝てば いい"
	katakana "カード"
	hiragana "を やるぜ!"
	done

Text1282:
	hiragana "どうやら だいぶ "
	textfw4 "GR"
	textfw2 "団"
	textfw0 "の対戦で"
	line ""
	textfw0 "きたえられたらしいな"
	line ""
	textfw0 "じゃあ やくそくだから"
	line ""
	textfw0 "いい"
	katakana "カード"
	hiragana "を やるぜ!"
	done

Text1283:
	hiragana "どうだ いい"
	katakana "カード"
	hiragana "だろ"
	line ""
	textfw0 "どうつかうかは おまえ しだいだ"
	line ""
	textfw0 "じゃあ "
	katakana "オレ"
	hiragana "は さきにいくぜ"
	line ""
	katakana "ガンバレ"
	hiragana "よ ", "<RAMNAME>", "!"
	done

Text1284:
	hiragana "なんだ?"
	line ""
	textfw0 "あいかわらず よわいじゃねぇか"
	line ""
	textfw0 "これじゃ このさきは "
	katakana "キビ"
	hiragana "しいぜ"
	line ""
	katakana "デッキ"
	hiragana "が わるいんじゃねぇのか"
	line ""
	katakana "オレ"
	hiragana "たちのしまへ もどって"
	line ""
	katakana "カード"
	hiragana "を あつめたほうが いいぜ!"
	line ""
	textfw0 "じゃあ "
	katakana "オレ"
	hiragana "は さきにいくぜ"
	line ""
	katakana "ガンバレ"
	hiragana "よ ", "<RAMNAME>", "!"
	done

Text1285:
	hiragana "やっときたか ", "<RAMNAME>"
	line ""
	textfw0 "はやく こっちへ こいよ!!"
	done

Text1286:
	textfw0 "オレ"
	hiragana "だ! "
	katakana "ランド"
	hiragana "だ!"
	line ""
	textfw0 "もう わかってんだろ!!"
	done

Text1287:
	textfw0 "闘"
	hiragana "の"
	textfw4 "GR"
	textfw2 "団"
	textfw0 "の"
	katakana "トリデ"
	hiragana "で"
	line ""
	katakana "ダンジョン"
	hiragana "にでも まよってたのか?"
	line ""
	textfw0 "まち くたびれちまったぜ!"
	line ""
	textfw4 "GR"
	textfw2 "団"
	textfw0 "のじょうほうだ よく きけよ"
	line ""
	textfw0 "このさきの "
	textfw4 "GR"
	textfw2 "団"
	textfw0 "の"
	katakana "キャッスル"
	hiragana "には"
	line ""
	textfw4 "GR"
	textfw2 "団"
	textfw0 "の"
	katakana "キング"
	hiragana "が いるんだ!"
	line ""
	textfw0 "だが やつにあうには"
	line ""
	textfw0 "れいによって "
	katakana "コイン"
	hiragana "が 2ついる"
	line ""
	textfw0 "「超の"
	textfw4 "GR"
	textfw2 "団"
	katakana "コイン」"
	hiragana "と"
	line ""
	textfw0 "「無の"
	textfw4 "GR"
	textfw2 "団"
	katakana "コイン」"
	hiragana "の ふたつだ!"
	line ""
	textfw0 "はやく "
	katakana "ゲット"
	hiragana "して"
	line ""
	textfw4 "GR"
	textfw2 "団"
	textfw0 "の"
	katakana "キャッスル"
	hiragana "に のりこめ!"
	line ""
	textfw0 "あんまり "
	katakana "ノロノロ"
	hiragana "してやがると"
	line ""
	katakana "オレ"
	hiragana "が さきに やっちまうぜ!!"
	line ""
	textfw0 "じゃあな!"
	line ""
	textfw0 "たのむぜ ", "<RAMNAME>", "!!"
	done

Text1288:
	hiragana "ま・・・まけた・・・"
	line ""
	katakana "カンペキ"
	hiragana "に まけたぜ・・・"
	done

Text1289:
	hiragana "ああ ", "<RAMNAME>", "か"
	line ""
	katakana "ヤツ"
	hiragana "らの つよさは はんぱじゃない"
	line ""
	katakana "オレ"
	hiragana "なんかじゃ"
	line ""
	textfw0 "ぜんぜん かなわないぜ!"
	line ""
	textfw0 "<RAMNAME>", " おまえ・・・"
	line ""
	katakana "デッキ"
	hiragana "のじゅんびは だいじょうぶか"
	line ""
	textfw0 "これが さいごだ"
	line ""
	textfw0 "おまえのちからを みてやるぜ!"
	line ""
	katakana "オレ"
	hiragana "に 勝てないようじゃ"
	line ""
	textfw4 "GR"
	textfw2 "団"
	textfw0 "の"
	katakana "キング"
	hiragana "には 勝てないぜ"
	line ""
	textfw0 "いつもの "
	katakana "サイドカード6枚"
	hiragana "だ"
	line ""
	textfw0 "勝てば 「超"
	katakana "エネ回収」"
	hiragana "を やるぜ!"
	done

Text128a:
	hiragana "さすがだな ", "<RAMNAME>"
	line ""
	textfw0 "おまえは つよいよ"
	line ""
	textfw0 "さあ"
	line ""
	textfw0 "「超"
	katakana "エネルギー回収」"
	hiragana "をもっていけ"
	done

Text128b:
	hiragana "おまえなら きっと 勝てる!!"
	line ""
	textfw0 "あとは まかせたぜ!"
	line ""
	textfw0 "じゃあな"
	line ""
	textfw0 "がんばれよ ", "<RAMNAME>", "!!"
	done

Text128c:
	hiragana "おい たのむぜ ", "<RAMNAME>", "!"
	line ""
	textfw0 "もう おまえしか いないんだぜ!"
	line ""
	katakana "オレ"
	hiragana "に まけているようじゃあ"
	line ""
	katakana "ヤツ"
	hiragana "らには 勝てないぜ!"
	line ""
	textfw0 "がんばってくれ! ", "<RAMNAME>", "!"
	line ""
	katakana "オレ"
	hiragana "は おまえを しんじてるぜ!"
	line ""
	textfw0 "おまえなら きっと 勝てる!!"
	line ""
	textfw0 "あとは まかせたぜ!"
	line ""
	textfw0 "じゃあな"
	line ""
	textfw0 "がんばれよ ", "<RAMNAME>", "!!"
	done

Text128d:
	hiragana "よぉ ", "<RAMNAME>", "!"
	line ""
	textfw0 "いいかんじ じゃないか!"
	done

Text128e:
	textfw4 "GR"
	textfw0 "3"
	textfw3 "FW3_9d"
	hiragana "のやつ あわてて"
	line ""
	katakana "カード"
	hiragana "を たくさん おとしていったぞ"
	line ""
	textfw0 "これで このしまに"
	line ""
	textfw0 "拡", "FW0_be"
	katakana "パック"
	hiragana "が 1つ ふえるぜ!"
	line ""
	textfw0 "ほら あたらしい拡", "FW0_be"
	katakana "パック"
	line ""
	textfw1 "FW1_f2"
	textfw0 "2"
	textfw2 "FW2_5a"
	textfw0 "「"
	hiragana "でんせつのちから」だ!!"
	done

Text128f:
	hiragana "このちょうしで たのむぜ"
	line ""
	textfw4 "GR"
	textfw2 "団"
	textfw0 "の"
	katakana "ヤツ"
	hiragana "らを やっつけてくれ!"
	line ""
	textfw0 "そうすりゃ また"
	line ""
	textfw0 "拡", "FW0_be"
	katakana "パック"
	hiragana "が ふえるぜ!"
	line ""
	textfw0 "じゃあ またな"
	line ""
	textfw0 "<RAMNAME>"
	done

Text1290:
	textfw0 "2"
	hiragana "つの"
	katakana "カード"
	hiragana "を くみあわせてつかうと"
	line ""
	textfw0 "きょうりょくな 「"
	katakana "コンボ」"
	hiragana "になる!"
	line ""
	textfw0 "特殊能力や "
	katakana "トレーナーカード"
	hiragana "は"
	line ""
	textfw0 "「"
	katakana "コンボ」"
	hiragana "に やくだつぞ!"
	line ""
	textfw0 "「"
	katakana "コンボ」"
	hiragana "を うみだす"
	katakana "カード"
	hiragana "の"
	line ""
	textfw0 "くみあわせを さがしだそう"
	done

Text1291:
	textfw0 "ナッシー"
	hiragana "を "
	katakana "バトル場"
	hiragana "にだしたけど"
	line ""
	katakana "エネルギー"
	hiragana "が ない?"
	line ""
	textfw0 "そんなときは "
	katakana "フシギバナ"
	hiragana "の"
	line ""
	katakana "エナジートランス"
	hiragana "だ!"
	line ""
	textfw0 "草"
	katakana "エネルギー"
	hiragana "を いどうして"
	line ""
	textfw0 "「たまなげ"
	textfw4 "MAX"
	textfw0 "」を つかおう"
	line ""
	textfw0 "たとえば 8枚"
	katakana "エネルギー"
	hiragana "をつけると"
	line ""
	textfw0 "あいてに "
	textfw4 "MAX"
	textfw0 "で160"
	katakana "ダメージ"
	hiragana "だ!"
	done

Text1292:
	textfw0 "ベトベトン"
	hiragana "の 「かがくへんか"
	katakana "ガス」"
	hiragana "は"
	line ""
	textfw0 "とっても きょうりょく!"
	line ""
	katakana "ポケモン"
	hiragana "の 特殊能力を"
	line ""
	textfw0 "ぜんぶ ふうじることが できる!"
	line ""
	textfw0 "でも じぶんの"
	katakana "ポケモン"
	hiragana "の特殊能力も"
	line ""
	textfw0 "つかえなくなるから きをつけよう"
	done

Text1293:
	textfw0 "カメックス"
	hiragana "の 「あまごい」は"
	line ""
	textfw0 "水"
	katakana "ポケモン"
	hiragana "には とても ゆうこうだ!"
	line ""
	textfw0 "じぶんの番に 水"
	katakana "エネルギー"
	hiragana "を"
	line ""
	textfw0 "水"
	katakana "ポケモン"
	hiragana "に なん枚でもつけられる"
	line ""
	textfw0 "水"
	katakana "ポケモン"
	hiragana "に 水"
	katakana "エネルギー"
	hiragana "を"
	line ""
	textfw0 "いっきにつけて きしゅうこうげきだ!"
	line ""
	textfw0 "手札に 水"
	katakana "エネルギー"
	hiragana "が ないときは"
	line ""
	katakana "トレーナーカード"
	hiragana "を つかうといいぞ"
	line ""
	textfw0 "「"
	katakana "オーキド"
	hiragana "はかせ」で 山札から"
	line ""
	katakana "カード"
	hiragana "をひいて 水"
	katakana "エネルギーゲット"
	hiragana "だ"
	done

Text1294:
	textfw0 "「"
	hiragana "じばく」するときには"
	line ""
	katakana "ディフェンダー"
	hiragana "を つけると"
	katakana "イイ!"
	line ""
	hiragana "こうすれば 「じばく」しても"
	line ""
	textfw0 "じぶんの"
	katakana "ポケモン"
	hiragana "は 「きぜつ」しない"
	line ""
	textfw0 "あいての 対戦"
	katakana "ポケモン"
	hiragana "や"
	line ""
	katakana "ベンチ"
	hiragana "の"
	katakana "ポケモン"
	hiragana "だけに 大"
	katakana "ダメージ!"
	done

Text1295:
	textfw0 "フーディン"
	hiragana "の "
	katakana "ダメージスワップ"
	hiragana "で"
	line ""
	katakana "ダメージカウンター"
	hiragana "が うごかせる"
	line ""
	textfw0 "「きぜつ」しそうな "
	katakana "ポケモン"
	hiragana "の"
	line ""
	katakana "ダメージカウンター"
	hiragana "を うつしたり"
	line ""
	textfw0 "「"
	katakana "ラッキー」"
	hiragana "や「"
	katakana "ポケモン回収」"
	hiragana "と"
	line ""
	textfw0 "くみあわせる "
	katakana "コンボ"
	hiragana "もある"
	line ""
	katakana "ポケモン"
	hiragana "の"
	katakana "ダメージカウンター"
	hiragana "を"
	line ""
	katakana "ラッキー"
	hiragana "に "
	katakana "ドンドン"
	hiragana "いどうさせる"
	line ""
	katakana "ダメージカウンター"
	hiragana "を いどうさせた"
	line ""
	katakana "ラッキー"
	hiragana "を「"
	katakana "ポケモン回収」"
	hiragana "で 手札へ"
	line ""
	textfw0 "ふたたび "
	katakana "ラッキー"
	hiragana "を 場にだせば"
	line ""
	katakana "ダメージカウンター"
	hiragana "だけが なくなる"
	done

Text1296:
	textfw0 "「超エネルギーリムーブ」"
	hiragana "や"
	line ""
	textfw0 "「"
	katakana "エネルギー・リムーブ」"
	hiragana "を つかって"
	line ""
	textfw0 "あいての"
	katakana "ポケモン"
	hiragana "の "
	katakana "エネルギー"
	hiragana "を"
	line ""
	textfw0 "はがして しまおう!"
	line ""
	katakana "エネルギー"
	hiragana "がなければ "
	katakana "ポケモン"
	hiragana "は"
	line ""
	textfw0 "「"
	katakana "ワザ」"
	hiragana "を つかうことも"
	line ""
	textfw0 "また "
	katakana "バトル場"
	hiragana "から"
	line ""
	textfw0 "「にげる」ことも できなくなる"
	line ""
	katakana "ワザ"
	hiragana "の 「はかいこうせん」も"
	line ""
	textfw0 "あいての"
	katakana "エネルギー"
	hiragana "を はがせるぞ!"
	done

Text1297:
	textfw0 "プテラ"
	hiragana "の 「げんしのちから」で"
	line ""
	textfw0 "あいての進化を ふうじこめよう"
	line ""
	textfw0 "じぶんの"
	katakana "ポケモン"
	hiragana "も 進化できない?"
	line ""
	textfw0 "そんな ときは・・・"
	line ""
	textfw0 "「"
	textfw1 "退"
	textfw0 "化"
	katakana "スプレー」"
	hiragana "で "
	katakana "プテラ"
	hiragana "を"
	line ""
	textfw0 "「なにかの化"
	textfw1 "石"
	textfw0 "」に もどしてしまおう"
	line ""
	textfw0 "こうすれば じぶんの"
	katakana "ポケモン"
	hiragana "は"
	line ""
	katakana "ドンドン 進化"
	hiragana "できるぞ!"
	line ""
	textfw0 "じぶんの"
	katakana "ポケモン"
	hiragana "の 進化がおわったら"
	line ""
	textfw0 "また "
	katakana "プテラ"
	hiragana "に 進化させよう"
	line ""
	textfw0 "これで また 「げんしのちから」で"
	line ""
	textfw0 "あいての"
	katakana "ポケモン"
	hiragana "は 進化できないぞ!"
	done

Text1298:
	hiragana "あいての弱点の色で こうげきすると"
	line ""
	katakana "ダメージ"
	hiragana "は 2ばいになる"
	line ""
	textfw0 "水"
	katakana "ポケモン"
	hiragana "の こうげきなら"
	line ""
	textfw0 "炎"
	katakana "ポケモン"
	hiragana "に "
	katakana "ダメージ2"
	hiragana "ばい!"
	line ""
	textfw0 "抵抗力の色で こうげきすると"
	line ""
	katakana "ダメージ"
	hiragana "は "
	katakana "マイナス30ダメージ"
	line ""
	textfw0 "30ダメージ"
	hiragana "の「"
	katakana "ワザ」"
	hiragana "だと"
	line ""
	katakana "ダメージ"
	hiragana "は なくなってしまう!"
	line ""
	textfw0 "「弱点」と「抵抗力」には"
	line ""
	textfw0 "きを つけよう!"
	done

Text1299:
	textfw4 "GR"
	textfw2 "団"
	hiragana "の ほんとうのなまえは"
	line ""
	textfw0 "「"
	katakana "グレートロケット"
	textfw2 "団"
	textfw0 "」"
	hiragana "だ!"
	line ""
	textfw4 "GR"
	textfw2 "団"
	textfw0 "は "
	katakana "カード"
	hiragana "は つかうことに"
	line ""
	textfw0 "かちがあると かんがえている"
	line ""
	textfw0 "つかわれない "
	katakana "カード"
	hiragana "を すくうために"
	line ""
	textfw4 "GR"
	textfw2 "団"
	textfw0 "は たたかっていると いう"
	line ""
	textfw4 "GR"
	textfw2 "団"
	textfw0 "の対戦には 特"
	textfw1 "別"
	katakana "ルール"
	hiragana "があって"
	line ""
	textfw0 "さまざまな"
	katakana "カード"
	hiragana "で対戦しているときく"
	line ""
	textfw0 "かれらも また "
	katakana "ポケモンカード"
	hiragana "を"
	line ""
	textfw0 "あいしていることに かわりはないのだ"
	done

Text129a:
	textfw4 "GR"
	textfw2 "団"
	hiragana "のしまには "
	katakana "ゲームセンター"
	hiragana "と"
	line ""
	textfw0 "よばれるところがある"
	line ""
	katakana "ゲームセンター"
	hiragana "で "
	katakana "チップ"
	hiragana "を"
	line ""
	textfw0 "あつめると "
	katakana "カード"
	hiragana "や"
	katakana "コイン"
	hiragana "がもらえる"
	line ""
	katakana "カード"
	hiragana "のなかには"
	katakana "ゲームセンター"
	hiragana "でしか"
	line ""
	katakana "ゲット"
	hiragana "できない "
	katakana "カード"
	hiragana "も あるらしい"
	done

Text129b:
	hiragana "おなじ"
	katakana "ポケモン"
	hiragana "でも "
	katakana "レベル"
	hiragana "がちがう"
	line ""
	katakana "ポケモンカード"
	hiragana "が たくさんある"
	line ""
	katakana "ポケモン"
	hiragana "の"
	katakana "レベル"
	hiragana "が ちがうと"
	line ""
	textfw4 "HP"
	textfw0 "や "
	katakana "ワザ"
	hiragana "も ちがっている"
	line ""
	katakana "ピカチュウ"
	hiragana "は ", "<Lv>", "5 ", "<Lv>", "12 ", "<Lv>", "13"
	line ""
	textfw0 "<Lv>", "14 ", "<Lv>", "16と 5つもある"
	line ""
	textfw0 "おなじ"
	katakana "ポケモンカード"
	hiragana "は 4枚しか"
	line ""
	textfw0 "いれられない きまりがあるから"
	line ""
	textfw0 "おなじ"
	katakana "ポケモン"
	hiragana "が たくさんあるときは"
	line ""
	textfw0 "どれをいれるかを よく かんがえよう"
	done

Text129c:
	textfw0 "岩・地面ポケモンカード"
	hiragana "の"
	line ""
	textfw0 "とくちょう"
	line ""
	textfw0 "雷"
	katakana "ポケモンカード"
	hiragana "に つよく"
	line ""
	textfw0 "草"
	katakana "ポケモンカード"
	hiragana "に よわい"
	line ""
	textfw0 "「"
	katakana "ワザ」"
	hiragana "を つかうには"
	line ""
	textfw0 "闘"
	katakana "エネルギーカード"
	hiragana "が ひつよう"
	done

Text129d:
	textfw0 "闘ポケモンカード"
	hiragana "は"
	line ""
	textfw0 "2進化"
	katakana "ポケモン"
	hiragana "が にがて"
	line ""
	textfw0 "2進化"
	katakana "ポケモン"
	hiragana "には 闘"
	katakana "ポケモン"
	hiragana "に"
	line ""
	textfw0 "「抵抗力」のある"
	katakana "カード"
	hiragana "が おおい"
	line ""
	textfw0 "あいてが 進化しないうちに"
	line ""
	textfw0 "はやめに たおすのが 勝つ"
	katakana "コツ"
	hiragana "だ!"
	done

Text129e:
	textfw0 "闘ポケモン"
	hiragana "は 無色のとり"
	katakana "ポケモン"
	hiragana "が"
	line ""
	textfw0 "とても にがてだ"
	line ""
	textfw0 "とり"
	katakana "ポケモン"
	hiragana "は 闘"
	katakana "ポケモン"
	hiragana "に"
	line ""
	textfw0 "「抵抗力」を もっているからだ"
	line ""
	katakana "デッキ"
	hiragana "に とり"
	katakana "ポケモン"
	hiragana "の「弱点」の"
	line ""
	textfw0 "雷"
	katakana "ポケモン"
	hiragana "を いれておくと いいぞ"
	done

Text129f:
	hiragana "かくとう"
	katakana "ポケモンカード"
	hiragana "の"
	line ""
	textfw0 "とくちょう"
	line ""
	textfw0 "雷"
	katakana "ポケモンカード"
	hiragana "に つよく"
	line ""
	textfw0 "超"
	katakana "ポケモンカード"
	hiragana "に よわい"
	line ""
	textfw0 "「"
	katakana "ワザ」"
	hiragana "を つかうには"
	line ""
	textfw0 "闘"
	katakana "エネルギーカード"
	hiragana "が ひつよう"
	done

Text12a0:
	hiragana "かくとう"
	katakana "ポケモン"
	hiragana "は"
	line ""
	textfw0 "「"
	katakana "コンボ」"
	hiragana "を つくりにくい"
	line ""
	textfw0 "かくとう"
	katakana "ポケモン"
	hiragana "には"
	line ""
	textfw0 "特殊能力が すくないからだ"
	line ""
	textfw0 "でも つよい「"
	katakana "ワザ」"
	hiragana "が おおいから"
	line ""
	textfw0 "「"
	katakana "コンボ」"
	hiragana "がなくても だいじょうぶ"
	done

Text12a1:
	hiragana "かくとう"
	katakana "ポケモン"
	hiragana "は"
	line ""
	textfw0 "超"
	katakana "ポケモン"
	hiragana "に 「弱点」をもっている"
	line ""
	katakana "デッキ"
	hiragana "に超"
	katakana "ポケモン"
	hiragana "に「抵抗力」のある"
	line ""
	katakana "ポケモン"
	hiragana "を いれて おくといいぞ"
	line ""
	textfw0 "「"
	katakana "ガルーラ」「ケンタロス」「ピッピ」"
	line ""
	hiragana "などの 無色"
	katakana "ポケモン"
	hiragana "が いいぞ"
	done

Text12a2:
	hiragana "しょくぶつ"
	katakana "ポケモンカード"
	hiragana "の"
	line ""
	textfw0 "とくちょう"
	line ""
	textfw0 "岩や地面の"
	katakana "ポケモンカード"
	hiragana "に つよく"
	line ""
	textfw0 "炎"
	katakana "ポケモンカード"
	hiragana "に よわい"
	line ""
	textfw0 "たまに 水"
	katakana "ポケモンカード"
	hiragana "に"
	line ""
	textfw0 "つよいことも ある"
	line ""
	textfw0 "「"
	katakana "ワザ」"
	hiragana "を つかうには"
	line ""
	textfw0 "草"
	katakana "エネルギーカード"
	hiragana "が ひつよう"
	done

Text12a3:
	textfw0 "草ポケモン"
	hiragana "には 2進化する"
	line ""
	katakana "ポケモン"
	hiragana "が おおい"
	line ""
	textfw0 "「"
	katakana "ポケモン"
	textfw1 "育"
	hiragana "て"
	textfw1 "FW1_9b"
	textfw0 "さん」を"
	line ""
	textfw0 "うまく つかおう"
	line ""
	textfw0 "はやく 2進化に 進化できれば"
	line ""
	textfw0 "つよい"
	katakana "ワザ"
	hiragana "が はやく つかえるぞ"
	line ""
	textfw0 "「"
	katakana "フシギバナ」"
	hiragana "や「"
	katakana "ラフレシア」"
	hiragana "で"
	line ""
	textfw0 "あいての"
	katakana "ポケモン"
	hiragana "を げきはしよう"
	done

Text12a4:
	textfw0 "草ポケモン"
	hiragana "は"
	line ""
	textfw0 "炎"
	katakana "ポケモン"
	hiragana "に 「弱点」をもっている"
	line ""
	katakana "デッキ"
	hiragana "に 炎"
	katakana "ポケモン"
	hiragana "の「弱点」の"
	line ""
	textfw0 "水"
	katakana "ポケモン"
	hiragana "をいれて おくといいぞ"
	line ""
	textfw0 "あいての場に 炎"
	katakana "ポケモン"
	hiragana "が"
	line ""
	textfw0 "でてきたら 水"
	katakana "ポケモン"
	hiragana "で こうげきだ"
	done

Text12a5:
	hiragana "かがく"
	katakana "ポケモンカード"
	hiragana "の"
	line ""
	textfw0 "とくちょう"
	line ""
	textfw0 "岩や地面の"
	katakana "ポケモンカード"
	hiragana "に つよく"
	line ""
	textfw0 "超"
	katakana "ポケモンカード"
	hiragana "に よわい"
	line ""
	textfw0 "あいてを「どく」や「こんらん」"
	line ""
	textfw0 "「ねむり」にする "
	katakana "カード"
	hiragana "がおおい"
	line ""
	textfw0 "「"
	katakana "ワザ」"
	hiragana "を つかうには"
	line ""
	textfw0 "草"
	katakana "エネルギーカード"
	hiragana "が ひつよう"
	done

Text12a6:
	hiragana "かがく"
	katakana "ポケモン"
	hiragana "は 「どく」「ねむり」"
	line ""
	textfw0 "「こんらん」の こうげきが おおい"
	line ""
	textfw0 "だから 特殊能力から かいふくできる"
	line ""
	textfw0 "「なんでもなおし」を いれておこう"
	line ""
	textfw0 "そうすれば 「どく」や「こんらん」に"
	line ""
	textfw0 "されても あんしんだ!"
	done

Text12a7:
	hiragana "かがく"
	katakana "ポケモン"
	hiragana "は"
	line ""
	textfw0 "超"
	katakana "ポケモン"
	hiragana "に 「弱点」をもっている"
	line ""
	katakana "デッキ"
	hiragana "に超"
	katakana "ポケモン"
	hiragana "に「抵抗力」のある"
	line ""
	katakana "ポケモン"
	hiragana "をいれて おくといいぞ"
	line ""
	textfw0 "「"
	katakana "プリン」"
	hiragana "や「"
	katakana "ペロリンガ」"
	line ""
	textfw0 "「カビゴン」"
	hiragana "なんかも いいぞ"
	done

Text12a8:
	textfw0 "水ポケモンカード"
	hiragana "の"
	line ""
	textfw0 "とくちょう"
	line ""
	textfw0 "炎"
	katakana "ポケモンカード"
	hiragana "に つよく"
	line ""
	textfw0 "雷"
	katakana "ポケモンカード"
	hiragana "に よわい"
	line ""
	textfw0 "たまに 草"
	katakana "ポケモンカード"
	hiragana "に"
	line ""
	textfw0 "よわい "
	katakana "カード"
	hiragana "もある"
	line ""
	textfw0 "「"
	katakana "ワザ」"
	hiragana "を つかうには"
	line ""
	textfw0 "水"
	katakana "エネルギーカード"
	hiragana "が ひつよう"
	done

Text12a9:
	textfw0 "「"
	hiragana "みずでっぽう」「"
	katakana "ハイドロポンプ」"
	hiragana "は"
	line ""
	textfw0 "こうげきりょくが かわる「"
	katakana "ワザ」"
	line ""
	textfw0 "水エネルギーカード"
	hiragana "を つけるほど"
	line ""
	textfw0 "こうげきりょくが つよくなる!"
	line ""
	textfw0 "ふやすことが できるのは"
	line ""
	textfw0 "水"
	katakana "エネルギー 2"
	hiragana "つぶんまでだ"
	done

Text12aa:
	textfw0 "コダック"
	hiragana "や "
	katakana "ゴルダック"
	hiragana "は"
	line ""
	textfw0 "超"
	katakana "エネルギー"
	hiragana "の "
	katakana "ワザ"
	hiragana "をもっている"
	line ""
	katakana "デッキ"
	hiragana "を つくるときは"
	line ""
	textfw0 "超"
	katakana "ポケモン"
	hiragana "と くみあわせると いいぞ"
	line ""
	textfw0 "超"
	katakana "ポケモン"
	hiragana "の"
	katakana "デッキ"
	hiragana "に 「"
	katakana "コダック」"
	hiragana "や"
	line ""
	textfw0 "「"
	katakana "ゴルダック」"
	hiragana "を いれてもいいぞ"
	done

Text12ab:
	textfw0 "炎ポケモンカード"
	hiragana "の"
	line ""
	textfw0 "とくちょう"
	line ""
	textfw0 "草"
	katakana "ポケモンカード"
	hiragana "に つよく"
	line ""
	textfw0 "水"
	katakana "ポケモンカード"
	hiragana "に よわい"
	line ""
	textfw0 "でも たまに 草"
	katakana "ポケモン"
	hiragana "でも"
	line ""
	textfw0 "炎によわくない"
	katakana "カード"
	hiragana "も ある!"
	done

Text12ac:
	textfw0 "炎ポケモンカード"
	hiragana "の 「"
	katakana "ワザ」"
	hiragana "は"
	line ""
	textfw0 "炎"
	katakana "エネルギー"
	hiragana "を はがすものが おおい"
	line ""
	textfw0 "炎"
	katakana "ポケモンカード中"
	textfw1 "心"
	hiragana "の "
	katakana "デッキ"
	hiragana "には"
	line ""
	textfw0 "炎"
	katakana "エネルギー"
	hiragana "を たくさん いれよう"
	line ""
	textfw0 "「"
	katakana "エネルギー回収」"
	hiragana "の"
	katakana "カード"
	hiragana "を"
	line ""
	textfw0 "いれておく ほうほうもあるぞ"
	done

Text12ad:
	textfw0 "炎ポケモン"
	hiragana "は"
	line ""
	textfw0 "水"
	katakana "ポケモン"
	hiragana "に 「弱点」をもっている"
	line ""
	katakana "デッキ"
	hiragana "に 水"
	katakana "ポケモン"
	hiragana "の「弱点」の"
	line ""
	textfw0 "雷"
	katakana "ポケモン"
	hiragana "をいれて おくといいぞ"
	line ""
	textfw0 "あいての場に 水"
	katakana "ポケモン"
	hiragana "が"
	line ""
	textfw0 "でてきたら 雷"
	katakana "ポケモン"
	hiragana "で こうげきだ"
	done

Text12ae:
	textfw0 "雷ポケモンカード"
	hiragana "の"
	line ""
	textfw0 "とくちょう"
	line ""
	textfw0 "水"
	katakana "ポケモンカード"
	hiragana "に つよく"
	line ""
	textfw0 "闘"
	katakana "ポケモンカード"
	hiragana "に よわい"
	line ""
	textfw0 "「"
	katakana "ワザ」"
	hiragana "を つかうには"
	line ""
	textfw0 "雷"
	katakana "エネルギーカード"
	hiragana "が ひつよう"
	done

Text12af:
	textfw0 "雷ポケモン"
	hiragana "は"
	line ""
	textfw0 "闘"
	katakana "ポケモン"
	hiragana "に 「弱点」をもっている"
	line ""
	katakana "デッキ"
	hiragana "に 闘"
	katakana "ポケモン"
	hiragana "に「抵抗力」ある"
	line ""
	textfw0 "とり"
	katakana "ポケモン"
	hiragana "をいれて おくといいぞ"
	line ""
	textfw0 "ほかにも そらをとぶ"
	katakana "ピカチュウ"
	hiragana "は"
	line ""
	textfw0 "抵抗力「闘」の 雷"
	katakana "ポケモン"
	hiragana "だ"
	line ""
	katakana "バトル場"
	hiragana "に 闘"
	katakana "ポケモン"
	hiragana "が でてきたら"
	line ""
	textfw0 "それらの "
	katakana "ポケモン"
	hiragana "で おうせんしよう"
	done

Text12b0:
	textfw0 "無色"
	hiragana "の"
	line ""
	textfw0 "とり"
	katakana "ポケモンカード"
	line ""
	textfw0 "闘ポケモンカード"
	hiragana "に 「抵抗力」があり"
	line ""
	textfw0 "雷"
	katakana "ポケモンカード"
	hiragana "に よわい"
	line ""
	textfw0 "どの色の "
	katakana "エネルギーカード"
	hiragana "でも"
	line ""
	textfw0 "「"
	katakana "ワザ」"
	hiragana "を つかうことが できる"
	line ""
	textfw0 "そらに とんでいるので"
	line ""
	textfw0 "にげやすいのも とくちょう"
	done

Text12b1:
	textfw0 "超ポケモンカード"
	hiragana "の"
	line ""
	textfw0 "とくちょう"
	line ""
	textfw0 "超"
	katakana "ポケモン"
	hiragana "は 「弱点」となる"
	katakana "カード"
	hiragana "も"
	line ""
	textfw0 "おなじ 超"
	katakana "ポケモンカード"
	line ""
	hiragana "でも 無色"
	katakana "ポケモンカード"
	hiragana "のなかには"
	line ""
	textfw0 "超"
	katakana "ポケモン"
	hiragana "に つよいのもある"
	line ""
	textfw0 "「"
	katakana "ワザ」"
	hiragana "をつかうには"
	line ""
	textfw0 "超"
	katakana "エネルギーカード"
	hiragana "が ひつよう"
	done

Text12b2:
	textfw0 "超ポケモンカード"
	hiragana "には 特殊能力を"
	line ""
	textfw0 "もっているものが おおい"
	line ""
	textfw0 "「"
	katakana "ダメージスワップ」「"
	hiragana "なぞのかべ」"
	line ""
	textfw0 "「へんなこうどう」に 「のろい」!"
	line ""
	textfw0 "この特殊能力を つかいこなすことが"
	line ""
	textfw0 "超"
	katakana "ポケモン"
	hiragana "を つかいこなすことだ"
	done
