; constants for use in the attack structs
; these map to a sequence of duel animations
; (see src\data\attack_animations.asm)
	const_def
	const ATK_ANIM_NONE                   ; $00
	const ATK_ANIM_HIT                    ; $01
	const ATK_ANIM_BIG_HIT                ; $02
	const ATK_ANIM_EARTHQUAKE             ; $03
	const ATK_ANIM_HIT_RECOIL             ; $04
	const ATK_ANIM_HIT_EFFECT             ; $05
	const ATK_ANIM_THUNDERSHOCK           ; $06
	const ATK_ANIM_THUNDER                ; $07
	const ATK_ANIM_THUNDERBOLT            ; $08
	const ATK_ANIM_THUNDERSHOCK_COPY      ; $09
	const ATK_ANIM_THUNDER_WHOLE_SCREEN   ; $0a
	const ATK_ANIM_UNUSED_0B              ; $0b
	const ATK_ANIM_THUNDERSTORM           ; $0c
	const ATK_ANIM_CHAIN_LIGHTNING        ; $0d
	const ATK_ANIM_SMALL_FLAME            ; $0e
	const ATK_ANIM_BIG_FLAME              ; $0f
	const ATK_ANIM_FIRE_SPIN              ; $10
	const ATK_ANIM_DIVE_BOMB              ; $11
	const ATK_ANIM_WATER_JETS             ; $12
	const ATK_ANIM_WATER_GUN              ; $13
	const ATK_ANIM_WHIRLPOOL              ; $14
	const ATK_ANIM_DRAGON_RAGE            ; $15
	const ATK_ANIM_HYDRO_PUMP             ; $16
	const ATK_ANIM_AEROBLAST              ; $17
	const ATK_ANIM_BLIZZARD               ; $18
	const ATK_ANIM_PSYCHIC_HIT            ; $19
	const ATK_ANIM_NIGHTMARE              ; $1a
	const ATK_ANIM_PSYSHOCK               ; $1b
	const ATK_ANIM_DARK_MIND              ; $1c
	const ATK_ANIM_BEAM                   ; $1d
	const ATK_ANIM_HYPER_BEAM             ; $1e
	const ATK_ANIM_ICE_BEAM               ; $1f
	const ATK_ANIM_AVALANCHE              ; $20
	const ATK_ANIM_STONE_BARRAGE          ; $21
	const ATK_ANIM_PUNCH                  ; $22
	const ATK_ANIM_THUNDERPUNCH           ; $23
	const ATK_ANIM_FIRE_PUNCH             ; $24
	const ATK_ANIM_STRETCH_KICK           ; $25
	const ATK_ANIM_SLASH                  ; $26
	const ATK_ANIM_WHIP                   ; $27
	const ATK_ANIM_TEAR                   ; $28
	const ATK_ANIM_MULTIPLE_SLASH         ; $29
	const ATK_ANIM_UNUSED_2A              ; $2a
	const ATK_ANIM_RAMPAGE                ; $2b
	const ATK_ANIM_DRILL                  ; $2c
	const ATK_ANIM_POT_SMASH              ; $2d
	const ATK_ANIM_BONEMERANG             ; $2e
	const ATK_ANIM_SEISMIC_TOSS           ; $2f
	const ATK_ANIM_NEEDLES                ; $30
	const ATK_ANIM_POISON_NEEDLE          ; $31
	const ATK_ANIM_SMOG                   ; $32
	const ATK_ANIM_POISON_GAS             ; $33
	const ATK_ANIM_UNUSED_34              ; $34
	const ATK_ANIM_FOUL_GAS               ; $35
	const ATK_ANIM_FOUL_ODOR              ; $36
	const ATK_ANIM_POWDER_EFFECT_CHANCE   ; $37
	const ATK_ANIM_POWDER_HIT_POISON      ; $38
	const ATK_ANIM_POISON_POWDER          ; $39
	const ATK_ANIM_UNUSED_3A              ; $3a
	const ATK_ANIM_STUN_SPORE             ; $3b
	const ATK_ANIM_POISONPOWDER           ; $3c
	const ATK_ANIM_GOO                    ; $3d
	const ATK_ANIM_UNUSED_3E              ; $3e
	const ATK_ANIM_SPIT_POISON            ; $3f
	const ATK_ANIM_STICKY_HANDS           ; $40
	const ATK_ANIM_BUBBLES                ; $41
	const ATK_ANIM_BUBBLES_COPY           ; $42
	const ATK_ANIM_STRING_SHOT            ; $43
	const ATK_ANIM_UNUSED_44              ; $44
	const ATK_ANIM_BOYFRIENDS             ; $45
	const ATK_ANIM_LURE                   ; $46
	const ATK_ANIM_TOXIC                  ; $47
	const ATK_ANIM_CONFUSE_RAY            ; $48
	const ATK_ANIM_UNUSED_49              ; $49
	const ATK_ANIM_SING                   ; $4a
	const ATK_ANIM_LULLABY                ; $4b
	const ATK_ANIM_SUPERSONIC             ; $4c
	const ATK_ANIM_SUPERSONIC_COPY        ; $4d
	const ATK_ANIM_PETAL_DANCE            ; $4e
	const ATK_ANIM_PROTECT                ; $4f
	const ATK_ANIM_BARRIER                ; $50
	const ATK_ANIM_QUICK_ATTACK           ; $51
	const ATK_ANIM_AGILITY_PROTECT        ; $52
	const ATK_ANIM_WHIRLWIND              ; $53
	const ATK_ANIM_CRY                    ; $54
	const ATK_ANIM_AMNESIA                ; $55
	const ATK_ANIM_SELFDESTRUCT           ; $56
	const ATK_ANIM_BIG_SELFDESTRUCTION    ; $57
	const ATK_ANIM_RECOVER                ; $58
	const ATK_ANIM_DRAIN                  ; $59
	const ATK_ANIM_DARK_GAS               ; $5a
	const ATK_ANIM_GLOW_EFFECT            ; $5b
	const ATK_ANIM_MIRROR_MOVE            ; $5c
	const ATK_ANIM_DEVOLUTION_BEAM        ; $5d
	const ATK_ANIM_PKMN_POWER_1           ; $5e
	const ATK_ANIM_FIREGIVER              ; $5f
	const ATK_ANIM_QUICKFREEZE            ; $60
	const ATK_ANIM_PEAL_OF_THUNDER        ; $61
	const ATK_ANIM_HEALING_WIND           ; $62
	const ATK_ANIM_WHIRLWIND_ZIGZAG       ; $63
	const ATK_ANIM_BIG_THUNDER            ; $64
	const ATK_ANIM_SOLAR_POWER            ; $65
	const ATK_ANIM_POISON_FANG            ; $66
	const ATK_ANIM_UNUSED_67              ; $67
	const ATK_ANIM_UNUSED_68              ; $68
	const ATK_ANIM_UNUSED_69              ; $69
	const ATK_ANIM_FRIENDSHIP_SONG        ; $6a
	const ATK_ANIM_SCRUNCH                ; $6b
	const ATK_ANIM_CAT_PUNCH              ; $6c
	const ATK_ANIM_MAGNETIC_STORM         ; $6d
	const ATK_ANIM_POISON_WHIP            ; $6e
	const ATK_ANIM_THUNDER_WAVE           ; $6f
	const ATK_ANIM_UNUSED_70              ; $70
	const ATK_ANIM_SPORE                  ; $71
	const ATK_ANIM_HYPNOSIS               ; $72
	const ATK_ANIM_ENERGY_CONVERSION      ; $73
	const ATK_ANIM_LEER                   ; $74
	const ATK_ANIM_CONFUSION_HIT          ; $75
	const ATK_ANIM_UNUSED_76              ; $76
	const ATK_ANIM_UNUSED_77              ; $77
	const ATK_ANIM_BENCH_HIT              ; $78
	const ATK_ANIM_HEAL                   ; $79
	const ATK_ANIM_RECOIL_HIT             ; $7a
	const ATK_ANIM_POISON                 ; $7b
	const ATK_ANIM_CONFUSION              ; $7c
	const ATK_ANIM_PARALYSIS              ; $7d
	const ATK_ANIM_SLEEP                  ; $7e
	const ATK_ANIM_IMAKUNI_CONFUSION      ; $7f
	const ATK_ANIM_SLEEPING_GAS           ; $80
	const ATK_ANIM_UNUSED_81              ; $81
	const ATK_ANIM_THUNDER_PLAY_AREA      ; $82
	const ATK_ANIM_CAT_PUNCH_PLAY_AREA    ; $83
	const ATK_ANIM_FIREGIVER_PLAYER       ; $84
	const ATK_ANIM_FIREGIVER_OPP          ; $85
	const ATK_ANIM_HEALING_WIND_PLAY_AREA ; $86
	const ATK_ANIM_GALE                   ; $87
	const ATK_ANIM_EXPAND                 ; $88
	const ATK_ANIM_UNUSED_89              ; $89
	const ATK_ANIM_FULL_HEAL              ; $8a
	const ATK_ANIM_UNUSED_8B              ; $8b
	const ATK_ANIM_SPIT_POISON_SUCCESS    ; $8c
	const ATK_ANIM_GUST_OF_WIND           ; $8d
	const ATK_ANIM_HEAL_BOTH_SIDES        ; $8e
	const ATK_ANIM_UNUSED_8F              ; $8f
	const ATK_ANIM_UNUSED_90              ; $90
	const ATK_ANIM_UNUSED_91              ; $91
	const ATK_ANIM_UNUSED_92              ; $92
	const ATK_ANIM_UNUSED_93              ; $93
	const ATK_ANIM_UNUSED_94              ; $94
	const ATK_ANIM_UNUSED_95              ; $95
	const ATK_ANIM_UNUSED_96              ; $96
	const ATK_ANIM_SNEAK_ATTACK           ; $97
	const ATK_ANIM_UNUSED_98              ; $98
	const ATK_ANIM_UNUSED_99              ; $99
	const ATK_ANIM_LIGHTNING_FLASH        ; $9a
	const ATK_ANIM_UNUSED_9B              ; $9b
	const ATK_ANIM_UNUSED_9C              ; $9c
	const ATK_ANIM_UNUSED_9D              ; $9d
	const ATK_ANIM_FIREBALL               ; $9e
	const ATK_ANIM_CONTINUOUS_FIREBALL    ; $9f
	const ATK_ANIM_FLAME_PILLAR           ; $a0
	const ATK_ANIM_WATER_BOMB             ; $a1
	const ATK_ANIM_UNUSED_A2              ; $a2
	const ATK_ANIM_UNUSED_A3              ; $a3
	const ATK_ANIM_UNUSED_A4              ; $a4
	const ATK_ANIM_BENCH_MANIPULATION     ; $a5
	const ATK_ANIM_BLINK                  ; $a6
	const ATK_ANIM_UNUSED_A7              ; $a7
	const ATK_ANIM_UNUSED_A8              ; $a8
	const ATK_ANIM_PSYBEAM                ; $a9
	const ATK_ANIM_UNUSED_AA              ; $aa
	const ATK_ANIM_UNUSED_AB              ; $ab
	const ATK_ANIM_AURORA_WAVE            ; $ac
	const ATK_ANIM_UNUSED_AD              ; $ad
	const ATK_ANIM_ROCK_THROW             ; $ae
	const ATK_ANIM_BOULDER_SMASH          ; $af
	const ATK_ANIM_MEGA_PUNCH             ; $b0
	const ATK_ANIM_PSYPUNCH               ; $b1
	const ATK_ANIM_SLUDGE_PUNCH           ; $b2
	const ATK_ANIM_UNUSED_B3              ; $b3
	const ATK_ANIM_UNUSED_B4              ; $b4
	const ATK_ANIM_ICE_PUNCH              ; $b5
	const ATK_ANIM_LEG_SWEEP              ; $b6
	const ATK_ANIM_UNUSED_B7              ; $b7
	const ATK_ANIM_SPARKING_KICK          ; $b8
	const ATK_ANIM_UNUSED_B9              ; $b9
	const ATK_ANIM_POLLEN_STENCH          ; $ba
	const ATK_ANIM_UNUSED_BB              ; $bb
	const ATK_ANIM_UNUSED_BC              ; $bc
	const ATK_ANIM_UNUSED_BD              ; $bd
	const ATK_ANIM_POISON_VAPOR           ; $be
	const ATK_ANIM_POISON_GAS_COPY        ; $bf
	const ATK_ANIM_EERIE_LIGHT            ; $c0
	const ATK_ANIM_SPOOKIFY               ; $c1
	const ATK_ANIM_MASS_EXPLOSION         ; $c2
	const ATK_ANIM_GAS_EXPLOSION          ; $c3
	const ATK_ANIM_UNUSED_C4              ; $c4
	const ATK_ANIM_UNUSED_C5              ; $c5
	const ATK_ANIM_LICK                   ; $c6
	const ATK_ANIM_UNUSED_C7              ; $c7
	const ATK_ANIM_TAIL_SLAP              ; $c8
	const ATK_ANIM_TAIL_WHIP              ; $c9
	const ATK_ANIM_UNUSED_CA              ; $ca
	const ATK_ANIM_SLAP                   ; $cb
	const ATK_ANIM_UNUSED_CC              ; $cc
	const ATK_ANIM_ROCKET_TACKLE          ; $cd
	const ATK_ANIM_STARE                  ; $ce
	const ATK_ANIM_UNUSED_CF              ; $cf
	const ATK_ANIM_COIN_HURL              ; $d0
	const ATK_ANIM_UNUSED_D1              ; $d1
	const ATK_ANIM_TELEPORT               ; $d2
	const ATK_ANIM_TELEPORT_BLAST         ; $d3
	const ATK_ANIM_FOLLOW_ME              ; $d4
	const ATK_ANIM_SHINING_FINGER         ; $d5
	const ATK_ANIM_UNUSED_D6              ; $d6
	const ATK_ANIM_SUSPICIOUS_SOUNDWAVE   ; $d7
	const ATK_ANIM_3D_ATTACK              ; $d8
	const ATK_ANIM_UNUSED_D9              ; $d9
	const ATK_ANIM_ROLL_OVER              ; $da
	const ATK_ANIM_SWIFT                  ; $db
	const ATK_ANIM_UNUSED_DC              ; $dc
	const ATK_ANIM_UNUSED_DD              ; $dd
	const ATK_ANIM_COLD_BREATH            ; $de
	const ATK_ANIM_DRY_UP                 ; $df
	const ATK_ANIM_UNUSED_E0              ; $e0
	const ATK_ANIM_TRANS_DAMAGE           ; $e1
	const ATK_ANIM_FOCUS_BLAST            ; $e2
	const ATK_ANIM_UNUSED_E3              ; $e3
	const ATK_ANIM_UNUSED_E4              ; $e4
	const ATK_ANIM_FADE_TO_BLACK          ; $e5
	const ATK_ANIM_UNUSED_E8              ; $e6
	const ATK_ANIM_POISON_SEED            ; $e7
	const ATK_ANIM_TWIDDLE                ; $e8
	const ATK_ANIM_UNUSED_E9              ; $e9
	const ATK_ANIM_BIG_YAWN               ; $ea
	const ATK_ANIM_BIG_SNORE              ; $eb
	const ATK_ANIM_SAND_VEIL              ; $ec
	const ATK_ANIM_UNUSED_ED              ; $ed
	const ATK_ANIM_HELPING_HAND           ; $ee
	const ATK_ANIM_REST                   ; $ef
	const ATK_ANIM_TERROR_STRIKE          ; $f0
	const ATK_ANIM_SKULL_BASH             ; $f1
	const ATK_ANIM_RAZOR_LEAF             ; $f2
	const ATK_ANIM_GUILLOTINE             ; $f3
	const ATK_ANIM_VINE_PULL              ; $f4
	const ATK_ANIM_FURY_STRIKES           ; $f5
	const ATK_ANIM_DRILL_DIVE             ; $f6
	const ATK_ANIM_DARK_SONG              ; $f7
	const ATK_ANIM_UNUSED_F8              ; $f8
	const ATK_ANIM_PERPLEX                ; $f9
	const ATK_ANIM_NINE_TAILS             ; $fa
	const ATK_ANIM_SPINNING_SHOWER        ; $fb
	const ATK_ANIM_SURPRISE_THUNDER       ; $fc
	const ATK_ANIM_PUSH_ASIDE             ; $fd
	const ATK_ANIM_BONE_HEADBUTT          ; $fe
	const ATK_ANIM_FF                     ; $ff
