; constants for use in the attack structs
; these map to a sequence of duel animations
; (see src\data\attack_animations.asm)
	const_def
	const ATK_ANIM_NONE                   ; $00
	const ATK_ANIM_HIT                    ; $01
	const ATK_ANIM_BIG_HIT                ; $02
	const ATK_ANIM_3                      ; $03
	const ATK_ANIM_HIT_RECOIL             ; $04
	const ATK_ANIM_HIT_EFFECT             ; $05
	const ATK_ANIM_THUNDERSHOCK           ; $06
	const ATK_ANIM_THUNDER                ; $07
	const ATK_ANIM_THUNDERBOLT            ; $08
	const ATK_ANIM_9                      ; $09
	const ATK_ANIM_THUNDER_WHOLE_SCREEN   ; $0a
	const ATK_ANIM_11                     ; $0b
	const ATK_ANIM_THUNDERSTORM           ; $0c
	const ATK_ANIM_CHAIN_LIGHTNING        ; $0d
	const ATK_ANIM_SMALL_FLAME            ; $0e
	const ATK_ANIM_BIG_FLAME              ; $0f
	const ATK_ANIM_FIRE_SPIN              ; $10
	const ATK_ANIM_DIVE_BOMB              ; $11
	const ATK_ANIM_WATER_JETS             ; $12
	const ATK_ANIM_WATER_GUN              ; $13
	const ATK_ANIM_WHIRLPOOL              ; $14
	const ATK_ANIM_DRAGON_RAGE            ; $15
	const ATK_ANIM_HYDRO_PUMP             ; $16
	const ATK_ANIM_23                     ; $17
	const ATK_ANIM_BLIZZARD               ; $18
	const ATK_ANIM_PSYCHIC_HIT            ; $19
	const ATK_ANIM_NIGHTMARE              ; $1a
	const ATK_ANIM_27                     ; $1b
	const ATK_ANIM_DARK_MIND              ; $1c
	const ATK_ANIM_BEAM                   ; $1d
	const ATK_ANIM_HYPER_BEAM             ; $1e
	const ATK_ANIM_31                     ; $1f
	const ATK_ANIM_ROCK_THROW             ; $20
	const ATK_ANIM_STONE_BARRAGE          ; $21
	const ATK_ANIM_PUNCH                  ; $22
	const ATK_ANIM_THUNDERPUNCH           ; $23
	const ATK_ANIM_FIRE_PUNCH             ; $24
	const ATK_ANIM_STRETCH_KICK           ; $25
	const ATK_ANIM_SLASH                  ; $26
	const ATK_ANIM_WHIP                   ; $27
	const ATK_ANIM_TEAR                   ; $28
	const ATK_ANIM_MULTIPLE_SLASH         ; $29
	const ATK_ANIM_42                     ; $2a
	const ATK_ANIM_RAMPAGE                ; $2b
	const ATK_ANIM_DRILL                  ; $2c
	const ATK_ANIM_POT_SMASH              ; $2d
	const ATK_ANIM_BONEMERANG             ; $2e
	const ATK_ANIM_SEISMIC_TOSS           ; $2f
	const ATK_ANIM_NEEDLES                ; $30
	const ATK_ANIM_49                     ; $31
	const ATK_ANIM_SMOG                   ; $32
	const ATK_ANIM_51                     ; $33
	const ATK_ANIM_52                     ; $34
	const ATK_ANIM_FOUL_GAS               ; $35
	const ATK_ANIM_FOUL_ODOR              ; $36
	const ATK_ANIM_POWDER_EFFECT_CHANCE   ; $37
	const ATK_ANIM_POWDER_HIT_POISON      ; $38
	const ATK_ANIM_POISON_POWDER          ; $39
	const ATK_ANIM_58                     ; $3a
	const ATK_ANIM_59                     ; $3b
	const ATK_ANIM_60                     ; $3c
	const ATK_ANIM_GOO                    ; $3d
	const ATK_ANIM_62                     ; $3e
	const ATK_ANIM_SPIT_POISON            ; $3f
	const ATK_ANIM_64                     ; $40
	const ATK_ANIM_BUBBLES                ; $41
	const ATK_ANIM_66                     ; $42
	const ATK_ANIM_STRING_SHOT            ; $43
	const ATK_ANIM_68                     ; $44
	const ATK_ANIM_BOYFRIENDS             ; $45
	const ATK_ANIM_LURE                   ; $46
	const ATK_ANIM_TOXIC                  ; $47
	const ATK_ANIM_CONFUSE_RAY            ; $48
	const ATK_ANIM_73                     ; $49
	const ATK_ANIM_SING                   ; $4a
	const ATK_ANIM_LULLABY                ; $4b
	const ATK_ANIM_SUPERSONIC             ; $4c
	const ATK_ANIM_77                     ; $4d
	const ATK_ANIM_PETAL_DANCE            ; $4e
	const ATK_ANIM_PROTECT                ; $4f
	const ATK_ANIM_BARRIER                ; $50
	const ATK_ANIM_QUICK_ATTACK           ; $51
	const ATK_ANIM_AGILITY_PROTECT        ; $52
	const ATK_ANIM_WHIRLWIND              ; $53
	const ATK_ANIM_CRY                    ; $54
	const ATK_ANIM_AMNESIA                ; $55
	const ATK_ANIM_SELFDESTRUCT           ; $56
	const ATK_ANIM_BIG_SELFDESTRUCTION    ; $57
	const ATK_ANIM_RECOVER                ; $58
	const ATK_ANIM_DRAIN                  ; $59
	const ATK_ANIM_DARK_GAS               ; $5a
	const ATK_ANIM_GLOW_EFFECT            ; $5b
	const ATK_ANIM_MIRROR_MOVE            ; $5c
	const ATK_ANIM_DEVOLUTION_BEAM        ; $5d
	const ATK_ANIM_PKMN_POWER_1           ; $5e
	const ATK_ANIM_FIREGIVER              ; $5f
	const ATK_ANIM_QUICKFREEZE            ; $60
	const ATK_ANIM_PEAL_OF_THUNDER        ; $61
	const ATK_ANIM_HEALING_WIND           ; $62
	const ATK_ANIM_WHIRLWIND_ZIGZAG       ; $63
	const ATK_ANIM_BIG_THUNDER            ; $64
	const ATK_ANIM_SOLAR_POWER            ; $65
	const ATK_ANIM_POISON_FANG            ; $66
	const ATK_ANIM_103                    ; $67
	const ATK_ANIM_104                    ; $68
	const ATK_ANIM_105                    ; $69
	const ATK_ANIM_FRIENDSHIP_SONG        ; $6a
	const ATK_ANIM_SCRUNCH                ; $6b
	const ATK_ANIM_CAT_PUNCH              ; $6c
	const ATK_ANIM_MAGNETIC_STORM         ; $6d
	const ATK_ANIM_POISON_WHIP            ; $6e
	const ATK_ANIM_THUNDER_WAVE           ; $6f
	const ATK_ANIM_112                    ; $70
	const ATK_ANIM_SPORE                  ; $71
	const ATK_ANIM_HYPNOSIS               ; $72
	const ATK_ANIM_ENERGY_CONVERSION      ; $73
	const ATK_ANIM_LEER                   ; $74
	const ATK_ANIM_CONFUSION_HIT          ; $75
	const ATK_ANIM_118                    ; $76
	const ATK_ANIM_119                    ; $77
	const ATK_ANIM_BENCH_HIT              ; $78
	const ATK_ANIM_HEAL                   ; $79
	const ATK_ANIM_RECOIL_HIT             ; $7a
	const ATK_ANIM_POISON                 ; $7b
	const ATK_ANIM_CONFUSION              ; $7c
	const ATK_ANIM_PARALYSIS              ; $7d
	const ATK_ANIM_SLEEP                  ; $7e
	const ATK_ANIM_IMAKUNI_CONFUSION      ; $7f
	const ATK_ANIM_SLEEPING_GAS           ; $80
	const ATK_ANIM_129                    ; $81
	const ATK_ANIM_THUNDER_PLAY_AREA      ; $82
	const ATK_ANIM_CAT_PUNCH_PLAY_AREA    ; $83
	const ATK_ANIM_FIREGIVER_PLAYER       ; $84
	const ATK_ANIM_FIREGIVER_OPP          ; $85
	const ATK_ANIM_HEALING_WIND_PLAY_AREA ; $86
	const ATK_ANIM_GALE                   ; $87
	const ATK_ANIM_EXPAND                 ; $88
	const ATK_ANIM_137                    ; $89
	const ATK_ANIM_FULL_HEAL              ; $8a
	const ATK_ANIM_139                    ; $8b
	const ATK_ANIM_SPIT_POISON_SUCCESS    ; $8c
	const ATK_ANIM_GUST_OF_WIND           ; $8d
	const ATK_ANIM_HEAL_BOTH_SIDES        ; $8e
	const ATK_ANIM_143                    ; $8f
	const ATK_ANIM_144                    ; $90
	const ATK_ANIM_145                    ; $91
	const ATK_ANIM_146                    ; $92
	const ATK_ANIM_147                    ; $93
	const ATK_ANIM_148                    ; $94
	const ATK_ANIM_149                    ; $95
	const ATK_ANIM_150                    ; $96
	const ATK_ANIM_151                    ; $97
	const ATK_ANIM_152                    ; $98
	const ATK_ANIM_153                    ; $99
	const ATK_ANIM_154                    ; $9a
	const ATK_ANIM_155                    ; $9b
	const ATK_ANIM_156                    ; $9c
	const ATK_ANIM_157                    ; $9d
	const ATK_ANIM_158                    ; $9e
	const ATK_ANIM_159                    ; $9f
	const ATK_ANIM_160                    ; $a0
	const ATK_ANIM_161                    ; $a1
	const ATK_ANIM_162                    ; $a2
	const ATK_ANIM_163                    ; $a3
	const ATK_ANIM_164                    ; $a4
	const ATK_ANIM_165                    ; $a5
	const ATK_ANIM_166                    ; $a6
	const ATK_ANIM_167                    ; $a7
	const ATK_ANIM_168                    ; $a8
	const ATK_ANIM_169                    ; $a9
	const ATK_ANIM_170                    ; $aa
	const ATK_ANIM_171                    ; $ab
	const ATK_ANIM_172                    ; $ac
	const ATK_ANIM_173                    ; $ad
	const ATK_ANIM_174                    ; $ae
	const ATK_ANIM_175                    ; $af
	const ATK_ANIM_176                    ; $b0
	const ATK_ANIM_177                    ; $b1
	const ATK_ANIM_178                    ; $b2
	const ATK_ANIM_179                    ; $b3
	const ATK_ANIM_180                    ; $b4
	const ATK_ANIM_181                    ; $b5
	const ATK_ANIM_182                    ; $b6
	const ATK_ANIM_183                    ; $b7
	const ATK_ANIM_184                    ; $b8
	const ATK_ANIM_185                    ; $b9
	const ATK_ANIM_186                    ; $ba
	const ATK_ANIM_187                    ; $bb
	const ATK_ANIM_188                    ; $bc
	const ATK_ANIM_189                    ; $bd
	const ATK_ANIM_190                    ; $be
	const ATK_ANIM_191                    ; $bf
	const ATK_ANIM_192                    ; $c0
	const ATK_ANIM_193                    ; $c1
	const ATK_ANIM_194                    ; $c2
	const ATK_ANIM_195                    ; $c3
	const ATK_ANIM_196                    ; $c4
	const ATK_ANIM_197                    ; $c5
	const ATK_ANIM_198                    ; $c6
	const ATK_ANIM_199                    ; $c7
	const ATK_ANIM_200                    ; $c8
	const ATK_ANIM_201                    ; $c9
	const ATK_ANIM_202                    ; $ca
	const ATK_ANIM_203                    ; $cb
	const ATK_ANIM_204                    ; $cc
	const ATK_ANIM_205                    ; $cd
	const ATK_ANIM_206                    ; $ce
	const ATK_ANIM_207                    ; $cf
	const ATK_ANIM_208                    ; $d0
	const ATK_ANIM_209                    ; $d1
	const ATK_ANIM_210                    ; $d2
	const ATK_ANIM_211                    ; $d3
	const ATK_ANIM_212                    ; $d4
	const ATK_ANIM_213                    ; $d5
	const ATK_ANIM_214                    ; $d6
	const ATK_ANIM_215                    ; $d7
	const ATK_ANIM_216                    ; $d8
	const ATK_ANIM_217                    ; $d9
	const ATK_ANIM_218                    ; $da
	const ATK_ANIM_219                    ; $db
	const ATK_ANIM_220                    ; $dc
	const ATK_ANIM_221                    ; $dd
	const ATK_ANIM_222                    ; $de
	const ATK_ANIM_223                    ; $df
	const ATK_ANIM_224                    ; $e0
	const ATK_ANIM_225                    ; $e1
	const ATK_ANIM_226                    ; $e2
	const ATK_ANIM_227                    ; $e3
	const ATK_ANIM_228                    ; $e4
	const ATK_ANIM_229                    ; $e5
	const ATK_ANIM_230                    ; $e6
	const ATK_ANIM_231                    ; $e7
	const ATK_ANIM_232                    ; $e8
	const ATK_ANIM_233                    ; $e9
	const ATK_ANIM_234                    ; $ea
	const ATK_ANIM_235                    ; $eb
	const ATK_ANIM_236                    ; $ec
	const ATK_ANIM_237                    ; $ed
	const ATK_ANIM_238                    ; $ee
	const ATK_ANIM_239                    ; $ef
	const ATK_ANIM_240                    ; $f0
	const ATK_ANIM_241                    ; $f1
	const ATK_ANIM_242                    ; $f2
	const ATK_ANIM_243                    ; $f3
	const ATK_ANIM_244                    ; $f4
	const ATK_ANIM_245                    ; $f5
	const ATK_ANIM_246                    ; $f6
	const ATK_ANIM_247                    ; $f7
	const ATK_ANIM_248                    ; $f8
	const ATK_ANIM_249                    ; $f9
	const ATK_ANIM_250                    ; $fa
	const ATK_ANIM_251                    ; $fb
	const ATK_ANIM_252                    ; $fc
	const ATK_ANIM_253                    ; $fd
	const ATK_ANIM_254                    ; $fe
