	const_def 1
	const GRASS_ENERGY             ; $001
	const FIRE_ENERGY              ; $002
	const WATER_ENERGY             ; $003
	const LIGHTNING_ENERGY         ; $004
	const FIGHTING_ENERGY          ; $005
	const PSYCHIC_ENERGY           ; $006
	const DOUBLE_COLORLESS_ENERGY  ; $007
	const POTION_ENERGY            ; $008
	const FULLHEAL_ENERGY          ; $009
	const RAINBOW_ENERGY           ; $00a
	const RECYCLE_ENERGY           ; $00b
	const BULBASAUR_LV12           ; $00c
	const BULBASAUR_LV13           ; $00d
	const BULBASAUR_LV15           ; $00e
	const IVYSAUR_LV20             ; $00f
	const IVYSAUR_LV26             ; $010
	const DARK_IVYSAUR             ; $011
	const VENUSAUR_LV64            ; $012
	const VENUSAUR_LV67            ; $013
	const VENUSAUR_ALT_LV67        ; $014
	const DARK_VENUSAUR            ; $015
	const CATERPIE                 ; $016
	const METAPOD_LV20             ; $017
	const METAPOD_LV21             ; $018
	const BUTTERFREE               ; $019
	const WEEDLE_LV12              ; $01a
	const WEEDLE_LV15              ; $01b
	const KAKUNA_LV20              ; $01c
	const KAKUNA_LV23              ; $01d
	const BEEDRILL                 ; $01e
	const EKANS_LV10               ; $01f
	const EKANS_LV15               ; $020
	const ARBOK_LV27               ; $021
	const ARBOK_LV30               ; $022
	const DARK_ARBOK               ; $023
	const NIDORANF_LV12            ; $024
	const NIDORANF_LV13            ; $025
	const NIDORINA_LV22            ; $026
	const NIDORINA_LV24            ; $027
	const NIDOQUEEN                ; $028
	const NIDORANM_LV20            ; $029
	const NIDORANM_LV22            ; $02a
	const NIDORINO_LV23            ; $02b
	const NIDORINO_LV25            ; $02c
	const NIDOKING                 ; $02d
	const ZUBAT_LV9                ; $02e
	const ZUBAT_LV10               ; $02f
	const ZUBAT_LV12               ; $030
	const GOLBAT_LV25              ; $031
	const GOLBAT_LV29              ; $032
	const DARK_GOLBAT              ; $033
	const ODDISH_LV8               ; $034
	const ODDISH_LV21              ; $035
	const GLOOM                    ; $036
	const DARK_GLOOM               ; $037
	const VILEPLUME                ; $038
	const DARK_VILEPLUME           ; $039
	const PARAS_LV8                ; $03a
	const PARAS_LV15               ; $03b
	const PARASECT_LV28            ; $03c
	const PARASECT_LV29            ; $03d
	const VENONAT_LV12             ; $03e
	const VENONAT_LV15             ; $03f
	const VENOMOTH_LV22            ; $040
	const VENOMOTH_LV28            ; $041
	const BELLSPROUT_LV10          ; $042
	const BELLSPROUT_LV11          ; $043
	const WEEPINBELL_LV23          ; $044
	const WEEPINBELL_LV28          ; $045
	const VICTREEBEL               ; $046
	const GRIMER_LV10              ; $047
	const GRIMER_LV17              ; $048
	const MUK                      ; $049
	const DARK_MUK                 ; $04a
	const EXEGGCUTE                ; $04b
	const EXEGGUTOR                ; $04c
	const KOFFING_LV12             ; $04d
	const KOFFING_LV13             ; $04e
	const KOFFING_LV14             ; $04f
	const WEEZING_LV26             ; $050
	const WEEZING_LV27             ; $051
	const DARK_WEEZING             ; $052
	const TANGELA_LV8              ; $053
	const TANGELA_LV12             ; $054
	const SCYTHER_LV23             ; $055
	const SCYTHER_LV25             ; $056
	const PINSIR_LV15              ; $057
	const PINSIR_LV24              ; $058
	const CHARMANDER_LV9           ; $059
	const CHARMANDER_LV10          ; $05a
	const CHARMANDER_LV12          ; $05b
	const CHARMELEON               ; $05c
	const DARK_CHARMELEON          ; $05d
	const CHARIZARD_LV76           ; $05e
	const CHARIZARD_ALT_LV76       ; $05f
	const DARK_CHARIZARD           ; $060
	const VULPIX_LV11              ; $061
	const VULPIX_LV13              ; $062
	const NINETALES_LV32           ; $063
	const NINETALES_LV35           ; $064
	const DARK_NINETALES           ; $065
	const GROWLITHE_LV12           ; $066
	const GROWLITHE_LV16           ; $067
	const GROWLITHE_LV18           ; $068
	const ARCANINE_LV34            ; $069
	const ARCANINE_LV35            ; $06a
	const ARCANINE_LV45            ; $06b
	const PONYTA_LV8               ; $06c
	const PONYTA_LV10              ; $06d
	const PONYTA_LV15              ; $06e
	const RAPIDASH_LV30            ; $06f
	const RAPIDASH_LV33            ; $070
	const DARK_RAPIDASH            ; $071
	const MAGMAR_LV18              ; $072
	const MAGMAR_LV24              ; $073
	const MAGMAR_LV27              ; $074
	const MAGMAR_LV31              ; $075
	const FLAREON_LV22             ; $076
	const FLAREON_LV28             ; $077
	const DARK_FLAREON             ; $078
	const MOLTRES_LV35             ; $079
	const MOLTRES_LV37             ; $07a
	const MOLTRES_LV40             ; $07b
	const SQUIRTLE_LV8             ; $07c
	const SQUIRTLE_LV14            ; $07d
	const SQUIRTLE_LV15            ; $07e
	const SQUIRTLE_LV16            ; $07f
	const WARTORTLE_LV22           ; $080
	const WARTORTLE_LV24           ; $081
	const DARK_WARTORTLE           ; $082
	const BLASTOISE_LV52           ; $083
	const BLASTOISE_ALT_LV52       ; $084
	const DARK_BLASTOISE           ; $085
	const PSYDUCK_LV15             ; $086
	const PSYDUCK_LV16             ; $087
	const GOLDUCK_LV27             ; $088
	const GOLDUCK_LV28             ; $089
	const DARK_GOLDUCK             ; $08a
	const POLIWAG_LV13             ; $08b
	const POLIWAG_LV15             ; $08c
	const POLIWHIRL_LV28           ; $08d
	const POLIWHIRL_LV30           ; $08e
	const POLIWRATH_LV40           ; $08f
	const POLIWRATH_LV48           ; $090
	const TENTACOOL                ; $091
	const TENTACRUEL               ; $092
	const SEEL_LV10                ; $093
	const SEEL_LV12                ; $094
	const DEWGONG_LV24             ; $095
	const DEWGONG_LV42             ; $096
	const SHELLDER_LV8             ; $097
	const SHELLDER_LV16            ; $098
	const CLOYSTER                 ; $099
	const KRABBY_LV17              ; $09a
	const KRABBY_LV20              ; $09b
	const KINGLER_LV27             ; $09c
	const KINGLER_LV33             ; $09d
	const HORSEA_LV19              ; $09e
	const HORSEA_LV20              ; $09f
	const SEADRA_LV23              ; $0a0
	const SEADRA_LV26              ; $0a1
	const GOLDEEN                  ; $0a2
	const SEAKING                  ; $0a3
	const STARYU_LV15              ; $0a4
	const STARYU_LV17              ; $0a5
	const STARMIE                  ; $0a6
	const DARK_STARMIE             ; $0a7
	const MAGIKARP_LV6             ; $0a8
	const MAGIKARP_LV8             ; $0a9
	const MAGIKARP_LV10            ; $0aa
	const GYARADOS                 ; $0ab
	const DARK_GYARADOS            ; $0ac
	const LAPRAS_LV24              ; $0ad
	const LAPRAS_LV31              ; $0ae
	const VAPOREON_LV29            ; $0af
	const VAPOREON_LV42            ; $0b0
	const DARK_VAPOREON            ; $0b1
	const OMANYTE_LV19             ; $0b2
	const OMANYTE_LV20             ; $0b3
	const OMANYTE_LV22             ; $0b4
	const OMASTAR_LV32             ; $0b5
	const OMASTAR_LV36             ; $0b6
	const ARTICUNO_LV34            ; $0b7
	const ARTICUNO_LV35            ; $0b8
	const ARTICUNO_LV37            ; $0b9
	const MARILL                   ; $0ba
	const PIKACHU_LV5              ; $0bb
	const PIKACHU_LV12             ; $0bc
	const PIKACHU_LV13             ; $0bd
	const PIKACHU_LV14             ; $0be
	const PIKACHU_LV16             ; $0bf
	const PIKACHU_ALT_LV16         ; $0c0
	const FLYING_PIKACHU_LV12      ; $0c1
	const FLYING_PIKACHU_ALT_LV12  ; $0c2
	const SURFING_PIKACHU_LV13     ; $0c3
	const SURFING_PIKACHU_ALT_LV13 ; $0c4
	const RAICHU_LV32              ; $0c5
	const RAICHU_LV33              ; $0c6
	const RAICHU_LV40              ; $0c7
	const RAICHU_LV45              ; $0c8
	const DARK_RAICHU              ; $0c9
	const MAGNEMITE_LV12           ; $0ca
	const MAGNEMITE_LV13           ; $0cb
	const MAGNEMITE_LV14           ; $0cc
	const MAGNEMITE_LV15           ; $0cd
	const MAGNETON_LV28            ; $0ce
	const MAGNETON_LV30            ; $0cf
	const MAGNETON_LV35            ; $0d0
	const DARK_MAGNETON            ; $0d1
	const VOLTORB_LV8              ; $0d2
	const VOLTORB_LV10             ; $0d3
	const VOLTORB_LV13             ; $0d4
	const ELECTRODE_LV35           ; $0d5
	const ELECTRODE_LV42           ; $0d6
	const DARK_ELECTRODE           ; $0d7
	const ELECTABUZZ_LV20          ; $0d8
	const ELECTABUZZ_LV30          ; $0d9
	const ELECTABUZZ_LV35          ; $0da
	const JOLTEON_LV24             ; $0db
	const JOLTEON_LV29             ; $0dc
	const DARK_JOLTEON             ; $0dd
	const ZAPDOS_LV28              ; $0de
	const ZAPDOS_LV40              ; $0df
	const ZAPDOS_LV64              ; $0e0
	const ZAPDOS_LV68              ; $0e1
	const SANDSHREW_LV12           ; $0e2
	const SANDSHREW_LV15           ; $0e3
	const SANDSLASH_LV33           ; $0e4
	const SANDSLASH_LV35           ; $0e5
	const DIGLETT_LV8              ; $0e6
	const DIGLETT_LV15             ; $0e7
	const DIGLETT_LV16             ; $0e8
	const DUGTRIO_LV36             ; $0e9
	const DUGTRIO_LV40             ; $0ea
	const DARK_DUGTRIO             ; $0eb
	const MANKEY_LV7               ; $0ec
	const MANKEY_ALT_LV7           ; $0ed
	const MANKEY_LV14              ; $0ee
	const PRIMEAPE                 ; $0ef
	const DARK_PRIMEAPE            ; $0f0
	const MACHOP_LV18              ; $0f1
	const MACHOP_LV20              ; $0f2
	const MACHOP_LV24              ; $0f3
	const MACHOKE_LV24             ; $0f4
	const MACHOKE_LV28             ; $0f5
	const MACHOKE_LV40             ; $0f6
	const DARK_MACHOKE             ; $0f7
	const MACHAMP_LV54             ; $0f8
	const MACHAMP_LV67             ; $0f9
	const DARK_MACHAMP             ; $0fa
	const GEODUDE_LV15             ; $0fb
	const GEODUDE_LV16             ; $0fc
	const GRAVELER_LV27            ; $0fd
	const GRAVELER_LV28            ; $0fe
	const GRAVELER_LV29            ; $0ff
	const GOLEM_LV36               ; $100
	const GOLEM_LV37               ; $101
	const ONIX_LV12                ; $102
	const ONIX_LV25                ; $103
	const CUBONE_LV13              ; $104
	const CUBONE_LV14              ; $105
	const MAROWAK_LV26             ; $106
	const MAROWAK_LV32             ; $107
	const DARK_MAROWAK             ; $108
	const HITMONLEE_LV23           ; $109
	const HITMONLEE_LV30           ; $10a
	const HITMONCHAN_LV23          ; $10b
	const HITMONCHAN_LV33          ; $10c
	const RHYHORN                  ; $10d
	const RHYDON_LV37              ; $10e
	const RHYDON_LV48              ; $10f
	const KABUTO_LV9               ; $110
	const KABUTO_LV22              ; $111
	const KABUTOPS                 ; $112
	const AERODACTYL_LV28          ; $113
	const AERODACTYL_LV30          ; $114
	const ABRA_LV8                 ; $115
	const ABRA_LV10                ; $116
	const ABRA_LV14                ; $117
	const KADABRA_LV38             ; $118
	const KADABRA_LV39             ; $119
	const DARK_KADABRA             ; $11a
	const ALAKAZAM_LV42            ; $11b
	const ALAKAZAM_LV45            ; $11c
	const DARK_ALAKAZAM            ; $11d
	const SLOWPOKE_LV9             ; $11e
	const SLOWPOKE_LV16            ; $11f
	const SLOWPOKE_LV18            ; $120
	const SLOWBRO_LV26             ; $121
	const SLOWBRO_LV35             ; $122
	const DARK_SLOWBRO             ; $123
	const GASTLY_LV8               ; $124
	const GASTLY_LV13              ; $125
	const GASTLY_LV17              ; $126
	const HAUNTER_LV17             ; $127
	const HAUNTER_LV22             ; $128
	const HAUNTER_LV25             ; $129
	const HAUNTER_LV26             ; $12a
	const DARK_HAUNTER             ; $12b
	const GENGAR_LV38              ; $12c
	const GENGAR_LV40              ; $12d
	const DARK_GENGAR              ; $12e
	const DROWZEE_LV10             ; $12f
	const DROWZEE_LV12             ; $130
	const HYPNO_LV30               ; $131
	const HYPNO_LV36               ; $132
	const DARK_HYPNO               ; $133
	const MR_MIME_LV20             ; $134
	const MR_MIME_LV28             ; $135
	const JYNX_LV18                ; $136
	const JYNX_LV23                ; $137
	const JYNX_LV27                ; $138
	const MEWTWO_LV30              ; $139
	const MEWTWO_LV53              ; $13a
	const MEWTWO_LV54              ; $13b
	const MEWTWO_LV60              ; $13c
	const MEWTWO_ALT_LV60          ; $13d
	const MEWTWO_LV67              ; $13e
	const GRS_MEWTWO               ; $13f
	const MEW_LV8                  ; $140
	const MEW_LV15                 ; $141
	const MEW_LV23                 ; $142
	const PIDGEY_LV8               ; $143
	const PIDGEY_LV10              ; $144
	const PIDGEOTTO_LV36           ; $145
	const PIDGEOTTO_LV38           ; $146
	const PIDGEOT_LV38             ; $147
	const PIDGEOT_LV40             ; $148
	const RATTATA_LV9              ; $149
	const RATTATA_LV12             ; $14a
	const RATTATA_LV15             ; $14b
	const RATICATE                 ; $14c
	const DARK_RATICATE            ; $14d
	const SPEAROW_LV9              ; $14e
	const SPEAROW_LV12             ; $14f
	const SPEAROW_LV13             ; $150
	const FEAROW_LV24              ; $151
	const FEAROW_LV27              ; $152
	const DARK_FEAROW              ; $153
	const CLEFAIRY_LV14            ; $154
	const CLEFAIRY_LV15            ; $155
	const CLEFABLE                 ; $156
	const DARK_CLEFABLE            ; $157
	const JIGGLYPUFF_LV12          ; $158
	const JIGGLYPUFF_LV13          ; $159
	const JIGGLYPUFF_LV14          ; $15a
	const WIGGLYTUFF_LV36          ; $15b
	const WIGGLYTUFF_LV40          ; $15c
	const MEOWTH_LV10              ; $15d
	const MEOWTH_LV13              ; $15e
	const MEOWTH_LV14              ; $15f
	const MEOWTH_LV15              ; $160
	const MEOWTH_LV17              ; $161
	const PERSIAN                  ; $162
	const DARK_PERSIAN_LV28        ; $163
	const DARK_PERSIAN_ALT_LV28    ; $164
	const FARFETCHD_LV20           ; $165
	const FARFETCHD_ALT_LV20       ; $166
	const DODUO_LV8                ; $167
	const DODUO_LV10               ; $168
	const DODRIO_LV25              ; $169
	const DODRIO_LV28              ; $16a
	const LICKITUNG_LV20           ; $16b
	const LICKITUNG_LV26           ; $16c
	const CHANSEY_LV40             ; $16d
	const CHANSEY_LV55             ; $16e
	const KANGASKHAN_LV36          ; $16f
	const KANGASKHAN_LV38          ; $170
	const KANGASKHAN_LV40          ; $171
	const TAUROS_LV32              ; $172
	const TAUROS_LV35              ; $173
	const DITTO                    ; $174
	const EEVEE_LV5                ; $175
	const EEVEE_LV9                ; $176
	const EEVEE_LV12               ; $177
	const PORYGON_LV12             ; $178
	const PORYGON_LV18             ; $179
	const PORYGON_LV20             ; $17a
	const COOL_PORYGON             ; $17b
	const SNORLAX_LV20             ; $17c
	const SNORLAX_LV35             ; $17d
	const HUNGRY_SNORLAX           ; $17e
	const DRATINI_LV10             ; $17f
	const DRATINI_LV12             ; $180
	const DRAGONAIR                ; $181
	const DARK_DRAGONAIR           ; $182
	const DRAGONITE_LV41           ; $183
	const DRAGONITE_LV43           ; $184
	const DRAGONITE_LV45           ; $185
	const DARK_DRAGONITE           ; $186
	const TOGEPI                   ; $187
	const LUGIA                    ; $188
	const SUPER_POTION             ; $189
	const IMAKUNI_CARD             ; $18a
	const ENERGY_REMOVAL           ; $18b
	const ENERGY_RETRIEVAL         ; $18c
	const ENERGY_SEARCH            ; $18d
	const PROFESSOR_OAK            ; $18e
	const FOSSIL_EXCAVATION        ; $18f
	const POTION                   ; $190
	const GAMBLER                  ; $191
	const REVIVE                   ; $192
	const MAX_REVIVE               ; $193
	const SUPER_SCOOP_UP           ; $194
	const DEVOLUTION_SPRAY         ; $195
	const ITEMFINDER               ; $196
	const CHALLENGE                ; $197
	const SUPER_ENERGY_RETRIEVAL   ; $198
	const SUPER_ENERGY_REMOVAL     ; $199
	const MOON_STONE               ; $19a
	const DEFENDER                 ; $19b
	const GUST_OF_WIND             ; $19c
	const MYSTERIOUS_FOSSIL        ; $19d
	const FULL_HEAL                ; $19e
	const IMPOSTER_OAKS_REVENGE    ; $19f
	const IMPOSTER_PROFESSOR_OAK   ; $1a0
	const SLEEP                    ; $1a1
	const COMPUTER_ERROR           ; $1a2
	const COMPUTER_SEARCH          ; $1a3
	const DIGGER                   ; $1a4
	const CLEFAIRY_DOLL            ; $1a5
	const MR_FUJI                  ; $1a6
	const PLUSPOWER                ; $1a7
	const SWITCH                   ; $1a8
	const SCOOP_UP                 ; $1a9
	const POKEMON_TRADER           ; $1aa
	const POKEMON_RECALL           ; $1ab
	const POKEDEX                  ; $1ac
	const POKEMON_CENTER           ; $1ad
	const POKEMON_BREEDER          ; $1ae
	const POKEMON_FLUTE            ; $1af
	const THE_BOSSS_WAY            ; $1b0
	const GOOP_GAS_ATTACK          ; $1b1
	const BILL                     ; $1b2
	const BILLS_TELEPORTER         ; $1b3
	const BILLS_COMPUTER           ; $1b4
	const MASTER_BALL              ; $1b5
	const LASS                     ; $1b6
	const MAINTENENCE              ; $1b7
	const POKEBALL                 ; $1b8
	const NIGHTLY_GARBAGE_RUN      ; $1b9
	const RECYCLE                  ; $1ba
	const ROCKETS_SNEAK_ATTACK     ; $1bb
	const HERE_COMES_TEAM_ROCKET   ; $1bc
	const THE_ROCKETS_TRAP         ; $1bd
DEF NUM_CARDS EQU const_value - 1
