; challenge cup constants
	const_def
	const TCG_CHALLENGE_CUP ; 0
	const GR_CHALLENGE_CUP  ; 1

; wChallengeCupIndex constants
; actual titles:
;   TCG: "Challenge Cup" (1, 2, 3)
;    GR: "Team GR Cup" (1, 2), "King Cup" (3)
	const_def
	const CHALLENGE_CUP_1 ; 0
	const CHALLENGE_CUP_2 ; 1
	const CHALLENGE_CUP_3 ; 2

; VAR_*_CHALLENGE_CUP_STATE constants
; cup 1 and 2: limited time windows
; cup 3: post-game
	const_def
	const CHALLENGE_CUP_DEAD       ; 0
	const CHALLENGE_CUP_1_START    ; 1
	const CHALLENGE_CUP_1_END      ; 2
	const CHALLENGE_CUP_2_START    ; 3
	const CHALLENGE_CUP_2_END      ; 4
	const CHALLENGE_CUP_3_UNLOCKED ; 5
	const CHALLENGE_CUP_3_START    ; 6

; challenge cup rounds
DEF NUM_CHALLENGE_CUP_ROUNDS EQU 3

; VAR_*_CHALLENGE_CUP_RESULT constants
	const_def
	const CHALLENGE_CUP_RESULT_NONE ; 0
	const CHALLENGE_CUP_RESULT_WON  ; 1
	const CHALLENGE_CUP_RESULT_LOST ; 2

; challenge cup win threshold for coin prizes
DEF NUM_CHALLENGE_CUP_WIN_THRESHOLD EQU 10

; cup opponents
	const_def
	const GRANDMASTERCUP_GENE   ; 0
	const GRANDMASTERCUP_MITCH  ; 1
	const GRANDMASTERCUP_NIKKI  ; 2
	const GRANDMASTERCUP_RICK   ; 3
	const GRANDMASTERCUP_AMY    ; 4
	const GRANDMASTERCUP_KEN    ; 5
	const GRANDMASTERCUP_ISAAC  ; 6
	const GRANDMASTERCUP_MURRAY ; 7
	const GRANDMASTERCUP_RONALD ; 8
DEF NUM_GRANDMASTERCUP_OPPONENT_IDS EQU const_value

DEF NUM_GRANDMASTERCUP_DUELISTS  EQU 8
DEF NUM_GRANDMASTERCUP_OPPONENTS EQU NUM_GRANDMASTERCUP_DUELISTS - 1 ; 7

DEF NUM_TCG_CHALLENGE_CUP_OPPONENT_POOL EQU 44
DEF NUM_GR_CHALLENGE_CUP_OPPONENT_POOL  EQU 27

; cup prize cards
DEF NUM_GRANDMASTERCUP_PRIZE_POOL EQU 37

  const_def
  const GRANDMASTERCUP_PRIZE_0 ; 0
  const GRANDMASTERCUP_PRIZE_1 ; 1
  const GRANDMASTERCUP_PRIZE_2 ; 2
  const GRANDMASTERCUP_PRIZE_3 ; 3

DEF NUM_TCG_CHALLENGE_CUP_PRIZE_POOL EQU 17
DEF NUM_GR_CHALLENGE_CUP_PRIZE_POOL  EQU 17
