; wChallengeCupIndex constants
; actual titles:
;   TCG: "Challenge Cup" (1, 2, 3)
;    GR: "Team GR Cup" (1, 2), "King Cup" (3)
	const_def
	const CHALLENGE_CUP_1 ; 0
	const CHALLENGE_CUP_2 ; 1
	const CHALLENGE_CUP_3 ; 2

; VAR_GRAND_MASTER_CUP_STATE constants
	const_def 1
	const GRAND_MASTER_CUP_INACTIVE          ; 1
	const GRAND_MASTER_CUP_ACTIVE            ; 2
	const GRAND_MASTER_CUP_ACTIVE_PRIZES_SET ; 3
	const GRAND_MASTER_CUP_PLAYING           ; 4
DEF GRAND_MASTER_CUP_PLAYED EQU const_value
	const GRAND_MASTER_CUP_RESULT_WON        ; 5
	const GRAND_MASTER_CUP_RESULT_LOST       ; 6

; VAR_*_CHALLENGE_CUP_STATE constants
; cup 1 and 2: limited time windows
; cup 3: post-game
	const_def
	const CHALLENGE_CUP_DEAD       ; 0
	const CHALLENGE_CUP_1_START    ; 1
	const CHALLENGE_CUP_1_END      ; 2
	const CHALLENGE_CUP_2_START    ; 3
	const CHALLENGE_CUP_2_END      ; 4
	const CHALLENGE_CUP_3_UNLOCKED ; 5
	const CHALLENGE_CUP_3_START    ; 6

; challenge cup rounds
DEF NUM_CHALLENGE_CUP_ROUNDS EQU 3

; VAR_*_CHALLENGE_CUP_RESULT constants
	const_def
	const CHALLENGE_CUP_RESULT_NONE ; 0
	const CHALLENGE_CUP_RESULT_WON  ; 1
	const CHALLENGE_CUP_RESULT_LOST ; 2

DEF NUM_CHALLENGE_CUP_WINS_FOR_COIN_PRIZE EQU 10

; cup opponents
	const_def
	const GRANDMASTERCUP_GENE   ; 0
	const GRANDMASTERCUP_MITCH  ; 1
	const GRANDMASTERCUP_NIKKI  ; 2
	const GRANDMASTERCUP_RICK   ; 3
	const GRANDMASTERCUP_AMY    ; 4
	const GRANDMASTERCUP_KEN    ; 5
	const GRANDMASTERCUP_ISAAC  ; 6
	const GRANDMASTERCUP_MURRAY ; 7
	const GRANDMASTERCUP_RONALD ; 8
DEF NUM_GRANDMASTERCUP_OPPONENT_POOL EQU const_value

DEF NUM_GRANDMASTERCUP_COMPETITORS     EQU 8
DEF NUM_GRANDMASTERCUP_NPC_COMPETITORS EQU NUM_GRANDMASTERCUP_COMPETITORS - 1 ; 7

	const_def
	const GRANDMASTERCUP_BRACKET_ROUND1_MATCH1 ; 0
	const GRANDMASTERCUP_BRACKET_ROUND1_MATCH2 ; 1
	const GRANDMASTERCUP_BRACKET_ROUND1_MATCH3 ; 2
	const GRANDMASTERCUP_BRACKET_ROUND1_MATCH4 ; 3
	const GRANDMASTERCUP_BRACKET_ROUND2_MATCH1 ; 4
	const GRANDMASTERCUP_BRACKET_ROUND2_MATCH2 ; 5
	const GRANDMASTERCUP_BRACKET_FINAL         ; 6
DEF NUM_GRANDMASTERCUP_BRACKET_MATCHES EQU const_value

	const_def
	const GRANDMASTERCUP_BRACKET_LEFT_WON_F  ; 0
	const GRANDMASTERCUP_BRACKET_RIGHT_WON_F ; 1

DEF GRANDMASTERCUP_BRACKET_LEFT_WON  EQU 1 << GRANDMASTERCUP_BRACKET_LEFT_WON_F  ; 1
DEF GRANDMASTERCUP_BRACKET_RIGHT_WON EQU 1 << GRANDMASTERCUP_BRACKET_RIGHT_WON_F ; 2

DEF NUM_TCG_CHALLENGE_CUP_OPPONENT_POOL EQU 44
DEF NUM_GR_CHALLENGE_CUP_OPPONENT_POOL  EQU 27

; cup prize cards
DEF NUM_GRANDMASTERCUP_PRIZE_POOL EQU 37

	const_def
	const GRANDMASTERCUP_PRIZE_0 ; 0
	const GRANDMASTERCUP_PRIZE_1 ; 1
	const GRANDMASTERCUP_PRIZE_2 ; 2
	const GRANDMASTERCUP_PRIZE_3 ; 3
DEF NUM_GRANDMASTERCUP_PRIZE_CANDIDATES EQU 4

DEF NUM_GRANDMASTERCUP_PRIZES_TO_RECEIVE EQU 2
DEF GRANDMASTERCUP_PRIZE_SELECTED        EQU $ff

DEF NUM_TCG_CHALLENGE_CUP_PRIZE_POOL EQU 17
DEF NUM_GR_CHALLENGE_CUP_PRIZE_POOL  EQU 17
