	const_def
	const COIN_CHANSEY ; $00
	const COIN_GR ; $01
	const COIN_ODDISH ; $02
	const COIN_CHARMANDER ; $03
	const COIN_STARMIE ; $04
	const COIN_PIKACHU ; $05
	const COIN_ALAKAZAM ; $06
	const COIN_KABUTO ; $07
	const COIN_MAGNEMITE ; $08
	const COIN_GOLBAT ; $09
	const COIN_MAGMAR ; $0a
	const COIN_PSYDUCK ; $0b
	const COIN_MACHAMP ; $0c
	const COIN_MEW ; $0d
	const COIN_SNORLAX ; $0e
	const COIN_TOGEPI ; $0f
	const COIN_PONYTA ; $10
	const COIN_HORSEA ; $11
	const COIN_ARBOK ; $12
	const COIN_JIGGLYPUFF ; $13
	const COIN_DUGTRIO ; $14
	const COIN_GENGAR ; $15
	const COIN_RAICHU ; $16
	const COIN_LUGIA ; $17
DEF NUM_COINS EQU const_value
