; cup opponents
	const_def
	const GRANDMASTERCUP_GENE   ; 0
	const GRANDMASTERCUP_MITCH  ; 1
	const GRANDMASTERCUP_NIKKI  ; 2
	const GRANDMASTERCUP_RICK   ; 3
	const GRANDMASTERCUP_AMY    ; 4
	const GRANDMASTERCUP_KEN    ; 5
	const GRANDMASTERCUP_ISAAC  ; 6
	const GRANDMASTERCUP_MURRAY ; 7
	const GRANDMASTERCUP_RONALD ; 8
DEF NUM_GRANDMASTERCUP_OPPONENT_IDS EQU const_value

DEF NUM_GRANDMASTERCUP_DUELISTS  EQU 8
DEF NUM_GRANDMASTERCUP_OPPONENTS EQU NUM_GRANDMASTERCUP_DUELISTS - 1 ; 7

; cup prizes
DEF NUM_GRANDMASTERCUP_PRIZE_POOL EQU 37

  const_def
  const GRANDMASTERCUP_PRIZE_0 ; 0
  const GRANDMASTERCUP_PRIZE_1 ; 1
  const GRANDMASTERCUP_PRIZE_2 ; 2
  const GRANDMASTERCUP_PRIZE_3 ; 3

DEF NUM_TCG_CHALLENGE_CUP_PRIZE_POOL EQU 17
DEF NUM_GR_CHALLENGE_CUP_PRIZE_POOL  EQU 17
