; wCardPageNumber constants
DEF CARDPAGE_POKEMON_OVERVIEW    EQU $01
DEF CARDPAGE_POKEMON_ATTACK1_1   EQU $02
DEF CARDPAGE_POKEMON_ATTACK1_2   EQU $03
DEF CARDPAGE_POKEMON_ATTACK2_1   EQU $04
DEF CARDPAGE_POKEMON_ATTACK2_2   EQU $05
DEF CARDPAGE_POKEMON_DESCRIPTION EQU $06
DEF CARDPAGE_ENERGY_1            EQU $09
DEF CARDPAGE_ENERGY_2            EQU $0a
DEF CARDPAGE_TRAINER_1           EQU $0d
DEF CARDPAGE_TRAINER_2           EQU $0e

; wCardPageType constants
DEF CARDPAGETYPE_NOT_PLAY_AREA EQU $00
DEF CARDPAGETYPE_PLAY_AREA     EQU $01

; card type header constants ($10-tile headers in DuelCardHeaderGraphics)
DEF HEADER_TRAINER EQU $00
DEF HEADER_ENERGY  EQU $01
DEF HEADER_POKEMON EQU $02
