; in-duel action structs
RSRESET
DEF DUEL_ACTION_STRUCT_ACTION_INDEX RB    ; $00
DEF DUEL_ACTION_STRUCT_CARD_INDEX   RB    ; $01

DEF DUEL_ACTION_STRUCT_ARGS         RB 15 ; $02
DEF DUEL_ACTION_ARGS_SIZE EQU _RS - DUEL_ACTION_STRUCT_ARGS ; 15

DEF DUEL_ACTION_STRUCT_TERMINATOR   RB    ; $11
DEF DUEL_ACTION_STRUCT_SIZE EQU _RS ; 18

DEF AI_TRAINER_ARGS_SIZE EQU 6

; common sets of argument offset in DUEL_ACTION_STRUCT_ARGS
; play pkmn/energy card from hand
RSRESET
DEF PLAYCARD_ARGS_CARD_INDEX   RB ; $0
DEF PLAYCARD_ARGS_TO_PLAY_AREA RB ; $1

; retreat
RSRESET
DEF RETREAT_ARGS_STATUS    RB   ; $0
DEF RETREAT_ARGS_BENCH     RB   ; $1
DEF RETREAT_ARGS_COST_LIST RB 7 ; $2

; pkmn powers
RSRESET
DEF PKMNPOWER_ARGS_PLAY_AREA RB ; $0
rsunion
	; choose 1 pkmn
	DEF PKMNPOWER_TARGET_ARGS_TO_PLAY_AREA RB ; $1
rsnextu
	; coin flip + choose 1 pkmn
	DEF PKMNPOWER_COIN_ARGS_COIN_RESULT  RB ; $1
	DEF PKMNPOWER_COIN_ARGS_TO_PLAY_AREA RB ; $2
rsnextu
	; move from-to
	DEF PKMNPOWER_MOVE_ARGS_FROM_PLAY_AREA RB ; $1
	DEF PKMNPOWER_MOVE_ARGS_TO_PLAY_AREA   RB ; $2
rsnextu
	; energy trans
	DEF ENERGYTRANS_ARGS_FROM_PLAY_AREA RB ; $1
	DEF ENERGYTRANS_ARGS_ENERGY_INDEX   RB ; $2
	DEF ENERGYTRANS_ARGS_TO_PLAY_AREA   RB ; $3
rsnextu
	; shift
	DEF VENOMOTH_SHIFT_ARGS_TARGET_COLOR RB ; $1
rsnextu
	; peek
	DEF MANKEY_PEEK_ARGS_TARGET RB ; $1
endrsunion

; trainers
; potion
RSRESET
DEF POTION_ARGS_TO_PLAY_AREA RB ; $0
DEF POTION_ARGS_HEAL_AMOUNT  RB ; $1

; super potion
RSRESET
DEF SUPERPOTION_ARGS_DISCARD_ENERGY_INDEX RB ; $0
DEF SUPERPOTION_ARGS_TO_PLAY_AREA         RB ; $1
DEF SUPERPOTION_ARGS_HEAL_AMOUNT          RB ; $2

; prize cards
RSRESET
DEF SELECTPRIZE_ARGS_BITFIELD              RB   ; $0
DEF SELECTPRIZE_ARGS_SELECTED_CARD_INDICES RB 6 ; $1
