; wCardPageNumber constants
DEF CARDPAGE_POKEMON_OVERVIEW    EQU $01
DEF CARDPAGE_POKEMON_ATTACK1_1   EQU $02
DEF CARDPAGE_POKEMON_ATTACK1_2   EQU $03
DEF CARDPAGE_POKEMON_ATTACK2_1   EQU $04
DEF CARDPAGE_POKEMON_ATTACK2_2   EQU $05
DEF CARDPAGE_POKEMON_DESCRIPTION EQU $06
DEF CARDPAGE_ENERGY_1            EQU $09
DEF CARDPAGE_ENERGY_2            EQU $0a
DEF CARDPAGE_TRAINER_1           EQU $0d
DEF CARDPAGE_TRAINER_2           EQU $0e

; wAttackPageNumber constants
DEF ATTACKPAGE_ATTACK1_1 EQU $00
DEF ATTACKPAGE_ATTACK1_2 EQU $01
DEF ATTACKPAGE_ATTACK2_1 EQU $02
DEF ATTACKPAGE_ATTACK2_2 EQU $03

; wCardPageType constants
DEF CARDPAGETYPE_NOT_PLAY_AREA EQU $00
DEF CARDPAGETYPE_PLAY_AREA     EQU $01

; card type header constants ($10-tile headers in DuelCardHeaderGraphics)
DEF HEADER_TRAINER EQU $00
DEF HEADER_ENERGY  EQU $01
DEF HEADER_POKEMON EQU $02

; Box message id's
	const_def
	const BOXMSG_PLAYERS_TURN
	const BOXMSG_OPPONENTS_TURN
	const BOXMSG_BETWEEN_TURNS
	const BOXMSG_DECISION
	const BOXMSG_BENCH_POKEMON
	const BOXMSG_ARENA_POKEMON
	const BOXMSG_COIN_TOSS

; wDuelDisplayedScreen constants
DEF DUEL_MAIN_SCENE     EQU $01
DEF PLAY_AREA_CARD_LIST EQU $02
DEF UNKNOWN_SCREEN_4    EQU $04 ; used for some animations
DEF UNKNOWN_SCREEN_5    EQU $05 ; used for some animations
DEF COIN_TOSS           EQU $06
DEF DRAW_CARDS          EQU $07
DEF LARGE_CARD_PICTURE  EQU $08
DEF SHUFFLE_DECK        EQU $09
DEF CHECK_PLAY_AREA     EQU $0a

; wCardListItemSelectionMenuType constants
;NONE        EQU $00
DEF PLAY_CHECK   EQU $01
DEF SELECT_CHECK EQU $02

; play area screen constants
DEF DUELIST_PLAYER   EQU $0
DEF DUELIST_OPPONENT EQU $1
DEF ARENA_CARD_PLAYER   EQU 1 << DUELIST_PLAYER   ; $1
DEF ARENA_CARD_OPPONENT EQU 1 << DUELIST_OPPONENT ; $2

	const_def 6 ; PLAY_AREA_BENCH_5 + PRIZES_1
	const INPLAYAREA_PRIZE_1 ; $6
	const INPLAYAREA_PRIZE_2 ; $7
	const INPLAYAREA_PRIZE_3 ; $8
	const INPLAYAREA_PRIZE_4 ; $9
	const INPLAYAREA_PRIZE_5 ; $a
	const INPLAYAREA_PRIZE_6 ; $b

	const_def
	const PLAYAREA_PLAYER_POKEMON        ; $0
	const PLAYAREA_PLAYER_HAND           ; $1
	const PLAYAREA_PLAYER_DISCARD_PILE   ; $2
	const PLAYAREA_PLAYER_PRIZES         ; $3
	const PLAYAREA_OPPONENT_POKEMON      ; $4
	const PLAYAREA_OPPONENT_HAND         ; $5
	const PLAYAREA_OPPONENT_DISCARD_PILE ; $6
	const PLAYAREA_OPPONENT_PRIZES       ; $7

	const_def
	const INPLAYAREA_PLAYER_BENCH_1      ; $00
	const INPLAYAREA_PLAYER_BENCH_2      ; $01
	const INPLAYAREA_PLAYER_BENCH_3      ; $02
	const INPLAYAREA_PLAYER_BENCH_4      ; $03
	const INPLAYAREA_PLAYER_BENCH_5      ; $04
	const INPLAYAREA_PLAYER_ACTIVE       ; $05
	const INPLAYAREA_PLAYER_HAND         ; $06
	const INPLAYAREA_PLAYER_DISCARD_PILE ; $07
	const INPLAYAREA_OPP_ACTIVE          ; $08
	const INPLAYAREA_OPP_HAND            ; $09
	const INPLAYAREA_OPP_DISCARD_PILE    ; $0a
	const INPLAYAREA_OPP_BENCH_1         ; $0b
	const INPLAYAREA_OPP_BENCH_2         ; $0c
	const INPLAYAREA_OPP_BENCH_3         ; $0d
	const INPLAYAREA_OPP_BENCH_4         ; $0e
	const INPLAYAREA_OPP_BENCH_5         ; $0f
	const INPLAYAREA_PLAYER_PRIZE_1      ; $10
	const INPLAYAREA_PLAYER_PRIZE_2      ; $11
	const INPLAYAREA_PLAYER_PRIZE_3      ; $12
	const INPLAYAREA_PLAYER_PRIZE_4      ; $13
	const INPLAYAREA_PLAYER_PRIZE_5      ; $14
	const INPLAYAREA_PLAYER_PRIZE_6      ; $15
	const INPLAYAREA_OPP_PRIZE_1         ; $16
	const INPLAYAREA_OPP_PRIZE_2         ; $17
	const INPLAYAREA_OPP_PRIZE_3         ; $18
	const INPLAYAREA_OPP_PRIZE_4         ; $19
	const INPLAYAREA_OPP_PRIZE_5         ; $1a
	const INPLAYAREA_OPP_PRIZE_6         ; $1b
DEF NUM_INPLAYAREA_POSITIONS EQU const_value
	const_def $80
	const INPLAYAREA_PLAYER_PLAY_AREA    ; $80
	const INPLAYAREA_OPP_PLAY_AREA       ; $81
