DEF MAX_CHIPS EQU 9999

; bet / chips per play
DEF CHIPS_BET_BLACK_BOX   EQU 5
DEF CHIPS_BET_BILLS_PC    EQU 20
DEF CHIPS_BET_COIN_FLIP   EQU 1
DEF CHIPS_BET_SLOT_1      EQU 1
DEF CHIPS_BET_SLOT_5      EQU 5
DEF CHIPS_BET_DUNGEON_10  EQU 10
DEF CHIPS_BET_DUNGEON_20  EQU 20
DEF CHIPS_BET_DUNGEON_30  EQU 30
DEF CHIPS_BET_DUNGEON_50  EQU 50
DEF CHIPS_BET_DUNGEON_100 EQU 100

; coin flip
DEF MIN_NUM_GAMECENTER_COIN_FLIP_STREAK EQU 3

DEF CHIPS_COIN_FLIP_STREAK_3 EQU 20
DEF CHIPS_COIN_FLIP_STREAK_4 EQU 40
DEF CHIPS_COIN_FLIP_STREAK_5 EQU 100
DEF CHIPS_COIN_FLIP_STREAK_6 EQU 200
DEF CHIPS_COIN_FLIP_STREAK_7 EQU 500
DEF CHIPS_COIN_FLIP_STREAK_8 EQU 1000
DEF CHIPS_COIN_FLIP_STREAK_9 EQU 3000

DEF MAX_NUM_GAMECENTER_COIN_FLIP_STREAK EQU 10

; black box
; insert 5 promos -> +[1, 5] bonus cards
DEF MAX_NUM_BLACK_BOX_INPUT  EQU 5
DEF MAX_NUM_BLACK_BOX_OUTPUT EQU 10
DEF BLACK_BOX_OUTPUT_BYTES   EQU 2 * MAX_NUM_BLACK_BOX_OUTPUT

; card dungeon
; for VAR_CARD_DUNGEON_PROGRESS
	const_def 1
	const CARDDUNGEON_BEAT_PAWN        ; 1
	const CARDDUNGEON_BEAT_KNIGHT      ; 2
	const CARDDUNGEON_BEAT_BISHOP      ; 3
	const CARDDUNGEON_BEAT_ROOK        ; 4
	const CARDDUNGEON_BEAT_QUEEN       ; 5
	const CARDDUNGEON_LOST             ; 6
	const CARDDUNGEON_QUIT_OR_WITHDREW ; 7

; slots
DEF MAX_NUM_SLOT_MACHINE_HOT_MODE    EQU 3
DEF MAX_NUM_SLOT_MACHINE_BONUS_PLAYS EQU 10

	const_def
	const SLOTMACHINE_LEFT_REEL   ; 0
	const SLOTMACHINE_CENTER_REEL ; 1
	const SLOTMACHINE_RIGHT_REEL  ; 2
DEF NUM_SLOT_MACHINE_REELS EQU const_value

DEF SLOT_MACHINE_REEL_LENGTH           EQU 20
DEF NUM_SLOT_MACHINE_SYMBOL_VERT_TILES EQU 3
DEF SLOT_MACHINE_REEL_OFFSET_LENGTH    EQU SLOT_MACHINE_REEL_LENGTH * NUM_SLOT_MACHINE_SYMBOL_VERT_TILES ; 60
DEF SLOT_MACHINE_REEL_VISIBLE_HEIGHT   EQU 7
DEF SLOT_MACHINE_REEL_VISIBLE_WIDTH    EQU 4

DEF SLOT_MACHINE_REEL_LANDING_F EQU 6
DEF SLOT_MACHINE_REEL_LANDED_F  EQU 7
	DEF SLOT_MACHINE_REEL_OFFSET_MASK EQU %00_111111
	DEF SLOT_MACHINE_REEL_FLAGS_MASK  EQU %11_000000
	DEF SLOT_MACHINE_REEL_TEASE_MASK  EQU %000_11111

; weird type/pkmn orders :(
	const_def
	const SLOTMACHINESYMBOL_FIRE      ; $0
	const SLOTMACHINESYMBOL_LIGHTNING ; $1
	const SLOTMACHINESYMBOL_WATER     ; $2
	const SLOTMACHINESYMBOL_COLORLESS ; $3
	const SLOTMACHINESYMBOL_RAINBOW   ; $4
	const SLOTMACHINESYMBOL_UNUSED    ; $5
	const SLOTMACHINESYMBOL_MONEYBAG  ; $6
	const SLOTMACHINESYMBOL_DRAGONITE ; $7
	const SLOTMACHINESYMBOL_ARTICUNO  ; $8
	const SLOTMACHINESYMBOL_MOLTRES   ; $9
	const SLOTMACHINESYMBOL_ZAPDOS    ; $a
DEF NUM_SLOTMACHINESYMBOLS EQU const_value

DEF NUM_SLOTMACHINESYMBOLS_TILES EQU NUM_SLOTMACHINESYMBOLS * NUM_SLOT_MACHINE_SYMBOL_VERT_TILES ; 33

; prize exchange
	const_def
	const GAMECENTERPRIZE_VENUSAUR        ; 0
	const GAMECENTERPRIZE_MEW             ; 1
	const GAMECENTERPRIZE_BILLS_COMPUTER  ; 2
	const GAMECENTERPRIZE_JIGGLYPUFF_COIN ; 3
	const GAMECENTERPRIZE_1_PRESENT_PACK  ; 4
	const GAMECENTERPRIZE_3_PRESENT_PACKS ; 5

; 3 present packs replace Jigglypuff Coin
DEF NUM_GAME_CENTER_PRIZE_LIST_ITEMS EQU 5

DEF GAMECENTERPRIZE_VENUSAUR_CHIPS        EQU 2000
DEF GAMECENTERPRIZE_MEW_CHIPS             EQU 2000
DEF GAMECENTERPRIZE_BILLS_COMPUTER_CHIPS  EQU 1000
DEF GAMECENTERPRIZE_JIGGLYPUFF_COIN_CHIPS EQU 500
DEF GAMECENTERPRIZE_1_PRESENT_PACK_CHIPS  EQU 200
DEF GAMECENTERPRIZE_3_PRESENT_PACKS_CHIPS EQU 500
