DEF MAX_CHIPS EQU 9999

; bet / chips per play
DEF CHIPS_BET_BLACK_BOX   EQU 5
DEF CHIPS_BET_BILLS_PC    EQU 20
DEF CHIPS_BET_COIN_FLIP   EQU 1
DEF CHIPS_BET_SLOT_1      EQU 1
DEF CHIPS_BET_SLOT_5      EQU 5
DEF CHIPS_BET_DUNGEON_10  EQU 10
DEF CHIPS_BET_DUNGEON_20  EQU 20
DEF CHIPS_BET_DUNGEON_30  EQU 30
DEF CHIPS_BET_DUNGEON_50  EQU 50
DEF CHIPS_BET_DUNGEON_100 EQU 100

; coin flip
DEF MIN_NUM_GAMECENTER_COIN_FLIP_STREAK EQU 3

DEF CHIPS_COIN_FLIP_STREAK_3 EQU 20
DEF CHIPS_COIN_FLIP_STREAK_4 EQU 40
DEF CHIPS_COIN_FLIP_STREAK_5 EQU 100
DEF CHIPS_COIN_FLIP_STREAK_6 EQU 200
DEF CHIPS_COIN_FLIP_STREAK_7 EQU 500
DEF CHIPS_COIN_FLIP_STREAK_8 EQU 1000
DEF CHIPS_COIN_FLIP_STREAK_9 EQU 3000

DEF MAX_NUM_GAMECENTER_COIN_FLIP_STREAK EQU 10

; black box
; insert 5 promos -> +[1, 5] bonus cards
DEF MAX_NUM_BLACK_BOX_INPUT  EQU 5
DEF MAX_NUM_BLACK_BOX_OUTPUT EQU 10
DEF BLACK_BOX_OUTPUT_BYTES   EQU 2 * MAX_NUM_BLACK_BOX_OUTPUT

; card dungeon
; for VAR_CARD_DUNGEON_PROGRESS
  const_def 1
  const CARDDUNGEON_WON_PAWN         ; 1
  const CARDDUNGEON_WON_KNIGHT       ; 2
  const CARDDUNGEON_WON_BISHOP       ; 3
  const CARDDUNGEON_WON_ROOK         ; 4
  const CARDDUNGEON_WON_QUEEN        ; 5
  const CARDDUNGEON_LOST             ; 6
  const CARDDUNGEON_QUIT_OR_WITHDREW ; 7
