; cgb palette size
DEF palettes EQUS "* PAL_SIZE"

DEF NUM_BACKGROUND_PALETTES EQU 8
DEF NUM_OBJECT_PALETTES     EQU 8

DEF PALRGB_WHITE EQU (31 << B_COLOR_BLUE) | (31 << B_COLOR_GREEN) | (31 << B_COLOR_RED)

; tile size
DEF tiles EQUS "* TILE_SIZE"

DEF TILE_SIZE_1BPP EQU 8 ; bytes
DEF tiles_1bpp EQUS "* TILE_SIZE_1BPP"

; icon tile offsets
DEF ICON_TILE_BASIC_POKEMON   EQU $d0
DEF ICON_TILE_STAGE_1_POKEMON EQU $d4
DEF ICON_TILE_STAGE_2_POKEMON EQU $d8
DEF ICON_TILE_TRAINER         EQU $dc

DEF ICON_TILE_FIRE            EQU $e0
DEF ICON_TILE_GRASS           EQU $e4
DEF ICON_TILE_LIGHTNING       EQU $e8
DEF ICON_TILE_WATER           EQU $ec
DEF ICON_TILE_FIGHTING        EQU $f0
DEF ICON_TILE_PSYCHIC         EQU $f4
DEF ICON_TILE_COLORLESS       EQU $f8
DEF ICON_TILE_ENERGY          EQU $fc

; card gfx
; see LoadCardGfx, CardGraphics
DEF CARD_GFX_WIDTH     EQU 8 ; in tiles
DEF CARD_GFX_HEIGHT    EQU 6 ; in tiles
DEF NUM_CARD_GFX_TILES EQU CARD_GFX_WIDTH * CARD_GFX_HEIGHT ; 48

RSRESET
DEF CARDGFXSTRUCT_PALS              RB 3 palettes ; $000
DEF CARDGFXSTRUCT_PALS_SIZE         EQU _RS ; 24

DEF CARDGFXSTRUCT_TILE_ATTRMAP      RB NUM_CARD_GFX_TILES ; $018
DEF CARDGFXSTRUCT_TILE_ATTRMAP_SIZE EQU _RS - CARDGFXSTRUCT_TILE_ATTRMAP ; 48
	DEF CARD_GFX_TILE_ATTRMAP_PAL_INDEX  EQU %11_000000
	; offset = 48 + (cur alt tile idx) - (cur tile idx)
	; 0 if no alt
	DEF CARD_GFX_TILE_ATTRMAP_ALT_OFFSET EQU %00_111111

DEF CARDGFXSTRUCT_TILES             RB NUM_CARD_GFX_TILES tiles ; $048
DEF CARDGFXSTRUCT_TILES_SIZE        EQU _RS - CARDGFXSTRUCT_TILES ; 768

; printer-only (grayscale) alt tiles, of variable length from 0 to 48
DEF CARDGFXSTRUCT_ALT_TILES_START   EQU _RS ; $348
