; cgb palette size
DEF palettes EQUS "* PAL_SIZE"

DEF NUM_BACKGROUND_PALETTES EQU 8
DEF NUM_OBJECT_PALETTES     EQU 8

DEF PALRGB_WHITE EQU (COLOR_CH_MAX << B_COLOR_BLUE) | (COLOR_CH_MAX << B_COLOR_GREEN) | (COLOR_CH_MAX << B_COLOR_RED)

; tile size
DEF tiles EQUS "* TILE_SIZE"

DEF TILE_SIZE_1BPP EQU 8 ; bytes
DEF tiles_1bpp EQUS "* TILE_SIZE_1BPP"

DEF CARD_HEADER_TILE_SIZE  EQU 8 * 2 ; tiles
DEF REGULAR_ICON_TILE_SIZE EQU 4 ; tiles

DEF NUM_CARD_OR_DUEL_BORDER_TILES EQU 8 ; tiles

; icon tile offsets
DEF CARD_TYPE_ICON_TILE_START EQU $d0

RSSET CARD_TYPE_ICON_TILE_START
DEF ICON_TILE_BASIC_POKEMON   RL ; $d0

DEF ICON_TILE_EVO_OR_TRAINER_OFFSET EQU _RS - ICON_TILE_BASIC_POKEMON ; $04
DEF ICON_TILE_STAGE_1_POKEMON RL ; $d4
DEF ICON_TILE_STAGE_2_POKEMON RL ; $d8
DEF ICON_TILE_TRAINER         RL ; $dc
DEF NUM_EVO_OR_TRAINER_ICON_TILES EQU _RS - ICON_TILE_STAGE_1_POKEMON ; $0c

DEF ICON_TILE_POKEMON_TYPES EQU _RS ; $e0
DEF ICON_TILE_FIRE            RL ; $e0
DEF ICON_TILE_GRASS           RL ; $e4
DEF ICON_TILE_LIGHTNING       RL ; $e8
DEF ICON_TILE_WATER           RL ; $ec
DEF ICON_TILE_FIGHTING        RL ; $f0
DEF ICON_TILE_PSYCHIC         RL ; $f4
DEF ICON_TILE_COLORLESS       RL ; $f8
DEF ICON_TILE_ENERGY          RL ; $fc

DEF NUM_CARD_TYPE_ICON_TILES EQU _RS - CARD_TYPE_ICON_TILE_START ; $30

; CardSymbolTable uses different order
	const_def
	const CARD_SYMBOL_FIRE            ; $0
	const CARD_SYMBOL_GRASS           ; $1
	const CARD_SYMBOL_LIGHTNING       ; $2
	const CARD_SYMBOL_WATER           ; $3
	const CARD_SYMBOL_FIGHTING        ; $4
	const CARD_SYMBOL_PSYCHIC         ; $5
	const CARD_SYMBOL_COLORLESS       ; $6
	const CARD_SYMBOL_ENERGY          ; $7
	const CARD_SYMBOL_BASIC_POKEMON   ; $8
	const CARD_SYMBOL_STAGE_1_POKEMON ; $9
	const CARD_SYMBOL_STAGE_2_POKEMON ; $a
	const CARD_SYMBOL_TRAINER         ; $b

; real-set icon tile offsets
RSRESET
DEF ICON_TILE_JUNGLE          RL ; $00
DEF ICON_TILE_FOSSIL          RL ; $04
DEF ICON_TILE_GB              RL ; $08
DEF ICON_TILE_TEAM_ROCKET     RL ; $0c
DEF ICON_TILE_EXPANSION_SHEET RL ; $10
DEF ICON_TILE_GYM_HEROES      RL ; $14
DEF ICON_TILE_BULBASAUR_DECK  RL ; $18
DEF ICON_TILE_SQUIRTLE_DECK   RL ; $1c

; check pokemon screen icon tile offsets
RSRESET
DEF ICON_TILE_CHECK_POKEMON_SCREEN_BASIC                 RL ; $00
DEF ICON_TILE_CHECK_POKEMON_SCREEN_STAGE1                RL ; $04
DEF ICON_TILE_CHECK_POKEMON_SCREEN_STAGE2                RL ; $08
DEF ICON_TILE_CHECK_POKEMON_SCREEN_STAGE2_WITHOUT_STAGE1 RL ; $0c
DEF NUM_CHECK_POKEMON_SCREEN_STAGE_ICON_TILES EQU _RS ; $10

DEF ICON_TILE_CHECK_POKEMON_SCREEN_PLAYER_ACT   RB 3 ; $10
DEF ICON_TILE_CHECK_POKEMON_SCREEN_PLAYER_BPX   RW   ; $13
DEF ICON_TILE_CHECK_POKEMON_SCREEN_PLAYER_BP1   RB   ; $15
DEF ICON_TILE_CHECK_POKEMON_SCREEN_PLAYER_BP2   RB   ; $16
DEF ICON_TILE_CHECK_POKEMON_SCREEN_PLAYER_BP3   RB   ; $17
DEF ICON_TILE_CHECK_POKEMON_SCREEN_PLAYER_BP4   RB   ; $18
DEF ICON_TILE_CHECK_POKEMON_SCREEN_PLAYER_BP5   RB   ; $19
DEF ICON_TILE_CHECK_POKEMON_SCREEN_OPPONENT_ACT RB 3 ; $1a
DEF ICON_TILE_CHECK_POKEMON_SCREEN_OPPONENT_BPX RW   ; $1d
DEF ICON_TILE_CHECK_POKEMON_SCREEN_OPPONENT_BP1 RB   ; $1f
DEF ICON_TILE_CHECK_POKEMON_SCREEN_OPPONENT_BP2 RB   ; $20
DEF ICON_TILE_CHECK_POKEMON_SCREEN_OPPONENT_BP3 RB   ; $21
DEF ICON_TILE_CHECK_POKEMON_SCREEN_OPPONENT_BP4 RB   ; $22
DEF ICON_TILE_CHECK_POKEMON_SCREEN_OPPONENT_BP5 RB   ; $23

DEF NUM_CHECK_POKEMON_SCREEN_ICON_TILES EQU _RS ; $24

; setup icon tile offsets
RSRESET
DEF ICON_TILE_SETUP_FACEDOWN_ARENA RB 12 ; $00
DEF ICON_TILE_SETUP_FACEDOWN_PRIZE RB    ; $0c

DEF NUM_SETUP_ICON_TILES EQU _RS ; $0d

; play area screen icon tile offsets
RSRESET
DEF ICON_TILE_PLAY_AREA_SCREEN_HAND                        RL ; $00
DEF ICON_TILE_PLAY_AREA_SCREEN_DECK                        RL ; $04
DEF ICON_TILE_PLAY_AREA_SCREEN_DISCARD_PILE                RL ; $08
DEF ICON_TILE_PLAY_AREA_SCREEN_PRIZE                       RL ; $0c
DEF ICON_TILE_PLAY_AREA_SCREEN_PRIZE_EMPTY                 RL ; $10
DEF ICON_TILE_PLAY_AREA_SCREEN_BENCH_BASIC                 RL ; $14
DEF ICON_TILE_PLAY_AREA_SCREEN_BENCH_STAGE1                RL ; $18
DEF ICON_TILE_PLAY_AREA_SCREEN_BENCH_STAGE2                RL ; $1c
DEF ICON_TILE_PLAY_AREA_SCREEN_BENCH_STAGE2_WITHOUT_STAGE1 RL ; $20
DEF ICON_TILE_PLAY_AREA_SCREEN_BENCH_EMPTY                 RL ; $24
DEF ICON_TILE_PLAY_AREA_SCREEN_TARGET_ARROW                RB ; $28
DEF ICON_TILE_PLAY_AREA_SCREEN_29                          RL ; $29

DEF NUM_PLAY_AREA_SCREEN_ICON_TILES EQU _RS ; $2d

; card gfx
; see LoadCardGfx, CardGraphics
DEF CARD_GFX_WIDTH     EQU 8 ; tiles
DEF CARD_GFX_HEIGHT    EQU 6 ; tiles
DEF NUM_CARD_GFX_TILES EQU CARD_GFX_WIDTH * CARD_GFX_HEIGHT ; 48

RSRESET
DEF CARDGFXSTRUCT_PALS              RB 3 palettes ; $000
DEF CARDGFXSTRUCT_PALS_SIZE         EQU _RS ; 24

DEF CARDGFXSTRUCT_TILE_ATTRMAP      RB NUM_CARD_GFX_TILES ; $018
DEF CARDGFXSTRUCT_TILE_ATTRMAP_SIZE EQU _RS - CARDGFXSTRUCT_TILE_ATTRMAP ; 48
	DEF CARD_GFX_TILE_ATTRMAP_PAL_INDEX  EQU %11_000000
	; offset = 48 + (cur alt tile idx) - (cur tile idx)
	; 0 if no alt
	DEF CARD_GFX_TILE_ATTRMAP_ALT_OFFSET EQU %00_111111

DEF CARDGFXSTRUCT_TILES             RB NUM_CARD_GFX_TILES tiles ; $048
DEF CARDGFXSTRUCT_TILES_SIZE        EQU _RS - CARDGFXSTRUCT_TILES ; 768

; printer-only (grayscale) alt tiles, of variable length from 0 to 48
DEF CARDGFXSTRUCT_ALT_TILES_START   EQU _RS ; $348
