	const_def
	const MUSIC_STOP           ; $00
	const MUSIC_TITLESCREEN    ; $01
	const MUSIC_DUELTHEME_1    ; $02
	const MUSIC_DUELTHEME_2    ; $03
	const MUSIC_DUELTHEME_3    ; $04
	const MUSIC_PAUSEMENU      ; $05
	const MUSIC_PCMAINMENU     ; $06
	const MUSIC_DECKMACHINE    ; $07
	const MUSIC_CARDPOP        ; $08
	const MUSIC_OVERWORLD      ; $09
	const MUSIC_POKEMONDOME    ; $0a
	const MUSIC_CHALLENGEHALL  ; $0b
	const MUSIC_CLUB_1         ; $0c
	const MUSIC_CLUB_2         ; $0d
	const MUSIC_CLUB_3         ; $0e
	const MUSIC_RONALD         ; $0f
	const MUSIC_IMAKUNI        ; $10
	const MUSIC_HALLOFHONOR    ; $11
	const MUSIC_12             ; $12
	const MUSIC_13             ; $13
	const MUSIC_HERECOMESGR    ; $14
	const MUSIC_GROVERWORLD    ; $15
	const MUSIC_FORT_1         ; $16
	const MUSIC_FORT_2         ; $17
	const MUSIC_FORT_3         ; $18
	const MUSIC_FORT_4         ; $19
	const MUSIC_GRCASTLE       ; $1a
	const MUSIC_1B             ; $1b
	const MUSIC_GRCHALLENGECUP ; $1c
	const MUSIC_GAMECORNER     ; $1d
	const MUSIC_GRBLIMP        ; $1e
	const MUSIC_GRDUELTHEME_1  ; $1f
	const MUSIC_GRDUELTHEME_2  ; $20
	const MUSIC_GRDUELTHEME_3  ; $21
	const MUSIC_22             ; $22
	const MUSIC_ISHIHARA       ; $23
	const MUSIC_IMAKUNI2       ; $24
	const MUSIC_CREDITS        ; $25
	const MUSIC_26             ; $26
	const MUSIC_27             ; $27
	const MUSIC_MATCHSTART_1   ; $28
	const MUSIC_MATCHSTART_2   ; $29
	const MUSIC_MATCHSTART_3   ; $2a
	const MUSIC_MATCHVICTORY   ; $2b
	const MUSIC_MATCHLOSS      ; $2c
	const MUSIC_MATCHDRAW      ; $2d
	const MUSIC_UNUSED_2E      ; $2e
	const MUSIC_BOOSTERPACK    ; $2f
	const MUSIC_MEDAL          ; $30
	const MUSIC_UNUSED_31      ; $31
	const MUSIC_DITTY_1        ; $32
	const MUSIC_DITTY_2        ; $33
	const MUSIC_DITTY_3        ; $34
	const MUSIC_DITTY_4        ; $35
	const MUSIC_DITTY_5        ; $36
	const MUSIC_37             ; $37
	const MUSIC_38             ; $38
	const MUSIC_39             ; $39
	const MUSIC_DITTY6         ; $3a
	const MUSIC_3B             ; $3b
