	const_def
	const MUSIC_STOP                      ; $00
	const MUSIC_TITLE_SCREEN              ; $01
	const MUSIC_DUEL_THEME_CLUB_MEMBER    ; $02
	const MUSIC_DUEL_THEME_CLUB_MASTER    ; $03
	const MUSIC_DUEL_THEME_GRAND_MASTER   ; $04
	const MUSIC_PAUSE_MENU                ; $05
	const MUSIC_PC_MAIN_MENU              ; $06
	const MUSIC_DECK_MACHINE              ; $07
	const MUSIC_CARD_POP                  ; $08
	const MUSIC_OVERWORLD                 ; $09
	const MUSIC_POKEMON_DOME              ; $0a
	const MUSIC_CHALLENGE_HALL            ; $0b
	const MUSIC_CLUB_1                    ; $0c
	const MUSIC_CLUB_2                    ; $0d
	const MUSIC_CLUB_3                    ; $0e
	const MUSIC_RONALD                    ; $0f
	const MUSIC_IMAKUNI_BLACK             ; $10
	const MUSIC_HALL_OF_HONOR             ; $11
	const MUSIC_12                        ; $12
	const MUSIC_13                        ; $13
	const MUSIC_HERE_COMES_GR             ; $14
	const MUSIC_GR_OVERWORLD              ; $15
	const MUSIC_FORT_1                    ; $16
	const MUSIC_FORT_2                    ; $17
	const MUSIC_FORT_3                    ; $18
	const MUSIC_FORT_4                    ; $19
	const MUSIC_GR_CASTLE                 ; $1a
	const MUSIC_1B                        ; $1b
	const MUSIC_GR_CHALLENGE_CUP          ; $1c
	const MUSIC_GAME_CENTER               ; $1d
	const MUSIC_GR_BLIMP                  ; $1e
	const MUSIC_DUEL_THEME_GR_MEMBER      ; $1f
	const MUSIC_DUEL_THEME_GR_LEADER      ; $20
	const MUSIC_DUEL_THEME_GR_KING        ; $21
	const MUSIC_22                        ; $22
	const MUSIC_ISHIHARA                  ; $23
	const MUSIC_IMAKUNI_RED               ; $24
	const MUSIC_CREDITS                   ; $25
	const MUSIC_26                        ; $26
	const MUSIC_27                        ; $27
	const MUSIC_MATCH_START_MEMBER        ; $28
	const MUSIC_MATCH_START_CLUB_MASTER   ; $29
	const MUSIC_MATCH_START_GRAND_MASTER  ; $2a
	const MUSIC_MATCH_VICTORY             ; $2b
	const MUSIC_MATCH_LOSS                ; $2c
	const MUSIC_MATCH_DRAW                ; $2d
	const MUSIC_UNUSED_2E                 ; $2e
	const MUSIC_BOOSTER_PACK              ; $2f
	const MUSIC_MEDAL                     ; $30
	const MUSIC_UNUSED_31                 ; $31
	const MUSIC_MATCH_START_GR_LEADER     ; $32
	const MUSIC_MATCH_START_GR_EXECS      ; $33
	const MUSIC_GAME_CENTER_POWER_ON      ; $34
	const MUSIC_FANFARE_1                 ; $35
	const MUSIC_FANFARE_2                 ; $36
	const MUSIC_STING_37                  ; $37
	const MUSIC_STING_38                  ; $38
	const MUSIC_STING_39                  ; $39
	const MUSIC_GRAND_MASTER_CUP_CHAMPION ; $3a
	const MUSIC_STING_3B                  ; $3b
