	const_def
	const MARK_PIC          ; $00
	const MINT_PIC          ; $01
	const MARK_LINK_PIC     ; $02
	const MINT_LINK_PIC     ; $03
	const RONALD_PIC        ; $04
	const SAM_PIC           ; $05
	const AARON_PIC         ; $06
	const ISHIHARA_PIC      ; $07
	const IMAKUNI_BLACK_PIC ; $08
	const IMAKUNI_RED_PIC   ; $09
	const ISAAC_PIC         ; $0a
	const JENNIFER_PIC      ; $0b
	const NICHOLAS_PIC      ; $0c
	const BRANDON_PIC       ; $0d
	const MURRAY_PIC        ; $0e
	const STEPHANIE_PIC     ; $0f
	const DANIEL_PIC        ; $10
	const ROBERT_PIC        ; $11
	const GENE_PIC          ; $12
	const MATTHEW_PIC       ; $13
	const RYAN_PIC          ; $14
	const ANDREW_PIC        ; $15
	const MITCH_PIC         ; $16
	const MICHAEL_PIC       ; $17
	const CHRIS_PIC         ; $18
	const JESSICA_PIC       ; $19
	const NIKKI_PIC         ; $1a
	const BRITTANY_PIC      ; $1b
	const KRISTIN_PIC       ; $1c
	const HEATHER_PIC       ; $1d
	const RICK_PIC          ; $1e
	const JOSEPH_PIC        ; $1f
	const DAVID_PIC         ; $20
	const ERIK_PIC          ; $21
	const AMY_PIC           ; $22
	const JOSHUA_PIC        ; $23
	const SARA_PIC          ; $24
	const AMANDA_PIC        ; $25
	const KEN_PIC           ; $26
	const JOHN_PIC          ; $27
	const ADAM_PIC          ; $28
	const JONATHAN_PIC      ; $29
	const COURTNEY_PIC      ; $2a
	const STEVE_PIC         ; $2b
	const JACK_PIC          ; $2c
	const ROD_PIC           ; $2d
	const EIJI_PIC          ; $2e
	const MAGICIAN_PIC      ; $2f
	const YUI_PIC           ; $30
	const TOSHIRON_PIC      ; $31
	const PIERROT_PIC       ; $32
	const ANNA_PIC          ; $33
	const DEE_PIC           ; $34
	const MASQUERADE_PIC    ; $35
	const PAWN_PIC          ; $36
	const KNIGHT_PIC        ; $37
	const BISHOP_PIC        ; $38
	const ROOK_PIC          ; $39
	const QUEEN_PIC         ; $3a
	const GR_1_PIC          ; $3b
	const GR_2_PIC          ; $3c
	const GR_3_PIC          ; $3d
	const GR_4_PIC          ; $3e
	const MIDORI_PIC        ; $3f
	const YUTA_PIC          ; $40
	const MIYUKI_PIC        ; $41
	const MORINO_PIC        ; $42
	const RENNA_PIC         ; $43
	const ICHIKAWA_PIC      ; $44
	const CATHERINE_PIC     ; $45
	const TAP_PIC           ; $46
	const JES_PIC           ; $47
	const YUKI_PIC          ; $48
	const SHOKO_PIC         ; $49
	const HIDERO_PIC        ; $4a
	const MIYAJIMA_PIC      ; $4b
	const SENTA_PIC         ; $4c
	const AIRA_PIC          ; $4d
	const KANOKO_PIC        ; $4e
	const GODA_PIC          ; $4f
	const GRACE_PIC         ; $50
	const KAMIYA_PIC        ; $51
	const MIWA_PIC          ; $52
	const KEVIN_PIC         ; $53
	const YOSUKE_PIC        ; $54
	const RYOKO_PIC         ; $55
	const MAMI_PIC          ; $56
	const NISHIJIMA_PIC     ; $57
	const ISHII_PIC         ; $58
	const SAMEJIMA_PIC      ; $59
	const KANZAKI_PIC       ; $5a
	const RUI_PIC           ; $5b
	const BIRURITCHI_PIC    ; $5c
	const GR_X_PIC          ; $5d
	const TOBICHAN_PIC      ; $5e
	const DR_MASON_PIC      ; $5f
DEF NUM_PICS EQU const_value

	const_def
	const NPC_MARK                              ; $00
	const NPC_MINT                              ; $01
	const NPC_DR_MASON                          ; $02
	const NPC_RONALD                            ; $03
	const NPC_ISHIHARA                          ; $04
	const NPC_IMAKUNI_BLACK                     ; $05
	const NPC_SAM                               ; $06
	const NPC_AARON                             ; $07
	const NPC_PAPPY_1                           ; $08
	const NPC_GENE                              ; $09
	const NPC_MATTHEW                           ; $0a
	const NPC_RYAN                              ; $0b
	const NPC_ANDREW                            ; $0c
	const NPC_MITCH                             ; $0d
	const NPC_MICHAEL                           ; $0e
	const NPC_CHRIS                             ; $0f
	const NPC_JESSICA                           ; $10
	const NPC_NIKKI                             ; $11
	const NPC_BRITTANY                          ; $12
	const NPC_KRISTIN                           ; $13
	const NPC_HEATHER                           ; $14
	const NPC_RICK                              ; $15
	const NPC_DAVID                             ; $16
	const NPC_JOSEPH                            ; $17
	const NPC_ERIK                              ; $18
	const NPC_AMY                               ; $19
	const NPC_AMY_LOUNGE                        ; $1a
	const NPC_JOSHUA                            ; $1b
	const NPC_SARA                              ; $1c
	const NPC_AMANDA                            ; $1d
	const NPC_KEN                               ; $1e
	const NPC_JOHN                              ; $1f
	const NPC_ADAM                              ; $20
	const NPC_JONATHAN                          ; $21
	const NPC_ISAAC                             ; $22
	const NPC_JENNIFER                          ; $23
	const NPC_NICHOLAS                          ; $24
	const NPC_BRANDON                           ; $25
	const NPC_MURRAY                            ; $26
	const NPC_ROBERT                            ; $27
	const NPC_DANIEL                            ; $28
	const NPC_STEPHANIE                         ; $29
	const NPC_COURTNEY                          ; $2a
	const NPC_STEVE                             ; $2b
	const NPC_JACK                              ; $2c
	const NPC_ROD                               ; $2d
	const NPC_GR_1                              ; $2e
	const NPC_GR_2                              ; $2f
	const NPC_GR_3                              ; $30
	const NPC_GR_4                              ; $31
	const NPC_GR_5                              ; $32
	const NPC_GR_LAD_1                          ; $33
	const NPC_MIDORI                            ; $34
	const NPC_YUTA                              ; $35
	const NPC_MIYUKI                            ; $36
	const NPC_MORINO                            ; $37
	const NPC_LIGHTNING_FORT_GR_LASS            ; $38
	const NPC_RENNA                             ; $39
	const NPC_ICHIKAWA                          ; $3a
	const NPC_CATHERINE                         ; $3b
	const NPC_GR_CHALLENGE_HALL_GR_GRANNY       ; $3c
	const NPC_FIRE_FORT_GRAMPY                  ; $3d
	const NPC_JES                               ; $3e
	const NPC_YUKI                              ; $3f
	const NPC_SHOKO                             ; $40
	const NPC_HIDERO                            ; $41
	const NPC_WATER_FORT_GLASSES_KID            ; $42
	const NPC_MIYAJIMA                          ; $43
	const NPC_SENTA                             ; $44
	const NPC_AIRA                              ; $45
	const NPC_KANOKO                            ; $46
	const NPC_GODA                              ; $47
	const NPC_GRACE                             ; $48
	const NPC_KAMIYA                            ; $49
	const NPC_PSYCHIC_STRONGHOLD_LADY           ; $4a
	const NPC_MIWA                              ; $4b
	const NPC_KEVIN                             ; $4c
	const NPC_YOSUKE                            ; $4d
	const NPC_RYOKO                             ; $4e
	const NPC_MAMI                              ; $4f
	const NPC_NISHIJIMA                         ; $50
	const NPC_ISHII                             ; $51
	const NPC_SAMEJIMA                          ; $52
	const NPC_KANZAKI                           ; $53
	const NPC_RUI                               ; $54
	const NPC_BIRURITCHI                        ; $55
	const NPC_TOBICHAN                          ; $56
	const NPC_EIJI                              ; $57
	const NPC_MAGICIAN                          ; $58
	const NPC_TOSHIRON                          ; $59
	const NPC_PIERROT                           ; $5a
	const NPC_ANNA                              ; $5b
	const NPC_DEE                               ; $5c
	const NPC_MASQUERADE                        ; $5d
	const NPC_PAWN                              ; $5e
	const NPC_KNIGHT                            ; $5f
	const NPC_BISHOP                            ; $60
	const NPC_ROOK                              ; $61
	const NPC_QUEEN                             ; $62
	const NPC_GR_X                              ; $63
	const NPC_CLERK_BATTLE_CENTER               ; $64
	const NPC_CLERK_GIFT_CENTER                 ; $65
	const NPC_GR_CLERK_TCG_AIRPORT              ; $66
	const NPC_GR_CLERK_GR_AIRPORT               ; $67
	const NPC_GR_CLERK_BATTLE_CENTER            ; $68
	const NPC_GR_CLERK_GIFT_CENTER              ; $69
	const NPC_ROCK_CLUB_LASS                    ; $6a
	const NPC_ROCK_CLUB_WOMAN                   ; $6b
	const NPC_ROCK_CLUB_CHAP                    ; $6c
	const NPC_ROCK_CLUB_CAPPED_LAD              ; $6d
	const NPC_FIGHTING_CLUB_PAPPY               ; $6e
	const NPC_FIGHTING_CLUB_GLASSES_KID         ; $6f
	const NPC_FIGHTING_CLUB_CAPPED_GUY          ; $70
	const NPC_FIGHTING_CLUB_CAPPED_LASS         ; $71
	const NPC_GRASS_CLUB_GRANNY                 ; $72
	const NPC_GRASS_CLUB_LASS                   ; $73
	const NPC_GRASS_CLUB_CAPPED_LASS            ; $74
	const NPC_SCIENCE_CLUB_MAN                  ; $75
	const NPC_LAD_5                             ; $76
	const NPC_SCIENCE_CLUB_GLASSES_KID          ; $77
	const NPC_SCIENCE_CLUB_TECH                 ; $78
	const NPC_WATER_CLUB_PAPPY                  ; $79
	const NPC_WATER_CLUB_LONGHAIRED_LASS        ; $7a
	const NPC_WATER_CLUB_LASS                   ; $7b
	const NPC_FIRE_CLUB_PUNK_GUY                ; $7c
	const NPC_FIRE_CLUB_MARTIAL_ARTIST          ; $7d
	const NPC_FIRE_CLUB_GAL                     ; $7e
	const NPC_LIGHTNING_CLUB_LASS               ; $7f
	const NPC_LIGHTNING_CLUB_PUNK_KID           ; $80
	const NPC_LIGHTNING_CLUB_LONGHAIRED_LASS    ; $81
	const NPC_LIGHTNING_CLUB_BRO                ; $82
	const NPC_PSYCHIC_CLUB_GLASSES_LAD          ; $83
	const NPC_PSYCHIC_CLUB_LASS                 ; $84
	const NPC_PSYCHIC_CLUB_CAPPED_LAD           ; $85
	const NPC_PSYCHIC_CLUB_GR_LASS              ; $86
	const NPC_GR_CLERK_5                        ; $87
	const NPC_TCG_AIRPORT_GR_SIS                ; $88
	const NPC_TCG_AIRPORT_MARTIAL_ARTIST        ; $89
	const NPC_CLERK_TCG_CHALLENGE_HALL_ENTRANCE ; $8a
	const NPC_TCG_CHALLENGE_HALL_CHAP           ; $8b
	const NPC_CUP_HOST                          ; $8c
	const NPC_TCG_CHALLENGE_HALL_PUNK           ; $8d
	const NPC_TCG_CHALLENGE_HALL_MAN            ; $8e
	const NPC_TCG_CHALLENGE_HALL_PAPPY          ; $8f
	const NPC_TCG_CHALLENGE_HALL_TECH           ; $90
	const NPC_TCG_CHALLENGE_HALL_GIRL           ; $91
	const NPC_TCG_CUP_CLERK_LEFT                ; $92
	const NPC_TCG_CUP_CLERK_RIGHT               ; $93
	const NPC_GR_CLERK_GR_AIRPORT_2             ; $94
	const NPC_GR_AIRPORT_GR_PAPPY               ; $95
	const NPC_GR_AIRPORT_GR_LASS                ; $96
	const NPC_GR_CLERK_GRASS_FORT               ; $97
	const NPC_GRASS_FORT_GR_GRUNT               ; $98
	const NPC_GRASS_FORT_GR_PAPPY               ; $99
	const NPC_GRASS_FORT_GR_LASS                ; $9a
	const NPC_GR_CLERK_LIGHTNING_FORT           ; $9b
	const NPC_LIGHTNING_FORT_GR_WOMAN           ; $9c
	const NPC_LIGHTNING_FORT_CHUBBY_KID         ; $9d
	const NPC_TAP                               ; $9e
	const NPC_GR_CLERK_FIRE_FORT                ; $9f
	const NPC_FIRE_FORT_YOUNGSTER               ; $a0
	const NPC_GR_CLERK_WATER_FORT               ; $a1
	const NPC_WATER_FORT_GR_GRANNY              ; $a2
	const NPC_WATER_FORT_GR_GAL                 ; $a3
	const NPC_GR_CLERK_FIGHTING_FORT            ; $a4
	const NPC_GR_CLERK_PSYCHIC_STRONGHOLD       ; $a5
	const NPC_PSYCHIC_STRONGHOLD_UNCAPPED_LAD   ; $a6
	const NPC_GR_PSYCHIC_STRONGHOLD_GR_LASS     ; $a7
	const NPC_GR_CLERK_13                       ; $a8
	const NPC_GAME_CENTER_TECH                  ; $a9
	const NPC_GAME_CENTER_GR_LASS               ; $aa
	const NPC_GAME_CENTER_GR_PAPPY              ; $ab
	const NPC_CAPTURED_AMY                      ; $ac
	const NPC_CAPTURED_SARA                     ; $ad
	const NPC_CAPTURED_AMANDA                   ; $ae
	const NPC_WARP_SPARKLES                     ; $af
	const NPC_YUI                               ; $b0
	const NPC_IMAKUNI_RED                       ; $b1
	const NPC_POKEMON_DOME_FAT_GUY              ; $b2
	const NPC_LAB_TECH_PC_GUIDE                 ; $b3
	const NPC_LAB_TECH_CLUB_GUIDE               ; $b4
	const NPC_LAB_TECH_BOOSTER_GUIDE            ; $b5
	const NPC_LAB_TECH_ROOM_GUIDE               ; $b6
	const NPC_LAB_TECH_AUTO_DECK_MACHINE_1      ; $b7
	const NPC_LAB_TECH_DECK_SAVE_MACHINE        ; $b8
	const NPC_LAB_TECH_COMPUTER_ROOM            ; $b9
	const NPC_LAB_TECH_AUTO_DECK_MACHINE_2      ; $ba
	const NPC_LAB_TECH_TRAINING_ROOM            ; $bb
	const NPC_GR_CLERK_CASTLE_RIGHT             ; $bc
	const NPC_GR_CLERK_CASTLE_LEFT              ; $bd
	const NPC_GR_CLERK_GAME_CENTER_PRIZE_DESK   ; $be
	const NPC_GR_CLERK_GAME_CENTER_CHIP_DESK    ; $bf
	const NPC_CHIP_GIRL                         ; $c0
	const NPC_CHIP_SECURITY                     ; $c1
	const NPC_ATTENDANT_BLACK_BOX               ; $c2
	const NPC_ATTENDANT_BILLS_PC                ; $c3
	const NPC_ATTENDANT_COIN_FLIP               ; $c4
	const NPC_ATTENDANT_1COIN_SLOT              ; $c5
	const NPC_ATTENDANT_5COIN_SLOT              ; $c6
	const NPC_ATTENDANT_CARD_DUNGEON            ; $c7
	const NPC_VOLCANO_SMOKE_TCG                 ; $c8
	const NPC_VOLCANO_SMOKE_GR                  ; $c9
	const NPC_CURSOR_TCG                        ; $ca
	const NPC_CURSOR_GR                         ; $cb
	const NPC_GR_CROSS                          ; $cc
	const NPC_GR_CASTLE_FLAG                    ; $cd
	const NPC_CHEST_CLOSED                      ; $ce
	const NPC_CHEST_OPENED                      ; $cf
	const NPC_GR_BLIMP_BEAM                     ; $d0
	const NPC_GR_BLIMP                          ; $d1
	const NPC_POD_DOORS                         ; $d2
	const NPC_WATER_FORT_GR_LAD                 ; $d3
	const NPC_LIGHTNING_CLUB_GR_LASS            ; $d4
	const NPC_POKEMON_DOME_GR_LASS              ; $d5
	const NPC_POKEMON_DOME_YOUNGSTER            ; $d6
	const NPC_POKEMON_DOME_SWIMMER              ; $d7
	const NPC_GAME_CENTER_GR_GAL                ; $d8
	const NPC_GAME_CENTER_CHUBBY_KID            ; $d9
	const NPC_GAME_CENTER_BOY                   ; $da
	const NPC_GAME_CENTER_FIXER                 ; $db
	const NPC_GAME_CENTER_GR_WOMAN              ; $dc
	const NPC_ISHIHARAS_VILLA_GR_GAL            ; $dd
	const NPC_GR_CLERK_CHALLENGE_HALL_ENTRANCE  ; $de
	const NPC_GR_CHALLENGE_HALL_GR_CHAP         ; $df
	const NPC_GR_CHALLENGE_HALL_GR_WOMAN        ; $e0
	const NPC_GR_STAFF                          ; $e1
	const NPC_GR_CUP_CLERK_LEFT                 ; $e2
	const NPC_GR_CUP_CLERK_RIGHT                ; $e3
	const NPC_RED_FORT_COIN                     ; $e4
	const NPC_BLUE_FORT_COIN                    ; $e5
	const NPC_WHITE_CASTLE_COIN                 ; $e6
	const NPC_PURPLE_CASTLE_COIN                ; $e7
	const NPC_STRONGHOLD_PLATFORM               ; $e8
	const_def -1
	const NPC_NONE                              ; $ff

; grand masters
	const_def
	const GRAND_MASTER_COURTNEY ; 0
	const GRAND_MASTER_STEVE    ; 1
	const GRAND_MASTER_JACK     ; 2
	const GRAND_MASTER_ROD      ; 3
DEF NUM_GRAND_MASTERS EQU const_value

; NPCDuelistPointers use this ordering
	const_def
	const NPC_DUELIST_SAM           ; $00
	const NPC_DUELIST_AARON         ; $01
	const NPC_DUELIST_NIKKI         ; $02
	const NPC_DUELIST_BRITTANY      ; $03
	const NPC_DUELIST_KRISTIN       ; $04
	const NPC_DUELIST_HEATHER       ; $05
	const NPC_DUELIST_AMY           ; $06
	const NPC_DUELIST_JOSHUA        ; $07
	const NPC_DUELIST_SARA          ; $08
	const NPC_DUELIST_AMANDA        ; $09
	const NPC_DUELIST_GENE          ; $0a
	const NPC_DUELIST_MATTHEW       ; $0b
	const NPC_DUELIST_RYAN          ; $0c
	const NPC_DUELIST_ANDREW        ; $0d
	const NPC_DUELIST_MITCH         ; $0e
	const NPC_DUELIST_MICHAEL       ; $0f
	const NPC_DUELIST_CHRIS         ; $10
	const NPC_DUELIST_JESSICA       ; $11
	const NPC_DUELIST_RICK          ; $12
	const NPC_DUELIST_DAVID         ; $13
	const NPC_DUELIST_JOSEPH        ; $14
	const NPC_DUELIST_ERIK          ; $15
	const NPC_DUELIST_KEN           ; $16
	const NPC_DUELIST_JOHN          ; $17
	const NPC_DUELIST_ADAM          ; $18
	const NPC_DUELIST_JONATHAN      ; $19
	const NPC_DUELIST_ISAAC         ; $1a
	const NPC_DUELIST_JENNIFER      ; $1b
	const NPC_DUELIST_NICHOLAS      ; $1c
	const NPC_DUELIST_BRANDON       ; $1d
	const NPC_DUELIST_MURRAY        ; $1e
	const NPC_DUELIST_ROBERT        ; $1f
	const NPC_DUELIST_DANIEL        ; $20
	const NPC_DUELIST_STEPHANIE     ; $21
	const NPC_DUELIST_ROD           ; $22
	const NPC_DUELIST_JACK          ; $23
	const NPC_DUELIST_STEVE         ; $24
	const NPC_DUELIST_COURTNEY      ; $25
	const NPC_DUELIST_MORINO        ; $26
	const NPC_DUELIST_MIYUKI        ; $27
	const NPC_DUELIST_YUTA          ; $28
	const NPC_DUELIST_MIDORI        ; $29
	const NPC_DUELIST_CATHERINE     ; $2a
	const NPC_DUELIST_ICHIKAWA      ; $2b
	const NPC_DUELIST_RENNA         ; $2c
	const NPC_DUELIST_HIDERO        ; $2d
	const NPC_DUELIST_SHOKO         ; $2e
	const NPC_DUELIST_YUKI          ; $2f
	const NPC_DUELIST_JES           ; $30
	const NPC_DUELIST_KANOKO        ; $31
	const NPC_DUELIST_AIRA          ; $32
	const NPC_DUELIST_SENTA         ; $33
	const NPC_DUELIST_MIYAJIMA      ; $34
	const NPC_DUELIST_KAMIYA        ; $35
	const NPC_DUELIST_GRACE         ; $36
	const NPC_DUELIST_GODA          ; $37
	const NPC_DUELIST_MAMI          ; $38
	const NPC_DUELIST_RYOKO         ; $39
	const NPC_DUELIST_YOSUKE        ; $3a
	const NPC_DUELIST_KEVIN         ; $3b
	const NPC_DUELIST_MIWA          ; $3c
	const NPC_DUELIST_SAMEJIMA      ; $3d
	const NPC_DUELIST_ISHII         ; $3e
	const NPC_DUELIST_NISHIJIMA     ; $3f
	const NPC_DUELIST_BIRURITCHI    ; $40
	const NPC_DUELIST_RUI           ; $41
	const NPC_DUELIST_KANZAKI       ; $42
	const NPC_DUELIST_RONALD        ; $43
	const NPC_DUELIST_IMAKUNI_BLACK ; $44
	const NPC_DUELIST_IMAKUNI_RED   ; $45
	const NPC_DUELIST_ISHIHARA      ; $46
	const NPC_DUELIST_TAP           ; $47
	const NPC_DUELIST_QUEEN         ; $48
	const NPC_DUELIST_ROOK          ; $49
	const NPC_DUELIST_BISHOP        ; $4a
	const NPC_DUELIST_KNIGHT        ; $4b
	const NPC_DUELIST_PAWN          ; $4c
	const NPC_DUELIST_TOBICHAN      ; $4d
	const NPC_DUELIST_EIJI          ; $4e
	const NPC_DUELIST_MAGICIAN      ; $4f
	const NPC_DUELIST_YUI           ; $50
	const NPC_DUELIST_TOSHIRON      ; $51
	const NPC_DUELIST_PIERROT       ; $52
	const NPC_DUELIST_ANNA          ; $53
	const NPC_DUELIST_DEE           ; $54
	const NPC_DUELIST_MASQUERADE    ; $55
	const NPC_DUELIST_GR_1          ; $56
	const NPC_DUELIST_GR_2          ; $57
	const NPC_DUELIST_GR_3          ; $58
	const NPC_DUELIST_GR_4          ; $59
DEF NUM_NPC_DUELIST_IDS EQU const_value

; NPC duelist struct constants
DEF MAX_NPC_DUELIST_DECKS EQU 5

RSRESET
DEF NPC_DUELIST_STRUCT_NPC_ID        RB ; $0
DEF NPC_DUELIST_STRUCT_DIALOG_NAME   RW ; $1
DEF NPC_DUELIST_STRUCT_LOCATION_NAME RW ; $3
DEF NPC_DUELIST_STRUCT_TITLE_NAME    RW ; $5
DEF NPC_DUELIST_STRUCT_DECKS         RB MAX_NPC_DUELIST_DECKS ; $7

DEF NPC_DUELIST_STRUCT_SIZE EQU _RS ; $c

; overworld npc struct constants
RSRESET
DEF OWNPCSTRUCT_NPC_ID       RB ; 0
DEF OWNPCSTRUCT_X_COORD      RB ; 1
DEF OWNPCSTRUCT_Y_COORD      RB ; 2
DEF OWNPCSTRUCT_DIRECTION    RB ; 3
DEF OWNPCSTRUCT_PRELOAD_FUNC RW ; 4

DEF OWNPCSTRUCT_LENGTH EQU _RS ; 6

; Aaron's steps, used in VAR_3B
	const_def 1
	const AARON_STEP_1 ; 1
	const AARON_STEP_2 ; 2
	const AARON_STEP_3 ; 3
	const AARON_STEP_4 ; 4
