	const_def
	const NPC_MARK          ; $00
	const NPC_MINT          ; $01
	const NPC_MARK_LINK     ; $02
	const NPC_MINT_LINK     ; $03
	const NPC_RONALD        ; $04
	const NPC_SAM           ; $05
	const NPC_AARON         ; $06
	const NPC_ISHIHARA      ; $07
	const NPC_IMAKUNI_BLACK ; $08
	const NPC_IMAKUNI_RED   ; $09
	const NPC_ISAAC         ; $0a
	const NPC_JENNIFER      ; $0b
	const NPC_NICHOLAS      ; $0c
	const NPC_BRANDON       ; $0d
	const NPC_MURRAY        ; $0e
	const NPC_STEPHANIE     ; $0f
	const NPC_DANIEL        ; $10
	const NPC_ROBERT        ; $11
	const NPC_GENE          ; $12
	const NPC_MATTHEW       ; $13
	const NPC_RYAN          ; $14
	const NPC_ANDREW        ; $15
	const NPC_MITCH         ; $16
	const NPC_MICHAEL       ; $17
	const NPC_CHRIS         ; $18
	const NPC_JESSICA       ; $19
	const NPC_NIKKI         ; $1a
	const NPC_BRITTANY      ; $1b
	const NPC_KRISTIN       ; $1c
	const NPC_HEATHER       ; $1d
	const NPC_RICK          ; $1e
	const NPC_JOSEPH        ; $1f
	const NPC_DAVID         ; $20
	const NPC_ERIK          ; $21
	const NPC_AMY           ; $22
	const NPC_JOSHUA        ; $23
	const NPC_SARA          ; $24
	const NPC_AMANDA        ; $25
	const NPC_KEN           ; $26
	const NPC_JOHN          ; $27
	const NPC_ADAM          ; $28
	const NPC_JONATHAN      ; $29
	const NPC_COURTNEY      ; $2a
	const NPC_STEVE         ; $2b
	const NPC_JACK          ; $2c
	const NPC_ROD           ; $2d
	const NPC_EIJI          ; $2e
	const NPC_MAGICIAN      ; $2f
	const NPC_YUI           ; $30
	const NPC_TOSHIRON      ; $31
	const NPC_PIERROT       ; $32
	const NPC_ANNA          ; $33
	const NPC_DEE           ; $34
	const NPC_MASQUERADE    ; $35
	const NPC_PAWN          ; $36
	const NPC_KNIGHT        ; $37
	const NPC_BISHOP        ; $38
	const NPC_ROOK          ; $39
	const NPC_QUEEN         ; $3a
	const NPC_GR_1          ; $3b
	const NPC_GR_2          ; $3c
	const NPC_GR_3          ; $3d
	const NPC_GR_4          ; $3e
	const NPC_MIDORI        ; $3f
	const NPC_YUTA          ; $40
	const NPC_MIYUKI        ; $41
	const NPC_MORINO        ; $42
	const NPC_RENNA         ; $43
	const NPC_ICHIKAWA      ; $44
	const NPC_CATHERINE     ; $45
	const NPC_TAP           ; $46
	const NPC_JES           ; $47
	const NPC_YUKI          ; $48
	const NPC_SHOKO         ; $49
	const NPC_HIDERO        ; $4a
	const NPC_MIYAJIMA      ; $4b
	const NPC_SENTA         ; $4c
	const NPC_AIRA          ; $4d
	const NPC_KANOKO        ; $4e
	const NPC_GODA          ; $4f
	const NPC_GRACE         ; $50
	const NPC_KAMIYA        ; $51
	const NPC_MIWA          ; $52
	const NPC_KEVIN         ; $53
	const NPC_YOSUKE        ; $54
	const NPC_RYOKO         ; $55
	const NPC_MAMI          ; $56
	const NPC_NISHIJIMA     ; $57
	const NPC_ISHII         ; $58
	const NPC_SAMEJIMA      ; $59
	const NPC_KANZAKI       ; $5a
	const NPC_RUI           ; $5b
	const NPC_BIRURITCHI    ; $5c
	const NPC_GR_X          ; $5d
	const NPC_TOBICHAN      ; $5e
	const NPC_DR_MASON      ; $5f
DEF NUM_NPC_IDS EQU const_value

; NPCDuelistPointers use this ordering
	const_def
	const NPC_DUELIST_SAM                  ; $00
	const NPC_DUELIST_AARON                ; $01
	const NPC_DUELIST_NIKKI                ; $02
	const NPC_DUELIST_BRITTANY             ; $03
	const NPC_DUELIST_KRISTIN              ; $04
	const NPC_DUELIST_HEATHER              ; $05
	const NPC_DUELIST_AMY                  ; $06
	const NPC_DUELIST_JOSHUA               ; $07
	const NPC_DUELIST_SARA                 ; $08
	const NPC_DUELIST_AMANDA               ; $09
	const NPC_DUELIST_GENE                 ; $0a
	const NPC_DUELIST_MATTHEW              ; $0b
	const NPC_DUELIST_RYAN                 ; $0c
	const NPC_DUELIST_ANDREW               ; $0d
	const NPC_DUELIST_MITCH                ; $0e
	const NPC_DUELIST_MICHAEL              ; $0f
	const NPC_DUELIST_CHRIS                ; $10
	const NPC_DUELIST_JESSICA              ; $11
	const NPC_DUELIST_RICK                 ; $12
	const NPC_DUELIST_DAVID                ; $13
	const NPC_DUELIST_JOSEPH               ; $14
	const NPC_DUELIST_ERIK                 ; $15
	const NPC_DUELIST_KEN                  ; $16
	const NPC_DUELIST_JOHN                 ; $17
	const NPC_DUELIST_ADAM                 ; $18
	const NPC_DUELIST_JONATHAN             ; $19
	const NPC_DUELIST_ISAAC                ; $1a
	const NPC_DUELIST_JENNIFER             ; $1b
	const NPC_DUELIST_NICHOLAS             ; $1c
	const NPC_DUELIST_BRANDON              ; $1d
	const NPC_DUELIST_MURRAY               ; $1e
	const NPC_DUELIST_ROBERT               ; $1f
	const NPC_DUELIST_DANIEL               ; $20
	const NPC_DUELIST_STEPHANIE            ; $21
	const NPC_DUELIST_ROD                  ; $22
	const NPC_DUELIST_JACK                 ; $23
	const NPC_DUELIST_STEVE                ; $24
	const NPC_DUELIST_COURTNEY             ; $25
	const NPC_DUELIST_MORINO               ; $26
	const NPC_DUELIST_MIYUKI               ; $27
	const NPC_DUELIST_YUTA                 ; $28
	const NPC_DUELIST_MIDORI               ; $29
	const NPC_DUELIST_CATHERINE            ; $2a
	const NPC_DUELIST_ICHIKAWA             ; $2b
	const NPC_DUELIST_RENNA                ; $2c
	const NPC_DUELIST_HIDERO               ; $2d
	const NPC_DUELIST_SHOKO                ; $2e
	const NPC_DUELIST_YUKI                 ; $2f
	const NPC_DUELIST_JES                  ; $30
	const NPC_DUELIST_KANOKO               ; $31
	const NPC_DUELIST_AIRA                 ; $32
	const NPC_DUELIST_SENTA                ; $33
	const NPC_DUELIST_MIYAJIMA             ; $34
	const NPC_DUELIST_KAMIYA               ; $35
	const NPC_DUELIST_GRACE                ; $36
	const NPC_DUELIST_GODA                 ; $37
	const NPC_DUELIST_MAMI                 ; $38
	const NPC_DUELIST_RYOKO                ; $39
	const NPC_DUELIST_YOSUKE               ; $3a
	const NPC_DUELIST_KEVIN                ; $3b
	const NPC_DUELIST_MIWA                 ; $3c
	const NPC_DUELIST_SAMEJIMA             ; $3d
	const NPC_DUELIST_ISHII                ; $3e
	const NPC_DUELIST_NISHIJIMA            ; $3f
	const NPC_DUELIST_BIRURITCHI           ; $40
	const NPC_DUELIST_RUI                  ; $41
	const NPC_DUELIST_KANZAKI              ; $42
	const NPC_DUELIST_RONALD               ; $43
	const NPC_DUELIST_IMAKUNI_BLACK        ; $44
	const NPC_DUELIST_IMAKUNI_RED          ; $45
	const NPC_DUELIST_ISHIHARA             ; $46
	const NPC_DUELIST_TAP                  ; $47
	const NPC_DUELIST_QUEEN                ; $48
	const NPC_DUELIST_ROOK                 ; $49
	const NPC_DUELIST_BISHOP               ; $4a
	const NPC_DUELIST_KNIGHT               ; $4b
	const NPC_DUELIST_PAWN                 ; $4c
	const NPC_DUELIST_TOBICHAN             ; $4d
	const NPC_DUELIST_EIJI                 ; $4e
	const NPC_DUELIST_MAGICIAN             ; $4f
	const NPC_DUELIST_YUI                  ; $50
	const NPC_DUELIST_TOSHIRON             ; $51
	const NPC_DUELIST_PIERROT              ; $52
	const NPC_DUELIST_ANNA                 ; $53
	const NPC_DUELIST_DEE                  ; $54
	const NPC_DUELIST_MASQUERADE           ; $55
	const NPC_DUELIST_GR_1                 ; $56
	const NPC_DUELIST_GR_2                 ; $57
	const NPC_DUELIST_GR_3                 ; $58
	const NPC_DUELIST_GR_4                 ; $59
DEF NUM_NPC_DUELIST_IDS EQU const_value

; NPC duelist struct constants
DEF MAX_NPC_DUELIST_DECKS EQU 5

RSRESET
DEF NPC_DUELIST_STRUCT_OW_OBJ        RB ; $0
DEF NPC_DUELIST_STRUCT_DIALOG_NAME   RW ; $1
DEF NPC_DUELIST_STRUCT_LOCATION_NAME RW ; $3
DEF NPC_DUELIST_STRUCT_TITLE_NAME    RW ; $5
DEF NPC_DUELIST_STRUCT_DECKS         RB MAX_NPC_DUELIST_DECKS ; $7

DEF NPC_DUELIST_STRUCT_SIZE EQU _RS ; $c
