	const_def
	const NPC_MARK          ; $00
	const NPC_MINT          ; $01
	const NPC_MARK_LINK     ; $02
	const NPC_MINT_LINK     ; $03
	const NPC_RONALD        ; $04
	const NPC_SAM           ; $05
	const NPC_AARON         ; $06
	const NPC_ISHIHARA      ; $07
	const NPC_IMAKUNI_BLACK ; $08
	const NPC_IMAKUNI_RED   ; $09
	const NPC_ISAAC         ; $0a
	const NPC_JENNIFER      ; $0b
	const NPC_NICHOLAS      ; $0c
	const NPC_BRANDON       ; $0d
	const NPC_MURRAY        ; $0e
	const NPC_STEPHANIE     ; $0f
	const NPC_DANIEL        ; $10
	const NPC_ROBERT        ; $11
	const NPC_GENE          ; $12
	const NPC_MATTHEW       ; $13
	const NPC_RYAN          ; $14
	const NPC_ANDREW        ; $15
	const NPC_MITCH         ; $16
	const NPC_MICHAEL       ; $17
	const NPC_CHRIS         ; $18
	const NPC_JESSICA       ; $19
	const NPC_NIKKI         ; $1a
	const NPC_BRITTANY      ; $1b
	const NPC_KRISTIN       ; $1c
	const NPC_HEATHER       ; $1d
	const NPC_RICK          ; $1e
	const NPC_JOSEPH        ; $1f
	const NPC_DAVID         ; $20
	const NPC_ERIK          ; $21
	const NPC_AMY           ; $22
	const NPC_JOSHUA        ; $23
	const NPC_SARA          ; $24
	const NPC_AMANDA        ; $25
	const NPC_KEN           ; $26
	const NPC_JOHN          ; $27
	const NPC_ADAM          ; $28
	const NPC_JONATHAN      ; $29
	const NPC_COURTNEY      ; $2a
	const NPC_STEVE         ; $2b
	const NPC_JACK          ; $2c
	const NPC_ROD           ; $2d
	const NPC_EIJI          ; $2e
	const NPC_MAGICIAN      ; $2f
	const NPC_YUI           ; $30
	const NPC_TOSHIRON      ; $31
	const NPC_PIERROT       ; $32
	const NPC_ANNA          ; $33
	const NPC_DEE           ; $34
	const NPC_MASQUERADE    ; $35
	const NPC_PAWN          ; $36
	const NPC_KNIGHT        ; $37
	const NPC_BISHOP        ; $38
	const NPC_ROOK          ; $39
	const NPC_QUEEN         ; $3a
	const NPC_GR_1          ; $3b
	const NPC_GR_2          ; $3c
	const NPC_GR_3          ; $3d
	const NPC_GR_4          ; $3e
	const NPC_MIDORI        ; $3f
	const NPC_YUUTA         ; $40
	const NPC_MIYUKI        ; $41
	const NPC_MORINO        ; $42
	const NPC_RENNA         ; $43
	const NPC_ICHIKAWA      ; $44
	const NPC_CATHERINE     ; $45
	const NPC_TAP           ; $46
	const NPC_JES           ; $47
	const NPC_YUKI          ; $48
	const NPC_SHOKO         ; $49
	const NPC_HIDERO        ; $4a
	const NPC_MIYAJIMA      ; $4b
	const NPC_SENTA         ; $4c
	const NPC_AIRA          ; $4d
	const NPC_KANOKO        ; $4e
	const NPC_GODA          ; $4f
	const NPC_GRACE         ; $50
	const NPC_KAMIYA        ; $51
	const NPC_MIWA          ; $52
	const NPC_KEVIN         ; $53
	const NPC_YOSUKE        ; $54
	const NPC_RYOKO         ; $55
	const NPC_MAMI          ; $56
	const NPC_NISHIJIMA     ; $57
	const NPC_ISHII         ; $58
	const NPC_SAMEJIMA      ; $59
	const NPC_KANZAKI       ; $5a
	const NPC_RUI           ; $5b
	const NPC_BIRURITCHI    ; $5c
	const NPC_GR_X          ; $5d
	const NPC_TOBI_CHAN     ; $5e
	const NPC_DR_MASON      ; $5f
DEF NUM_NPC_IDS EQU const_value
