	const_def
	const OW_PLAYERM       ; $00
	const OW_PLAYERF       ; $01
	const OW_DRMASON       ; $02
	const OW_RONALD        ; $03
	const OW_ISHIHARA      ; $04
	const OW_IMAKUNI1      ; $05
	const OW_TECH1         ; $06
	const OW_TECH2         ; $07
	const OW_PAPPY1        ; $08
	const OW_GENE          ; $09
	const OW_MANIA1        ; $0a
	const OW_YOUNGSTER1    ; $0b
	const OW_MAN1          ; $0c
	const OW_MITCH         ; $0d
	const OW_MANIA2        ; $0e
	const OW_MANIA3        ; $0f
	const OW_LASS1         ; $10
	const OW_NIKKI         ; $11
	const OW_GIRL1         ; $12
	const OW_LASS2         ; $13
	const OW_LASS3         ; $14
	const OW_RICK          ; $15
	const OW_TECH3         ; $16
	const OW_TECH4         ; $17
	const OW_TECH5         ; $18
	const OW_AMY1          ; $19
	const OW_AMY2          ; $1a
	const OW_JOSHUA1       ; $1b
	const OW_SARA          ; $1c
	const OW_AMANDA        ; $1d
	const OW_KEN           ; $1e
	const OW_LAD1          ; $1f
	const OW_SPECS1        ; $20
	const OW_YOUNGSTER2    ; $21
	const OW_ISAAC         ; $22
	const OW_GIRL2         ; $23
	const OW_HOOD1         ; $24
	const OW_HOOD2         ; $25
	const OW_MURRAY        ; $26
	const OW_YOUNGSTER3    ; $27
	const OW_LAD2          ; $28
	const OW_GIRL3         ; $29
	const OW_COURTNEY      ; $2a
	const OW_STEVE1        ; $2b
	const OW_JACK          ; $2c
	const OW_ROD           ; $2d
	const OW_UNK_2E        ; $2e
	const OW_UNK_2F        ; $2f
	const OW_UNK_30        ; $30
	const OW_UNK_31        ; $31
	const OW_UNK_32        ; $32
	const OW_GRYOUNGSTER1  ; $33
	const OW_UNK_34        ; $34
	const OW_UNK_35        ; $35
	const OW_UNK_36        ; $36
	const OW_UNK_37        ; $37
	const OW_GRLASS1       ; $38
	const OW_UNK_39        ; $39
	const OW_UNK_3A        ; $3a
	const OW_UNK_3B        ; $3b
	const OW_GRGRANNY1     ; $3c
	const OW_UNK_3D        ; $3d
	const OW_UNK_3E        ; $3e
	const OW_UNK_3F        ; $3f
	const OW_UNK_40        ; $40
	const OW_UNK_41        ; $41
	const OW_SPECS2        ; $42
	const OW_UNK_43        ; $43
	const OW_JOSHUA2       ; $44
	const OW_UNK_45        ; $45
	const OW_UNK_46        ; $46
	const OW_UNK_47        ; $47
	const OW_UNK_48        ; $48
	const OW_UNK_49        ; $49
	const OW_GAL1          ; $4a
	const OW_UNK_4B        ; $4b
	const OW_UNK_4C        ; $4c
	const OW_UNK_4D        ; $4d
	const OW_UNK_4E        ; $4e
	const OW_UNK_4F        ; $4f
	const OW_UNK_50        ; $50
	const OW_UNK_51        ; $51
	const OW_UNK_52        ; $52
	const OW_UNK_53        ; $53
	const OW_UNK_54        ; $54
	const OW_UNK_55        ; $55
	const OW_UNK_56        ; $56
	const OW_STEVE2        ; $57
	const OW_UNK_58        ; $58
	const OW_STEVE3        ; $59
	const OW_UNK_5A        ; $5a
	const OW_UNK_5B        ; $5b
	const OW_STEVE4        ; $5c
	const OW_UNK_5D        ; $5d
	const OW_UNK_5E        ; $5e
	const OW_UNK_5F        ; $5f
	const OW_UNK_60        ; $60
	const OW_UNK_61        ; $61
	const OW_UNK_62        ; $62
	const OW_UNK_63        ; $63
	const OW_CLERK1        ; $64
	const OW_CLERK2        ; $65
	const OW_GRCLERK1      ; $66
	const OW_GRCLERK2      ; $67
	const OW_GRCLERK3      ; $68
	const OW_GRCLERK4      ; $69
	const OW_LASS4         ; $6a
	const OW_WOMAN         ; $6b
	const OW_CHAP1         ; $6c
	const OW_LAD3          ; $6d
	const OW_PAPPY2        ; $6e
	const OW_SPECS3        ; $6f
	const OW_LAD4          ; $70
	const OW_GIRL4         ; $71
	const OW_GRANNY        ; $72
	const OW_LASS5         ; $73
	const OW_GIRL5         ; $74
	const OW_MAN2          ; $75
	const OW_LAD5          ; $76
	const OW_SPECS4        ; $77
	const OW_TECH6         ; $78
	const OW_PAPPY3        ; $79
	const OW_LASS6         ; $7a
	const OW_LASS7         ; $7b
	const OW_HOOD3         ; $7c
	const OW_MANIA4        ; $7d
	const OW_GAL2          ; $7e
	const OW_LASS8         ; $7f
	const OW_HOOD4         ; $80
	const OW_LASS9         ; $81
	const OW_CHAP2         ; $82
	const OW_SPECS5        ; $83
	const OW_LASS10        ; $84
	const OW_LAD6          ; $85
	const OW_GRLASS2       ; $86
	const OW_GRCLERK5      ; $87
	const OW_GRGAL1        ; $88
	const OW_MANIA5        ; $89
	const OW_CLERK3        ; $8a
	const OW_CHAP3         ; $8b
	const OW_GAL3          ; $8c
	const OW_HOOD5         ; $8d
	const OW_MAN3          ; $8e
	const OW_PAPPY4        ; $8f
	const OW_TECH7         ; $90
	const OW_GIRL6         ; $91
	const OW_LASS11        ; $92
	const OW_LASS12        ; $93
	const OW_GRCLERK6      ; $94
	const OW_UNK_95        ; $95
	const OW_GRLASS3       ; $96
	const OW_GRCLERK7      ; $97
	const OW_GRYOUNGSTER2  ; $98
	const OW_UNK_99        ; $99
	const OW_GRLASS4       ; $9a
	const OW_GRCLERK8      ; $9b
	const OW_GRWOMAN1      ; $9c
	const OW_BUTCH1        ; $9d
	const OW_CHAP4         ; $9e
	const OW_GRCLERK9      ; $9f
	const OW_YOUNGSTER4    ; $a0
	const OW_GRCLERK10     ; $a1
	const OW_GRGRANNY2     ; $a2
	const OW_GRGAL2        ; $a3
	const OW_GRCLERK11     ; $a4
	const OW_GRCLERK12     ; $a5
	const OW_MANIA6        ; $a6
	const OW_GRLASS5       ; $a7
	const OW_GRCLERK13     ; $a8
	const OW_TECH8         ; $a9
	const OW_GRLASS6       ; $aa
	const OW_UNK_AB        ; $ab
	const OW_UNK_AC        ; $ac
	const OW_UNK_AD        ; $ad
	const OW_UNK_AE        ; $ae
	const OW_UNK_AF        ; $af
	const OW_LASS13        ; $b0
	const OW_IMAKUNI2      ; $b1
	const OW_BUTCH2        ; $b2
	const OW_TECH9         ; $b3
	const OW_TECH10        ; $b4
	const OW_TECH11        ; $b5
	const OW_TECH12        ; $b6
	const OW_TECH13        ; $b7
	const OW_TECH14        ; $b8
	const OW_TECH15        ; $b9
	const OW_TECH16        ; $ba
	const OW_TECH17        ; $bb
	const OW_GRCLERK14     ; $bc
	const OW_GRCLERK15     ; $bd
	const OW_GRCLERK16     ; $be
	const OW_GRCLERK17     ; $bf
	const OW_UNK_C0        ; $c0
	const OW_UNK_C1        ; $c1
	const OW_UNK_C2        ; $c2
	const OW_UNK_C3        ; $c3
	const OW_UNK_C4        ; $c4
	const OW_UNK_C5        ; $c5
	const OW_UNK_C6        ; $c6
	const OW_UNK_C7        ; $c7
	const OW_UNK_C8        ; $c8
	const OW_UNK_C9        ; $c9
	const OW_UNK_CA        ; $ca
	const OW_UNK_CB        ; $cb
	const OW_UNK_CC        ; $cc
	const OW_UNK_CD        ; $cd
	const OW_UNK_CE        ; $ce
	const OW_UNK_CF        ; $cf
	const OW_GRSHIPBEAM    ; $d0
	const OW_GRSHIP        ; $d1
	const OW_UNK_D2        ; $d2
	const OW_GRYOUNGSTER3  ; $d3
	const OW_GRLASS7       ; $d4
	const OW_GRLASS8       ; $d5
	const OW_YOUNGSTER5    ; $d6
	const OW_SWIMMER       ; $d7
	const OW_GRGAL3        ; $d8
	const OW_BUTCH3        ; $d9
	const OW_MANIA7        ; $da
	const OW_UNK_DB        ; $db
	const OW_GRWOMAN2      ; $dc
	const OW_GRGAL4        ; $dd
	const OW_GRCLERK18     ; $de
	const OW_UNK_DF        ; $df
	const OW_GRWOMAN3      ; $e0
	const OW_UNK_E1        ; $e1
	const OW_LASS14        ; $e2
	const OW_LASS15        ; $e3
	const OW_UNK_E4        ; $e4
	const OW_UNK_E5        ; $e5
	const OW_UNK_E6        ; $e6
	const OW_UNK_E7        ; $e7
	const OW_UNK_E8        ; $e8

; OW sprites represent what graphics
; are associated with an OW object
	const_def
	const OWSPRITE_PLAYERM     ; $00
	const OWSPRITE_PLAYERF     ; $01
	const OWSPRITE_DRMASON     ; $02
	const OWSPRITE_RONALD      ; $03
	const OWSPRITE_ISHIHARA    ; $04
	const OWSPRITE_IMAKUNI1    ; $05
	const OWSPRITE_IMAKUNI2    ; $06
	const OWSPRITE_ISAAC       ; $07
	const OWSPRITE_MURRAY      ; $08
	const OWSPRITE_GENE        ; $09
	const OWSPRITE_MITCH       ; $0a
	const OWSPRITE_NIKKI       ; $0b
	const OWSPRITE_RICK        ; $0c
	const OWSPRITE_AMY1        ; $0d
	const OWSPRITE_AMY2        ; $0e
	const OWSPRITE_SARA        ; $0f
	const OWSPRITE_AMANDA      ; $10
	const OWSPRITE_KEN         ; $11
	const OWSPRITE_COURTNEY    ; $12
	const OWSPRITE_STEVE1      ; $13
	const OWSPRITE_JACK        ; $14
	const OWSPRITE_ROD         ; $15
	const OWSPRITE_STEVE2      ; $16
	const OWSPRITE_17          ; $17
	const OWSPRITE_STEVE3      ; $18
	const OWSPRITE_19          ; $19
	const OWSPRITE_1A          ; $1a
	const OWSPRITE_STEVE4      ; $1b
	const OWSPRITE_1C          ; $1c
	const OWSPRITE_1D          ; $1d
	const OWSPRITE_1E          ; $1e
	const OWSPRITE_1F          ; $1f
	const OWSPRITE_20          ; $20
	const OWSPRITE_21          ; $21
	const OWSPRITE_22          ; $22
	const OWSPRITE_23          ; $23
	const OWSPRITE_24          ; $24
	const OWSPRITE_25          ; $25
	const OWSPRITE_26          ; $26
	const OWSPRITE_27          ; $27
	const OWSPRITE_28          ; $28
	const OWSPRITE_29          ; $29
	const OWSPRITE_2A          ; $2a
	const OWSPRITE_2B          ; $2b
	const OWSPRITE_2C          ; $2c
	const OWSPRITE_2D          ; $2d
	const OWSPRITE_2E          ; $2e
	const OWSPRITE_2F          ; $2f
	const OWSPRITE_30          ; $30
	const OWSPRITE_31          ; $31
	const OWSPRITE_32          ; $32
	const OWSPRITE_33          ; $33
	const OWSPRITE_34          ; $34
	const OWSPRITE_35          ; $35
	const OWSPRITE_36          ; $36
	const OWSPRITE_37          ; $37
	const OWSPRITE_38          ; $38
	const OWSPRITE_39          ; $39
	const OWSPRITE_3A          ; $3a
	const OWSPRITE_3B          ; $3b
	const OWSPRITE_3C          ; $3c
	const OWSPRITE_3D          ; $3d
	const OWSPRITE_3E          ; $3e
	const OWSPRITE_3F          ; $3f
	const OWSPRITE_40          ; $40
	const OWSPRITE_41          ; $41
	const OWSPRITE_YOUNGSTER   ; $42
	const OWSPRITE_LAD         ; $43
	const OWSPRITE_SPECS       ; $44
	const OWSPRITE_BUTCH       ; $45
	const OWSPRITE_MANIA       ; $46
	const OWSPRITE_JOSHUA      ; $47
	const OWSPRITE_HOOD        ; $48
	const OWSPRITE_TECH        ; $49
	const OWSPRITE_CHAP        ; $4a
	const OWSPRITE_MAN         ; $4b
	const OWSPRITE_PAPPY       ; $4c
	const OWSPRITE_4D          ; $4d
	const OWSPRITE_GRYOUNGSTER ; $4e
	const OWSPRITE_4F          ; $4f
	const OWSPRITE_50          ; $50
	const OWSPRITE_51          ; $51
	const OWSPRITE_52          ; $52
	const OWSPRITE_53          ; $53
	const OWSPRITE_GIRL        ; $54
	const OWSPRITE_LASS1       ; $55
	const OWSPRITE_LASS2       ; $56
	const OWSPRITE_LASS3       ; $57
	const OWSPRITE_SWIMMER     ; $58
	const OWSPRITE_GAL         ; $59
	const OWSPRITE_WOMAN       ; $5a
	const OWSPRITE_GRANNY      ; $5b
	const OWSPRITE_5C          ; $5c
	const OWSPRITE_GRLASS1     ; $5d
	const OWSPRITE_GRGAL       ; $5e
	const OWSPRITE_GRWOMAN     ; $5f
	const OWSPRITE_GRGRANNY    ; $60
	const OWSPRITE_61          ; $61
	const OWSPRITE_62          ; $62
	const OWSPRITE_CLERK       ; $63
	const OWSPRITE_GRCLERK     ; $64
	const OWSPRITE_65          ; $65
	const OWSPRITE_66          ; $66
	const OWSPRITE_67          ; $67
	const OWSPRITE_68          ; $68
	const OWSPRITE_GRSHIP      ; $69
	const OWSPRITE_GRSHIPBEAM  ; $6a
	const OWSPRITE_6B          ; $6b
	const OWSPRITE_6C          ; $6c
	const OWSPRITE_6D          ; $6d
	const OWSPRITE_6E          ; $6e
	const OWSPRITE_6F          ; $6f
	const OWSPRITE_70          ; $70
	const OWSPRITE_71          ; $71
	const OWSPRITE_72          ; $72
	const OWSPRITE_73          ; $73
	const OWSPRITE_74          ; $74
	const OWSPRITE_75          ; $75
	const OWSPRITE_76          ; $76
	const OWSPRITE_77          ; $77
	const OWSPRITE_78          ; $78

	const_def
	const OWFRAMEGROUP_00 ; $00
	const OWFRAMEGROUP_01 ; $01
	const OWFRAMEGROUP_02 ; $02
	const OWFRAMEGROUP_03 ; $03
	const OWFRAMEGROUP_04 ; $04
	const OWFRAMEGROUP_05 ; $05
	const OWFRAMEGROUP_06 ; $06
	const OWFRAMEGROUP_07 ; $07
	const OWFRAMEGROUP_08 ; $08
	const OWFRAMEGROUP_09 ; $09
	const OWFRAMEGROUP_0A ; $0a
	const OWFRAMEGROUP_0B ; $0b
	const OWFRAMEGROUP_0C ; $0c
	const OWFRAMEGROUP_0D ; $0d
	const OWFRAMEGROUP_0E ; $0e
	const OWFRAMEGROUP_0F ; $0f
	const OWFRAMEGROUP_10 ; $10
	const OWFRAMEGROUP_11 ; $11
	const OWFRAMEGROUP_12 ; $12
	const OWFRAMEGROUP_13 ; $13
	const OWFRAMEGROUP_14 ; $14
	const OWFRAMEGROUP_15 ; $15
	const OWFRAMEGROUP_16 ; $16
	const OWFRAMEGROUP_17 ; $17
	const OWFRAMEGROUP_18 ; $18
	const OWFRAMEGROUP_19 ; $19
	const OWFRAMEGROUP_1A ; $1a
	const OWFRAMEGROUP_1B ; $1b
	const OWFRAMEGROUP_1C ; $1c
	const OWFRAMEGROUP_1D ; $1d
	const OWFRAMEGROUP_1E ; $1e
	const OWFRAMEGROUP_1F ; $1f
	const OWFRAMEGROUP_20 ; $20
	const OWFRAMEGROUP_21 ; $21
	const OWFRAMEGROUP_22 ; $22
	const OWFRAMEGROUP_23 ; $23
	const OWFRAMEGROUP_24 ; $24
	const OWFRAMEGROUP_25 ; $25
	const OWFRAMEGROUP_26 ; $26
	const OWFRAMEGROUP_27 ; $27
	const OWFRAMEGROUP_28 ; $28
	const OWFRAMEGROUP_29 ; $29
	const OWFRAMEGROUP_2A ; $2a
	const OWFRAMEGROUP_2B ; $2b
	const OWFRAMEGROUP_2C ; $2c
	const OWFRAMEGROUP_2D ; $2d
	const OWFRAMEGROUP_2E ; $2e
	const OWFRAMEGROUP_2F ; $2f
	const OWFRAMEGROUP_30 ; $30
	const OWFRAMEGROUP_31 ; $31
	const OWFRAMEGROUP_32 ; $32
	const OWFRAMEGROUP_33 ; $33

DEF MAX_NUM_OW_OBJECTS EQU 10

RSRESET
OWOBJSTRUCT_FLAGS           RB ; $0
OWOBJSTRUCT_ID              RB ; $1
OWOBJSTRUCT_ANIM_PTR        RW ; $2
OWOBJSTRUCT_4               RB ; $4
OWOBJSTRUCT_5               RB ; $5
OWOBJSTRUCT_6               RW ; $6
DEF OWOBJSTRUCT_LENGTH EQU _RS

; OWOBJSTRUCT_FLAGS bit flags
	const_def 7
	const ACTIVE_OBJ_F ; 7

ACTIVE_OBJ EQU 1 << ACTIVE_OBJ_F
