	const_def
	const OW_MARK                  ; $00
	const OW_MINT                  ; $01
	const OW_DR_MASON              ; $02
	const OW_RONALD                ; $03
	const OW_ISHIHARA              ; $04
	const OW_IMAKUNI_BLACK         ; $05
	const OW_SAM                   ; $06
	const OW_AARON                 ; $07
	const OW_PAPPY_1               ; $08
	const OW_GENE                  ; $09
	const OW_MATTHEW               ; $0a
	const OW_RYAN                  ; $0b
	const OW_ANDREW                ; $0c
	const OW_MITCH                 ; $0d
	const OW_MICHAEL               ; $0e
	const OW_CHRIS                 ; $0f
	const OW_JESSICA               ; $10
	const OW_NIKKI                 ; $11
	const OW_BRITTANY              ; $12
	const OW_KRISTIN               ; $13
	const OW_HEATHER               ; $14
	const OW_RICK                  ; $15
	const OW_DAVID                 ; $16
	const OW_JOSEPH                ; $17
	const OW_ERIK                  ; $18
	const OW_AMY                   ; $19
	const OW_AMY_LOUNGE            ; $1a
	const OW_JOSHUA                ; $1b
	const OW_SARA                  ; $1c
	const OW_AMANDA                ; $1d
	const OW_KEN                   ; $1e
	const OW_JOHN                  ; $1f
	const OW_ADAM                  ; $20
	const OW_JONATHAN              ; $21
	const OW_ISAAC                 ; $22
	const OW_JENNIFER              ; $23
	const OW_NICHOLAS              ; $24
	const OW_BRANDON               ; $25
	const OW_MURRAY                ; $26
	const OW_ROBERT                ; $27
	const OW_DANIEL                ; $28
	const OW_STEPHANIE             ; $29
	const OW_COURTNEY              ; $2a
	const OW_STEVE                 ; $2b
	const OW_JACK                  ; $2c
	const OW_ROD                   ; $2d
	const OW_GR_1                  ; $2e
	const OW_GR_2                  ; $2f
	const OW_GR_3                  ; $30
	const OW_GR_4                  ; $31
	const OW_GR_5                  ; $32
	const OW_GR_LAD_1              ; $33
	const OW_MIDORI                ; $34
	const OW_YUTA                  ; $35
	const OW_MIYUKI                ; $36
	const OW_MORINO                ; $37
	const OW_GR_LASS_1             ; $38
	const OW_RENNA                 ; $39
	const OW_ICHIKAWA              ; $3a
	const OW_CATHERINE             ; $3b
	const OW_GR_GRANNY_1           ; $3c
	const OW_MIYAJIMA_ALT          ; $3d
	const OW_JES                   ; $3e
	const OW_YUKI                  ; $3f
	const OW_SHOKO                 ; $40
	const OW_HIDERO                ; $41
	const OW_SPECS_2               ; $42
	const OW_MIYAJIMA              ; $43
	const OW_SENTA                 ; $44
	const OW_AIRA                  ; $45
	const OW_KANOKO                ; $46
	const OW_GODA                  ; $47
	const OW_GRACE                 ; $48
	const OW_KAMIYA                ; $49
	const OW_GAL_1                 ; $4a
	const OW_MIWA                  ; $4b
	const OW_KEVIN                 ; $4c
	const OW_YOSUKE                ; $4d
	const OW_RYOKO                 ; $4e
	const OW_MAMI                  ; $4f
	const OW_NISHIJIMA             ; $50
	const OW_ISHII                 ; $51
	const OW_SAMEJIMA              ; $52
	const OW_KANZAKI               ; $53
	const OW_RUI                   ; $54
	const OW_BIRURITCHI            ; $55
	const OW_TOBICHAN              ; $56
	const OW_EIJI                  ; $57
	const OW_MAGICIAN              ; $58
	const OW_TOSHIRON              ; $59
	const OW_PIERROT               ; $5a
	const OW_ANNA                  ; $5b
	const OW_DEE                   ; $5c
	const OW_MASQUERADE            ; $5d
	const OW_PAWN                  ; $5e
	const OW_KNIGHT                ; $5f
	const OW_BISHOP                ; $60
	const OW_ROOK                  ; $61
	const OW_QUEEN                 ; $62
	const OW_GR_X                  ; $63
	const OW_CLERK_1               ; $64
	const OW_CLERK_2               ; $65
	const OW_GR_CLERK_1            ; $66
	const OW_GR_CLERK_2            ; $67
	const OW_GR_CLERK_3            ; $68
	const OW_GR_CLERK_4            ; $69
	const OW_LASS2_2               ; $6a
	const OW_WOMAN                 ; $6b
	const OW_CHAP_1                ; $6c
	const OW_LAD_3                 ; $6d
	const OW_PAPPY_2               ; $6e
	const OW_SPECS_3               ; $6f
	const OW_LAD4                  ; $70
	const OW_GIRL_4                ; $71
	const OW_GRANNY                ; $72
	const OW_LASS2_3               ; $73
	const OW_GIRL_5                ; $74
	const OW_MAN_2                 ; $75
	const OW_LAD_5                 ; $76
	const OW_SPECS_4               ; $77
	const OW_TECH_6                ; $78
	const OW_PAPPY_3               ; $79
	const OW_LASS1_2               ; $7a
	const OW_LASS2_4               ; $7b
	const OW_HOOD_3                ; $7c
	const OW_MANIA_4               ; $7d
	const OW_GAL_2                 ; $7e
	const OW_LASS3_2               ; $7f
	const OW_HOOD_4                ; $80
	const OW_LASS1_3               ; $81
	const OW_CHAP_2                ; $82
	const OW_SPECS_5               ; $83
	const OW_LASS1_4               ; $84
	const OW_LAD_6                 ; $85
	const OW_GR_LASS_2             ; $86
	const OW_GR_CLERK_5            ; $87
	const OW_GR_GAL_1              ; $88
	const OW_MANIA_5               ; $89
	const OW_CLERK_3               ; $8a
	const OW_CHAP_3                ; $8b
	const OW_GAL_3                 ; $8c
	const OW_HOOD_5                ; $8d
	const OW_MAN_3                 ; $8e
	const OW_PAPPY_4               ; $8f
	const OW_TECH_7                ; $90
	const OW_GIRL_6                ; $91
	const OW_LASS1_5               ; $92
	const OW_LASS2_5               ; $93
	const OW_GR_CLERK_6            ; $94
	const OW_GR_PAPPY_1            ; $95
	const OW_GR_LASS_3             ; $96
	const OW_GR_CLERK_7            ; $97
	const OW_GR_LAD_2              ; $98
	const OW_GR_PAPPY_2            ; $99
	const OW_GR_LASS_4             ; $9a
	const OW_GR_CLERK_8            ; $9b
	const OW_GR_WOMAN_1            ; $9c
	const OW_BUTCH_1               ; $9d
	const OW_TAP                   ; $9e
	const OW_GR_CLERK_9            ; $9f
	const OW_YOUNGSTER_4           ; $a0
	const OW_GR_CLERK_10           ; $a1
	const OW_GR_GRANNY_2           ; $a2
	const OW_GR_GAL_2              ; $a3
	const OW_GR_CLERK_11           ; $a4
	const OW_GR_CLERK_12           ; $a5
	const OW_MANIA_6               ; $a6
	const OW_GR_LASS_5             ; $a7
	const OW_GR_CLERK_13           ; $a8
	const OW_TECH_8                ; $a9
	const OW_GR_LASS_6             ; $aa
	const OW_GR_PAPPY_3            ; $ab
	const OW_CAPTURED_AMY          ; $ac
	const OW_CAPTURED_SARA         ; $ad
	const OW_CAPTURED_AMANDA       ; $ae
	const OW_WARP_SPARKLES         ; $af
	const OW_YUI                   ; $b0
	const OW_IMAKUNI_RED           ; $b1
	const OW_BUTCH_2               ; $b2
	const OW_TECH_9                ; $b3
	const OW_TECH_10               ; $b4
	const OW_TECH_11               ; $b5
	const OW_TECH_12               ; $b6
	const OW_TECH_13               ; $b7
	const OW_TECH_14               ; $b8
	const OW_TECH_15               ; $b9
	const OW_TECH_16               ; $ba
	const OW_TECH_17               ; $bb
	const OW_GR_CLERK_14           ; $bc
	const OW_GR_CLERK_15           ; $bd
	const OW_GR_CLERK_16           ; $be
	const OW_GR_CLERK_17           ; $bf
	const OW_CHIP_GIRL_1           ; $c0
	const OW_MONOCLE_1             ; $c1
	const OW_MONOCLE_2             ; $c2
	const OW_DEALER_BOY_1          ; $c3
	const OW_DEALER_GIRL_1         ; $c4
	const OW_DEALER_BOY_2          ; $c5
	const OW_CHIP_GIRL_2           ; $c6
	const OW_DEALER_GIRL_2         ; $c7
	const OW_VOLCANO_SMOKE_TCG     ; $c8
	const OW_VOLCANO_SMOKE_GR      ; $c9
	const OW_CURSOR_TCG            ; $ca
	const OW_CURSOR_GR             ; $cb
	const OW_GR_CROSS              ; $cc
	const OW_GR_CASTLE_FLAG        ; $cd
	const OW_CHEST_CLOSED          ; $ce
	const OW_CHEST_OPENED          ; $cf
	const OW_GR_BLIMP_BEAM         ; $d0
	const OW_GR_BLIMP              ; $d1
	const OW_POD_DOORS             ; $d2
	const OW_GR_LAD_3              ; $d3
	const OW_GR_LASS_7             ; $d4
	const OW_GR_LASS_8             ; $d5
	const OW_YOUNGSTER_5           ; $d6
	const OW_SWIMMER               ; $d7
	const OW_GR_GAL_3              ; $d8
	const OW_BUTCH_3               ; $d9
	const OW_MANIA_7               ; $da
	const OW_GAMBLER               ; $db
	const OW_GR_WOMAN_2            ; $dc
	const OW_GR_GAL_4              ; $dd
	const OW_GR_CLERK_18           ; $de
	const OW_GR_CHAP               ; $df
	const OW_GR_WOMAN_3            ; $e0
	const OW_GR_STAFF              ; $e1
	const OW_LASS1_6               ; $e2
	const OW_LASS2_7               ; $e3
	const OW_RED_FORT_COIN         ; $e4
	const OW_BLUE_FORT_COIN        ; $e5
	const OW_WHITE_CASTLE_COIN     ; $e6
	const OW_PURPLE_CASTLE_COIN    ; $e7
	const OW_STRONGHOLD_PLATFORM   ; $e8

; OW sprites represent what graphics
; are associated with an OW object
	const_def
	const OWSPRITE_MARK                  ; $00
	const OWSPRITE_MINT                  ; $01
	const OWSPRITE_DR_MASON              ; $02
	const OWSPRITE_RONALD                ; $03
	const OWSPRITE_ISHIHARA              ; $04
	const OWSPRITE_IMAKUNI_BLACK         ; $05
	const OWSPRITE_IMAKUNI_RED           ; $06
	const OWSPRITE_ISAAC                 ; $07
	const OWSPRITE_MURRAY                ; $08
	const OWSPRITE_GENE                  ; $09
	const OWSPRITE_MITCH                 ; $0a
	const OWSPRITE_NIKKI                 ; $0b
	const OWSPRITE_RICK                  ; $0c
	const OWSPRITE_AMY                   ; $0d
	const OWSPRITE_AMY_LOUNGE            ; $0e
	const OWSPRITE_SARA                  ; $0f
	const OWSPRITE_AMANDA                ; $10
	const OWSPRITE_KEN                   ; $11
	const OWSPRITE_COURTNEY              ; $12
	const OWSPRITE_STEVE                 ; $13
	const OWSPRITE_JACK                  ; $14
	const OWSPRITE_ROD                   ; $15
	const OWSPRITE_EIJI                  ; $16
	const OWSPRITE_MAGICIAN              ; $17
	const OWSPRITE_TOSHIRON              ; $18
	const OWSPRITE_PIERROT               ; $19
	const OWSPRITE_ANNA                  ; $1a
	const OWSPRITE_DEE                   ; $1b
	const OWSPRITE_MASQUERADE            ; $1c
	const OWSPRITE_PAWN                  ; $1d
	const OWSPRITE_KNIGHT                ; $1e
	const OWSPRITE_BISHOP                ; $1f
	const OWSPRITE_ROOK                  ; $20
	const OWSPRITE_QUEEN                 ; $21
	const OWSPRITE_GR_1                  ; $22
	const OWSPRITE_GR_2                  ; $23
	const OWSPRITE_GR_3                  ; $24
	const OWSPRITE_GR_4                  ; $25
	const OWSPRITE_GR_5                  ; $26
	const OWSPRITE_MIDORI                ; $27
	const OWSPRITE_MORINO                ; $28
	const OWSPRITE_RENNA                 ; $29
	const OWSPRITE_ICHIKAWA              ; $2a
	const OWSPRITE_CATHERINE             ; $2b
	const OWSPRITE_JES                   ; $2c
	const OWSPRITE_YUKI                  ; $2d
	const OWSPRITE_SHOKO                 ; $2e
	const OWSPRITE_HIDERO                ; $2f
	const OWSPRITE_AIRA                  ; $30
	const OWSPRITE_KANOKO                ; $31
	const OWSPRITE_GODA                  ; $32
	const OWSPRITE_GRACE                 ; $33
	const OWSPRITE_KAMIYA                ; $34
	const OWSPRITE_MIWA                  ; $35
	const OWSPRITE_KEVIN                 ; $36
	const OWSPRITE_YOSUKE                ; $37
	const OWSPRITE_RYOKO                 ; $38
	const OWSPRITE_MAMI                  ; $39
	const OWSPRITE_NISHIJIMA             ; $3a
	const OWSPRITE_ISHII                 ; $3b
	const OWSPRITE_SAMEJIMA              ; $3c
	const OWSPRITE_KANZAKI               ; $3d
	const OWSPRITE_RUI                   ; $3e
	const OWSPRITE_BIRURITCHI            ; $3f
	const OWSPRITE_GR_X                  ; $40
	const OWSPRITE_TOBICHAN              ; $41
	const OWSPRITE_YOUNGSTER             ; $42
	const OWSPRITE_LAD                   ; $43
	const OWSPRITE_SPECS                 ; $44
	const OWSPRITE_BUTCH                 ; $45
	const OWSPRITE_MANIA                 ; $46
	const OWSPRITE_JOSHUA                ; $47
	const OWSPRITE_HOOD                  ; $48
	const OWSPRITE_TECH                  ; $49
	const OWSPRITE_CHAP                  ; $4a
	const OWSPRITE_MAN                   ; $4b
	const OWSPRITE_PAPPY                 ; $4c
	const OWSPRITE_GAMBLER               ; $4d
	const OWSPRITE_GR_LAD                ; $4e
	const OWSPRITE_GR_CHAP               ; $4f
	const OWSPRITE_MIYAJIMA              ; $50
	const OWSPRITE_GR_PAPPY              ; $51
	const OWSPRITE_DEALER_BOY            ; $52
	const OWSPRITE_MONOCLE               ; $53
	const OWSPRITE_GIRL                  ; $54
	const OWSPRITE_LASS1                 ; $55
	const OWSPRITE_LASS2                 ; $56
	const OWSPRITE_LASS3                 ; $57
	const OWSPRITE_SWIMMER               ; $58
	const OWSPRITE_GAL                   ; $59
	const OWSPRITE_WOMAN                 ; $5a
	const OWSPRITE_GRANNY                ; $5b
	const OWSPRITE_GR_STAFF              ; $5c
	const OWSPRITE_GR_LASS               ; $5d
	const OWSPRITE_GR_GAL                ; $5e
	const OWSPRITE_GR_WOMAN              ; $5f
	const OWSPRITE_GR_GRANNY             ; $60
	const OWSPRITE_CHIP_GIRL             ; $61
	const OWSPRITE_DEALER_GIRL           ; $62
	const OWSPRITE_CLERK                 ; $63
	const OWSPRITE_GR_CLERK              ; $64
	const OWSPRITE_CAPTURED_AMY          ; $65
	const OWSPRITE_CAPTURED_SARA         ; $66
	const OWSPRITE_CAPTURED_AMANDA       ; $67
	const OWSPRITE_WARP_SPARKLES         ; $68
	const OWSPRITE_GR_BLIMP              ; $69
	const OWSPRITE_GR_BLIMP_BEAM         ; $6a
	const OWSPRITE_VOLCANO_SMOKE_TCG     ; $6b
	const OWSPRITE_CURSOR_TCG            ; $6c
	const OWSPRITE_VOLCANO_SMOKE_GR      ; $6d
	const OWSPRITE_GR_CASTLE_FLAG        ; $6e
	const OWSPRITE_CURSOR_GR             ; $6f
	const OWSPRITE_GR_CROSS              ; $70
	const OWSPRITE_CHEST_CLOSED          ; $71
	const OWSPRITE_CHEST_OPENED          ; $72
	const OWSPRITE_POD_DOORS             ; $73
	const OWSPRITE_STRONGHOLD_PLATFORM   ; $74
	const OWSPRITE_RED_FORT_COIN         ; $75
	const OWSPRITE_BLUE_FORT_COIN        ; $76
	const OWSPRITE_WHITE_CASTLE_COIN     ; $77
	const OWSPRITE_PURPLE_CASTLE_COIN    ; $78

	const_def
	const OWFRAMEGROUP_00 ; $00
	const OWFRAMEGROUP_01 ; $01
	const OWFRAMEGROUP_02 ; $02
	const OWFRAMEGROUP_03 ; $03
	const OWFRAMEGROUP_04 ; $04
	const OWFRAMEGROUP_05 ; $05
	const OWFRAMEGROUP_06 ; $06
	const OWFRAMEGROUP_07 ; $07
	const OWFRAMEGROUP_08 ; $08
	const OWFRAMEGROUP_09 ; $09
	const OWFRAMEGROUP_0A ; $0a
	const OWFRAMEGROUP_0B ; $0b
	const OWFRAMEGROUP_0C ; $0c
	const OWFRAMEGROUP_0D ; $0d
	const OWFRAMEGROUP_0E ; $0e
	const OWFRAMEGROUP_0F ; $0f
	const OWFRAMEGROUP_10 ; $10
	const OWFRAMEGROUP_11 ; $11
	const OWFRAMEGROUP_12 ; $12
	const OWFRAMEGROUP_13 ; $13
	const OWFRAMEGROUP_14 ; $14
	const OWFRAMEGROUP_15 ; $15
	const OWFRAMEGROUP_16 ; $16
	const OWFRAMEGROUP_17 ; $17
	const OWFRAMEGROUP_18 ; $18
	const OWFRAMEGROUP_19 ; $19
	const OWFRAMEGROUP_1A ; $1a
	const OWFRAMEGROUP_1B ; $1b
	const OWFRAMEGROUP_1C ; $1c
	const OWFRAMEGROUP_1D ; $1d
	const OWFRAMEGROUP_1E ; $1e
	const OWFRAMEGROUP_1F ; $1f
	const OWFRAMEGROUP_20 ; $20
	const OWFRAMEGROUP_21 ; $21
	const OWFRAMEGROUP_22 ; $22
	const OWFRAMEGROUP_23 ; $23
	const OWFRAMEGROUP_24 ; $24
	const OWFRAMEGROUP_25 ; $25
	const OWFRAMEGROUP_26 ; $26
	const OWFRAMEGROUP_27 ; $27
	const OWFRAMEGROUP_28 ; $28
	const OWFRAMEGROUP_29 ; $29
	const OWFRAMEGROUP_2A ; $2a
	const OWFRAMEGROUP_2B ; $2b
	const OWFRAMEGROUP_2C ; $2c
	const OWFRAMEGROUP_2D ; $2d
	const OWFRAMEGROUP_2E ; $2e
	const OWFRAMEGROUP_2F ; $2f
	const OWFRAMEGROUP_30 ; $30
	const OWFRAMEGROUP_31 ; $31
	const OWFRAMEGROUP_32 ; $32
	const OWFRAMEGROUP_33 ; $33

DEF MAX_NUM_OW_OBJECTS EQU 10

RSRESET
DEF OWOBJSTRUCT_FLAGS                  RB ; $0
DEF OWOBJSTRUCT_ID                     RB ; $1
DEF OWOBJSTRUCT_ANIM_PTR               RW ; $2
DEF OWOBJSTRUCT_4                      RB ; $4
DEF OWOBJSTRUCT_5                      RB ; $5
DEF OWOBJSTRUCT_6                      RW ; $6
DEF OWOBJSTRUCT_LENGTH EQU _RS

; OWOBJSTRUCT_FLAGS bit flags
	const_def 7
	const ACTIVE_OBJ_F ; 7

DEF ACTIVE_OBJ EQU 1 << ACTIVE_OBJ_F
