; constants for the Pokédex numbers of each card
	const_def 1
	const DEX_BULBASAUR  ; $01
	const DEX_IVYSAUR    ; $02
	const DEX_VENUSAUR   ; $03
	const DEX_CHARMANDER ; $04
	const DEX_CHARMELEON ; $05
	const DEX_CHARIZARD  ; $06
	const DEX_SQUIRTLE   ; $07
	const DEX_WARTORTLE  ; $08
	const DEX_BLASTOISE  ; $09
	const DEX_CATERPIE   ; $0a
	const DEX_METAPOD    ; $0b
	const DEX_BUTTERFREE ; $0c
	const DEX_WEEDLE     ; $0d
	const DEX_KAKUNA     ; $0e
	const DEX_BEEDRILL   ; $0f
	const DEX_PIDGEY     ; $10
	const DEX_PIDGEOTTO  ; $11
	const DEX_PIDGEOT    ; $12
	const DEX_RATTATA    ; $13
	const DEX_RATICATE   ; $14
	const DEX_SPEAROW    ; $15
	const DEX_FEAROW     ; $16
	const DEX_EKANS      ; $17
	const DEX_ARBOK      ; $18
	const DEX_PIKACHU    ; $19
	const DEX_RAICHU     ; $1a
	const DEX_SANDSHREW  ; $1b
	const DEX_SANDSLASH  ; $1c
	const DEX_NIDORAN_F  ; $1d
	const DEX_NIDORINA   ; $1e
	const DEX_NIDOQUEEN  ; $1f
	const DEX_NIDORAN_M  ; $20
	const DEX_NIDORINO   ; $21
	const DEX_NIDOKING   ; $22
	const DEX_CLEFAIRY   ; $23
	const DEX_CLEFABLE   ; $24
	const DEX_VULPIX     ; $25
	const DEX_NINETALES  ; $26
	const DEX_JIGGLYPUFF ; $27
	const DEX_WIGGLYTUFF ; $28
	const DEX_ZUBAT      ; $29
	const DEX_GOLBAT     ; $2a
	const DEX_ODDISH     ; $2b
	const DEX_GLOOM      ; $2c
	const DEX_VILEPLUME  ; $2d
	const DEX_PARAS      ; $2e
	const DEX_PARASECT   ; $2f
	const DEX_VENONAT    ; $30
	const DEX_VENOMOTH   ; $31
	const DEX_DIGLETT    ; $32
	const DEX_DUGTRIO    ; $33
	const DEX_MEOWTH     ; $34
	const DEX_PERSIAN    ; $35
	const DEX_PSYDUCK    ; $36
	const DEX_GOLDUCK    ; $37
	const DEX_MANKEY     ; $38
	const DEX_PRIMEAPE   ; $39
	const DEX_GROWLITHE  ; $3a
	const DEX_ARCANINE   ; $3b
	const DEX_POLIWAG    ; $3c
	const DEX_POLIWHIRL  ; $3d
	const DEX_POLIWRATH  ; $3e
	const DEX_ABRA       ; $3f
	const DEX_KADABRA    ; $40
	const DEX_ALAKAZAM   ; $41
	const DEX_MACHOP     ; $42
	const DEX_MACHOKE    ; $43
	const DEX_MACHAMP    ; $44
	const DEX_BELLSPROUT ; $45
	const DEX_WEEPINBELL ; $46
	const DEX_VICTREEBEL ; $47
	const DEX_TENTACOOL  ; $48
	const DEX_TENTACRUEL ; $49
	const DEX_GEODUDE    ; $4a
	const DEX_GRAVELER   ; $4b
	const DEX_GOLEM      ; $4c
	const DEX_PONYTA     ; $4d
	const DEX_RAPIDASH   ; $4e
	const DEX_SLOWPOKE   ; $4f
	const DEX_SLOWBRO    ; $50
	const DEX_MAGNEMITE  ; $51
	const DEX_MAGNETON   ; $52
	const DEX_FARFETCH_D ; $53
	const DEX_DODUO      ; $54
	const DEX_DODRIO     ; $55
	const DEX_SEEL       ; $56
	const DEX_DEWGONG    ; $57
	const DEX_GRIMER     ; $58
	const DEX_MUK        ; $59
	const DEX_SHELLDER   ; $5a
	const DEX_CLOYSTER   ; $5b
	const DEX_GASTLY     ; $5c
	const DEX_HAUNTER    ; $5d
	const DEX_GENGAR     ; $5e
	const DEX_ONIX       ; $5f
	const DEX_DROWZEE    ; $60
	const DEX_HYPNO      ; $61
	const DEX_KRABBY     ; $62
	const DEX_KINGLER    ; $63
	const DEX_VOLTORB    ; $64
	const DEX_ELECTRODE  ; $65
	const DEX_EXEGGCUTE  ; $66
	const DEX_EXEGGUTOR  ; $67
	const DEX_CUBONE     ; $68
	const DEX_MAROWAK    ; $69
	const DEX_HITMONLEE  ; $6a
	const DEX_HITMONCHAN ; $6b
	const DEX_LICKITUNG  ; $6c
	const DEX_KOFFING    ; $6d
	const DEX_WEEZING    ; $6e
	const DEX_RHYHORN    ; $6f
	const DEX_RHYDON     ; $70
	const DEX_CHANSEY    ; $71
	const DEX_TANGELA    ; $72
	const DEX_KANGASKHAN ; $73
	const DEX_HORSEA     ; $74
	const DEX_SEADRA     ; $75
	const DEX_GOLDEEN    ; $76
	const DEX_SEAKING    ; $77
	const DEX_STARYU     ; $78
	const DEX_STARMIE    ; $79
	const DEX_MR__MIME   ; $7a
	const DEX_SCYTHER    ; $7b
	const DEX_JYNX       ; $7c
	const DEX_ELECTABUZZ ; $7d
	const DEX_MAGMAR     ; $7e
	const DEX_PINSIR     ; $7f
	const DEX_TAUROS     ; $80
	const DEX_MAGIKARP   ; $81
	const DEX_GYARADOS   ; $82
	const DEX_LAPRAS     ; $83
	const DEX_DITTO      ; $84
	const DEX_EEVEE      ; $85
	const DEX_VAPOREON   ; $86
	const DEX_JOLTEON    ; $87
	const DEX_FLAREON    ; $88
	const DEX_PORYGON    ; $89
	const DEX_OMANYTE    ; $8a
	const DEX_OMASTAR    ; $8b
	const DEX_KABUTO     ; $8c
	const DEX_KABUTOPS   ; $8d
	const DEX_AERODACTYL ; $8e
	const DEX_SNORLAX    ; $8f
	const DEX_ARTICUNO   ; $90
	const DEX_ZAPDOS     ; $91
	const DEX_MOLTRES    ; $92
	const DEX_DRATINI    ; $93
	const DEX_DRAGONAIR  ; $94
	const DEX_DRAGONITE  ; $95
	const DEX_MEWTWO     ; $96
	const DEX_MEW        ; $97
