	const_def
	const PORTRAIT_MARK          ; $00
	const PORTRAIT_MINT          ; $01
	const PORTRAIT_MARK_LINK     ; $02
	const PORTRAIT_MINT_LINK     ; $03
	const PORTRAIT_RONALD        ; $04
	const PORTRAIT_SAM           ; $05
	const PORTRAIT_AARON         ; $06
	const PORTRAIT_ISHIHARA      ; $07
	const PORTRAIT_ISAAC         ; $08
	const PORTRAIT_JENNIFER      ; $09
	const PORTRAIT_NICHOLAS      ; $0a
	const PORTRAIT_BRANDON       ; $0b
	const PORTRAIT_MURRAY        ; $0c
	const PORTRAIT_STEPHANIE     ; $0d
	const PORTRAIT_DANIEL        ; $0e
	const PORTRAIT_ROBERT        ; $0f
	const PORTRAIT_GENE          ; $10
	const PORTRAIT_MATTHEW       ; $11
	const PORTRAIT_RYAN          ; $12
	const PORTRAIT_ANDREW        ; $13
	const PORTRAIT_MITCH         ; $14
	const PORTRAIT_MICHAEL       ; $15
	const PORTRAIT_CHRIS         ; $16
	const PORTRAIT_JESSICA       ; $17
	const PORTRAIT_NIKKI         ; $18
	const PORTRAIT_BRITTANY      ; $19
	const PORTRAIT_KRISTIN       ; $1a
	const PORTRAIT_HEATHER       ; $1b
	const PORTRAIT_RICK          ; $1c
	const PORTRAIT_JOSEPH        ; $1d
	const PORTRAIT_DAVID         ; $1e
	const PORTRAIT_ERIK          ; $1f
	const PORTRAIT_AMY           ; $20
	const PORTRAIT_JOSHUA        ; $21
	const PORTRAIT_SARA          ; $22
	const PORTRAIT_AMANDA        ; $23
	const PORTRAIT_KEN           ; $24
	const PORTRAIT_JOHN          ; $25
	const PORTRAIT_ADAM          ; $26
	const PORTRAIT_JONATHAN      ; $27
	const PORTRAIT_COURTNEY      ; $28
	const PORTRAIT_STEVE         ; $29
	const PORTRAIT_JACK          ; $2a
	const PORTRAIT_ROD           ; $2b
	const PORTRAIT_EIJI          ; $2c
	const PORTRAIT_MAGICIAN      ; $2d
	const PORTRAIT_YUI           ; $2e
	const PORTRAIT_TOSHIRON      ; $2f
	const PORTRAIT_PIERROT       ; $30
	const PORTRAIT_ANNA          ; $31
	const PORTRAIT_DEE           ; $32
	const PORTRAIT_MASQUERADE    ; $33
	const PORTRAIT_PAWN          ; $34
	const PORTRAIT_KNIGHT        ; $35
	const PORTRAIT_BISHOP        ; $36
	const PORTRAIT_ROOK          ; $37
	const PORTRAIT_QUEEN         ; $38
	const PORTRAIT_GR_1          ; $39
	const PORTRAIT_GR_2          ; $3a
	const PORTRAIT_GR_3          ; $3b
	const PORTRAIT_GR_4          ; $3c
	const PORTRAIT_MIDORI        ; $3d
	const PORTRAIT_YUUTA         ; $3e
	const PORTRAIT_MIYUKI        ; $3f
	const PORTRAIT_MORINO        ; $40
	const PORTRAIT_RENNA         ; $41
	const PORTRAIT_ICHIKAWA      ; $42
	const PORTRAIT_CATHERINE     ; $43
	const PORTRAIT_TAP           ; $44
	const PORTRAIT_JES           ; $45
	const PORTRAIT_YUKI          ; $46
	const PORTRAIT_SHOKO         ; $47
	const PORTRAIT_HIDERO        ; $48
	const PORTRAIT_MIYAJIMA      ; $49
	const PORTRAIT_SENTA         ; $4a
	const PORTRAIT_AIRA          ; $4b
	const PORTRAIT_KANOKO        ; $4c
	const PORTRAIT_GODA          ; $4d
	const PORTRAIT_GRACE         ; $4e
	const PORTRAIT_KAMIYA        ; $4f
	const PORTRAIT_MIWA          ; $50
	const PORTRAIT_KEVIN         ; $51
	const PORTRAIT_YOSUKE        ; $52
	const PORTRAIT_RYOKO         ; $53
	const PORTRAIT_MAMI          ; $54
	const PORTRAIT_NISHIJIMA     ; $55
	const PORTRAIT_ISHII         ; $56
	const PORTRAIT_SAMEJIMA      ; $57
	const PORTRAIT_KANZAKI       ; $58
	const PORTRAIT_RUI           ; $59
	const PORTRAIT_BIRURITCHI    ; $5a
	const PORTRAIT_GR_X          ; $5b
	const PORTRAIT_TOBI_CHAN     ; $5c
	const PORTRAIT_DR_MASON      ; $5d
	const PORTRAIT_IMAKUNI_BLACK ; $5e
	const PORTRAIT_IMAKUNI_RED   ; $5f

; each portrait has 3 variants
	const_def
	const PORTRAITVARIANT_NORMAL ; $0
	const PORTRAITVARIANT_HAPPY  ; $1
	const PORTRAITVARIANT_SAD    ; $2
