	const_def
	const SFX_STOP                     ; $00
	const SFX_CURSOR                   ; $01
	const SFX_CONFIRM                  ; $02
	const SFX_CANCEL                   ; $03
	const SFX_DENIED                   ; $04
	const SFX_JINGLE                   ; $05
	const SFX_06                       ; $06
	const SFX_CARD_SHUFFLE             ; $07
	const SFX_PLACE_PRIZE              ; $08
	const SFX_09                       ; $09
	const SFX_0A                       ; $0a
	const SFX_COIN_TOSS                ; $0b
	const SFX_WARP                     ; $0c
	const SFX_0D                       ; $0d
	const SFX_0E                       ; $0e
	const SFX_DOORS                    ; $0f
	const SFX_TCG1_LEGENDARY_CARDS     ; $10
	const SFX_GLOW                     ; $11
	const SFX_PARALYSIS                ; $12
	const SFX_SLEEP                    ; $13
	const SFX_CONFUSION                ; $14
	const SFX_POISON                   ; $15
	const SFX_SMALL_HIT                ; $16
	const SFX_HIT                      ; $17
	const SFX_THUNDER_SHOCK            ; $18
	const SFX_LIGHTNING                ; $19
	const SFX_BORDER_SPARK             ; $1a
	const SFX_BIG_LIGHTNING            ; $1b
	const SFX_SMALL_FLAME              ; $1c
	const SFX_BIG_FLAME                ; $1d
	const SFX_FIRE_SPIN                ; $1e
	const SFX_DIVE_BOMB                ; $1f
	const SFX_WATER_JETS               ; $20
	const SFX_WATER_GUN                ; $21
	const SFX_WHIRLPOOL                ; $22
	const SFX_HYDRO_PUMP               ; $23
	const SFX_BLIZZARD                 ; $24
	const SFX_PSYCHIC                  ; $25
	const SFX_LEER                     ; $26
	const SFX_BEAM                     ; $27
	const SFX_HYPER_BEAM               ; $28
	const SFX_AVALANCHE                ; $29
	const SFX_STONE_BARRAGE            ; $2a
	const SFX_PUNCH                    ; $2b
	const SFX_STRETCH_KICK             ; $2c
	const SFX_SLASH                    ; $2d
	const SFX_SONIC_BOOM               ; $2e
	const SFX_FURY_SWIPES              ; $2f
	const SFX_DRILL                    ; $30
	const SFX_POT_SMASH                ; $31
	const SFX_BONEMERANG               ; $32
	const SFX_SEISMIC_TOSS             ; $33
	const SFX_NEEDLES                  ; $34
	const SFX_WHITE_GAS                ; $35
	const SFX_POWDER                   ; $36
	const SFX_GOO                      ; $37
	const SFX_BUBBLES                  ; $38
	const SFX_STRING_SHOT              ; $39
	const SFX_BOYFRIENDS               ; $3a
	const SFX_LURE                     ; $3b
	const SFX_TOXIC                    ; $3c
	const SFX_CONFUSE_RAY              ; $3d
	const SFX_SING                     ; $3e
	const SFX_SUPERSONIC               ; $3f
	const SFX_PETAL_DANCE              ; $40
	const SFX_PROTECT                  ; $41
	const SFX_BARRIER                  ; $42
	const SFX_SPEED                    ; $43
	const SFX_WHIRLWIND                ; $44
	const SFX_CRY                      ; $45
	const SFX_QUESTION_MARK            ; $46
	const SFX_SELFDESTRUCT             ; $47
	const SFX_BIG_SELFDESTRUCT         ; $48
	const SFX_HEAL                     ; $49
	const SFX_DRAIN                    ; $4a
	const SFX_DARK_GAS                 ; $4b
	const SFX_HEALING_WIND             ; $4c
	const SFX_WHIRLWIND_BENCH          ; $4d
	const SFX_EXPAND                   ; $4e
	const SFX_CAT_PUNCH                ; $4f
	const SFX_THUNDER_WAVE             ; $50
	const SFX_FIREGIVER                ; $51
	const SFX_THUNDER_PUNCH            ; $52
	const SFX_FIRE_PUNCH               ; $53
	const SFX_COIN_TOSS_POSITIVE       ; $54
	const SFX_COIN_TOSS_NEGATIVE       ; $55
	const SFX_SAVE_GAME                ; $56
	const SFX_PLAYER_WALK_MAP          ; $57
	const SFX_TCG1_INTRO_ORB           ; $58
	const SFX_TCG1_INTRO_ORB_SWOOP     ; $59
	const SFX_TCG1_INTRO_ORB_TITLE     ; $5a
	const SFX_TCG1_INTRO_ORB_SCATTER   ; $5b
	const SFX_FIREGIVER_START          ; $5c
	const SFX_RECEIVE_CARD_POP         ; $5d
	const SFX_POKEMON_EVOLUTION        ; $5e
	const SFX_5F                       ; $5f
	const SFX_PLACEHOLDER_60           ; $60
	const SFX_PLACEHOLDER_61           ; $61
	const SFX_PLACEHOLDER_62           ; $62
	const SFX_PLACEHOLDER_63           ; $63
	const SFX_FIREBALL                 ; $64
	const SFX_CONTINUOUS_FIREBALL      ; $65
	const SFX_BENCH_MANIPULATION       ; $66
	const SFX_PSYCHIC_BEAM             ; $67
	const SFX_PSYCHIC_BEAM_BENCH       ; $68
	const SFX_BOULDER_SMASH            ; $69
	const SFX_MEGA_PUNCH               ; $6a
	const SFX_PSYPUNCH                 ; $6b
	const SFX_SLUDGE_PUNCH             ; $6c
	const SFX_ICE_PUNCH                ; $6d
	const SFX_KICK                     ; $6e
	const SFX_TAIL_SLAP                ; $6f
	const SFX_TAIL_WHIP                ; $70
	const SFX_SLAP                     ; $71
	const SFX_QUESTION_MARK_BENCH      ; $72
	const SFX_SKULL_BASH               ; $73
	const SFX_COIN_HURL                ; $74
	const SFX_TELEPORT                 ; $75
	const SFX_FOLLOW_ME                ; $76
	const SFX_SWIFT                    ; $77
	const SFX_3D_ATTACK                ; $78
	const SFX_DRY_UP                   ; $79
	const SFX_FOCUS_BLAST              ; $7a
	const SFX_FOCUS_BLAST_BENCH        ; $7b
	const SFX_CHIPS_COUNTING           ; $7c
	const SFX_SLOT_START               ; $7d
	const SFX_SLOT_REEL                ; $7e
	const SFX_BLACK_BOX_INSERT         ; $7f
	const SFX_BLACK_BOX_INSERTED       ; $80
	const SFX_BLACK_BOX_TRANSMITTED    ; $81
	const SFX_NEW_MAIL                 ; $82
	const SFX_POD_DOORS                ; $83
	const SFX_PITFALL                  ; $84
	const SFX_OPEN_CHEST               ; $85
	const SFX_NPC_WARP_TRANSFORM       ; $86
	const SFX_STRONGHOLD_PLATFORM_UP   ; $87
	const SFX_STRONGHOLD_PLATFORM_DOWN ; $88
	const SFX_GR_BLIMP_HATCH_CLOSE     ; $89
	const SFX_GR_BLIMP_HATCH_OPEN      ; $8a
	const SFX_GR_BLIMP_TRACTOR_BEAM    ; $8b
	const SFX_BONE_TOSS_BENCH          ; $8c
	const SFX_COIN_HURL_BENCH          ; $8d
	const SFX_BIG_SNORE                ; $8e
	const SFX_SLOT_BIG_HIT             ; $8f
	const SFX_SLOT_BONUS_HIT           ; $90
	const SFX_SLOT_SMALL_HIT           ; $91
	const SFX_RAZOR_LEAF               ; $92
	const SFX_GUILLOTINE               ; $93
	const SFX_VINE_PULL                ; $94
	const SFX_PERPLEX                  ; $95
	const SFX_NINE_TAILS               ; $96
	const SFX_BONE_HEADBUTT            ; $97
	const SFX_DRILL_DIVE               ; $98
	const SFX_DARK_SONG                ; $99
	const SFX_TCG2_INTRO_ORBS          ; $9a
	const SFX_TCG2_INTRO_TITLE         ; $9b
	const SFX_TCG2_INTRO_SUBTITLE      ; $9c
	const SFX_ELECTRONIC_INPUT         ; $9d
	const SFX_ELECTRONIC_RESPONSE      ; $9e
	const SFX_GHOST_MASTER_APPEAR      ; $9f
	const SFX_GHOST_MASTER_DISAPPEAR   ; $a0

DEF NUM_SFX EQU const_value
