	const_def
	const SFX_STOP            ; $00
	const SFX_01              ; $01
	const SFX_02              ; $02
	const SFX_03              ; $03
	const SFX_04              ; $04
	const SFX_05              ; $05
	const SFX_06              ; $06
	const SFX_07              ; $07
	const SFX_08              ; $08
	const SFX_09              ; $09
	const SFX_0A              ; $0a
	const SFX_0B              ; $0b
	const SFX_0C              ; $0c
	const SFX_0D              ; $0d
	const SFX_0E              ; $0e
	const SFX_0F              ; $0f
	const SFX_10              ; $10
	const SFX_11              ; $11
	const SFX_12              ; $12
	const SFX_13              ; $13
	const SFX_14              ; $14
	const SFX_15              ; $15
	const SFX_16              ; $16
	const SFX_17              ; $17
	const SFX_18              ; $18
	const SFX_19              ; $19
	const SFX_1A              ; $1a
	const SFX_1B              ; $1b
	const SFX_1C              ; $1c
	const SFX_1D              ; $1d
	const SFX_1E              ; $1e
	const SFX_1F              ; $1f
	const SFX_20              ; $20
	const SFX_21              ; $21
	const SFX_22              ; $22
	const SFX_23              ; $23
	const SFX_24              ; $24
	const SFX_25              ; $25
	const SFX_26              ; $26
	const SFX_27              ; $27
	const SFX_28              ; $28
	const SFX_29              ; $29
	const SFX_2A              ; $2a
	const SFX_2B              ; $2b
	const SFX_2C              ; $2c
	const SFX_2D              ; $2d
	const SFX_2E              ; $2e
	const SFX_2F              ; $2f
	const SFX_30              ; $30
	const SFX_31              ; $31
	const SFX_32              ; $32
	const SFX_33              ; $33
	const SFX_34              ; $34
	const SFX_35              ; $35
	const SFX_36              ; $36
	const SFX_37              ; $37
	const SFX_38              ; $38
	const SFX_39              ; $39
	const SFX_3A              ; $3a
	const SFX_3B              ; $3b
	const SFX_3C              ; $3c
	const SFX_3D              ; $3d
	const SFX_3E              ; $3e
	const SFX_3F              ; $3f
	const SFX_40              ; $40
	const SFX_41              ; $41
	const SFX_42              ; $42
	const SFX_43              ; $43
	const SFX_44              ; $44
	const SFX_45              ; $45
	const SFX_46              ; $46
	const SFX_47              ; $47
	const SFX_48              ; $48
	const SFX_49              ; $49
	const SFX_4A              ; $4a
	const SFX_4B              ; $4b
	const SFX_4C              ; $4c
	const SFX_4D              ; $4d
	const SFX_4E              ; $4e
	const SFX_4F              ; $4f
	const SFX_50              ; $50
	const SFX_51              ; $51
	const SFX_52              ; $52
	const SFX_53              ; $53
	const SFX_54              ; $54
	const SFX_55              ; $55
	const SFX_56              ; $56
	const SFX_57              ; $57
	const SFX_58              ; $58
	const SFX_59              ; $59
	const SFX_5A              ; $5a
	const SFX_5B              ; $5b
	const SFX_5C              ; $5c
	const SFX_5D              ; $5d
	const SFX_5E              ; $5e
	const SFX_5F              ; $5f
	const SFX_60              ; $60
	const SFX_61              ; $61
	const SFX_62              ; $62
	const SFX_63              ; $63
	const SFX_64              ; $64
	const SFX_65              ; $65
	const SFX_66              ; $66
	const SFX_67              ; $67
	const SFX_68              ; $68
	const SFX_69              ; $69
	const SFX_6A              ; $6a
	const SFX_6B              ; $6b
	const SFX_6C              ; $6c
	const SFX_6D              ; $6d
	const SFX_6E              ; $6e
	const SFX_6F              ; $6f
	const SFX_70              ; $70
	const SFX_71              ; $71
	const SFX_72              ; $72
	const SFX_73              ; $73
	const SFX_74              ; $74
	const SFX_75              ; $75
	const SFX_76              ; $76
	const SFX_77              ; $77
	const SFX_78              ; $78
	const SFX_79              ; $79
	const SFX_7A              ; $7a
	const SFX_7B              ; $7b
	const SFX_CHIPS_COUNTING  ; $7c
	const SFX_7D              ; $7d
	const SFX_7E              ; $7e
	const SFX_7F              ; $7f
	const SFX_80              ; $80
	const SFX_81              ; $81
	const SFX_82              ; $82
	const SFX_83              ; $83
	const SFX_84              ; $84
	const SFX_85              ; $85
	const SFX_86              ; $86
	const SFX_87              ; $87
	const SFX_88              ; $88
	const SFX_89              ; $89
	const SFX_8A              ; $8a
	const SFX_8B              ; $8b
	const SFX_8C              ; $8c
	const SFX_8D              ; $8d
	const SFX_8E              ; $8e
	const SFX_8F              ; $8f
	const SFX_90              ; $90
	const SFX_91              ; $91
	const SFX_92              ; $92
	const SFX_93              ; $93
	const SFX_94              ; $94
	const SFX_95              ; $95
	const SFX_96              ; $96
	const SFX_97              ; $97
	const SFX_98              ; $98
	const SFX_99              ; $99
	const SFX_9A              ; $9a
	const SFX_9B              ; $9b
	const SFX_9C              ; $9c
	const SFX_9D              ; $9d
	const SFX_9E              ; $9e
	const SFX_9F              ; $9f
	const SFX_A0              ; $a0

DEF NUM_SFX EQU const_value
