	const_def
	const TILESET_TCG_ISLAND                  ; $000
	const TILESET_TCG_OAM                     ; $001
	const TILESET_GR_ISLAND                   ; $002
	const TILESET_GR_OAM                      ; $003
	const TILESET_MASON_LAB_MAIN              ; $004
	const TILESET_MASON_LAB_SIDE_1            ; $005
	const TILESET_MASON_LAB_SIDE_2            ; $006
	const TILESET_ISHIHARA_HOUSE              ; $007
	const TILESET_LIGHTNING_CLUB_ENTRANCE     ; $008
	const TILESET_LIGHTNING_CLUB_LOBBY        ; $009
	const TILESET_LIGHTNING_CLUB              ; $00a
	const TILESET_PSYCHIC_CLUB_ENTRANCE       ; $00b
	const TILESET_PSYCHIC_CLUB_LOBBY          ; $00c
	const TILESET_PSYCHIC_CLUB                ; $00d
	const TILESET_ROCK_CLUB_ENTRANCE          ; $00e
	const TILESET_ROCK_CLUB_LOBBY             ; $00f
	const TILESET_ROCK_CLUB                   ; $010
	const TILESET_FIGHTING_CLUB_ENTRANCE      ; $011
	const TILESET_FIGHTING_CLUB_LOBBY         ; $012
	const TILESET_FIGHTING_CLUB               ; $013
	const TILESET_GRASS_CLUB_ENTRANCE         ; $014
	const TILESET_GRASS_CLUB_LOBBY            ; $015
	const TILESET_GRASS_CLUB                  ; $016
	const TILESET_SCIENCE_CLUB_ENTRANCE       ; $017
	const TILESET_SCIENCE_CLUB_LOBBY          ; $018
	const TILESET_SCIENCE_CLUB                ; $019
	const TILESET_WATER_CLUB_ENTRANCE         ; $01a
	const TILESET_WATER_CLUB_LOBBY            ; $01b
	const TILESET_WATER_CLUB                  ; $01c
	const TILESET_FIRE_CLUB_ENTRANCE          ; $01d
	const TILESET_FIRE_CLUB_LOBBY             ; $01e
	const TILESET_FIRE_CLUB                   ; $01f
	const TILESET_TCG_AIRPORT_ENTRANCE        ; $020
	const TILESET_TCG_AIRPORT                 ; $021
	const TILESET_TCG_CHALLENGE_HALL_ENTRANCE ; $022
	const TILESET_TCG_CHALLENGE_HALL_LOBBY    ; $023
	const TILESET_TCG_CHALLENGE_HALL          ; $024
	const TILESET_POKEMON_DOME_ENTRANCE       ; $025
	const TILESET_POKEMON_DOME                ; $026
	const TILESET_OVERHEAD_ISLANDS            ; $027
	const TILESET_GR_AIRPORT_ENTRANCE         ; $028
	const TILESET_GR_AIRPORT                  ; $029
	const TILESET_ISHIHARA_VILLA_1            ; $02a
	const TILESET_ISHIHARA_VILLA_2            ; $02b
	const TILESET_GAME_CENTER_ENTRANCE        ; $02c
	const TILESET_GAME_CENTER_LOBBY           ; $02d
	const TILESET_GAME_CENTER_1               ; $02e
	const TILESET_GAME_CENTER_2               ; $02f
	const TILESET_CARD_DUNGEON_PAWN           ; $030
	const TILESET_CARD_DUNGEON_KNIGHT         ; $031
	const TILESET_CARD_DUNGEON_BISHOP         ; $032
	const TILESET_CARD_DUNGEON_ROOK           ; $033
	const TILESET_CARD_DUNGEON_QUEEN          ; $034
	const TILESET_SEALED_FORT_ENTRANCE        ; $035
	const TILESET_SEALED_FORT                 ; $036
	const TILESET_GR_CHALLENGE_HALL_ENTRANCE  ; $037
	const TILESET_GR_CHALLENGE_HALL_LOBBY     ; $038
	const TILESET_GR_CHALLENGE_HALL           ; $039
	const TILESET_GRASS_FORT_ENTRANCE         ; $03a
	const TILESET_GRASS_FORT_LOBBY            ; $03b
	const TILESET_GRASS_FORT_MIDORI           ; $03c
	const TILESET_GRASS_FORT_YUUTA            ; $03d
	const TILESET_GRASS_FORT_MIYUKI           ; $03e
	const TILESET_GRASS_FORT_MORINO           ; $03f
	const TILESET_LIGHTNING_FORT_ENTRANCE     ; $040
	const TILESET_LIGHTNING_FORT_LOBBY        ; $041
	const TILESET_LIGHTNING_FORT_RENNA        ; $042
	const TILESET_LIGHTNING_FORT_ICHIKAWA     ; $043
	const TILESET_LIGHTNING_FORT_CATHERINE    ; $044
	const TILESET_FIRE_FORT_ENTRANCE          ; $045
	const TILESET_FIRE_FORT_LOBBY             ; $046
	const TILESET_FIRE_FORT_JES               ; $047
	const TILESET_FIRE_FORT_YUKI              ; $048
	const TILESET_FIRE_FORT_SHOKO             ; $049
	const TILESET_FIRE_FORT_HIDERO            ; $04a
	const TILESET_WATER_FORT_ENTRANCE         ; $04b
	const TILESET_WATER_FORT_LOBBY            ; $04c
	const TILESET_WATER_FORT_MIYAJIMA         ; $04d
	const TILESET_WATER_FORT_SENTA            ; $04e
	const TILESET_WATER_FORT_AIRA             ; $04f
	const TILESET_WATER_FORT_KANOKO           ; $050
	const TILESET_FIGHTING_FORT_ENTRANCE      ; $051
	const TILESET_FIGHTING_FORT               ; $052
	const TILESET_FIGHTING_FORT_MAZE_1        ; $053
	const TILESET_FIGHTING_FORT_MAZE_2        ; $054
	const TILESET_FIGHTING_FORT_MAZE_3        ; $055
	const TILESET_FIGHTING_FORT_MAZE_4        ; $056
	const TILESET_FIGHTING_FORT_MAZE_5        ; $057
	const TILESET_FIGHTING_FORT_MAZE_6        ; $058
	const TILESET_FIGHTING_FORT_GODA          ; $059
	const TILESET_FIGHTING_FORT_GRACE         ; $05a
	const TILESET_PSYCHIC_STRONGHOLD_ENTRANCE ; $05b
	const TILESET_PSYCHIC_STRONGHOLD_LOBBY    ; $05c
	const TILESET_PSYCHIC_STRONGHOLD          ; $05d
	const TILESET_PSYCHIC_STRONGHOLD_MAMI     ; $05e
	const TILESET_COLORLESS_ALTAR_ENTRANCE    ; $05f
	const TILESET_COLORLESS_ALTAR             ; $060
	const TILESET_GR_CASTLE_ENTRANCE          ; $061
	const TILESET_GR_CASTLE                   ; $062
	const TILESET_GR_CASTLE_BIRURITCHI        ; $063
	const TILESET_POKEMON_DOME_BACK           ; $064
	const TILESET_FIGHTING_FORT_MAZE_7        ; $065
	const TILESET_FIGHTING_FORT_MAZE_8        ; $066
	const TILESET_FIGHTING_FORT_MAZE_9        ; $067
	const TILESET_FIGHTING_FORT_MAZE_10       ; $068
	const TILESET_FIGHTING_FORT_MAZE_11       ; $069
	const TILESET_FIGHTING_FORT_MAZE_12       ; $06a
	const TILESET_FIGHTING_FORT_MAZE_13       ; $06b
	const TILESET_FIGHTING_FORT_MAZE_14       ; $06c
	const TILESET_FIGHTING_FORT_MAZE_15       ; $06d
	const TILESET_FIGHTING_FORT_MAZE_16       ; $06e
	const TILESET_FIGHTING_FORT_MAZE_17       ; $06f
	const TILESET_FIGHTING_FORT_MAZE_18       ; $070
	const TILESET_FIGHTING_FORT_MAZE_19       ; $071
	const TILESET_FIGHTING_FORT_MAZE_20       ; $072
	const TILESET_FIGHTING_FORT_MAZE_21       ; $073
	const TILESET_FIGHTING_FORT_MAZE_22       ; $074
	const TILESET_FIGHTING_FORT_BASEMENT      ; $075
	const TILESET_GR_CHALLENGE_HALL_2         ; $076
	const TILESET_CHEST                       ; $077
	const TILESET_POD_DOORS                   ; $078
	const TILESET_FIRE                        ; $079
	const TILESET_PLATFORM                    ; $07a
	const TILESET_COINS_FORT                  ; $07b
	const TILESET_COINS_CASTLE                ; $07c
	const TILESET_MARK_PORTRAIT               ; $07d
	const TILESET_MINT_PORTRAIT               ; $07e
	const TILESET_MARK_LINK_PORTRAIT          ; $07f
	const TILESET_MINT_LINK_PORTRAIT          ; $080
	const TILESET_RONALD_PORTRAIT             ; $081
	const TILESET_SAM_PORTRAIT                ; $082
	const TILESET_AARON_PORTRAIT              ; $083
	const TILESET_ISHIHARA_PORTRAIT           ; $084
	const TILESET_IMAKUNI_BLACK_PORTRAIT      ; $085
	const TILESET_IMAKUNI_RED_PORTRAIT        ; $086
	const TILESET_ISAAC_PORTRAIT              ; $087
	const TILESET_JENNIFER_PORTRAIT           ; $088
	const TILESET_NICHOLAS_PORTRAIT           ; $089
	const TILESET_BRANDON_PORTRAIT            ; $08a
	const TILESET_MURRAY_PORTRAIT             ; $08b
	const TILESET_STEPHANIE_PORTRAIT          ; $08c
	const TILESET_DANIEL_PORTRAIT             ; $08d
	const TILESET_ROBERT_PORTRAIT             ; $08e
	const TILESET_GENE_PORTRAIT               ; $08f
	const TILESET_MATTHEW_PORTRAIT            ; $090
	const TILESET_RYAN_PORTRAIT               ; $091
	const TILESET_ANDREW_PORTRAIT             ; $092
	const TILESET_MITCH_PORTRAIT              ; $093
	const TILESET_MICHAEL_PORTRAIT            ; $094
	const TILESET_CHRIS_PORTRAIT              ; $095
	const TILESET_JESSICA_PORTRAIT            ; $096
	const TILESET_NIKKI_PORTRAIT              ; $097
	const TILESET_BRITTANY_PORTRAIT           ; $098
	const TILESET_KRISTIN_PORTRAIT            ; $099
	const TILESET_HEATHER_PORTRAIT            ; $09a
	const TILESET_RICK_PORTRAIT               ; $09b
	const TILESET_JOSEPH_PORTRAIT             ; $09c
	const TILESET_DAVID_PORTRAIT              ; $09d
	const TILESET_ERIK_PORTRAIT               ; $09e
	const TILESET_AMY_PORTRAIT                ; $09f
	const TILESET_JOSHUA_PORTRAIT             ; $0a0
	const TILESET_SARA_PORTRAIT               ; $0a1
	const TILESET_AMANDA_PORTRAIT             ; $0a2
	const TILESET_KEN_PORTRAIT                ; $0a3
	const TILESET_JOHN_PORTRAIT               ; $0a4
	const TILESET_ADAM_PORTRAIT               ; $0a5
	const TILESET_JONATHAN_PORTRAIT           ; $0a6
	const TILESET_COURTNEY_PORTRAIT           ; $0a7
	const TILESET_STEVE_PORTRAIT              ; $0a8
	const TILESET_JACK_PORTRAIT               ; $0a9
	const TILESET_ROD_PORTRAIT                ; $0aa
	const TILESET_EIJI_PORTRAIT               ; $0ab
	const TILESET_MAGICIAN_PORTRAIT           ; $0ac
	const TILESET_YUI_PORTRAIT                ; $0ad
	const TILESET_TOSHIRON_PORTRAIT           ; $0ae
	const TILESET_PIERROT_PORTRAIT            ; $0af
	const TILESET_ANNA_PORTRAIT               ; $0b0
	const TILESET_DEE_PORTRAIT                ; $0b1
	const TILESET_MASQUERADE_PORTRAIT         ; $0b2
	const TILESET_PAWN_PORTRAIT               ; $0b3
	const TILESET_KNIGHT_PORTRAIT             ; $0b4
	const TILESET_BISHOP_PORTRAIT             ; $0b5
	const TILESET_ROOK_PORTRAIT               ; $0b6
	const TILESET_QUEEN_PORTRAIT              ; $0b7
	const TILESET_GR_1_PORTRAIT               ; $0b8
	const TILESET_GR_2_PORTRAIT               ; $0b9
	const TILESET_GR_3_PORTRAIT               ; $0ba
	const TILESET_GR_4_PORTRAIT               ; $0bb
	const TILESET_MIDORI_PORTRAIT             ; $0bc
	const TILESET_YUUTA_PORTRAIT              ; $0bd
	const TILESET_MIYUKI_PORTRAIT             ; $0be
	const TILESET_MORINO_PORTRAIT             ; $0bf
	const TILESET_RENNA_PORTRAIT              ; $0c0
	const TILESET_ICHIKAWA_PORTRAIT           ; $0c1
	const TILESET_CATHERINE_PORTRAIT          ; $0c2
	const TILESET_TAP_PORTRAIT                ; $0c3
	const TILESET_JES_PORTRAIT                ; $0c4
	const TILESET_YUKI_PORTRAIT               ; $0c5
	const TILESET_SHOKO_PORTRAIT              ; $0c6
	const TILESET_HIDERO_PORTRAIT             ; $0c7
	const TILESET_MIYAJIMA_PORTRAIT           ; $0c8
	const TILESET_SENTA_PORTRAIT              ; $0c9
	const TILESET_AIRA_PORTRAIT               ; $0ca
	const TILESET_KANOKO_PORTRAIT             ; $0cb
	const TILESET_GODA_PORTRAIT               ; $0cc
	const TILESET_GRACE_PORTRAIT              ; $0cd
	const TILESET_KAMIYA_PORTRAIT             ; $0ce
	const TILESET_MIWA_PORTRAIT               ; $0cf
	const TILESET_KEVIN_PORTRAIT              ; $0d0
	const TILESET_YOSUKE_PORTRAIT             ; $0d1
	const TILESET_RYOKO_PORTRAIT              ; $0d2
	const TILESET_MAMI_PORTRAIT               ; $0d3
	const TILESET_NISHIJIMA_PORTRAIT          ; $0d4
	const TILESET_ISHII_PORTRAIT              ; $0d5
	const TILESET_SAMEJIMA_PORTRAIT           ; $0d6
	const TILESET_KANZAKI_PORTRAIT            ; $0d7
	const TILESET_RUI_PORTRAIT                ; $0d8
	const TILESET_BIRURITCHI_PORTRAIT         ; $0d9
	const TILESET_GR_X_PORTRAIT               ; $0da
	const TILESET_TOBI_CHAN_PORTRAIT          ; $0db
	const TILESET_DR_MASON_PORTRAIT           ; $0dc
	const TILESET_MARK                        ; $0dd
	const TILESET_MINT                        ; $0de
	const TILESET_DR_MASON                    ; $0df
	const TILESET_RONALD                      ; $0e0
	const TILESET_ISHIHARA                    ; $0e1
	const TILESET_IMAKUNI_BLACK               ; $0e2
	const TILESET_IMAKUNI_RED                 ; $0e3
	const TILESET_ISAAC                       ; $0e4
	const TILESET_MURRAY                      ; $0e5
	const TILESET_GENE                        ; $0e6
	const TILESET_MITCH                       ; $0e7
	const TILESET_NIKKI                       ; $0e8
	const TILESET_RICK                        ; $0e9
	const TILESET_AMY                         ; $0ea
	const TILESET_AMY_COPY                    ; $0eb
	const TILESET_SARA                        ; $0ec
	const TILESET_AMANDA                      ; $0ed
	const TILESET_KEN                         ; $0ee
	const TILESET_COURTNEY                    ; $0ef
	const TILESET_STEVE                       ; $0f0
	const TILESET_JACK                        ; $0f1
	const TILESET_ROD                         ; $0f2
	const TILESET_EIJI                        ; $0f3
	const TILESET_MAGICIAN                    ; $0f4
	const TILESET_TOSHIRON                    ; $0f5
	const TILESET_PIERROT                     ; $0f6
	const TILESET_ANNA                        ; $0f7
	const TILESET_DEE                         ; $0f8
	const TILESET_MASQUERADE                  ; $0f9
	const TILESET_PAWN                        ; $0fa
	const TILESET_KNIGHT                      ; $0fb
	const TILESET_BISHOP                      ; $0fc
	const TILESET_ROOK                        ; $0fd
	const TILESET_QUEEN                       ; $0fe
	const TILESET_GR_1                        ; $0ff
	const TILESET_GR_2                        ; $100
	const TILESET_GR_3                        ; $101
	const TILESET_GR_4                        ; $102
	const TILESET_GR_5                        ; $103
	const TILESET_MIDORI                      ; $104
	const TILESET_MORINO                      ; $105
	const TILESET_RENNA                       ; $106
	const TILESET_ICHIKAWA                    ; $107
	const TILESET_CATHERINE                   ; $108
	const TILESET_JES                         ; $109
	const TILESET_YUKI                        ; $10a
	const TILESET_SHOKO                       ; $10b
	const TILESET_HIDERO                      ; $10c
	const TILESET_AIRA                        ; $10d
	const TILESET_KANOKO                      ; $10e
	const TILESET_GODA                        ; $10f
	const TILESET_GRACE                       ; $110
	const TILESET_KAMIYA                      ; $111
	const TILESET_MIWA                        ; $112
	const TILESET_KEVIN                       ; $113
	const TILESET_YOSUKE                      ; $114
	const TILESET_RYOKO                       ; $115
	const TILESET_MAMI                        ; $116
	const TILESET_NISHIJIMA                   ; $117
	const TILESET_ISHII                       ; $118
	const TILESET_SAMEJIMA                    ; $119
	const TILESET_KANZAKI                     ; $11a
	const TILESET_RUI                         ; $11b
	const TILESET_BIRURITCHI                  ; $11c
	const TILESET_GR_X                        ; $11d
	const TILESET_TOBI_CHAN                   ; $11e
	const TILESET_YOUNGSTER                   ; $11f
	const TILESET_LAD                         ; $120
	const TILESET_SPECS                       ; $121
	const TILESET_BUTCH                       ; $122
	const TILESET_MANIA                       ; $123
	const TILESET_JOSHUA                      ; $124
	const TILESET_HOOD                        ; $125
	const TILESET_TECH                        ; $126
	const TILESET_CHAP                        ; $127
	const TILESET_MAN                         ; $128
	const TILESET_PAPPY                       ; $129
	const TILESET_GAMBLER                     ; $12a
	const TILESET_GR_LAD                      ; $12b
	const TILESET_GR_CHAP                     ; $12c
	const TILESET_MIYAJIMA                    ; $12d
	const TILESET_GR_PAPPY                    ; $12e
	const TILESET_DEALER_BOY                  ; $12f
	const TILESET_MONOCLE                     ; $130
	const TILESET_GIRL                        ; $131
	const TILESET_LASS1                       ; $132
	const TILESET_LASS2                       ; $133
	const TILESET_LASS3                       ; $134
	const TILESET_SWIMMER                     ; $135
	const TILESET_GAL                         ; $136
	const TILESET_WOMAN                       ; $137
	const TILESET_GRANNY                      ; $138
	const TILESET_GR_STAFF                    ; $139
	const TILESET_GR_LASS                     ; $13a
	const TILESET_GR_GAL                      ; $13b
	const TILESET_GR_WOMAN                    ; $13c
	const TILESET_GR_GRANNY                   ; $13d
	const TILESET_CHIP_GIRL                   ; $13e
	const TILESET_DEALER_GIRL                 ; $13f
	const TILESET_CLERK                       ; $140
	const TILESET_GR_CLERK                    ; $141
	const TILESET_CAPTURED_AMY                ; $142
	const TILESET_CAPTURED_SARA               ; $143
	const TILESET_CAPTURED_AMANDA             ; $144
	const TILESET_WARP_SPARKLES               ; $145
	const TILESET_GR_BLIMP                    ; $146
	const TILESET_TRACTOR_BEAM                ; $147
	const TILESET_HIT                         ; $148
	const TILESET_PARALYSIS                   ; $149
	const TILESET_SLEEP                       ; $14a
	const TILESET_CONFUSION_STAR              ; $14b
	const TILESET_POISON                      ; $14c
	const TILESET_GLOW                        ; $14d
	const TILESET_DAMAGE                      ; $14e
	const TILESET_THUNDER                     ; $14f
	const TILESET_LIGHTING                    ; $150
	const TILESET_SPARK                       ; $151
	const TILESET_BIG_LIGHTING                ; $152
	const TILESET_EMBER                       ; $153
	const TILESET_FIRE_SPIN                   ; $154
	const TILESET_FIRE_BIRD                   ; $155
	const TILESET_WATER_DROP                  ; $156
	const TILESET_WATER_GUN                   ; $157
	const TILESET_WHIRLPOOL                   ; $158
	const TILESET_HYDRO_PUMP                  ; $159
	const TILESET_SNOW                        ; $15a
	const TILESET_PSYCHIC                     ; $15b
	const TILESET_EVIL_EYES                   ; $15c
	const TILESET_BEAM                        ; $15d
	const TILESET_HYPER_BEAM                  ; $15e
	const TILESET_ROCK                        ; $15f
	const TILESET_PUNCH                       ; $160
	const TILESET_STRETCH_KICK                ; $161
	const TILESET_SLASH                       ; $162
	const TILESET_VINE_WHIP                   ; $163
	const TILESET_SONIC_BOOM                  ; $164
	const TILESET_HORN_DRILL                  ; $165
	const TILESET_POT_SMASH                   ; $166
	const TILESET_BONE                        ; $167
	const TILESET_SEISMIC_TOSS                ; $168
	const TILESET_NEEDLES                     ; $169
	const TILESET_GAS                         ; $16a
	const TILESET_POWDER                      ; $16b
	const TILESET_GOO                         ; $16c
	const TILESET_BUBBLE                      ; $16d
	const TILESET_STRING_SHOT                 ; $16e
	const TILESET_HEART                       ; $16f
	const TILESET_LURE                        ; $170
	const TILESET_SKULL                       ; $171
	const TILESET_CONFUSE_RAY                 ; $172
	const TILESET_NOTES                       ; $173
	const TILESET_SOUND                       ; $174
	const TILESET_PETAL                       ; $175
	const TILESET_PROTECT                     ; $176
	const TILESET_BARRIER                     ; $177
	const TILESET_SPEED                       ; $178
	const TILESET_WHIRLWIND                   ; $179
	const TILESET_SNIVEL                      ; $17a
	const TILESET_QUESTION_MARK               ; $17b
	const TILESET_EXPLOSION                   ; $17c
	const TILESET_HEAL                        ; $17d
	const TILESET_DRAIN                       ; $17e
	const TILESET_SMALL_GLOW                  ; $17f
	const TILESET_EXPAND                      ; $180
	const TILESET_CAT_PUNCH                   ; $181
	const TILESET_ELECTRIC_WAVE               ; $182
	const TILESET_FIREBALLS                   ; $183
	const TILESET_BENCH_MANIP                 ; $184
	const TILESET_PSYCHIC_BEAM                ; $185
	const TILESET_BENCH_PSYCHIC_BEAM          ; $186
	const TILESET_ROCK_THROW                  ; $187
	const TILESET_MEGA_PUNCH                  ; $188
	const TILESET_PSYPUNCH                    ; $189
	const TILESET_SLUDGE_PUNCH                ; $18a
	const TILESET_ICE_PUNCH                   ; $18b
	const TILESET_KICK                        ; $18c
	const TILESET_TAIL_SLAP                   ; $18d
	const TILESET_TAIL_WHIP                   ; $18e
	const TILESET_SLAP                        ; $18f
	const TILESET_QUESTION_MARK_SMALL         ; $190
	const TILESET_SKULL_BASH                  ; $191
	const TILESET_COIN_HURL                   ; $192
	const TILESET_193                         ; $193
	const TILESET_FOLLOW_ME                   ; $194
	const TILESET_SWIFT                       ; $195
	const TILESET_3D_ATTACK                   ; $196
	const TILESET_WATER_DROP2                 ; $197
	const TILESET_FOCUS_BLAST                 ; $198
	const TILESET_FOCUS_BLAST_BENCH           ; $199
	const TILESET_BONE2                       ; $19a
	const TILESET_BIG_SNORE                   ; $19b
	const TILESET_RAZOR_LEAF                  ; $19c
	const TILESET_GUILLOTINE                  ; $19d
	const TILESET_VINE_PULL                   ; $19e
	const TILESET_PERPLEX                     ; $19f
	const TILESET_NINE_TAILS                  ; $1a0
	const TILESET_BONE_HEADBUTT               ; $1a1
	const TILESET_DRILL_DIVE                  ; $1a2
	const TILESET_DARK_SONG                   ; $1a3
	const TILESET_CARD                        ; $1a4
	const TILESET_TCG1_PIKACHU_COIN           ; $1a5
	const TILESET_DUEL_RESULT		  ; $1a6
	const TILESET_SMALL_COINS                 ; $1a7
	const TILESET_CHANSEY_COIN                ; $1a8
	const TILESET_ODDISH_COIN                 ; $1a9
	const TILESET_CHARMANDER_COIN             ; $1aa
	const TILESET_STARMIE_COIN                ; $1ab
	const TILESET_PIKACHU_COIN                ; $1ac
	const TILESET_ALAKAZAM_COIN               ; $1ad
	const TILESET_KABUTO_COIN                 ; $1ae
	const TILESET_GR_COIN                     ; $1af
	const TILESET_GOLBAT_COIN                 ; $1b0
	const TILESET_MAGNEMITE_COIN              ; $1b1
	const TILESET_MAGMAR_COIN                 ; $1b2
	const TILESET_PSYDUCK_COIN                ; $1b3
	const TILESET_MACHAMP_COIN                ; $1b4
	const TILESET_MEW_COIN                    ; $1b5
	const TILESET_SNORLAX_COIN                ; $1b6
	const TILESET_TOGEPI_COIN                 ; $1b7
	const TILESET_PONYTA_COIN                 ; $1b8
	const TILESET_HORSEA_COIN                 ; $1b9
	const TILESET_ARBOK_COIN                  ; $1ba
	const TILESET_JIGGLYPUFF_COIN             ; $1bb
	const TILESET_DUGTRIO_COIN                ; $1bc
	const TILESET_GENGAR_COIN                 ; $1bd
	const TILESET_RAICHU_COIN                 ; $1be
	const TILESET_LUGIA_COIN                  ; $1bf
	const TILESET_BEGINNING_PACK              ; $1c0
	const TILESET_LEGENDARY_PACK              ; $1c1
	const TILESET_FOSSIL_PACK                 ; $1c2
	const TILESET_PSYCHIC_PACK                ; $1c3
	const TILESET_FLYING_PACK                 ; $1c4
	const TILESET_ROCKET_PACK                 ; $1c5
	const TILESET_AMBITION_PACK               ; $1c6
	const TILESET_PRESENT_PACK                ; $1c7
	const TILESET_INTRO_BASE_SET              ; $1c8
	const TILESET_INTRO_JUNGLE                ; $1c9
	const TILESET_INTRO_FOSSIL                ; $1ca
	const TILESET_INTRO_TEAM_ROCKET           ; $1cb
	const TILESET_PACK_OAM                    ; $1cc
	const TILESET_TITLE_SCREEN                ; $1cd
	const TILESET_START_ENERGIES              ; $1ce
	const TILESET_GB_ERROR                    ; $1cf
	const TILESET_COMPANIES                   ; $1d0
	const TILESET_BLACK_BOX_BG                ; $1d1
	const TILESET_BLACK_BOX_CARD              ; $1d2
	const TILESET_ENVELOPE                    ; $1d3
	const TILESET_WINDOW                      ; $1d4
	const TILESET_TOURNAMENT_TABLE            ; $1d5
	const TILESET_SLOTS_BG_ICONS              ; $1d6
	const TILESET_SLOTS_MESSAGES              ; $1d7
	const TILESET_1D8                         ; $1d8
	const TILESET_CARD_POP_MENU               ; $1d9
	const TILESET_CARD_POP_MENU_OAM           ; $1da
	const TILESET_CARD_POP_SCENE              ; $1db
	const TILESET_LINK_CROSS                  ; $1dc
	const TILESET_CARD_POP_OAM                ; $1dd
	const TILESET_LINK_SCENE                  ; $1de
	const TILESET_RARE_CARD_POP_SCENE         ; $1df
	const TILESET_RARE_CARD_POP_OAM           ; $1e0
	const TILESET_SPECIAL_RULES               ; $1e1
	const TILESET_PRINTER_SCENE               ; $1e2
	const TILESET_PRINTER_OAM                 ; $1e3
	const TILESET_FULL_MAILBOX                ; $1e4
	const TILESET_MAIL_CROSS                  ; $1e5
	const TILESET_MAILBOX                     ; $1e6
	const TILESET_GOT_MAIL_ANIM               ; $1e7
	const TILESET_MAILBOX_COPY                ; $1e8
	const TILESET_SMALL_ENVELOPE              ; $1e9
	const TILESET_DECK_DIAGNOSIS              ; $1ea
	const TILESET_LINK_SCENE_INTRO            ; $1eb
	const TILESET_LINK_OAM                    ; $1ec
	const TILESET_COIN_TOSS_RESULT            ; $1ed
	const TILESET_GR_PIECES                   ; $1ee
