	const_def
	const VAR_00                      ; $00
	const VAR_01                      ; $01
	const VAR_02                      ; $02
	const VAR_03                      ; $03
	const VAR_TIMES_MET_RONALD        ; $04
	const VAR_05                      ; $05
	const VAR_06                      ; $06
	const VAR_07                      ; $07
	const VAR_08                      ; $08
	const VAR_09                      ; $09
	const VAR_0A                      ; $0a
	const VAR_0B                      ; $0b
	const VAR_0C                      ; $0c
	const VAR_0D                      ; $0d
	const VAR_0E                      ; $0e
	const VAR_0F                      ; $0f
	const VAR_10                      ; $10
	const VAR_11                      ; $11
	const VAR_12                      ; $12
	const VAR_13                      ; $13
	const VAR_14                      ; $14
	const VAR_15                      ; $15
	const VAR_16                      ; $16
	const VAR_17                      ; $17
	const VAR_18                      ; $18
	const VAR_19                      ; $19
	const VAR_1A                      ; $1a
	const VAR_1B                      ; $1b
	const VAR_1C                      ; $1c
	const VAR_1D                      ; $1d
	const VAR_1E                      ; $1e
	const VAR_1F                      ; $1f
	const VAR_20                      ; $20
	const VAR_21                      ; $21
	const VAR_IMAKUNI_BLACK_WIN_COUNT ; $22
	const VAR_23                      ; $23
	const VAR_24                      ; $24
	const VAR_25                      ; $25
	const VAR_26                      ; $26
	const VAR_27                      ; $27
	const VAR_28                      ; $28
	const VAR_29                      ; $29
	const VAR_2A                      ; $2a
	const VAR_2B                      ; $2b
	const VAR_2C                      ; $2c
	const VAR_2D                      ; $2d
	const VAR_2E                      ; $2e
	const VAR_2F                      ; $2f
	const VAR_30                      ; $30
	const VAR_31                      ; $31
	const VAR_32                      ; $32
	const VAR_33                      ; $33
	const VAR_34                      ; $34
	const VAR_35                      ; $35
	const VAR_36                      ; $36
	const VAR_37                      ; $37
	const VAR_38                      ; $38
	const VAR_39                      ; $39
	const VAR_3A                      ; $3a
	const VAR_3B                      ; $3b
	const VAR_NPC_DECK_ID             ; $3c
	const VAR_3D                      ; $3d
	const VAR_3E                      ; $3e
