	const_def
	const VAR_00                                       ; $00
	const VAR_01                                       ; $01
	const VAR_ISHIHARA_STATE                           ; $02
	const VAR_03                                       ; $03
	const VAR_TIMES_MET_RONALD                         ; $04
	const VAR_05                                       ; $05
	const VAR_06                                       ; $06
	const VAR_07                                       ; $07
	const VAR_08                                       ; $08
	const VAR_09                                       ; $09
	const VAR_0A                                       ; $0a
	const VAR_0B                                       ; $0b
	const VAR_FINAL_CUP_PLAYED_ROUNDS                  ; $0c
	const VAR_GRAND_MASTER_CUP_STATE                   ; $0d
	const VAR_GRANDMASTERCUP_CURRENT_ROUND             ; $0e
	const VAR_0F                                       ; $0f
	const VAR_GRANDMASTERCUP_PRIZE_INDEX_0             ; $10
	const VAR_GRANDMASTERCUP_PRIZE_INDEX_1             ; $11
	const VAR_GRANDMASTERCUP_PRIZE_INDEX_2             ; $12
	const VAR_GRANDMASTERCUP_PRIZE_INDEX_3             ; $13
	const VAR_GRANDMASTERCUP_OPPONENT_DECK_0           ; $14
	const VAR_GRANDMASTERCUP_OPPONENT_DECK_1           ; $15
	const VAR_GRANDMASTERCUP_OPPONENT_DECK_2           ; $16
	const VAR_GRANDMASTERCUP_OPPONENT_DECK_3           ; $17
	const VAR_GRANDMASTERCUP_OPPONENT_DECK_4           ; $18
	const VAR_GRANDMASTERCUP_OPPONENT_DECK_5           ; $19
	const VAR_GRANDMASTERCUP_OPPONENT_DECK_6           ; $1a
	const VAR_1B                                       ; $1b
	const VAR_1C                                       ; $1c
	const VAR_1D                                       ; $1d
	const VAR_1E                                       ; $1e
	const VAR_GRANDMASTERCUP_OPPONENT_GRAND_MASTER     ; $1f
	const VAR_TIMES_WON_LINK_DUEL_FOR_GRAND_MASTER_CUP ; $20
	const VAR_21                                       ; $21
	const VAR_IMAKUNI_BLACK_WIN_COUNT                  ; $22
	const VAR_23                                       ; $23
	const VAR_24                                       ; $24
	const VAR_25                                       ; $25
	const VAR_26                                       ; $26
	const VAR_27                                       ; $27
	const VAR_TCG_CHALLENGE_CUP_STATE                  ; $28
	const VAR_TCG_CHALLENGE_CUP_PRIZE_INDEX            ; $29
	const VAR_TIMES_WON_TCG_CHALLENGE_CUP              ; $2a
	const VAR_TCG_CHALLENGE_CUP_RESULT                 ; $2b
	const VAR_CHALLENGECUP_CURRENT_ROUND               ; $2c
	const VAR_CHALLENGECUP_ROUND1_OPPONENT_DECK_ID     ; $2d
	const VAR_CHALLENGECUP_ROUND2_OPPONENT_DECK_ID     ; $2e
	const VAR_CHALLENGECUP_ROUND3_OPPONENT_DECK_ID     ; $2f
	const VAR_GR_CHALLENGE_CUP_STATE                   ; $30
	const VAR_GR_CHALLENGE_CUP_PRIZE_INDEX             ; $31
	const VAR_TIMES_WON_GR_CHALLENGE_CUP               ; $32
	const VAR_GR_CHALLENGE_CUP_RESULT                  ; $33
	const VAR_CHALLENGEMACHINE_CURRENT_ROUND           ; $34
	const VAR_CHALLENGEMACHINE_ROUND1_OPPONENT_DECK_ID ; $35
	const VAR_CHALLENGEMACHINE_ROUND2_OPPONENT_DECK_ID ; $36
	const VAR_CHALLENGEMACHINE_ROUND3_OPPONENT_DECK_ID ; $37
	const VAR_CHALLENGEMACHINE_ROUND4_OPPONENT_DECK_ID ; $38
	const VAR_CHALLENGEMACHINE_ROUND5_OPPONENT_DECK_ID ; $39
	const VAR_CARD_DUNGEON_PROGRESS                    ; $3a
	const VAR_3B                                       ; $3b: AARON_STEP_* / Fighting Fort
	const VAR_NPC_DECK_ID                              ; $3c
	const VAR_DUEL_START_THEME                         ; $3d
	const VAR_3E                                       ; $3e

; VAR_ISHIHARA_STATE values
	const_def 1
	const ISHIHARA_HELPING_NIKKI         ; $1
	const ISHIHARA_HELPED_NIKKI          ; $2
	const ISHIHARA_TRADE_1_DONE          ; $3
	const ISHIHARA_TRADE_2_DONE          ; $4
	const ISHIHARA_TRADE_3_DONE          ; $5
	const ISHIHARA_TALKED_AT_VILLA       ; $6
	const ISHIHARA_TRADE_4_DONE          ; $7
	const ISHIHARA_TRADE_5_DONE          ; $8
	const ISHIHARA_TRADE_6_DONE          ; $9
	const ISHIHARA_TRADE_7_DONE_COMPLETE ; $a
