; input:
;  a = PORTRAIT_* constant
;  b = portrait slot (0 or 1)
;  c = portrait variant
;  de = coordinates
DrawPortrait::
	push af
	push bc
	push de
	push hl
	push bc
	push de
	ld e, b
	ld d, c
	push de
	ld e, a
	ld d, 0
	ld bc, 10 ; size of each portrait entry
	call MultiplyBCByDE
	ld b, h
	ld c, l
	pop de
	ld hl, Portraits
	add hl, bc

	; tileset
	ld a, [hli]
	ld c, a
	ld a, [hli]
	ld b, a
	push hl
	farcall GetTilesetGfxPointer
	ld c, d
	call LoadPortraitTiles
	pop hl

	; palette
	ld a, [hli]
	ld c, a
	ld a, [hli]
	ld b, a
	push hl
	farcall GetPaletteGfxPointer
	call LoadPortraitPalettes
	pop hl

	; tilemap
	pop de
	pop bc
	ld a, b ; slot
	ld [wPortraitSlot], a
	ld a, c ; variant
	ld [wPortraitVariant], a
	ld b, $00
	sla c ; *2
	add hl, bc
	ld a, [hli]
	ld c, a
	ld a, [hli]
	ld b, a
	farcall GetTilemapGfxPointer
	ld a, [wPortraitVariant]
	ld c, a
	ld a, [wPortraitSlot]
	farcall LoadPortraitAttributeMap
	pop hl
	pop de
	pop bc
	pop af
	ret

Data_13005b::
	dw OWSPRITE_MARK                  ; OW_MARK
	dw OWSPRITE_MINT                  ; OW_MINT
	dw OWSPRITE_DR_MASON              ; OW_DR_MASON
	dw OWSPRITE_RONALD                ; OW_RONALD
	dw OWSPRITE_ISHIHARA              ; OW_ISHIHARA
	dw OWSPRITE_IMAKUNI_BLACK         ; OW_IMAKUNI_BLACK
	dw OWSPRITE_TECH                  ; OW_TECH_1
	dw OWSPRITE_TECH                  ; OW_TECH_2
	dw OWSPRITE_PAPPY                 ; OW_PAPPY_1
	dw OWSPRITE_GENE                  ; OW_GENE
	dw OWSPRITE_MANIA                 ; OW_MANIA_1
	dw OWSPRITE_YOUNGSTER             ; OW_YOUNGSTER_1
	dw OWSPRITE_MAN                   ; OW_MAN_1
	dw OWSPRITE_MITCH                 ; OW_MITCH
	dw OWSPRITE_MANIA                 ; OW_MANIA_2
	dw OWSPRITE_MANIA                 ; OW_MANIA_3
	dw OWSPRITE_LASS3                 ; OW_LASS3_1
	dw OWSPRITE_NIKKI                 ; OW_NIKKI
	dw OWSPRITE_GIRL                  ; OW_GIRL1
	dw OWSPRITE_LASS2                 ; OW_LASS2_1
	dw OWSPRITE_LASS1                 ; OW_LASS3_1
	dw OWSPRITE_RICK                  ; OW_RICK
	dw OWSPRITE_TECH                  ; OW_TECH_3
	dw OWSPRITE_TECH                  ; OW_TECH_4
	dw OWSPRITE_TECH                  ; OW_TECH_5
	dw OWSPRITE_AMY                   ; OW_AMY
	dw OWSPRITE_AMY_LOUNGE            ; OW_AMY_LOUNGE
	dw OWSPRITE_JOSHUA                ; OW_JOSHUA_1
	dw OWSPRITE_SARA                  ; OW_SARA
	dw OWSPRITE_AMANDA                ; OW_AMANDA
	dw OWSPRITE_KEN                   ; OW_KEN
	dw OWSPRITE_LAD                   ; OW_LAD_1
	dw OWSPRITE_SPECS                 ; OW_SPECS_1
	dw OWSPRITE_YOUNGSTER             ; OW_YOUNGSTER_2
	dw OWSPRITE_ISAAC                 ; OW_ISAAC
	dw OWSPRITE_GIRL                  ; OW_GIRL_2
	dw OWSPRITE_HOOD                  ; OW_HOOD_1
	dw OWSPRITE_HOOD                  ; OW_HOOD_2
	dw OWSPRITE_MURRAY                ; OW_MURRAY
	dw OWSPRITE_YOUNGSTER             ; OW_YOUNGSTER_3
	dw OWSPRITE_LAD                   ; OW_LAD_2
	dw OWSPRITE_GIRL                  ; OW_GIRL_3
	dw OWSPRITE_COURTNEY              ; OW_COURTNEY
	dw OWSPRITE_STEVE                 ; OW_STEVE
	dw OWSPRITE_JACK                  ; OW_JACK
	dw OWSPRITE_ROD                   ; OW_ROD
	dw OWSPRITE_GR_1                  ; OW_GR_1
	dw OWSPRITE_GR_2                  ; OW_GR_2
	dw OWSPRITE_GR_3                  ; OW_GR_3
	dw OWSPRITE_GR_4                  ; OW_GR_4
	dw OWSPRITE_GR_5                  ; OW_GR_5
	dw OWSPRITE_GR_LAD                ; OW_GR_LAD_1
	dw OWSPRITE_MIDORI                ; OW_MIDORI_1
	dw OWSPRITE_MORINO                ; OW_MORINO_1
	dw OWSPRITE_MIDORI                ; OW_MIDORI_2
	dw OWSPRITE_MORINO                ; OW_MORINO_2
	dw OWSPRITE_GR_LASS               ; OW_GR_LASS_1
	dw OWSPRITE_RENNA                 ; OW_RENNA
	dw OWSPRITE_ICHIKAWA              ; OW_ICHIKAWA
	dw OWSPRITE_CATHERINE             ; OW_CATHERINE
	dw OWSPRITE_GR_GRANNY             ; OW_GR_GRANNY_1
	dw OWSPRITE_MIYAJIMA              ; OW_MIYAJIMA_1
	dw OWSPRITE_JES                   ; OW_JES
	dw OWSPRITE_YUKI                  ; OW_YUKI
	dw OWSPRITE_SHOKO                 ; OW_SHOKO
	dw OWSPRITE_HIDERO                ; OW_HIDERO
	dw OWSPRITE_SPECS                 ; OW_SPECS_2
	dw OWSPRITE_MIYAJIMA              ; OW_MIYAJIMA_2
	dw OWSPRITE_JOSHUA                ; OW_JOSHUA_2
	dw OWSPRITE_AIRA                  ; OW_AIRA
	dw OWSPRITE_KANOKO                ; OW_KANOKO
	dw OWSPRITE_GODA                  ; OW_GODA
	dw OWSPRITE_GRACE                 ; OW_GRACE
	dw OWSPRITE_KAMIYA                ; OW_KAMIYA
	dw OWSPRITE_GAL                   ; OW_GAL_1
	dw OWSPRITE_MIWA                  ; OW_MIWA
	dw OWSPRITE_KEVIN                 ; OW_KEVIN
	dw OWSPRITE_YOSUKE                ; OW_YOSUKE
	dw OWSPRITE_RYOKO                 ; OW_RYOKO
	dw OWSPRITE_MAMI                  ; OW_MAMI
	dw OWSPRITE_NISHIJIMA             ; OW_NISHIJIMA
	dw OWSPRITE_ISHII                 ; OW_ISHII
	dw OWSPRITE_SAMEJIMA              ; OW_SAMEJIMA
	dw OWSPRITE_KANZAKI               ; OW_KANZAKI
	dw OWSPRITE_RUI                   ; OW_RUI
	dw OWSPRITE_BIRURITCHI            ; OW_BIRURITCHI
	dw OWSPRITE_TOBI_CHAN             ; OW_TOBI_CHAN
	dw OWSPRITE_EIJI                  ; OW_EIJI
	dw OWSPRITE_MAGICIAN              ; OW_MAGICIAN
	dw OWSPRITE_TOSHIRON              ; OW_TOSHIRON
	dw OWSPRITE_PIERROT               ; OW_PIERROT
	dw OWSPRITE_ANNA                  ; OW_ANNA
	dw OWSPRITE_DEE                   ; OW_DEE
	dw OWSPRITE_MASQUERADE            ; OW_MASQUERADE
	dw OWSPRITE_PAWN                  ; OW_PAWN
	dw OWSPRITE_KNIGHT                ; OW_KNIGHT
	dw OWSPRITE_BISHOP                ; OW_BISHOP
	dw OWSPRITE_ROOK                  ; OW_ROOK
	dw OWSPRITE_QUEEN                 ; OW_QUEEN
	dw OWSPRITE_GR_X                  ; OW_GR_X
	dw OWSPRITE_CLERK                 ; OW_CLERK_1
	dw OWSPRITE_CLERK                 ; OW_CLERK_2
	dw OWSPRITE_GR_CLERK              ; OW_GR_CLERK_1
	dw OWSPRITE_GR_CLERK              ; OW_GR_CLERK_2
	dw OWSPRITE_GR_CLERK              ; OW_GR_CLERK_3
	dw OWSPRITE_GR_CLERK              ; OW_GR_CLERK_4
	dw OWSPRITE_LASS2                 ; OW_LASS2_2
	dw OWSPRITE_WOMAN                 ; OW_WOMAN
	dw OWSPRITE_CHAP                  ; OW_CHAP_1
	dw OWSPRITE_LAD                   ; OW_LAD_3
	dw OWSPRITE_PAPPY                 ; OW_PAPPY_2
	dw OWSPRITE_SPECS                 ; OW_SPECS_3
	dw OWSPRITE_LAD                   ; OW_LAD_4
	dw OWSPRITE_GIRL                  ; OW_GIRL_4
	dw OWSPRITE_GRANNY                ; OW_GRANNY
	dw OWSPRITE_LASS2                 ; OW_LASS2_3
	dw OWSPRITE_GIRL                  ; OW_GIRL_5
	dw OWSPRITE_MAN                   ; OW_MAN_2
	dw OWSPRITE_LAD                   ; OW_LAD_5
	dw OWSPRITE_SPECS                 ; OW_SPECS_4
	dw OWSPRITE_TECH                  ; OW_TECH_6
	dw OWSPRITE_PAPPY                 ; OW_PAPPY_3
	dw OWSPRITE_LASS1                 ; OW_LASS1_2
	dw OWSPRITE_LASS2                 ; OW_LASS2_4
	dw OWSPRITE_HOOD                  ; OW_HOOD_3
	dw OWSPRITE_MANIA                 ; OW_MANIA_4
	dw OWSPRITE_GAL                   ; OW_GAL_2
	dw OWSPRITE_LASS3                 ; OW_LASS3_2
	dw OWSPRITE_HOOD                  ; OW_HOOD_4
	dw OWSPRITE_LASS1                 ; OW_LASS1_3
	dw OWSPRITE_CHAP                  ; OW_CHAP_2
	dw OWSPRITE_SPECS                 ; OW_SPECS_5
	dw OWSPRITE_LASS1                 ; OW_LASS1_4
	dw OWSPRITE_LAD                   ; OW_LAD_6
	dw OWSPRITE_GR_LASS               ; OW_GR_LASS_2
	dw OWSPRITE_GR_CLERK              ; OW_GR_CLERK_5
	dw OWSPRITE_GR_GAL                ; OW_GR_GAL_1
	dw OWSPRITE_MANIA                 ; OW_MANIA_5
	dw OWSPRITE_CLERK                 ; OW_CLERK_3
	dw OWSPRITE_CHAP                  ; OW_CHAP_3
	dw OWSPRITE_GAL                   ; OW_GAL_3
	dw OWSPRITE_HOOD                  ; OW_HOOD_5
	dw OWSPRITE_MAN                   ; OW_MAN_3
	dw OWSPRITE_PAPPY                 ; OW_PAPPY_4
	dw OWSPRITE_TECH                  ; OW_TECH_7
	dw OWSPRITE_GIRL                  ; OW_GIRL_6
	dw OWSPRITE_LASS1                 ; OW_LASS1_5
	dw OWSPRITE_LASS2                 ; OW_LASS2_5
	dw OWSPRITE_GR_CLERK              ; OW_GR_CLERK_6
	dw OWSPRITE_GR_PAPPY              ; OW_GR_PAPPY_1
	dw OWSPRITE_GR_LASS               ; OW_GR_LASS_4
	dw OWSPRITE_GR_CLERK              ; OW_GR_CLERK_7
	dw OWSPRITE_GR_LAD                ; OW_GR_LAD2
	dw OWSPRITE_GR_PAPPY              ; OW_GR_PAPPY_2
	dw OWSPRITE_GR_LASS               ; OW_GR_LASS_4
	dw OWSPRITE_GR_CLERK              ; OW_GR_CLERK_8
	dw OWSPRITE_GR_WOMAN              ; OW_GR_WOMAN_1
	dw OWSPRITE_BUTCH                 ; OW_BUTCH_1
	dw OWSPRITE_CHAP                  ; OW_CHAP_4
	dw OWSPRITE_GR_CLERK              ; OW_GR_CLERK_9
	dw OWSPRITE_YOUNGSTER             ; OW_YOUNGSTER_4
	dw OWSPRITE_GR_CLERK              ; OW_GR_CLERK_10
	dw OWSPRITE_GR_GRANNY             ; OW_GR_GRANNY_2
	dw OWSPRITE_GR_GAL                ; OW_GR_GAL2
	dw OWSPRITE_GR_CLERK              ; OW_GR_CLERK_11
	dw OWSPRITE_GR_CLERK              ; OW_GR_CLERK_12
	dw OWSPRITE_MANIA                 ; OW_MANIA_6
	dw OWSPRITE_GR_LASS               ; OW_GRLASS_5
	dw OWSPRITE_GR_CLERK              ; OW_GR_CLERK_13
	dw OWSPRITE_TECH                  ; OW_TECH_8
	dw OWSPRITE_GR_LASS               ; OW_GR_LASS_6
	dw OWSPRITE_GR_PAPPY              ; OW_GR_PAPPY_3
	dw OWSPRITE_CAPTURED_AMY          ; OW_CAPTURED_AMY
	dw OWSPRITE_CAPTURED_SARA         ; OW_CAPTURED_SARA
	dw OWSPRITE_CAPTURED_AMANDA       ; OW_CAPTURED_AMANDA
	dw OWSPRITE_WARP_SPARKLES         ; OW_WARP_SPARKLES
	dw OWSPRITE_LASS2                 ; OW_LASS2_6
	dw OWSPRITE_IMAKUNI_RED           ; OW_IMAKUNI_RED
	dw OWSPRITE_BUTCH                 ; OW_BUTCH_2
	dw OWSPRITE_TECH                  ; OW_TECH_9
	dw OWSPRITE_TECH                  ; OW_TECH_10
	dw OWSPRITE_TECH                  ; OW_TECH_11
	dw OWSPRITE_TECH                  ; OW_TECH_12
	dw OWSPRITE_TECH                  ; OW_TECH_13
	dw OWSPRITE_TECH                  ; OW_TECH_14
	dw OWSPRITE_TECH                  ; OW_TECH_15
	dw OWSPRITE_TECH                  ; OW_TECH_16
	dw OWSPRITE_TECH                  ; OW_TECH_17
	dw OWSPRITE_GR_CLERK              ; OW_GR_CLERK_14
	dw OWSPRITE_GR_CLERK              ; OW_GR_CLERK_15
	dw OWSPRITE_GR_CLERK              ; OW_GR_CLERK_16
	dw OWSPRITE_GR_CLERK              ; OW_GR_CLERK_17
	dw OWSPRITE_CHIP_GIRL             ; OW_CHIP_GIRL_1
	dw OWSPRITE_MONOCLE               ; OW_MONOCLE_1
	dw OWSPRITE_MONOCLE               ; OW_MONOCLE_2
	dw OWSPRITE_DEALER_BOY            ; OW_DEALER_BOY_1
	dw OWSPRITE_DEALER_GIRL           ; OW_DEALER_GIRL_1
	dw OWSPRITE_DEALER_BOY            ; OW_DEALER_BOY_2
	dw OWSPRITE_CHIP_GIRL             ; OW_CHIP_GIRL_2
	dw OWSPRITE_DEALER_GIRL           ; OW_DEALER_GIRL_2
	dw OWSPRITE_VULCANO_SMOKE_TCG     ; OW_VULCANO_SMOKE_TCG
	dw OWSPRITE_VULCANO_SMOKE_GR      ; OW_VULCANO_SMOKE_GR
	dw OWSPRITE_CURSOR_TCG            ; OW_CURSOR_TCG
	dw OWSPRITE_CURSOR_GR             ; OW_CURSOR_GR
	dw OWSPRITE_GR_CROSS              ; OW_GR_CROSS
	dw OWSPRITE_GR_CASTLE_FLAG        ; OW_GR_CASTLE_FLAG
	dw OWSPRITE_CHEST_CLOSED          ; OW_CHEST_CLOSED
	dw OWSPRITE_CHEST_OPENED          ; OW_CHEST_OPENED
	dw OWSPRITE_GR_BLIMP_BEAM         ; OW_GR_BLIMP_BEAM
	dw OWSPRITE_GR_BLIMP              ; OW_GR_BLIMP
	dw OWSPRITE_POD_DOORS             ; OW_POD_DOORS
	dw OWSPRITE_GR_LAD                ; OW_GR_LAD_3
	dw OWSPRITE_GR_LASS               ; OW_GR_LASS_7
	dw OWSPRITE_GR_LASS               ; OW_GR_LASS_8
	dw OWSPRITE_YOUNGSTER             ; OW_YOUNGSTER_5
	dw OWSPRITE_SWIMMER               ; OW_SWIMMER
	dw OWSPRITE_GR_GAL                ; OW_GR_GAL_3
	dw OWSPRITE_BUTCH                 ; OW_BUTCH_3
	dw OWSPRITE_MANIA                 ; OW_MANIA_7
	dw OWSPRITE_GAMBLER               ; OW_GAMBLER
	dw OWSPRITE_GR_WOMAN              ; OW_GR_WOMAN_2
	dw OWSPRITE_GR_GAL                ; OW_GR_GAL_4
	dw OWSPRITE_GR_CLERK              ; OW_GR_CLERK_18
	dw OWSPRITE_GR_CHAP               ; OW_GR_CHAP
	dw OWSPRITE_GR_WOMAN              ; OW_GR_WOMAN_3
	dw OWSPRITE_GR_STAFF              ; OW_GR_STAFF
	dw OWSPRITE_LASS1                 ; OW_LASS1_6
	dw OWSPRITE_LASS2                 ; OW_LASS2_7
	dw OWSPRITE_RED_FORT_COIN         ; OW_RED_FORT_COIN
	dw OWSPRITE_BLUE_FORT_COIN        ; OW_BLUE_FORT_COIN
	dw OWSPRITE_WHITE_CASTLE_COIN     ; OW_WHITE_CASTLE_COIN
	dw OWSPRITE_PURPLE_CASTLE_COIN    ; OW_PURPLE_CASTLE_COIN
	dw OWSPRITE_STRONGHOLD_PLATFORM   ; OW_STRONGHOLD_PLATFORM

Portraits:
	dw TILESET_MARK_PORTRAIT, PALETTE_078, TILEMAP_0D3, TILEMAP_0D3, TILEMAP_0D3          ; PORTRAIT_00
	dw TILESET_MINT_PORTRAIT, PALETTE_079, TILEMAP_0D4, TILEMAP_0D4, TILEMAP_0D4          ; PORTRAIT_01
	dw TILESET_MARK_LINK_PORTRAIT, PALETTE_07A, TILEMAP_0D5, TILEMAP_0D5, TILEMAP_0D5     ; PORTRAIT_02
	dw TILESET_MINT_LINK_PORTRAIT, PALETTE_07B, TILEMAP_0D6, TILEMAP_0D6, TILEMAP_0D6     ; PORTRAIT_03
	dw TILESET_RONALD_PORTRAIT, PALETTE_07C, TILEMAP_0D7, TILEMAP_0D8, TILEMAP_0D9        ; PORTRAIT_04
	dw TILESET_SAM_PORTRAIT, PALETTE_07D, TILEMAP_0DA, TILEMAP_0DB, TILEMAP_0DC           ; PORTRAIT_05
	dw TILESET_AARON_PORTRAIT, PALETTE_07E, TILEMAP_0DD, TILEMAP_0DE, TILEMAP_0DF         ; PORTRAIT_06
	dw TILESET_ISHIHARA_PORTRAIT, PALETTE_07F, TILEMAP_0E0, TILEMAP_0E1, TILEMAP_0E2      ; PORTRAIT_07
	dw TILESET_ISAAC_PORTRAIT, PALETTE_082, TILEMAP_0E9, TILEMAP_0EA, TILEMAP_0EB         ; PORTRAIT_08
	dw TILESET_JENNIFER_PORTRAIT, PALETTE_083, TILEMAP_0EC, TILEMAP_0ED, TILEMAP_0EE      ; PORTRAIT_09
	dw TILESET_NICHOLAS_PORTRAIT, PALETTE_084, TILEMAP_0EF, TILEMAP_0F0, TILEMAP_0F1      ; PORTRAIT_0A
	dw TILESET_BRANDON_PORTRAIT, PALETTE_085, TILEMAP_0F2, TILEMAP_0F3, TILEMAP_0F4       ; PORTRAIT_0B
	dw TILESET_MURRAY_PORTRAIT, PALETTE_086, TILEMAP_0F5, TILEMAP_0F6, TILEMAP_0F7        ; PORTRAIT_0C
	dw TILESET_STEPHANIE_PORTRAIT, PALETTE_087, TILEMAP_0F8, TILEMAP_0F9, TILEMAP_0FA     ; PORTRAIT_0D
	dw TILESET_DANIEL_PORTRAIT, PALETTE_088, TILEMAP_0FB, TILEMAP_0FC, TILEMAP_0FD        ; PORTRAIT_0E
	dw TILESET_ROBERT_PORTRAIT, PALETTE_089, TILEMAP_0FE, TILEMAP_0FF, TILEMAP_100        ; PORTRAIT_0F
	dw TILESET_GENE_PORTRAIT, PALETTE_08A, TILEMAP_101, TILEMAP_102, TILEMAP_103          ; PORTRAIT_10
	dw TILESET_MATTHEW_PORTRAIT, PALETTE_08B, TILEMAP_104, TILEMAP_105, TILEMAP_106       ; PORTRAIT_11
	dw TILESET_RYAN_PORTRAIT, PALETTE_08C, TILEMAP_107, TILEMAP_108, TILEMAP_109          ; PORTRAIT_12
	dw TILESET_ANDREW_PORTRAIT, PALETTE_08D, TILEMAP_10A, TILEMAP_10B, TILEMAP_10C        ; PORTRAIT_13
	dw TILESET_MITCH_PORTRAIT, PALETTE_08E, TILEMAP_10D, TILEMAP_10E, TILEMAP_10F         ; PORTRAIT_14
	dw TILESET_MICHAEL_PORTRAIT, PALETTE_08F, TILEMAP_110, TILEMAP_111, TILEMAP_112       ; PORTRAIT_15
	dw TILESET_CHRIS_PORTRAIT, PALETTE_090, TILEMAP_113, TILEMAP_114, TILEMAP_115         ; PORTRAIT_16
	dw TILESET_JESSICA_PORTRAIT, PALETTE_091, TILEMAP_116, TILEMAP_117, TILEMAP_118       ; PORTRAIT_17
	dw TILESET_NIKKI_PORTRAIT, PALETTE_092, TILEMAP_119, TILEMAP_11A, TILEMAP_11B         ; PORTRAIT_18
	dw TILESET_BRITTANY_PORTRAIT, PALETTE_093, TILEMAP_11C, TILEMAP_11D, TILEMAP_11E      ; PORTRAIT_19
	dw TILESET_KRISTIN_PORTRAIT, PALETTE_094, TILEMAP_11F, TILEMAP_120, TILEMAP_121       ; PORTRAIT_1A
	dw TILESET_HEATHER_PORTRAIT, PALETTE_095, TILEMAP_122, TILEMAP_123, TILEMAP_124       ; PORTRAIT_1B
	dw TILESET_RICK_PORTRAIT, PALETTE_096, TILEMAP_125, TILEMAP_126, TILEMAP_127          ; PORTRAIT_1C
	dw TILESET_JOSEPH_PORTRAIT, PALETTE_097, TILEMAP_128, TILEMAP_129, TILEMAP_12A        ; PORTRAIT_1D
	dw TILESET_DAVID_PORTRAIT, PALETTE_098, TILEMAP_12B, TILEMAP_12C, TILEMAP_12D         ; PORTRAIT_1E
	dw TILESET_ERIK_PORTRAIT, PALETTE_099, TILEMAP_12E, TILEMAP_12F, TILEMAP_130          ; PORTRAIT_1F
	dw TILESET_AMY_PORTRAIT, PALETTE_09A, TILEMAP_131, TILEMAP_132, TILEMAP_133           ; PORTRAIT_20
	dw TILESET_JOSHUA_PORTRAIT, PALETTE_09B, TILEMAP_134, TILEMAP_135, TILEMAP_136        ; PORTRAIT_21
	dw TILESET_SARA_PORTRAIT, PALETTE_09C, TILEMAP_137, TILEMAP_138, TILEMAP_139          ; PORTRAIT_22
	dw TILESET_AMANDA_PORTRAIT, PALETTE_09D, TILEMAP_13A, TILEMAP_13B, TILEMAP_13C        ; PORTRAIT_23
	dw TILESET_KEN_PORTRAIT, PALETTE_09E, TILEMAP_13D, TILEMAP_13E, TILEMAP_13F           ; PORTRAIT_24
	dw TILESET_JOHN_PORTRAIT, PALETTE_09F, TILEMAP_140, TILEMAP_141, TILEMAP_142          ; PORTRAIT_25
	dw TILESET_ADAM_PORTRAIT, PALETTE_0A0, TILEMAP_143, TILEMAP_144, TILEMAP_145          ; PORTRAIT_26
	dw TILESET_JONATHAN_PORTRAIT, PALETTE_0A1, TILEMAP_146, TILEMAP_147, TILEMAP_148      ; PORTRAIT_27
	dw TILESET_COURTNEY_PORTRAIT, PALETTE_0A2, TILEMAP_149, TILEMAP_14A, TILEMAP_14B      ; PORTRAIT_28
	dw TILESET_STEVE_PORTRAIT, PALETTE_0A3, TILEMAP_14C, TILEMAP_14D, TILEMAP_14E         ; PORTRAIT_29
	dw TILESET_JACK_PORTRAIT, PALETTE_0A4, TILEMAP_14F, TILEMAP_150, TILEMAP_151          ; PORTRAIT_2A
	dw TILESET_ROD_PORTRAIT, PALETTE_0A5, TILEMAP_152, TILEMAP_153, TILEMAP_154           ; PORTRAIT_2B
	dw TILESET_EIJI_PORTRAIT, PALETTE_0A6, TILEMAP_155, TILEMAP_156, TILEMAP_157          ; PORTRAIT_2C
	dw TILESET_MAGICIAN_PORTRAIT, PALETTE_0A7, TILEMAP_158, TILEMAP_159, TILEMAP_15A      ; PORTRAIT_2D
	dw TILESET_YUI_PORTRAIT, PALETTE_0A8, TILEMAP_15B, TILEMAP_15C, TILEMAP_15D           ; PORTRAIT_2E
	dw TILESET_TOSHIRON_PORTRAIT, PALETTE_0A9, TILEMAP_15E, TILEMAP_15F, TILEMAP_160      ; PORTRAIT_2F
	dw TILESET_PIERROT_PORTRAIT, PALETTE_0AA, TILEMAP_161, TILEMAP_162, TILEMAP_163       ; PORTRAIT_30
	dw TILESET_ANNA_PORTRAIT, PALETTE_0AB, TILEMAP_164, TILEMAP_165, TILEMAP_166          ; PORTRAIT_31
	dw TILESET_DEE_PORTRAIT, PALETTE_0AC, TILEMAP_167, TILEMAP_168, TILEMAP_169           ; PORTRAIT_32
	dw TILESET_MASQUERADE_PORTRAIT, PALETTE_0AD, TILEMAP_16A, TILEMAP_16B, TILEMAP_16C    ; PORTRAIT_33
	dw TILESET_PAWN_PORTRAIT, PALETTE_0AE, TILEMAP_16D, TILEMAP_16E, TILEMAP_16F          ; PORTRAIT_34
	dw TILESET_KNIGHT_PORTRAIT, PALETTE_0AF, TILEMAP_170, TILEMAP_171, TILEMAP_172        ; PORTRAIT_35
	dw TILESET_BISHOP_PORTRAIT, PALETTE_0B0, TILEMAP_173, TILEMAP_174, TILEMAP_175        ; PORTRAIT_36
	dw TILESET_ROOK_PORTRAIT, PALETTE_0B1, TILEMAP_176, TILEMAP_177, TILEMAP_178          ; PORTRAIT_37
	dw TILESET_QUEEN_PORTRAIT, PALETTE_0B2, TILEMAP_179, TILEMAP_17A, TILEMAP_17B         ; PORTRAIT_38
	dw TILESET_GR_1_PORTRAIT, PALETTE_0B3, TILEMAP_17C, TILEMAP_17D, TILEMAP_17E          ; PORTRAIT_39
	dw TILESET_GR_2_PORTRAIT, PALETTE_0B4, TILEMAP_17F, TILEMAP_180, TILEMAP_181          ; PORTRAIT_3A
	dw TILESET_GR_3_PORTRAIT, PALETTE_0B5, TILEMAP_182, TILEMAP_183, TILEMAP_184          ; PORTRAIT_3B
	dw TILESET_GR_4_PORTRAIT, PALETTE_0B6, TILEMAP_185, TILEMAP_186, TILEMAP_187          ; PORTRAIT_3C
	dw TILESET_MIDORI_PORTRAIT, PALETTE_0B7, TILEMAP_188, TILEMAP_189, TILEMAP_18A        ; PORTRAIT_3D
	dw TILESET_YUUTA_PORTRAIT, PALETTE_0B8, TILEMAP_18B, TILEMAP_18C, TILEMAP_18D         ; PORTRAIT_3E
	dw TILESET_MIYUKI_PORTRAIT, PALETTE_0B9, TILEMAP_18E, TILEMAP_18F, TILEMAP_190        ; PORTRAIT_3F
	dw TILESET_MORINO_PORTRAIT, PALETTE_0BA, TILEMAP_191, TILEMAP_192, TILEMAP_193        ; PORTRAIT_40
	dw TILESET_RENNA_PORTRAIT, PALETTE_0BB, TILEMAP_194, TILEMAP_195, TILEMAP_196         ; PORTRAIT_41
	dw TILESET_ICHIKAWA_PORTRAIT, PALETTE_0BC, TILEMAP_197, TILEMAP_198, TILEMAP_199      ; PORTRAIT_42
	dw TILESET_CATHERINE_PORTRAIT, PALETTE_0BD, TILEMAP_19A, TILEMAP_19B, TILEMAP_19C     ; PORTRAIT_43
	dw TILESET_TAP_PORTRAIT, PALETTE_0BE, TILEMAP_19D, TILEMAP_19E, TILEMAP_19F           ; PORTRAIT_44
	dw TILESET_JES_PORTRAIT, PALETTE_0BF, TILEMAP_1A0, TILEMAP_1A1, TILEMAP_1A2           ; PORTRAIT_45
	dw TILESET_YUKI_PORTRAIT, PALETTE_0C0, TILEMAP_1A3, TILEMAP_1A4, TILEMAP_1A5          ; PORTRAIT_46
	dw TILESET_SHOKO_PORTRAIT, PALETTE_0C1, TILEMAP_1A6, TILEMAP_1A7, TILEMAP_1A8         ; PORTRAIT_47
	dw TILESET_HIDERO_PORTRAIT, PALETTE_0C2, TILEMAP_1A9, TILEMAP_1AA, TILEMAP_1AB        ; PORTRAIT_48
	dw TILESET_MIYAJIMA_PORTRAIT, PALETTE_0C3, TILEMAP_1AC, TILEMAP_1AD, TILEMAP_1AE      ; PORTRAIT_49
	dw TILESET_SENTA_PORTRAIT, PALETTE_0C4, TILEMAP_1AF, TILEMAP_1B0, TILEMAP_1B1         ; PORTRAIT_4A
	dw TILESET_AIRA_PORTRAIT, PALETTE_0C5, TILEMAP_1B2, TILEMAP_1B3, TILEMAP_1B4          ; PORTRAIT_4B
	dw TILESET_KANOKO_PORTRAIT, PALETTE_0C6, TILEMAP_1B5, TILEMAP_1B6, TILEMAP_1B7        ; PORTRAIT_4C
	dw TILESET_GODA_PORTRAIT, PALETTE_0C7, TILEMAP_1B8, TILEMAP_1B9, TILEMAP_1BA          ; PORTRAIT_4D
	dw TILESET_GRACE_PORTRAIT, PALETTE_0C8, TILEMAP_1BB, TILEMAP_1BC, TILEMAP_1BD         ; PORTRAIT_4E
	dw TILESET_KAMIYA_PORTRAIT, PALETTE_0C9, TILEMAP_1BE, TILEMAP_1BF, TILEMAP_1C0        ; PORTRAIT_4F
	dw TILESET_MIWA_PORTRAIT, PALETTE_0CA, TILEMAP_1C1, TILEMAP_1C2, TILEMAP_1C3          ; PORTRAIT_50
	dw TILESET_KEVIN_PORTRAIT, PALETTE_0CB, TILEMAP_1C4, TILEMAP_1C5, TILEMAP_1C6         ; PORTRAIT_51
	dw TILESET_YOSUKE_PORTRAIT, PALETTE_0CC, TILEMAP_1C7, TILEMAP_1C8, TILEMAP_1C9        ; PORTRAIT_52
	dw TILESET_RYOKO_PORTRAIT, PALETTE_0CD, TILEMAP_1CA, TILEMAP_1CB, TILEMAP_1CC         ; PORTRAIT_53
	dw TILESET_MAMI_PORTRAIT, PALETTE_0CE, TILEMAP_1CD, TILEMAP_1CE, TILEMAP_1CF          ; PORTRAIT_54
	dw TILESET_NISHIJIMA_PORTRAIT, PALETTE_0CF, TILEMAP_1D0, TILEMAP_1D1, TILEMAP_1D2     ; PORTRAIT_55
	dw TILESET_ISHII_PORTRAIT, PALETTE_0D0, TILEMAP_1D3, TILEMAP_1D4, TILEMAP_1D5         ; PORTRAIT_56
	dw TILESET_SAMEJIMA_PORTRAIT, PALETTE_0D1, TILEMAP_1D6, TILEMAP_1D7, TILEMAP_1D8      ; PORTRAIT_57
	dw TILESET_KANZAKI_PORTRAIT, PALETTE_0D2, TILEMAP_1D9, TILEMAP_1DA, TILEMAP_1DB       ; PORTRAIT_58
	dw TILESET_RUI_PORTRAIT, PALETTE_0D3, TILEMAP_1DC, TILEMAP_1DD, TILEMAP_1DE           ; PORTRAIT_59
	dw TILESET_BIRURITCHI_PORTRAIT, PALETTE_0D4, TILEMAP_1DF, TILEMAP_1E0, TILEMAP_1E1    ; PORTRAIT_5A
	dw TILESET_GR_X_PORTRAIT, PALETTE_0D5, TILEMAP_1E2, TILEMAP_1E3, TILEMAP_1E4          ; PORTRAIT_5B
	dw TILESET_TOBI_CHAN_PORTRAIT, PALETTE_0D6, TILEMAP_1E5, TILEMAP_1E6, TILEMAP_1E7     ; PORTRAIT_5C
	dw TILESET_DR_MASON_PORTRAIT, PALETTE_0D7, TILEMAP_1E8, TILEMAP_1E9, TILEMAP_1EA      ; PORTRAIT_5D
	dw TILESET_IMAKUNI_BLACK_PORTRAIT, PALETTE_080, TILEMAP_0E3, TILEMAP_0E4, TILEMAP_0E5 ; PORTRAIT_5E
	dw TILESET_IMAKUNI_RED_PORTRAIT, PALETTE_081, TILEMAP_0E6, TILEMAP_0E7, TILEMAP_0E8   ; PORTRAIT_5F
