; input:
;  a = PORTRAIT_* constant
;  b = portrait slot (0 or 1)
;  c = EMOTION_* constant
;  de = coordinates
DrawPortrait::
	push af
	push bc
	push de
	push hl
	push bc
	push de
	ld e, b
	ld d, c
	push de
	ld e, a
	ld d, 0
	ld bc, 10 ; size of each portrait entry
	call MultiplyBCByDE
	ld b, h
	ld c, l
	pop de
	ld hl, Portraits
	add hl, bc

	; tileset
	ld a, [hli]
	ld c, a
	ld a, [hli]
	ld b, a
	push hl
	farcall GetTilesetGfxPointer
	ld c, d
	call LoadPortraitTiles
	pop hl

	; palette
	ld a, [hli]
	ld c, a
	ld a, [hli]
	ld b, a
	push hl
	farcall GetPaletteGfxPointer
	call LoadPortraitPalettes
	pop hl

	; tilemap
	pop de
	pop bc
	ld a, b ; slot
	ld [wPortraitSlot], a
	ld a, c ; emotion
	ld [wPortraitEmotion], a
	ld b, $00
	sla c ; *2
	add hl, bc
	ld a, [hli]
	ld c, a
	ld a, [hli]
	ld b, a
	farcall GetTilemapGfxPointer
	ld a, [wPortraitEmotion]
	ld c, a
	ld a, [wPortraitSlot]
	farcall LoadPortraitAttributeMap
	pop hl
	pop de
	pop bc
	pop af
	ret

Data_13005b::
	dw OWSPRITE_MARK                ; NPC_MARK
	dw OWSPRITE_MINT                ; NPC_MINT
	dw OWSPRITE_DR_MASON            ; NPC_DR_MASON
	dw OWSPRITE_RONALD              ; NPC_RONALD
	dw OWSPRITE_ISHIHARA            ; NPC_ISHIHARA
	dw OWSPRITE_IMAKUNI_BLACK       ; NPC_IMAKUNI_BLACK
	dw OWSPRITE_TECH                ; NPC_SAM
	dw OWSPRITE_TECH                ; NPC_AARON
	dw OWSPRITE_PAPPY               ; NPC_PAPPY_1
	dw OWSPRITE_GENE                ; NPC_GENE
	dw OWSPRITE_MANIA               ; NPC_MATTHEW
	dw OWSPRITE_YOUNGSTER           ; NPC_RYAN
	dw OWSPRITE_MAN                 ; NPC_ANDREW
	dw OWSPRITE_MITCH               ; NPC_MITCH
	dw OWSPRITE_MANIA               ; NPC_MICHAEL
	dw OWSPRITE_MANIA               ; NPC_CHRIS
	dw OWSPRITE_LASS3               ; NPC_JESSICA
	dw OWSPRITE_NIKKI               ; NPC_NIKKI
	dw OWSPRITE_GIRL                ; NPC_BRITTANY
	dw OWSPRITE_LASS2               ; NPC_KRISTIN
	dw OWSPRITE_LASS1               ; NPC_HEATHER
	dw OWSPRITE_RICK                ; NPC_RICK
	dw OWSPRITE_TECH                ; NPC_DAVID
	dw OWSPRITE_TECH                ; NPC_JOSEPH
	dw OWSPRITE_TECH                ; NPC_ERIK
	dw OWSPRITE_AMY                 ; NPC_AMY
	dw OWSPRITE_AMY_LOUNGE          ; NPC_AMY_LOUNGE
	dw OWSPRITE_JOSHUA              ; NPC_JOSHUA
	dw OWSPRITE_SARA                ; NPC_SARA
	dw OWSPRITE_AMANDA              ; NPC_AMANDA
	dw OWSPRITE_KEN                 ; NPC_KEN
	dw OWSPRITE_LAD                 ; NPC_JOHN
	dw OWSPRITE_SPECS               ; NPC_ADAM
	dw OWSPRITE_YOUNGSTER           ; NPC_JONATHAN
	dw OWSPRITE_ISAAC               ; NPC_ISAAC
	dw OWSPRITE_GIRL                ; NPC_JENNIFER
	dw OWSPRITE_HOOD                ; NPC_NICHOLAS
	dw OWSPRITE_HOOD                ; NPC_BRANDON
	dw OWSPRITE_MURRAY              ; NPC_MURRAY
	dw OWSPRITE_YOUNGSTER           ; NPC_ROBERT
	dw OWSPRITE_LAD                 ; NPC_DANIEL
	dw OWSPRITE_GIRL                ; NPC_STEPHANIE
	dw OWSPRITE_COURTNEY            ; NPC_COURTNEY
	dw OWSPRITE_STEVE               ; NPC_STEVE
	dw OWSPRITE_JACK                ; NPC_JACK
	dw OWSPRITE_ROD                 ; NPC_ROD
	dw OWSPRITE_GR_1                ; NPC_GR_1
	dw OWSPRITE_GR_2                ; NPC_GR_2
	dw OWSPRITE_GR_3                ; NPC_GR_3
	dw OWSPRITE_GR_4                ; NPC_GR_4
	dw OWSPRITE_GR_5                ; NPC_GR_5
	dw OWSPRITE_GR_LAD              ; NPC_GR_LAD_1
	dw OWSPRITE_MIDORI              ; NPC_MIDORI
	dw OWSPRITE_MORINO              ; NPC_YUTA
	dw OWSPRITE_MIDORI              ; NPC_MIYUKI
	dw OWSPRITE_MORINO              ; NPC_MORINO
	dw OWSPRITE_GR_LASS             ; NPC_LIGHTNING_FORT_GR_LASS
	dw OWSPRITE_RENNA               ; NPC_RENNA
	dw OWSPRITE_ICHIKAWA            ; NPC_ICHIKAWA
	dw OWSPRITE_CATHERINE           ; NPC_CATHERINE
	dw OWSPRITE_GR_GRANNY           ; NPC_GR_CHALLENGE_HALL_GR_GRANNY
	dw OWSPRITE_MIYAJIMA            ; NPC_FIRE_FORT_GRAMPY
	dw OWSPRITE_JES                 ; NPC_JES
	dw OWSPRITE_YUKI                ; NPC_YUKI
	dw OWSPRITE_SHOKO               ; NPC_SHOKO
	dw OWSPRITE_HIDERO              ; NPC_HIDERO
	dw OWSPRITE_SPECS               ; NPC_WATER_FORT_GLASSES_KID
	dw OWSPRITE_MIYAJIMA            ; NPC_MIYAJIMA
	dw OWSPRITE_JOSHUA              ; NPC_SENTA
	dw OWSPRITE_AIRA                ; NPC_AIRA
	dw OWSPRITE_KANOKO              ; NPC_KANOKO
	dw OWSPRITE_GODA                ; NPC_GODA
	dw OWSPRITE_GRACE               ; NPC_GRACE
	dw OWSPRITE_KAMIYA              ; NPC_KAMIYA
	dw OWSPRITE_GAL                 ; NPC_PSYCHIC_STRONGHOLD_LADY
	dw OWSPRITE_MIWA                ; NPC_MIWA
	dw OWSPRITE_KEVIN               ; NPC_KEVIN
	dw OWSPRITE_YOSUKE              ; NPC_YOSUKE
	dw OWSPRITE_RYOKO               ; NPC_RYOKO
	dw OWSPRITE_MAMI                ; NPC_MAMI
	dw OWSPRITE_NISHIJIMA           ; NPC_NISHIJIMA
	dw OWSPRITE_ISHII               ; NPC_ISHII
	dw OWSPRITE_SAMEJIMA            ; NPC_SAMEJIMA
	dw OWSPRITE_KANZAKI             ; NPC_KANZAKI
	dw OWSPRITE_RUI                 ; NPC_RUI
	dw OWSPRITE_BIRURITCHI          ; NPC_BIRURITCHI
	dw OWSPRITE_TOBICHAN            ; NPC_TOBICHAN
	dw OWSPRITE_EIJI                ; NPC_EIJI
	dw OWSPRITE_MAGICIAN            ; NPC_MAGICIAN
	dw OWSPRITE_TOSHIRON            ; NPC_TOSHIRON
	dw OWSPRITE_PIERROT             ; NPC_PIERROT
	dw OWSPRITE_ANNA                ; NPC_ANNA
	dw OWSPRITE_DEE                 ; NPC_DEE
	dw OWSPRITE_MASQUERADE          ; NPC_MASQUERADE
	dw OWSPRITE_PAWN                ; NPC_PAWN
	dw OWSPRITE_KNIGHT              ; NPC_KNIGHT
	dw OWSPRITE_BISHOP              ; NPC_BISHOP
	dw OWSPRITE_ROOK                ; NPC_ROOK
	dw OWSPRITE_QUEEN               ; NPC_QUEEN
	dw OWSPRITE_GR_X                ; NPC_GR_X
	dw OWSPRITE_CLERK               ; NPC_CLERK_BATTLE_CENTER
	dw OWSPRITE_CLERK               ; NPC_CLERK_GIFT_CENTER
	dw OWSPRITE_GR_CLERK            ; NPC_GR_CLERK_TCG_AIRPORT
	dw OWSPRITE_GR_CLERK            ; NPC_GR_CLERK_GR_AIRPORT
	dw OWSPRITE_GR_CLERK            ; NPC_GR_CLERK_BATTLE_CENTER
	dw OWSPRITE_GR_CLERK            ; NPC_GR_CLERK_GIFT_CENTER
	dw OWSPRITE_LASS2               ; NPC_ROCK_CLUB_LASS
	dw OWSPRITE_WOMAN               ; NPC_ROCK_CLUB_WOMAN
	dw OWSPRITE_CHAP                ; NPC_ROCK_CLUB_CHAP
	dw OWSPRITE_LAD                 ; NPC_ROCK_CLUB_CAPPED_LAD
	dw OWSPRITE_PAPPY               ; NPC_FIGHTING_CLUB_PAPPY
	dw OWSPRITE_SPECS               ; NPC_FIGHTING_CLUB_GLASSES_KID
	dw OWSPRITE_LAD                 ; NPC_FIGHTING_CLUB_CAPPED_GUY
	dw OWSPRITE_GIRL                ; NPC_FIGHTING_CLUB_CAPPED_LASS
	dw OWSPRITE_GRANNY              ; NPC_GRASS_CLUB_GRANNY
	dw OWSPRITE_LASS2               ; NPC_GRASS_CLUB_LASS
	dw OWSPRITE_GIRL                ; NPC_GRASS_CLUB_CAPPED_LASS
	dw OWSPRITE_MAN                 ; NPC_SCIENCE_CLUB_MAN
	dw OWSPRITE_LAD                 ; NPC_LAD_5
	dw OWSPRITE_SPECS               ; NPC_SCIENCE_CLUB_GLASSES_KID
	dw OWSPRITE_TECH                ; NPC_SCIENCE_CLUB_TECH
	dw OWSPRITE_PAPPY               ; NPC_WATER_CLUB_PAPPY
	dw OWSPRITE_LASS1               ; NPC_WATER_CLUB_LONGHAIRED_LASS
	dw OWSPRITE_LASS2               ; NPC_WATER_CLUB_LASS
	dw OWSPRITE_HOOD                ; NPC_FIRE_CLUB_PUNK_GUY
	dw OWSPRITE_MANIA               ; NPC_FIRE_CLUB_MARTIAL_ARTIST
	dw OWSPRITE_GAL                 ; NPC_FIRE_CLUB_GAL
	dw OWSPRITE_LASS3               ; NPC_LIGHTNING_CLUB_LASS
	dw OWSPRITE_HOOD                ; NPC_LIGHTNING_CLUB_PUNK_KID
	dw OWSPRITE_LASS1               ; NPC_LIGHTNING_CLUB_LONGHAIRED_LASS
	dw OWSPRITE_CHAP                ; NPC_LIGHTNING_CLUB_BRO
	dw OWSPRITE_SPECS               ; NPC_PSYCHIC_CLUB_GLASSES_LAD
	dw OWSPRITE_LASS1               ; NPC_PSYCHIC_CLUB_LASS
	dw OWSPRITE_LAD                 ; NPC_PSYCHIC_CLUB_CAPPED_LAD
	dw OWSPRITE_GR_LASS             ; NPC_PSYCHIC_CLUB_GR_LASS
	dw OWSPRITE_GR_CLERK            ; NPC_GR_CLERK_5
	dw OWSPRITE_GR_GAL              ; NPC_TCG_AIRPORT_GR_SIS
	dw OWSPRITE_MANIA               ; NPC_TCG_AIRPORT_MARTIAL_ARTIST
	dw OWSPRITE_CLERK               ; NPC_CLERK_TCG_CHALLENGE_HALL_ENTRANCE
	dw OWSPRITE_CHAP                ; NPC_TCG_CHALLENGE_HALL_CHAP
	dw OWSPRITE_GAL                 ; NPC_CUP_HOST
	dw OWSPRITE_HOOD                ; NPC_TCG_CHALLENGE_HALL_PUNK
	dw OWSPRITE_MAN                 ; NPC_TCG_CHALLENGE_HALL_MAN
	dw OWSPRITE_PAPPY               ; NPC_TCG_CHALLENGE_HALL_PAPPY
	dw OWSPRITE_TECH                ; NPC_TCG_CHALLENGE_HALL_TECH
	dw OWSPRITE_GIRL                ; NPC_TCG_CHALLENGE_HALL_GIRL
	dw OWSPRITE_LASS1               ; NPC_TCG_CUP_CLERK_LEFT
	dw OWSPRITE_LASS2               ; NPC_TCG_CUP_CLERK_RIGHT
	dw OWSPRITE_GR_CLERK            ; NPC_GR_CLERK_GR_AIRPORT_2
	dw OWSPRITE_GR_PAPPY            ; NPC_GR_AIRPORT_GR_PAPPY
	dw OWSPRITE_GR_LASS             ; NPC_GRASS_FORT_GR_LASS
	dw OWSPRITE_GR_CLERK            ; NPC_GR_CLERK_GRASS_FORT
	dw OWSPRITE_GR_LAD              ; NPC_GRASS_FORT_GR_GRUNT
	dw OWSPRITE_GR_PAPPY            ; NPC_GRASS_FORT_GR_PAPPY
	dw OWSPRITE_GR_LASS             ; NPC_GRASS_FORT_GR_LASS
	dw OWSPRITE_GR_CLERK            ; NPC_GR_CLERK_LIGHTNING_FORT
	dw OWSPRITE_GR_WOMAN            ; NPC_LIGHTNING_FORT_GR_WOMAN
	dw OWSPRITE_BUTCH               ; NPC_LIGHTNING_FORT_CHUBBY_KID
	dw OWSPRITE_CHAP                ; NPC_TAP
	dw OWSPRITE_GR_CLERK            ; NPC_GR_CLERK_FIRE_FORT
	dw OWSPRITE_YOUNGSTER           ; NPC_FIRE_FORT_YOUNGSTER
	dw OWSPRITE_GR_CLERK            ; NPC_GR_CLERK_WATER_FORT
	dw OWSPRITE_GR_GRANNY           ; NPC_WATER_FORT_GR_GRANNY
	dw OWSPRITE_GR_GAL              ; NPC_WATER_FORT_GR_GAL
	dw OWSPRITE_GR_CLERK            ; NPC_GR_CLERK_FIGHTING_FORT
	dw OWSPRITE_GR_CLERK            ; NPC_GR_CLERK_PSYCHIC_STRONGHOLD
	dw OWSPRITE_MANIA               ; NPC_PSYCHIC_STRONGHOLD_UNCAPPED_LAD
	dw OWSPRITE_GR_LASS             ; NPC_GR_PSYCHIC_STRONGHOLD_GR_LASS
	dw OWSPRITE_GR_CLERK            ; NPC_GR_CLERK_13
	dw OWSPRITE_TECH                ; NPC_GAME_CENTER_TECH
	dw OWSPRITE_GR_LASS             ; NPC_GAME_CENTER_GR_LASS
	dw OWSPRITE_GR_PAPPY            ; NPC_GAME_CENTER_GR_PAPPY
	dw OWSPRITE_CAPTURED_AMY        ; NPC_CAPTURED_AMY
	dw OWSPRITE_CAPTURED_SARA       ; NPC_CAPTURED_SARA
	dw OWSPRITE_CAPTURED_AMANDA     ; NPC_CAPTURED_AMANDA
	dw OWSPRITE_WARP_SPARKLES       ; NPC_WARP_SPARKLES
	dw OWSPRITE_LASS2               ; NPC_YUI
	dw OWSPRITE_IMAKUNI_RED         ; NPC_IMAKUNI_RED
	dw OWSPRITE_BUTCH               ; NPC_POKEMON_DOME_FAT_GUY
	dw OWSPRITE_TECH                ; NPC_LAB_TECH_PC_GUIDE
	dw OWSPRITE_TECH                ; NPC_LAB_TECH_CLUB_GUIDE
	dw OWSPRITE_TECH                ; NPC_LAB_TECH_BOOSTER_GUIDE
	dw OWSPRITE_TECH                ; NPC_LAB_TECH_ROOM_GUIDE
	dw OWSPRITE_TECH                ; NPC_LAB_TECH_AUTO_DECK_MACHINE_1
	dw OWSPRITE_TECH                ; NPC_LAB_TECH_DECK_SAVE_MACHINE
	dw OWSPRITE_TECH                ; NPC_LAB_TECH_COMPUTER_ROOM
	dw OWSPRITE_TECH                ; NPC_LAB_TECH_AUTO_DECK_MACHINE_2
	dw OWSPRITE_TECH                ; NPC_LAB_TECH_TRAINING_ROOM
	dw OWSPRITE_GR_CLERK            ; NPC_GR_CLERK_CASTLE_RIGHT
	dw OWSPRITE_GR_CLERK            ; NPC_GR_CLERK_CASTLE_LEFT
	dw OWSPRITE_GR_CLERK            ; NPC_GR_CLERK_GAME_CENTER_PRIZE_DESK
	dw OWSPRITE_GR_CLERK            ; NPC_GR_CLERK_GAME_CENTER_CHIP_DESK
	dw OWSPRITE_CHIP_GIRL           ; NPC_CHIP_GIRL
	dw OWSPRITE_MONOCLE             ; NPC_CHIP_SECURITY
	dw OWSPRITE_MONOCLE             ; NPC_ATTENDANT_BLACK_BOX
	dw OWSPRITE_DEALER_BOY          ; NPC_ATTENDANT_BILLS_PC
	dw OWSPRITE_DEALER_GIRL         ; NPC_ATTENDANT_COIN_FLIP
	dw OWSPRITE_DEALER_BOY          ; NPC_ATTENDANT_1COIN_SLOT
	dw OWSPRITE_CHIP_GIRL           ; NPC_ATTENDANT_5COIN_SLOT
	dw OWSPRITE_DEALER_GIRL         ; NPC_ATTENDANT_CARD_DUNGEON
	dw OWSPRITE_VOLCANO_SMOKE_TCG   ; NPC_VOLCANO_SMOKE_TCG
	dw OWSPRITE_VOLCANO_SMOKE_GR    ; NPC_VOLCANO_SMOKE_GR
	dw OWSPRITE_CURSOR_TCG          ; NPC_CURSOR_TCG
	dw OWSPRITE_CURSOR_GR           ; NPC_CURSOR_GR
	dw OWSPRITE_GR_CROSS            ; NPC_GR_CROSS
	dw OWSPRITE_GR_CASTLE_FLAG      ; NPC_GR_CASTLE_FLAG
	dw OWSPRITE_CHEST_CLOSED        ; NPC_CHEST_CLOSED
	dw OWSPRITE_CHEST_OPENED        ; NPC_CHEST_OPENED
	dw OWSPRITE_GR_BLIMP_BEAM       ; NPC_GR_BLIMP_BEAM
	dw OWSPRITE_GR_BLIMP            ; NPC_GR_BLIMP
	dw OWSPRITE_POD_DOORS           ; NPC_POD_DOORS
	dw OWSPRITE_GR_LAD              ; NPC_WATER_FORT_GR_LAD
	dw OWSPRITE_GR_LASS             ; NPC_LIGHTNING_CLUB_GR_LASS
	dw OWSPRITE_GR_LASS             ; NPC_POKEMON_DOME_GR_LASS
	dw OWSPRITE_YOUNGSTER           ; NPC_POKEMON_DOME_YOUNGSTER
	dw OWSPRITE_SWIMMER             ; NPC_POKEMON_DOME_SWIMMER
	dw OWSPRITE_GR_GAL              ; NPC_GAME_CENTER_GR_GAL
	dw OWSPRITE_BUTCH               ; NPC_GAME_CENTER_CHUBBY_KID
	dw OWSPRITE_MANIA               ; NPC_GAME_CENTER_BOY
	dw OWSPRITE_FIXER               ; NPC_GAME_CENTER_FIXER
	dw OWSPRITE_GR_WOMAN            ; NPC_GAME_CENTER_GR_WOMAN
	dw OWSPRITE_GR_GAL              ; NPC_ISHIHARAS_VILLA_GR_GAL
	dw OWSPRITE_GR_CLERK            ; NPC_GR_CLERK_CHALLENGE_HALL_ENTRANCE
	dw OWSPRITE_GR_CHAP             ; NPC_GR_CHALLENGE_HALL_GR_CHAP
	dw OWSPRITE_GR_WOMAN            ; NPC_GR_CHALLENGE_HALL_GR_WOMAN
	dw OWSPRITE_GR_STAFF            ; NPC_GR_STAFF
	dw OWSPRITE_LASS1               ; NPC_GR_CUP_CLERK_LEFT
	dw OWSPRITE_LASS2               ; NPC_GR_CUP_CLERK_RIGHT
	dw OWSPRITE_RED_FORT_COIN       ; NPC_RED_FORT_COIN
	dw OWSPRITE_BLUE_FORT_COIN      ; NPC_BLUE_FORT_COIN
	dw OWSPRITE_WHITE_CASTLE_COIN   ; NPC_WHITE_CASTLE_COIN
	dw OWSPRITE_PURPLE_CASTLE_COIN  ; NPC_PURPLE_CASTLE_COIN
	dw OWSPRITE_STRONGHOLD_PLATFORM ; NPC_STRONGHOLD_PLATFORM

Portraits:
	dw TILESET_MARK_PORTRAIT, PALETTE_078, TILEMAP_0D3, TILEMAP_0D3, TILEMAP_0D3          ; PORTRAIT_MARK
	dw TILESET_MINT_PORTRAIT, PALETTE_079, TILEMAP_0D4, TILEMAP_0D4, TILEMAP_0D4          ; PORTRAIT_MINT
	dw TILESET_MARK_LINK_PORTRAIT, PALETTE_07A, TILEMAP_0D5, TILEMAP_0D5, TILEMAP_0D5     ; PORTRAIT_MARK_LINK
	dw TILESET_MINT_LINK_PORTRAIT, PALETTE_07B, TILEMAP_0D6, TILEMAP_0D6, TILEMAP_0D6     ; PORTRAIT_MINT_LINK
	dw TILESET_RONALD_PORTRAIT, PALETTE_07C, TILEMAP_0D7, TILEMAP_0D8, TILEMAP_0D9        ; PORTRAIT_RONALD
	dw TILESET_SAM_PORTRAIT, PALETTE_07D, TILEMAP_0DA, TILEMAP_0DB, TILEMAP_0DC           ; PORTRAIT_SAM
	dw TILESET_AARON_PORTRAIT, PALETTE_07E, TILEMAP_0DD, TILEMAP_0DE, TILEMAP_0DF         ; PORTRAIT_AARON
	dw TILESET_ISHIHARA_PORTRAIT, PALETTE_07F, TILEMAP_0E0, TILEMAP_0E1, TILEMAP_0E2      ; PORTRAIT_ISHIHARA
	dw TILESET_ISAAC_PORTRAIT, PALETTE_082, TILEMAP_0E9, TILEMAP_0EA, TILEMAP_0EB         ; PORTRAIT_ISAAC
	dw TILESET_JENNIFER_PORTRAIT, PALETTE_083, TILEMAP_0EC, TILEMAP_0ED, TILEMAP_0EE      ; PORTRAIT_JENNIFER
	dw TILESET_NICHOLAS_PORTRAIT, PALETTE_084, TILEMAP_0EF, TILEMAP_0F0, TILEMAP_0F1      ; PORTRAIT_NICHOLAS
	dw TILESET_BRANDON_PORTRAIT, PALETTE_085, TILEMAP_0F2, TILEMAP_0F3, TILEMAP_0F4       ; PORTRAIT_BRANDON
	dw TILESET_MURRAY_PORTRAIT, PALETTE_086, TILEMAP_0F5, TILEMAP_0F6, TILEMAP_0F7        ; PORTRAIT_MURRAY
	dw TILESET_STEPHANIE_PORTRAIT, PALETTE_087, TILEMAP_0F8, TILEMAP_0F9, TILEMAP_0FA     ; PORTRAIT_STEPHANIE
	dw TILESET_DANIEL_PORTRAIT, PALETTE_088, TILEMAP_0FB, TILEMAP_0FC, TILEMAP_0FD        ; PORTRAIT_DANIEL
	dw TILESET_ROBERT_PORTRAIT, PALETTE_089, TILEMAP_0FE, TILEMAP_0FF, TILEMAP_100        ; PORTRAIT_ROBERT
	dw TILESET_GENE_PORTRAIT, PALETTE_08A, TILEMAP_101, TILEMAP_102, TILEMAP_103          ; PORTRAIT_GENE
	dw TILESET_MATTHEW_PORTRAIT, PALETTE_08B, TILEMAP_104, TILEMAP_105, TILEMAP_106       ; PORTRAIT_MATTHEW
	dw TILESET_RYAN_PORTRAIT, PALETTE_08C, TILEMAP_107, TILEMAP_108, TILEMAP_109          ; PORTRAIT_RYAN
	dw TILESET_ANDREW_PORTRAIT, PALETTE_08D, TILEMAP_10A, TILEMAP_10B, TILEMAP_10C        ; PORTRAIT_ANDREW
	dw TILESET_MITCH_PORTRAIT, PALETTE_08E, TILEMAP_10D, TILEMAP_10E, TILEMAP_10F         ; PORTRAIT_MITCH
	dw TILESET_MICHAEL_PORTRAIT, PALETTE_08F, TILEMAP_110, TILEMAP_111, TILEMAP_112       ; PORTRAIT_MICHAEL
	dw TILESET_CHRIS_PORTRAIT, PALETTE_090, TILEMAP_113, TILEMAP_114, TILEMAP_115         ; PORTRAIT_CHRIS
	dw TILESET_JESSICA_PORTRAIT, PALETTE_091, TILEMAP_116, TILEMAP_117, TILEMAP_118       ; PORTRAIT_JESSICA
	dw TILESET_NIKKI_PORTRAIT, PALETTE_092, TILEMAP_119, TILEMAP_11A, TILEMAP_11B         ; PORTRAIT_NIKKI
	dw TILESET_BRITTANY_PORTRAIT, PALETTE_093, TILEMAP_11C, TILEMAP_11D, TILEMAP_11E      ; PORTRAIT_BRITTANY
	dw TILESET_KRISTIN_PORTRAIT, PALETTE_094, TILEMAP_11F, TILEMAP_120, TILEMAP_121       ; PORTRAIT_KRISTIN
	dw TILESET_HEATHER_PORTRAIT, PALETTE_095, TILEMAP_122, TILEMAP_123, TILEMAP_124       ; PORTRAIT_HEATHER
	dw TILESET_RICK_PORTRAIT, PALETTE_096, TILEMAP_125, TILEMAP_126, TILEMAP_127          ; PORTRAIT_RICK
	dw TILESET_JOSEPH_PORTRAIT, PALETTE_097, TILEMAP_128, TILEMAP_129, TILEMAP_12A        ; PORTRAIT_JOSEPH
	dw TILESET_DAVID_PORTRAIT, PALETTE_098, TILEMAP_12B, TILEMAP_12C, TILEMAP_12D         ; PORTRAIT_DAVID
	dw TILESET_ERIK_PORTRAIT, PALETTE_099, TILEMAP_12E, TILEMAP_12F, TILEMAP_130          ; PORTRAIT_ERIK
	dw TILESET_AMY_PORTRAIT, PALETTE_09A, TILEMAP_131, TILEMAP_132, TILEMAP_133           ; PORTRAIT_AMY
	dw TILESET_JOSHUA_PORTRAIT, PALETTE_09B, TILEMAP_134, TILEMAP_135, TILEMAP_136        ; PORTRAIT_JOSHUA
	dw TILESET_SARA_PORTRAIT, PALETTE_09C, TILEMAP_137, TILEMAP_138, TILEMAP_139          ; PORTRAIT_SARA
	dw TILESET_AMANDA_PORTRAIT, PALETTE_09D, TILEMAP_13A, TILEMAP_13B, TILEMAP_13C        ; PORTRAIT_AMANDA
	dw TILESET_KEN_PORTRAIT, PALETTE_09E, TILEMAP_13D, TILEMAP_13E, TILEMAP_13F           ; PORTRAIT_KEN
	dw TILESET_JOHN_PORTRAIT, PALETTE_09F, TILEMAP_140, TILEMAP_141, TILEMAP_142          ; PORTRAIT_JOHN
	dw TILESET_ADAM_PORTRAIT, PALETTE_0A0, TILEMAP_143, TILEMAP_144, TILEMAP_145          ; PORTRAIT_ADAM
	dw TILESET_JONATHAN_PORTRAIT, PALETTE_0A1, TILEMAP_146, TILEMAP_147, TILEMAP_148      ; PORTRAIT_JONATHAN
	dw TILESET_COURTNEY_PORTRAIT, PALETTE_0A2, TILEMAP_149, TILEMAP_14A, TILEMAP_14B      ; PORTRAIT_COURTNEY
	dw TILESET_STEVE_PORTRAIT, PALETTE_0A3, TILEMAP_14C, TILEMAP_14D, TILEMAP_14E         ; PORTRAIT_STEVE
	dw TILESET_JACK_PORTRAIT, PALETTE_0A4, TILEMAP_14F, TILEMAP_150, TILEMAP_151          ; PORTRAIT_JACK
	dw TILESET_ROD_PORTRAIT, PALETTE_0A5, TILEMAP_152, TILEMAP_153, TILEMAP_154           ; PORTRAIT_ROD
	dw TILESET_EIJI_PORTRAIT, PALETTE_0A6, TILEMAP_155, TILEMAP_156, TILEMAP_157          ; PORTRAIT_EIJI
	dw TILESET_MAGICIAN_PORTRAIT, PALETTE_0A7, TILEMAP_158, TILEMAP_159, TILEMAP_15A      ; PORTRAIT_MAGICIAN
	dw TILESET_YUI_PORTRAIT, PALETTE_0A8, TILEMAP_15B, TILEMAP_15C, TILEMAP_15D           ; PORTRAIT_YUI
	dw TILESET_TOSHIRON_PORTRAIT, PALETTE_0A9, TILEMAP_15E, TILEMAP_15F, TILEMAP_160      ; PORTRAIT_TOSHIRON
	dw TILESET_PIERROT_PORTRAIT, PALETTE_0AA, TILEMAP_161, TILEMAP_162, TILEMAP_163       ; PORTRAIT_PIERROT
	dw TILESET_ANNA_PORTRAIT, PALETTE_0AB, TILEMAP_164, TILEMAP_165, TILEMAP_166          ; PORTRAIT_ANNA
	dw TILESET_DEE_PORTRAIT, PALETTE_0AC, TILEMAP_167, TILEMAP_168, TILEMAP_169           ; PORTRAIT_DEE
	dw TILESET_MASQUERADE_PORTRAIT, PALETTE_0AD, TILEMAP_16A, TILEMAP_16B, TILEMAP_16C    ; PORTRAIT_MASQUERADE
	dw TILESET_PAWN_PORTRAIT, PALETTE_0AE, TILEMAP_16D, TILEMAP_16E, TILEMAP_16F          ; PORTRAIT_PAWN
	dw TILESET_KNIGHT_PORTRAIT, PALETTE_0AF, TILEMAP_170, TILEMAP_171, TILEMAP_172        ; PORTRAIT_KNIGHT
	dw TILESET_BISHOP_PORTRAIT, PALETTE_0B0, TILEMAP_173, TILEMAP_174, TILEMAP_175        ; PORTRAIT_BISHOP
	dw TILESET_ROOK_PORTRAIT, PALETTE_0B1, TILEMAP_176, TILEMAP_177, TILEMAP_178          ; PORTRAIT_ROOK
	dw TILESET_QUEEN_PORTRAIT, PALETTE_0B2, TILEMAP_179, TILEMAP_17A, TILEMAP_17B         ; PORTRAIT_QUEEN
	dw TILESET_GR_1_PORTRAIT, PALETTE_0B3, TILEMAP_17C, TILEMAP_17D, TILEMAP_17E          ; PORTRAIT_GR_1
	dw TILESET_GR_2_PORTRAIT, PALETTE_0B4, TILEMAP_17F, TILEMAP_180, TILEMAP_181          ; PORTRAIT_GR_2
	dw TILESET_GR_3_PORTRAIT, PALETTE_0B5, TILEMAP_182, TILEMAP_183, TILEMAP_184          ; PORTRAIT_GR_3
	dw TILESET_GR_4_PORTRAIT, PALETTE_0B6, TILEMAP_185, TILEMAP_186, TILEMAP_187          ; PORTRAIT_GR_4
	dw TILESET_MIDORI_PORTRAIT, PALETTE_0B7, TILEMAP_188, TILEMAP_189, TILEMAP_18A        ; PORTRAIT_MIDORI
	dw TILESET_YUTA_PORTRAIT, PALETTE_0B8, TILEMAP_18B, TILEMAP_18C, TILEMAP_18D          ; PORTRAIT_YUTA
	dw TILESET_MIYUKI_PORTRAIT, PALETTE_0B9, TILEMAP_18E, TILEMAP_18F, TILEMAP_190        ; PORTRAIT_MIYUKI
	dw TILESET_MORINO_PORTRAIT, PALETTE_0BA, TILEMAP_191, TILEMAP_192, TILEMAP_193        ; PORTRAIT_MORINO
	dw TILESET_RENNA_PORTRAIT, PALETTE_0BB, TILEMAP_194, TILEMAP_195, TILEMAP_196         ; PORTRAIT_RENNA
	dw TILESET_ICHIKAWA_PORTRAIT, PALETTE_0BC, TILEMAP_197, TILEMAP_198, TILEMAP_199      ; PORTRAIT_ICHIKAWA
	dw TILESET_CATHERINE_PORTRAIT, PALETTE_0BD, TILEMAP_19A, TILEMAP_19B, TILEMAP_19C     ; PORTRAIT_CATHERINE
	dw TILESET_TAP_PORTRAIT, PALETTE_0BE, TILEMAP_19D, TILEMAP_19E, TILEMAP_19F           ; PORTRAIT_TAP
	dw TILESET_JES_PORTRAIT, PALETTE_0BF, TILEMAP_1A0, TILEMAP_1A1, TILEMAP_1A2           ; PORTRAIT_JES
	dw TILESET_YUKI_PORTRAIT, PALETTE_0C0, TILEMAP_1A3, TILEMAP_1A4, TILEMAP_1A5          ; PORTRAIT_YUKI
	dw TILESET_SHOKO_PORTRAIT, PALETTE_0C1, TILEMAP_1A6, TILEMAP_1A7, TILEMAP_1A8         ; PORTRAIT_SHOKO
	dw TILESET_HIDERO_PORTRAIT, PALETTE_0C2, TILEMAP_1A9, TILEMAP_1AA, TILEMAP_1AB        ; PORTRAIT_HIDERO
	dw TILESET_MIYAJIMA_PORTRAIT, PALETTE_0C3, TILEMAP_1AC, TILEMAP_1AD, TILEMAP_1AE      ; PORTRAIT_MIYAJIMA
	dw TILESET_SENTA_PORTRAIT, PALETTE_0C4, TILEMAP_1AF, TILEMAP_1B0, TILEMAP_1B1         ; PORTRAIT_SENTA
	dw TILESET_AIRA_PORTRAIT, PALETTE_0C5, TILEMAP_1B2, TILEMAP_1B3, TILEMAP_1B4          ; PORTRAIT_AIRA
	dw TILESET_KANOKO_PORTRAIT, PALETTE_0C6, TILEMAP_1B5, TILEMAP_1B6, TILEMAP_1B7        ; PORTRAIT_KANOKO
	dw TILESET_GODA_PORTRAIT, PALETTE_0C7, TILEMAP_1B8, TILEMAP_1B9, TILEMAP_1BA          ; PORTRAIT_GODA
	dw TILESET_GRACE_PORTRAIT, PALETTE_0C8, TILEMAP_1BB, TILEMAP_1BC, TILEMAP_1BD         ; PORTRAIT_GRACE
	dw TILESET_KAMIYA_PORTRAIT, PALETTE_0C9, TILEMAP_1BE, TILEMAP_1BF, TILEMAP_1C0        ; PORTRAIT_KAMIYA
	dw TILESET_MIWA_PORTRAIT, PALETTE_0CA, TILEMAP_1C1, TILEMAP_1C2, TILEMAP_1C3          ; PORTRAIT_MIWA
	dw TILESET_KEVIN_PORTRAIT, PALETTE_0CB, TILEMAP_1C4, TILEMAP_1C5, TILEMAP_1C6         ; PORTRAIT_KEVIN
	dw TILESET_YOSUKE_PORTRAIT, PALETTE_0CC, TILEMAP_1C7, TILEMAP_1C8, TILEMAP_1C9        ; PORTRAIT_YOSUKE
	dw TILESET_RYOKO_PORTRAIT, PALETTE_0CD, TILEMAP_1CA, TILEMAP_1CB, TILEMAP_1CC         ; PORTRAIT_RYOKO
	dw TILESET_MAMI_PORTRAIT, PALETTE_0CE, TILEMAP_1CD, TILEMAP_1CE, TILEMAP_1CF          ; PORTRAIT_MAMI
	dw TILESET_NISHIJIMA_PORTRAIT, PALETTE_0CF, TILEMAP_1D0, TILEMAP_1D1, TILEMAP_1D2     ; PORTRAIT_NISHIJIMA
	dw TILESET_ISHII_PORTRAIT, PALETTE_0D0, TILEMAP_1D3, TILEMAP_1D4, TILEMAP_1D5         ; PORTRAIT_ISHII
	dw TILESET_SAMEJIMA_PORTRAIT, PALETTE_0D1, TILEMAP_1D6, TILEMAP_1D7, TILEMAP_1D8      ; PORTRAIT_SAMEJIMA
	dw TILESET_KANZAKI_PORTRAIT, PALETTE_0D2, TILEMAP_1D9, TILEMAP_1DA, TILEMAP_1DB       ; PORTRAIT_KANZAKI
	dw TILESET_RUI_PORTRAIT, PALETTE_0D3, TILEMAP_1DC, TILEMAP_1DD, TILEMAP_1DE           ; PORTRAIT_RUI
	dw TILESET_BIRURITCHI_PORTRAIT, PALETTE_0D4, TILEMAP_1DF, TILEMAP_1E0, TILEMAP_1E1    ; PORTRAIT_BIRURITCHI
	dw TILESET_GR_X_PORTRAIT, PALETTE_0D5, TILEMAP_1E2, TILEMAP_1E3, TILEMAP_1E4          ; PORTRAIT_GR_X
	dw TILESET_TOBICHAN_PORTRAIT, PALETTE_0D6, TILEMAP_1E5, TILEMAP_1E6, TILEMAP_1E7      ; PORTRAIT_TOBICHAN
	dw TILESET_DR_MASON_PORTRAIT, PALETTE_0D7, TILEMAP_1E8, TILEMAP_1E9, TILEMAP_1EA      ; PORTRAIT_DR_MASON
	dw TILESET_IMAKUNI_BLACK_PORTRAIT, PALETTE_080, TILEMAP_0E3, TILEMAP_0E4, TILEMAP_0E5 ; PORTRAIT_IMAKUNI_BLACK
	dw TILESET_IMAKUNI_RED_PORTRAIT, PALETTE_081, TILEMAP_0E6, TILEMAP_0E7, TILEMAP_0E8   ; PORTRAIT_IMAKUNI_RED
