; input:
;  a = PORTRAIT_* constant
;  b = portrait slot (0 or 1)
;  c = portrait variant
;  de = coordinates
DrawPortrait::
	push af
	push bc
	push de
	push hl
	push bc
	push de
	ld e, b
	ld d, c
	push de
	ld e, a
	ld d, 0
	ld bc, 10 ; size of each portrait entry
	call MultiplyBCByDE
	ld b, h
	ld c, l
	pop de
	ld hl, Portraits
	add hl, bc

	; tileset
	ld a, [hli]
	ld c, a
	ld a, [hli]
	ld b, a
	push hl
	farcall GetTilesetGfxPointer
	ld c, d
	call LoadPortraitTiles
	pop hl

	; palette
	ld a, [hli]
	ld c, a
	ld a, [hli]
	ld b, a
	push hl
	farcall GetPaletteGfxPointer
	call LoadPortraitPalettes
	pop hl

	; tilemap
	pop de
	pop bc
	ld a, b ; slot
	ld [wPortraitSlot], a
	ld a, c ; variant
	ld [wPortraitVariant], a
	ld b, $00
	sla c ; *2
	add hl, bc
	ld a, [hli]
	ld c, a
	ld a, [hli]
	ld b, a
	farcall GetTilemapGfxPointer
	ld a, [wPortraitVariant]
	ld c, a
	ld a, [wPortraitSlot]
	farcall LoadPortraitAttributeMap
	pop hl
	pop de
	pop bc
	pop af
	ret

Data_13005b::
	dw OWSPRITE_PLAYERM      ; OW_PLAYERM
	dw OWSPRITE_PLAYERF      ; OW_PLAYERF
	dw OWSPRITE_DRMASON      ; OW_DRMASON
	dw OWSPRITE_RONALD       ; OW_RONALD
	dw OWSPRITE_ISHIHARA     ; OW_ISHIHARA
	dw OWSPRITE_IMAKUNI1     ; OW_IMAKUNI1
	dw OWSPRITE_TECH         ; OW_TECH1
	dw OWSPRITE_TECH         ; OW_TECH2
	dw OWSPRITE_PAPPY        ; OW_PAPPY1
	dw OWSPRITE_GENE         ; OW_GENE
	dw OWSPRITE_MANIA        ; OW_MANIA1
	dw OWSPRITE_YOUNGSTER    ; OW_YOUNGSTER1
	dw OWSPRITE_MAN          ; OW_MAN1
	dw OWSPRITE_MITCH        ; OW_MITCH
	dw OWSPRITE_MANIA        ; OW_MANIA2
	dw OWSPRITE_MANIA        ; OW_MANIA3
	dw OWSPRITE_LASS3        ; OW_LASS1
	dw OWSPRITE_NIKKI        ; OW_NIKKI
	dw OWSPRITE_GIRL         ; OW_GIRL1
	dw OWSPRITE_LASS2        ; OW_LASS2
	dw OWSPRITE_LASS1        ; OW_LASS3
	dw OWSPRITE_RICK         ; OW_RICK
	dw OWSPRITE_TECH         ; OW_TECH3
	dw OWSPRITE_TECH         ; OW_TECH4
	dw OWSPRITE_TECH         ; OW_TECH5
	dw OWSPRITE_AMY1         ; OW_AMY1
	dw OWSPRITE_AMY2         ; OW_AMY2
	dw OWSPRITE_JOSHUA       ; OW_JOSHUA1
	dw OWSPRITE_SARA         ; OW_SARA
	dw OWSPRITE_AMANDA       ; OW_AMANDA
	dw OWSPRITE_KEN          ; OW_KEN
	dw OWSPRITE_LAD          ; OW_LAD1
	dw OWSPRITE_SPECS        ; OW_SPECS1
	dw OWSPRITE_YOUNGSTER    ; OW_YOUNGSTER2
	dw OWSPRITE_ISAAC        ; OW_ISAAC
	dw OWSPRITE_GIRL         ; OW_GIRL2
	dw OWSPRITE_HOOD         ; OW_HOOD1
	dw OWSPRITE_HOOD         ; OW_HOOD2
	dw OWSPRITE_MURRAY       ; OW_MURRAY
	dw OWSPRITE_YOUNGSTER    ; OW_YOUNGSTER3
	dw OWSPRITE_LAD          ; OW_LAD2
	dw OWSPRITE_GIRL         ; OW_GIRL3
	dw OWSPRITE_COURTNEY     ; OW_COURTNEY
	dw OWSPRITE_STEVE1       ; OW_STEVE1
	dw OWSPRITE_JACK         ; OW_JACK
	dw OWSPRITE_ROD          ; OW_ROD
	dw OWSPRITE_22           ; OW_UNK_2E
	dw OWSPRITE_23           ; OW_UNK_2F
	dw OWSPRITE_24           ; OW_UNK_30
	dw OWSPRITE_25           ; OW_UNK_31
	dw OWSPRITE_26           ; OW_UNK_32
	dw OWSPRITE_GRYOUNGSTER  ; OW_GRYOUNGSTER1
	dw OWSPRITE_27           ; OW_UNK_34
	dw OWSPRITE_28           ; OW_UNK_35
	dw OWSPRITE_27           ; OW_UNK_36
	dw OWSPRITE_28           ; OW_UNK_37
	dw OWSPRITE_GRLASS1      ; OW_GRLASS1
	dw OWSPRITE_29           ; OW_UNK_39
	dw OWSPRITE_2A           ; OW_UNK_3A
	dw OWSPRITE_2B           ; OW_UNK_3B
	dw OWSPRITE_GRGRANNY     ; OW_GRGRANNY1
	dw OWSPRITE_50           ; OW_UNK_3D
	dw OWSPRITE_2C           ; OW_UNK_3E
	dw OWSPRITE_2D           ; OW_UNK_3F
	dw OWSPRITE_2E           ; OW_UNK_40
	dw OWSPRITE_2F           ; OW_UNK_41
	dw OWSPRITE_SPECS        ; OW_SPECS2
	dw OWSPRITE_50           ; OW_UNK_43
	dw OWSPRITE_JOSHUA       ; OW_JOSHUA2
	dw OWSPRITE_30           ; OW_UNK_45
	dw OWSPRITE_31           ; OW_UNK_46
	dw OWSPRITE_32           ; OW_UNK_47
	dw OWSPRITE_33           ; OW_UNK_48
	dw OWSPRITE_34           ; OW_UNK_49
	dw OWSPRITE_GAL          ; OW_GAL1
	dw OWSPRITE_35           ; OW_UNK_4B
	dw OWSPRITE_36           ; OW_UNK_4C
	dw OWSPRITE_37           ; OW_UNK_4D
	dw OWSPRITE_38           ; OW_UNK_4E
	dw OWSPRITE_39           ; OW_UNK_4F
	dw OWSPRITE_3A           ; OW_UNK_50
	dw OWSPRITE_3B           ; OW_UNK_51
	dw OWSPRITE_3C           ; OW_UNK_52
	dw OWSPRITE_3D           ; OW_UNK_53
	dw OWSPRITE_3E           ; OW_UNK_54
	dw OWSPRITE_3F           ; OW_UNK_55
	dw OWSPRITE_41           ; OW_UNK_56
	dw OWSPRITE_STEVE2       ; OW_STEVE2
	dw OWSPRITE_17           ; OW_UNK_58
	dw OWSPRITE_STEVE3       ; OW_STEVE3
	dw OWSPRITE_19           ; OW_UNK_5A
	dw OWSPRITE_1A           ; OW_UNK_5B
	dw OWSPRITE_STEVE4       ; OW_STEVE4
	dw OWSPRITE_1C           ; OW_UNK_5D
	dw OWSPRITE_1D           ; OW_UNK_5E
	dw OWSPRITE_1E           ; OW_UNK_5F
	dw OWSPRITE_1F           ; OW_UNK_60
	dw OWSPRITE_20           ; OW_UNK_61
	dw OWSPRITE_21           ; OW_UNK_62
	dw OWSPRITE_40           ; OW_UNK_63
	dw OWSPRITE_CLERK        ; OW_CLERK1
	dw OWSPRITE_CLERK        ; OW_CLERK2
	dw OWSPRITE_GRCLERK      ; OW_GRCLERK1
	dw OWSPRITE_GRCLERK      ; OW_GRCLERK2
	dw OWSPRITE_GRCLERK      ; OW_GRCLERK3
	dw OWSPRITE_GRCLERK      ; OW_GRCLERK4
	dw OWSPRITE_LASS2        ; OW_LASS4
	dw OWSPRITE_WOMAN        ; OW_WOMAN
	dw OWSPRITE_CHAP         ; OW_CHAP1
	dw OWSPRITE_LAD          ; OW_LAD3
	dw OWSPRITE_PAPPY        ; OW_PAPPY2
	dw OWSPRITE_SPECS        ; OW_SPECS3
	dw OWSPRITE_LAD          ; OW_LAD4
	dw OWSPRITE_GIRL         ; OW_GIRL4
	dw OWSPRITE_GRANNY       ; OW_GRANNY
	dw OWSPRITE_LASS2        ; OW_LASS5
	dw OWSPRITE_GIRL         ; OW_GIRL5
	dw OWSPRITE_MAN          ; OW_MAN2
	dw OWSPRITE_LAD          ; OW_LAD5
	dw OWSPRITE_SPECS        ; OW_SPECS4
	dw OWSPRITE_TECH         ; OW_TECH6
	dw OWSPRITE_PAPPY        ; OW_PAPPY3
	dw OWSPRITE_LASS1        ; OW_LASS6
	dw OWSPRITE_LASS2        ; OW_LASS7
	dw OWSPRITE_HOOD         ; OW_HOOD3
	dw OWSPRITE_MANIA        ; OW_MANIA4
	dw OWSPRITE_GAL          ; OW_GAL2
	dw OWSPRITE_LASS3        ; OW_LASS8
	dw OWSPRITE_HOOD         ; OW_HOOD4
	dw OWSPRITE_LASS1        ; OW_LASS9
	dw OWSPRITE_CHAP         ; OW_CHAP2
	dw OWSPRITE_SPECS        ; OW_SPECS5
	dw OWSPRITE_LASS1        ; OW_LASS10
	dw OWSPRITE_LAD          ; OW_LAD6
	dw OWSPRITE_GRLASS1      ; OW_GRLASS2
	dw OWSPRITE_GRCLERK      ; OW_GRCLERK5
	dw OWSPRITE_GRGAL        ; OW_GRGAL1
	dw OWSPRITE_MANIA        ; OW_MANIA5
	dw OWSPRITE_CLERK        ; OW_CLERK3
	dw OWSPRITE_CHAP         ; OW_CHAP3
	dw OWSPRITE_GAL          ; OW_GAL3
	dw OWSPRITE_HOOD         ; OW_HOOD5
	dw OWSPRITE_MAN          ; OW_MAN3
	dw OWSPRITE_PAPPY        ; OW_PAPPY4
	dw OWSPRITE_TECH         ; OW_TECH7
	dw OWSPRITE_GIRL         ; OW_GIRL6
	dw OWSPRITE_LASS1        ; OW_LASS11
	dw OWSPRITE_LASS2        ; OW_LASS12
	dw OWSPRITE_GRCLERK      ; OW_GRCLERK6
	dw OWSPRITE_51           ; OW_UNK_95
	dw OWSPRITE_GRLASS1      ; OW_GRLASS3
	dw OWSPRITE_GRCLERK      ; OW_GRCLERK7
	dw OWSPRITE_GRYOUNGSTER  ; OW_GRYOUNGSTER2
	dw OWSPRITE_51           ; OW_UNK_99
	dw OWSPRITE_GRLASS1      ; OW_GRLASS4
	dw OWSPRITE_GRCLERK      ; OW_GRCLERK8
	dw OWSPRITE_GRWOMAN      ; OW_GRWOMAN1
	dw OWSPRITE_BUTCH        ; OW_BUTCH1
	dw OWSPRITE_CHAP         ; OW_CHAP4
	dw OWSPRITE_GRCLERK      ; OW_GRCLERK9
	dw OWSPRITE_YOUNGSTER    ; OW_YOUNGSTER4
	dw OWSPRITE_GRCLERK      ; OW_GRCLERK10
	dw OWSPRITE_GRGRANNY     ; OW_GRGRANNY2
	dw OWSPRITE_GRGAL        ; OW_GRGAL2
	dw OWSPRITE_GRCLERK      ; OW_GRCLERK11
	dw OWSPRITE_GRCLERK      ; OW_GRCLERK12
	dw OWSPRITE_MANIA        ; OW_MANIA6
	dw OWSPRITE_GRLASS1      ; OW_GRLASS5
	dw OWSPRITE_GRCLERK      ; OW_GRCLERK13
	dw OWSPRITE_TECH         ; OW_TECH8
	dw OWSPRITE_GRLASS1      ; OW_GRLASS6
	dw OWSPRITE_51           ; OW_UNK_AB
	dw OWSPRITE_65           ; OW_UNK_AC
	dw OWSPRITE_66           ; OW_UNK_AD
	dw OWSPRITE_67           ; OW_UNK_AE
	dw OWSPRITE_68           ; OW_UNK_AF
	dw OWSPRITE_LASS2        ; OW_LASS13
	dw OWSPRITE_IMAKUNI2     ; OW_IMAKUNI2
	dw OWSPRITE_BUTCH        ; OW_BUTCH2
	dw OWSPRITE_TECH         ; OW_TECH9
	dw OWSPRITE_TECH         ; OW_TECH10
	dw OWSPRITE_TECH         ; OW_TECH11
	dw OWSPRITE_TECH         ; OW_TECH12
	dw OWSPRITE_TECH         ; OW_TECH13
	dw OWSPRITE_TECH         ; OW_TECH14
	dw OWSPRITE_TECH         ; OW_TECH15
	dw OWSPRITE_TECH         ; OW_TECH16
	dw OWSPRITE_TECH         ; OW_TECH17
	dw OWSPRITE_GRCLERK      ; OW_GRCLERK14
	dw OWSPRITE_GRCLERK      ; OW_GRCLERK15
	dw OWSPRITE_GRCLERK      ; OW_GRCLERK16
	dw OWSPRITE_GRCLERK      ; OW_GRCLERK17
	dw OWSPRITE_61           ; OW_UNK_C0
	dw OWSPRITE_53           ; OW_UNK_C1
	dw OWSPRITE_53           ; OW_UNK_C2
	dw OWSPRITE_52           ; OW_UNK_C3
	dw OWSPRITE_62           ; OW_UNK_C4
	dw OWSPRITE_52           ; OW_UNK_C5
	dw OWSPRITE_61           ; OW_UNK_C6
	dw OWSPRITE_62           ; OW_UNK_C7
	dw OWSPRITE_6B           ; OW_UNK_C8
	dw OWSPRITE_6D           ; OW_UNK_C9
	dw OWSPRITE_6C           ; OW_UNK_CA
	dw OWSPRITE_6F           ; OW_UNK_CB
	dw OWSPRITE_70           ; OW_UNK_CC
	dw OWSPRITE_6E           ; OW_UNK_CD
	dw OWSPRITE_71           ; OW_UNK_CE
	dw OWSPRITE_72           ; OW_UNK_CF
	dw OWSPRITE_GRSHIPBEAM   ; OW_GRSHIPBEAM
	dw OWSPRITE_GRSHIP       ; OW_GRSHIP
	dw OWSPRITE_73           ; OW_UNK_D2
	dw OWSPRITE_GRYOUNGSTER  ; OW_GRYOUNGSTER3
	dw OWSPRITE_GRLASS1      ; OW_GRLASS7
	dw OWSPRITE_GRLASS1      ; OW_GRLASS8
	dw OWSPRITE_YOUNGSTER    ; OW_YOUNGSTER5
	dw OWSPRITE_SWIMMER      ; OW_SWIMMER
	dw OWSPRITE_GRGAL        ; OW_GRGAL3
	dw OWSPRITE_BUTCH        ; OW_BUTCH3
	dw OWSPRITE_MANIA        ; OW_MANIA7
	dw OWSPRITE_4D           ; OW_UNK_DB
	dw OWSPRITE_GRWOMAN      ; OW_GRWOMAN2
	dw OWSPRITE_GRGAL        ; OW_GRGAL4
	dw OWSPRITE_GRCLERK      ; OW_GRCLERK18
	dw OWSPRITE_4F           ; OW_UNK_DF
	dw OWSPRITE_GRWOMAN      ; OW_GRWOMAN3
	dw OWSPRITE_5C           ; OW_UNK_E1
	dw OWSPRITE_LASS1        ; OW_LASS14
	dw OWSPRITE_LASS2        ; OW_LASS15
	dw OWSPRITE_75           ; OW_UNK_E4
	dw OWSPRITE_76           ; OW_UNK_E5
	dw OWSPRITE_77           ; OW_UNK_E6
	dw OWSPRITE_78           ; OW_UNK_E7
	dw OWSPRITE_74           ; OW_UNK_E8

Portraits:
	dw TILESET_07D, PALETTE_078, TILEMAP_0D3, TILEMAP_0D3, TILEMAP_0D3 ; PORTRAIT_00
	dw TILESET_07E, PALETTE_079, TILEMAP_0D4, TILEMAP_0D4, TILEMAP_0D4 ; PORTRAIT_01
	dw TILESET_07F, PALETTE_07A, TILEMAP_0D5, TILEMAP_0D5, TILEMAP_0D5 ; PORTRAIT_02
	dw TILESET_080, PALETTE_07B, TILEMAP_0D6, TILEMAP_0D6, TILEMAP_0D6 ; PORTRAIT_03
	dw TILESET_081, PALETTE_07C, TILEMAP_0D7, TILEMAP_0D8, TILEMAP_0D9 ; PORTRAIT_04
	dw TILESET_082, PALETTE_07D, TILEMAP_0DA, TILEMAP_0DB, TILEMAP_0DC ; PORTRAIT_05
	dw TILESET_083, PALETTE_07E, TILEMAP_0DD, TILEMAP_0DE, TILEMAP_0DF ; PORTRAIT_06
	dw TILESET_084, PALETTE_07F, TILEMAP_0E0, TILEMAP_0E1, TILEMAP_0E2 ; PORTRAIT_07
	dw TILESET_087, PALETTE_082, TILEMAP_0E9, TILEMAP_0EA, TILEMAP_0EB ; PORTRAIT_08
	dw TILESET_088, PALETTE_083, TILEMAP_0EC, TILEMAP_0ED, TILEMAP_0EE ; PORTRAIT_09
	dw TILESET_089, PALETTE_084, TILEMAP_0EF, TILEMAP_0F0, TILEMAP_0F1 ; PORTRAIT_0A
	dw TILESET_08A, PALETTE_085, TILEMAP_0F2, TILEMAP_0F3, TILEMAP_0F4 ; PORTRAIT_0B
	dw TILESET_08B, PALETTE_086, TILEMAP_0F5, TILEMAP_0F6, TILEMAP_0F7 ; PORTRAIT_0C
	dw TILESET_08C, PALETTE_087, TILEMAP_0F8, TILEMAP_0F9, TILEMAP_0FA ; PORTRAIT_0D
	dw TILESET_08D, PALETTE_088, TILEMAP_0FB, TILEMAP_0FC, TILEMAP_0FD ; PORTRAIT_0E
	dw TILESET_08E, PALETTE_089, TILEMAP_0FE, TILEMAP_0FF, TILEMAP_100 ; PORTRAIT_0F
	dw TILESET_08F, PALETTE_08A, TILEMAP_101, TILEMAP_102, TILEMAP_103 ; PORTRAIT_10
	dw TILESET_090, PALETTE_08B, TILEMAP_104, TILEMAP_105, TILEMAP_106 ; PORTRAIT_11
	dw TILESET_091, PALETTE_08C, TILEMAP_107, TILEMAP_108, TILEMAP_109 ; PORTRAIT_12
	dw TILESET_092, PALETTE_08D, TILEMAP_10A, TILEMAP_10B, TILEMAP_10C ; PORTRAIT_13
	dw TILESET_093, PALETTE_08E, TILEMAP_10D, TILEMAP_10E, TILEMAP_10F ; PORTRAIT_14
	dw TILESET_094, PALETTE_08F, TILEMAP_110, TILEMAP_111, TILEMAP_112 ; PORTRAIT_15
	dw TILESET_095, PALETTE_090, TILEMAP_113, TILEMAP_114, TILEMAP_115 ; PORTRAIT_16
	dw TILESET_096, PALETTE_091, TILEMAP_116, TILEMAP_117, TILEMAP_118 ; PORTRAIT_17
	dw TILESET_097, PALETTE_092, TILEMAP_119, TILEMAP_11A, TILEMAP_11B ; PORTRAIT_18
	dw TILESET_098, PALETTE_093, TILEMAP_11C, TILEMAP_11D, TILEMAP_11E ; PORTRAIT_19
	dw TILESET_099, PALETTE_094, TILEMAP_11F, TILEMAP_120, TILEMAP_121 ; PORTRAIT_1A
	dw TILESET_09A, PALETTE_095, TILEMAP_122, TILEMAP_123, TILEMAP_124 ; PORTRAIT_1B
	dw TILESET_09B, PALETTE_096, TILEMAP_125, TILEMAP_126, TILEMAP_127 ; PORTRAIT_1C
	dw TILESET_09C, PALETTE_097, TILEMAP_128, TILEMAP_129, TILEMAP_12A ; PORTRAIT_1D
	dw TILESET_09D, PALETTE_098, TILEMAP_12B, TILEMAP_12C, TILEMAP_12D ; PORTRAIT_1E
	dw TILESET_09E, PALETTE_099, TILEMAP_12E, TILEMAP_12F, TILEMAP_130 ; PORTRAIT_1F
	dw TILESET_09F, PALETTE_09A, TILEMAP_131, TILEMAP_132, TILEMAP_133 ; PORTRAIT_20
	dw TILESET_0A0, PALETTE_09B, TILEMAP_134, TILEMAP_135, TILEMAP_136 ; PORTRAIT_21
	dw TILESET_0A1, PALETTE_09C, TILEMAP_137, TILEMAP_138, TILEMAP_139 ; PORTRAIT_22
	dw TILESET_0A2, PALETTE_09D, TILEMAP_13A, TILEMAP_13B, TILEMAP_13C ; PORTRAIT_23
	dw TILESET_0A3, PALETTE_09E, TILEMAP_13D, TILEMAP_13E, TILEMAP_13F ; PORTRAIT_24
	dw TILESET_0A4, PALETTE_09F, TILEMAP_140, TILEMAP_141, TILEMAP_142 ; PORTRAIT_25
	dw TILESET_0A5, PALETTE_0A0, TILEMAP_143, TILEMAP_144, TILEMAP_145 ; PORTRAIT_26
	dw TILESET_0A6, PALETTE_0A1, TILEMAP_146, TILEMAP_147, TILEMAP_148 ; PORTRAIT_27
	dw TILESET_0A7, PALETTE_0A2, TILEMAP_149, TILEMAP_14A, TILEMAP_14B ; PORTRAIT_28
	dw TILESET_0A8, PALETTE_0A3, TILEMAP_14C, TILEMAP_14D, TILEMAP_14E ; PORTRAIT_29
	dw TILESET_0A9, PALETTE_0A4, TILEMAP_14F, TILEMAP_150, TILEMAP_151 ; PORTRAIT_2A
	dw TILESET_0AA, PALETTE_0A5, TILEMAP_152, TILEMAP_153, TILEMAP_154 ; PORTRAIT_2B
	dw TILESET_0AB, PALETTE_0A6, TILEMAP_155, TILEMAP_156, TILEMAP_157 ; PORTRAIT_2C
	dw TILESET_0AC, PALETTE_0A7, TILEMAP_158, TILEMAP_159, TILEMAP_15A ; PORTRAIT_2D
	dw TILESET_0AD, PALETTE_0A8, TILEMAP_15B, TILEMAP_15C, TILEMAP_15D ; PORTRAIT_2E
	dw TILESET_0AE, PALETTE_0A9, TILEMAP_15E, TILEMAP_15F, TILEMAP_160 ; PORTRAIT_2F
	dw TILESET_0AF, PALETTE_0AA, TILEMAP_161, TILEMAP_162, TILEMAP_163 ; PORTRAIT_30
	dw TILESET_0B0, PALETTE_0AB, TILEMAP_164, TILEMAP_165, TILEMAP_166 ; PORTRAIT_31
	dw TILESET_0B1, PALETTE_0AC, TILEMAP_167, TILEMAP_168, TILEMAP_169 ; PORTRAIT_32
	dw TILESET_0B2, PALETTE_0AD, TILEMAP_16A, TILEMAP_16B, TILEMAP_16C ; PORTRAIT_33
	dw TILESET_0B3, PALETTE_0AE, TILEMAP_16D, TILEMAP_16E, TILEMAP_16F ; PORTRAIT_34
	dw TILESET_0B4, PALETTE_0AF, TILEMAP_170, TILEMAP_171, TILEMAP_172 ; PORTRAIT_35
	dw TILESET_0B5, PALETTE_0B0, TILEMAP_173, TILEMAP_174, TILEMAP_175 ; PORTRAIT_36
	dw TILESET_0B6, PALETTE_0B1, TILEMAP_176, TILEMAP_177, TILEMAP_178 ; PORTRAIT_37
	dw TILESET_0B7, PALETTE_0B2, TILEMAP_179, TILEMAP_17A, TILEMAP_17B ; PORTRAIT_38
	dw TILESET_0B8, PALETTE_0B3, TILEMAP_17C, TILEMAP_17D, TILEMAP_17E ; PORTRAIT_39
	dw TILESET_0B9, PALETTE_0B4, TILEMAP_17F, TILEMAP_180, TILEMAP_181 ; PORTRAIT_3A
	dw TILESET_0BA, PALETTE_0B5, TILEMAP_182, TILEMAP_183, TILEMAP_184 ; PORTRAIT_3B
	dw TILESET_0BB, PALETTE_0B6, TILEMAP_185, TILEMAP_186, TILEMAP_187 ; PORTRAIT_3C
	dw TILESET_0BC, PALETTE_0B7, TILEMAP_188, TILEMAP_189, TILEMAP_18A ; PORTRAIT_3D
	dw TILESET_0BD, PALETTE_0B8, TILEMAP_18B, TILEMAP_18C, TILEMAP_18D ; PORTRAIT_3E
	dw TILESET_0BE, PALETTE_0B9, TILEMAP_18E, TILEMAP_18F, TILEMAP_190 ; PORTRAIT_3F
	dw TILESET_0BF, PALETTE_0BA, TILEMAP_191, TILEMAP_192, TILEMAP_193 ; PORTRAIT_40
	dw TILESET_0C0, PALETTE_0BB, TILEMAP_194, TILEMAP_195, TILEMAP_196 ; PORTRAIT_41
	dw TILESET_0C1, PALETTE_0BC, TILEMAP_197, TILEMAP_198, TILEMAP_199 ; PORTRAIT_42
	dw TILESET_0C2, PALETTE_0BD, TILEMAP_19A, TILEMAP_19B, TILEMAP_19C ; PORTRAIT_43
	dw TILESET_0C3, PALETTE_0BE, TILEMAP_19D, TILEMAP_19E, TILEMAP_19F ; PORTRAIT_44
	dw TILESET_0C4, PALETTE_0BF, TILEMAP_1A0, TILEMAP_1A1, TILEMAP_1A2 ; PORTRAIT_45
	dw TILESET_0C5, PALETTE_0C0, TILEMAP_1A3, TILEMAP_1A4, TILEMAP_1A5 ; PORTRAIT_46
	dw TILESET_0C6, PALETTE_0C1, TILEMAP_1A6, TILEMAP_1A7, TILEMAP_1A8 ; PORTRAIT_47
	dw TILESET_0C7, PALETTE_0C2, TILEMAP_1A9, TILEMAP_1AA, TILEMAP_1AB ; PORTRAIT_48
	dw TILESET_0C8, PALETTE_0C3, TILEMAP_1AC, TILEMAP_1AD, TILEMAP_1AE ; PORTRAIT_49
	dw TILESET_0C9, PALETTE_0C4, TILEMAP_1AF, TILEMAP_1B0, TILEMAP_1B1 ; PORTRAIT_4A
	dw TILESET_0CA, PALETTE_0C5, TILEMAP_1B2, TILEMAP_1B3, TILEMAP_1B4 ; PORTRAIT_4B
	dw TILESET_0CB, PALETTE_0C6, TILEMAP_1B5, TILEMAP_1B6, TILEMAP_1B7 ; PORTRAIT_4C
	dw TILESET_0CC, PALETTE_0C7, TILEMAP_1B8, TILEMAP_1B9, TILEMAP_1BA ; PORTRAIT_4D
	dw TILESET_0CD, PALETTE_0C8, TILEMAP_1BB, TILEMAP_1BC, TILEMAP_1BD ; PORTRAIT_4E
	dw TILESET_0CE, PALETTE_0C9, TILEMAP_1BE, TILEMAP_1BF, TILEMAP_1C0 ; PORTRAIT_4F
	dw TILESET_0CF, PALETTE_0CA, TILEMAP_1C1, TILEMAP_1C2, TILEMAP_1C3 ; PORTRAIT_50
	dw TILESET_0D0, PALETTE_0CB, TILEMAP_1C4, TILEMAP_1C5, TILEMAP_1C6 ; PORTRAIT_51
	dw TILESET_0D1, PALETTE_0CC, TILEMAP_1C7, TILEMAP_1C8, TILEMAP_1C9 ; PORTRAIT_52
	dw TILESET_0D2, PALETTE_0CD, TILEMAP_1CA, TILEMAP_1CB, TILEMAP_1CC ; PORTRAIT_53
	dw TILESET_0D3, PALETTE_0CE, TILEMAP_1CD, TILEMAP_1CE, TILEMAP_1CF ; PORTRAIT_54
	dw TILESET_0D4, PALETTE_0CF, TILEMAP_1D0, TILEMAP_1D1, TILEMAP_1D2 ; PORTRAIT_55
	dw TILESET_0D5, PALETTE_0D0, TILEMAP_1D3, TILEMAP_1D4, TILEMAP_1D5 ; PORTRAIT_56
	dw TILESET_0D6, PALETTE_0D1, TILEMAP_1D6, TILEMAP_1D7, TILEMAP_1D8 ; PORTRAIT_57
	dw TILESET_0D7, PALETTE_0D2, TILEMAP_1D9, TILEMAP_1DA, TILEMAP_1DB ; PORTRAIT_58
	dw TILESET_0D8, PALETTE_0D3, TILEMAP_1DC, TILEMAP_1DD, TILEMAP_1DE ; PORTRAIT_59
	dw TILESET_0D9, PALETTE_0D4, TILEMAP_1DF, TILEMAP_1E0, TILEMAP_1E1 ; PORTRAIT_5A
	dw TILESET_0DA, PALETTE_0D5, TILEMAP_1E2, TILEMAP_1E3, TILEMAP_1E4 ; PORTRAIT_5B
	dw TILESET_0DB, PALETTE_0D6, TILEMAP_1E5, TILEMAP_1E6, TILEMAP_1E7 ; PORTRAIT_5C
	dw TILESET_0DC, PALETTE_0D7, TILEMAP_1E8, TILEMAP_1E9, TILEMAP_1EA ; PORTRAIT_5D
	dw TILESET_085, PALETTE_080, TILEMAP_0E3, TILEMAP_0E4, TILEMAP_0E5 ; PORTRAIT_5E
	dw TILESET_086, PALETTE_081, TILEMAP_0E6, TILEMAP_0E7, TILEMAP_0E8 ; PORTRAIT_5F
