	cardattrs_start
	cardattr 1, HAS_ALT_TILE
	cardattr 1, HAS_ALT_TILE
	cardattr 1, HAS_ALT_TILE
	cardattr 1, HAS_ALT_TILE
	cardattr 1, HAS_ALT_TILE
	cardattr 1, HAS_ALT_TILE
	cardattr 1, HAS_ALT_TILE
	cardattr 1, HAS_ALT_TILE
	cardattr 1, HAS_ALT_TILE
	cardattr 1, HAS_ALT_TILE
	cardattr 0, HAS_ALT_TILE
	cardattr 0, HAS_ALT_TILE
	cardattr 0, HAS_ALT_TILE
	cardattr 0, HAS_ALT_TILE
	cardattr 0, HAS_ALT_TILE
	cardattr 1, HAS_ALT_TILE
	cardattr 1, HAS_ALT_TILE
	cardattr 0, HAS_ALT_TILE
	cardattr 0, HAS_ALT_TILE
	cardattr 0, HAS_ALT_TILE
	cardattr 0, HAS_ALT_TILE
	cardattr 0, HAS_ALT_TILE
	cardattr 2, HAS_ALT_TILE
	cardattr 1, HAS_ALT_TILE
	cardattr 1, HAS_ALT_TILE
	cardattr 1, HAS_ALT_TILE
	cardattr 0, HAS_ALT_TILE
	cardattr 0, HAS_ALT_TILE
	cardattr 0, HAS_ALT_TILE
	cardattr 2, HAS_ALT_TILE
	cardattr 1, HAS_ALT_TILE
	cardattr 1, HAS_ALT_TILE
	cardattr 1, HAS_ALT_TILE
	cardattr 1, HAS_ALT_TILE
	cardattr 0, HAS_ALT_TILE
	cardattr 0, HAS_ALT_TILE
	cardattr 0, HAS_ALT_TILE
	cardattr 2, HAS_ALT_TILE
	cardattr 1, HAS_ALT_TILE
	cardattr 1, HAS_ALT_TILE
	cardattr 1, HAS_ALT_TILE
	cardattr 1, HAS_ALT_TILE
	cardattr 0, HAS_ALT_TILE
	cardattr 0, HAS_ALT_TILE
	cardattr 0, HAS_ALT_TILE
	cardattr 1, HAS_ALT_TILE
	cardattr 1, HAS_ALT_TILE
	cardattr 1, HAS_ALT_TILE
